### ISSUE TITLE
Question / Bug in SMC device?

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#1008]
I implemented the thermal sensor device of the Xbox in one of my branches, and tested it with UnleashX, since I know it prints the CPU and M/B temperatures on the screen. However, I've seen that the values are not read correctly and upon debugging I discovered it's because the dashboard is calling HalReadSMBusValue with the parameters 0x20 (SMC device software address), 0x9 or 0xA (commands read cpu and m/b temperature) and false (read 8 bits). However, our code expects that a read will use the software address 0x21 (0x20 is for writing) and so the call will fail to retrieve the data, hence the failure observed. So am I missing something or is this a bug in the current implementation? Additionaly, I have also found that RDX dashboard does the same call of above with the same parameters, and fails in the same way

**Comment by PatrickvL** [comment]
Hm. Perhaps a read or's in a 1?

**Comment by ergo720** [comment]
Adding | 1 to Address to the IOWrite call in HalReadSMBusValue fixes this so I'll close this
