### ISSUE TITLE
CXBX RELOADED (3/29/18) update Jet Set Radio (NTSC-U) Problem. (Windows 7 64 bit)

### ISSUE THREAD

**Issue by Vampira138** [Cxbx-Reloaded/Cxbx-Reloaded#1014]
A Weird Graphical Glitch happens when you start the game. Random colors on certain textures that i have never seen before? It stops when you mess around with the LLE Jit Setting. Not sure if that helps the devs but i figured i would report and help this issue. im also using windows 7 64bit. cpu i5 videocard intel hd.

Questions can be asked at Gitter: https://gitter.im/Cxbx-Reloaded/Lobby
If this is an issue specifically related to one game, please report it at https://github.com/Cxbx-Reloaded/game-compatibility
Any emulation/general issues (e.g. crashes when controller is connected or regressions across several titles) can be reported here

-->

**Comment by CakeLancelot** [comment]
These problems are a known issue, described [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/703). The LLE JIT setting should have nothing to do with it, it just seems to vary during each run of the game.

I'll be closing this as an issue already exists in the game compatibility repository. If you face any issues that haven't been reported yet you can do so there.

**Comment by PatrickvL** [comment]
I'm working on rendering improvements, but it'll take some time
