### ISSUE TITLE
"Introduce functional NV2A LLE" April Fools?

### ISSUE THREAD

**Issue by Paradise12314** [Cxbx-Reloaded/Cxbx-Reloaded#1021]
Perhaps I shouldn't be asking on here. But Is the NV2A now functional? I tried it, with no luck. Just a black screen, and "WARN: NV2A: Unknown NV_IMAGE_BLIT Method" at the bottom of KrnlDebug. 

So I'm guessing April Fools. But you never know!

**Comment by Voxel9** [comment]
It's no April fools' joke, the functional LLE was in fact added; just at a bad time lol.

LLE is _extremely_ slow in its current state right now, so you might have to wait up to a couple of minutes for anything to even draw on-screen.
Note that currently NVIDIA GPUs seem to be having trouble drawing anything, but I'm sure it will be fixed later.

**Comment by ObiKKa** [comment]
It was added in the early morning of April 2, 2018. So it's no joke, indeed.
