### ISSUE TITLE
Grand Theft Auto 3 crash

### ISSUE THREAD

**Issue by TotalCaesar659** [Cxbx-Reloaded/Cxbx-Reloaded#103]
Grand Theft Auto 3 doesn't start.
Version https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/90d4dfe811bd2182dbda974869309c98c7d9b41b.
Windows 7 x64.
KrnlDebug.txt:
>[0x1544] EmuMain: Cxbx-Reloaded Version 1c8228c (Jan 14 2017)
[0x1544] EmuMain: Debug Console Allocated (DM_FILE).
[0x1544] EmuMain: Debug Trace Disabled.
CxbxDbg> Found
[0x1544] EmuMain: Recieved Fatal Message:
>
>* EmuD3DDeferredTextureState was not found!
>
>CxbxKrnl: Terminating Process

P.S. There is misspelling in "EmuMain: **Recieved** Fatal Message" and "EmuMain: **Recieved** Exception" from here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/101.
**Received** is correct. Please, fix it.

**Comment by LukeUsher** [comment]
Most titles that show an issue with EmuD3DDeferredRenderState or EmuD3DDeferredTextureState are compiled with link time optimisation. Cxbx-Reloaded cannot properly support these titles until low-level emulation is fully implemented.

These titles can be identified by making an Xbe dump [Edit => Dump XBE] and checking for the presence of D3D8LTCG.  If this library is used, we cannot properly support the title with HLE, and it will have to wait until low level emulation of the graphics hardware is fully implemented

**Comment by TotalCaesar659** [comment]
Yeah, D3D8LTCG is there. Thank you for the explanation.

**Comment by PatrickvL** [comment]
This issue should be closed, and we should think about a way to communicate loud and clear that software build with LTCG libraries will probably never work under HLE, to prevent people submitting unnecessary issues.

**Comment by LukeUsher** [comment]
Agreed,
