### ISSUE TITLE
Release build compilation fails with errors

### ISSUE THREAD

**Issue by DisorderIy** [Cxbx-Reloaded/Cxbx-Reloaded#104]
(I didn't really know what else to call this issue.)

When trying to compile a Release build (Win 10 x64, VS 2015) on the latest master, I get these two errors:

Error	LNK1181	cannot open input file 'Zydis.lib'	CxbxKrnl	D:\GitHub\Cxbx-Reloaded\build\win32\LINK	1	
Error	LNK1181	cannot open input file 'CxbxKrnl.lib'	Cxbx	D:\GitHub\Cxbx-Reloaded\build\win32\LINK	1	

This doesn't happen when compiling a Debug build.

**Comment by LukeUsher** [comment]
Fixed in #105

**Comment by DisorderIy** [comment]
Holy cow, that was quick O_O
