### ISSUE TITLE
ReFS + Storage Space support

### ISSUE THREAD

**Issue by GXTX** [Cxbx-Reloaded/Cxbx-Reloaded#1052]
Seems the emulator does not like loading xbe's stored on a storage space pool with ReFS as the filesystem.

Attempts to load required files for ~20 seconds then stops, and nothing loads. However the emulator does not crash during this.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1886968/KrnlDebug.txt)

**Comment by jarupxx** [comment]
Unfortunately, I could not confirm the issue.

I testing that store Cxbx-Reloaded\EmuDisk on NTFS filesystem HDD, JSRF was stored in ReFS filesystem HDD.
Loading xbe successfully and the SEGA logo will be displayed, that same result as stored in NTFS HDD.
It looks like work fine on a ReFS filesystem storage, I think.

Tested with 9917594c

**Comment by PatrickvL** [comment]
Thanks @jarupxx - let's close this for now.

**Comment by RadWolfie** [comment]
Thanks for unable to reproduce the issue. It might be network/harddrive bandwidth latency issue between server and host computers on their side.

**Comment by GXTX** [comment]
Went ahead and made a quick 2 minute vid for proof. Same thing happens on the non-software-RAID1 ```G:\``` drive.

https://youtu.be/FTbe41Ks9q8

_I legally own JSRF, this is a personal preservation copy._

**Comment by GXTX** [comment]
Some more info.

D:\ is a storage space RAID1 volume, that seems to be the issue. I attempted to run the debug version of CXBXR and dump the kernel log to a file, it wouldn't write to the D:\ drive, G:\ which is just a JBOD from storage spaces works fine.

**Comment by GXTX** [comment]
Appears to be all games, attempted to load Fairly Odd Parents: Breakin Da Rules and it gives me the dirty disk error, loads fine while not on a storage space volume.

**Comment by RadWolfie** [comment]
ReFS is not the only format has this issue. User report ExFAT also has same issue. However, PS3 and Xenia emulators are able to boot titles from ExFAT partition (from external drive). It is also reported NTFS on external drive (USB 3.0) do work as well.

**Comment by GXTX** [comment]
Thanks for reminding me about this. I have just retested with the latest master version as of today and am still getting similar results.

Tested on 2 different "drives". 1 being a managed two-way mirror in Storage Spaces formatted as ReFS, 2nd being a parity array in Storage Spaces on ReFS.

**Comment by GXTX** [comment]
For the sake of it I retried today (same game) as I hadn't tried since the new loader. Same issue. I noticed another issue (which probably deserves it's own thread) that JSRF no longer shows the "Now Loading" screen on my system even when the game launches correctly on my `C:\` drive.

**Comment by GXTX** [comment]
Probably fixed by #2341
