### ISSUE TITLE
'Boost dash' post-processing effect fails in JSRF, possibly others

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#1068]
After collecting 10 spray cans in Jet Set Radio Future, you can press B to do a boost dash which produces a post-processing effect that covers the screen for a few seconds. The effect is meant to 'blur' the entirety of the screen, giving the feeling of increased speed.

In Cxbx-Reloaded, instead of blurring the screen as expected it will either produce random garbage or a black screen. When random garbage appears onscreen, you can see the effect 'working' it just seems the 'input' is incorrect.

I recorded a Kernel Debug and a d3d8to9 log of starting the game, loading a save file, collecting spray cans, and boosting. The Kernel Debug log is zipped for filesize concerns (normally 751MB). I also have provided still images and videos of both the effect on Cxbx-Reloaded and Xbox hardware below.

[KrnlDebug-boost.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913252/KrnlDebug-boost.zip)
[d3d8.log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913251/d3d8.log)

Cxbx-Reloaded:
![mpv_2018-04-15_14-53-41](https://user-images.githubusercontent.com/5341136/38782682-da994af0-40bc-11e8-87b0-a1afcd90ed6a.png)
Xbox:
![mpv_2018-04-15_14-53-32](https://user-images.githubusercontent.com/5341136/38782681-da852db8-40bc-11e8-9afe-abfe14911de0.png)

[MP4 captured from Cxbx-Reloaded](https://cdn.discordapp.com/attachments/293096509019258880/435154130160582688/2018-04-15_14-05-30.mp4)

[MP4 captured from Xbox](https://cdn.discordapp.com/attachments/293096509019258880/435156469516730368/2018-04-15_14-14-23.mp4)

**Comment by Crimsom13** [comment]
seems to be a common problem with full screen alpha overlays here is hunter the recknoning game over smoke fade out. 
![alpha](https://user-images.githubusercontent.com/38405862/38782777-659fe6fa-40c6-11e8-897b-f665da6b0f38.jpg)

**Comment by ObiKKa** [comment]
Fixing this might also fix that Burnout's overhead cam view 'Crash' indication filter screen. I can't remember of any other specific examples now. But there could be many.
Maybe Whiteout the racer (Yellow filter at most times).

**Comment by PatrickvL** [comment]
@CakeLancelot please attach a save file (generated without a custom keys.bin) of a point where this is possible.

**Comment by CakeLancelot** [comment]
> @CakeLancelot please attach a save file (generated without a custom keys.bin) of a point where this is possible.

Save slot 2 should start off in an area with enough spraycans to easily reproduce the issue. This save is from a combo-disc NTSC copy of the game.
[JSRF-NTSC-combo-savedata.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1914210/JSRF-NTSC-combo-savedata.zip)

**Comment by PatrickvL** [comment]
Duplicate report : https://github.com/Cxbx-Reloaded/game-compatibility/issues/723

**Comment by Mythras1229** [comment]
When I boost dash the screen goes black and then the game crashes, is there any way around this?

**Comment by LukeUsher** [comment]
@Mythras1229 you'll have to provide more info on your settings, what version of the emulator you are using, etc. There are currently no issues like this with boost dash in either the latest release or development builds.

If you are using any resolution scaling hacks such as scale viewport or any resolution settings other than 'automatic' please use the default settings instead: resolution scaling is known to introduce bugs with this same behavior.

**Comment by Mythras1229** [comment]
Ahh I was trying to upscale the resolution, it did work when on auto. Is there a way to play in full screen while also on auto resolution? turning on "use hardware video mode" causes it to fail to start when on auto res

**Comment by LukeUsher** [comment]
@Mythras1229 you could use the Alt+Enter keyboard shortcut.
For further support, please use our Discord: This issue tracker is the place for reporting bugs/issues, not for support.

Thanks
