### ISSUE TITLE
Conflict Global Terror, Disk read error while launching campaign/tutorial.

### ISSUE THREAD

**Issue by Crimsom13** [Cxbx-Reloaded/Cxbx-Reloaded#1069]
![global](https://user-images.githubusercontent.com/38405862/38782813-efe3ead2-40c6-11e8-90eb-70296eaf7516.JPG)

I am getting a disk read error while trying to launch into this game from the menus.

Menus work fine, but loading into engine or intro movie seems to yield an error.

**Comment by PatrickvL** [comment]
Please add more details, like log files. Also, makes sure you're using a clean dump and avoid making any modifications

**Comment by Crimsom13** [comment]
-Launch game via start new game option. (disk read error)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913401/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913403/CxbxDebug.txt)

-Launch game via run tutorial option freeze.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913407/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1913408/CxbxDebug.txt)

**Comment by PatrickvL** [comment]
@ergo720 Two lines jump out of this KrnlDebug.txt log :
```
WARN: KRNL: MmQueryStatistics with unusual size -> 0xAD574AF4
WARN: PMEM Out of physical memory!
```
Meaning this might have nothing to do with the `NtReadFile` failures (or it's running a corrupt dump).

**Comment by ergo720** [comment]
@Crimsom13 can you please re-upload a new kernel log with the most-recent cxbx version? It now also prints if the xbe is valid, so we can rule out a corrupt dump. @PatrickvL a title that crashes with PMEM Out of physical memory! usually means the game is not expecting the allocation to fail, and it will attempt to dereference the pointer returned by the memory function (nullptr in the case of failure), hence the crash. This title is not crashing it seems though, so it could be something else (or it's detecting the nullptr and displaying the error screen instead). I have also seen the MmQueryStatistics error in other games, but never investigated the cause of it. They could have the same cause, so I'll try to reproduce again the error (if it still happens).

**Comment by PatrickvL** [comment]
We might need an actual pool allocator in the AllocatePool API's as these currently use whole pages

**Comment by Crimsom13** [comment]
Single player start game (disk read error)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930662/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930664/KrnlDebug.txt)

Start training mode (hard lock up)

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930671/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930672/KrnlDebug.txt)

**Comment by Crimsom13** [comment]
looks like it's getting an invalid signature.

**Comment by Crimsom13** [comment]
Think I fixed my rip, still getting disk read error, here is the latest log file.

Single player start game (disk read error)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930917/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930919/KrnlDebug.txt)

Start training mode (hard lock up)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930926/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930927/KrnlDebug.txt)

**Comment by ergo720** [comment]
Update: X-Marbles doesn't hit an "out of memory" error even on the current master at the moment (a6efd010), so it's unrelated to ExAllocatePoolWithTag since it is still not implemented correctly in master (or I have a different version of X-Marbles).
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1957798/KrnlDebug.txt)

**Comment by ergo720** [comment]
According to a discord post, @Crimsom13 encountered the same "Dirty disc error" with JSRF
```
[0x2614] WARN: PMEM Out of physical memory!
Org:"Z:\Media\Cache\JSRF_FATAL.ERR"
New:"$CxbxPath\Partition4\Media\Cache\JSRF_FATAL.ERR"
[0x0C20] MAIN: Terminating Process
```
but it turned out it was the same timing error which afflicts DOA titles as well. If so, then the above error could have the same origin and be unrelated to memory errors. @Crimsom13 can you retest the game now that the pool manager is in, please?

**Comment by Crimsom13** [comment]
the dirty disk error with JSRF was in 720p hack version which may have slowed the rendered down to the point it errored out? I tried it again in 420P and got though the intro just fine... 

-Launch single player campaign (dirty disk error)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962537/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962540/KrnlDebug.txt)

-Launch training (crash half way through load)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962542/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962543/KrnlDebug.txt)

same - progress on conflict vietnam though see thread for details.

**Comment by LukeUsher** [comment]
This is a game specific issue an should be in our game-compatibility tracker instead.
