### ISSUE TITLE
Wiki: Add how to download compiled build from AppVeyor site

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1074]
Here's the steps I gave at least 3 times on discord. Please add it to FAQ page in order to prevent losing information from discord chats.

---
For manual download from specific day/commit from AppVeyor by clicking the checkmark icon from github, follow this steps.

1. Go to this link: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commits/master
2. Scroll all the way down to see the latest commit
3. Look for checkmark icon next to date, select it.
4. Select release configure if you're not a developer.
5. Select Artifacts tab.
6. Click the zip file to download.

**Comment by PatrickvL** [comment]
Thanks - it's pasted here : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-download-specific-cxbx-reloaded-builds

**Comment by RadWolfie** [comment]
Um... I made a mistake. On master, the latest is at the top. However the PR's latest commit is at the bottom.

**Comment by x1nixmzeng** [comment]
@RadWolfie the wiki is editable by everyone!
