### ISSUE TITLE
Fix IDirect3DDevice8_SetSoftDisplayFilter_1_0_5344 OOVPA

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#108]
IDirect3DDevice8_SetSoftDisplayFilter_1_0_5344 contains non-incremental, and conflicting offset + value pairs, fix them

**Comment by jarupxx** [comment]
It was confirmed by xdk 5344 game. https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/109

**Comment by PatrickvL** [comment]
This issue can be closed now PR #109 is merged
