### ISSUE TITLE
Conflict Vietnam  (profile error)

### ISSUE THREAD

**Issue by Crimsom13** [Cxbx-Reloaded/Cxbx-Reloaded#1080]
ffceb160 (Apr 19 2018) build
![conflict vietnam](https://user-images.githubusercontent.com/38405862/39031251-09b52d42-4435-11e8-955b-86acc49a41f9.JPG)

After creating a new player profile it becomes damaged and unreadable, unable to proceed to game.

Me pressing on profile 3 or 4 times.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930677/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1930678/KrnlDebug.txt)

**Comment by Crimsom13** [comment]
Profile error now (sometimes works)  we still have the same problem that persists with conflict vietnam and conflict global terror a crash in midway through engine load.

Crash log with profile not being damaged.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962552/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1962553/KrnlDebug.txt)

See above crash log for when profile goes corrupt...

Tried 4x and about half the time it went corrupt the other half it worked. Maybe it will work 100% of the time with freshly created profiles?

Good work though none the less you're clearly on the right track.

**Comment by LukeUsher** [comment]
This is a game specific issue an should be in our game-compatibility tracker instead.
