### ISSUE TITLE
Xbox Kernel Test Suite Crashes Immediately

### ISSUE THREAD

**Issue by Fisherman166** [Cxbx-Reloaded/Cxbx-Reloaded#1083]
Last weekend the Xbox Kernel Test Suite ran fine. This weekend, it crashes immediately with no error messages in the logfiles. I was able to git bisect the issue back to this commit.

commit e8c1c7670a403923d39434d09db530c3d68f263d
Author: @ergo720 
Date:   Wed Apr 18 19:30:47 2018 +0200

    Use real RSA public key

Attached is the copy of the test suite xbe: [default.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1934879/default.zip)

**Comment by ergo720** [comment]
The crash comes from the popg function, which is called during the decryption of the signature header. Not sure yet why it causes a crash, this handles fine xbe's with invalid signatures as well. Perhaps xbe's generated by nxdk are slightly different than those generated by official XDK?

![capture](https://user-images.githubusercontent.com/30000751/39088123-e1083000-45ac-11e8-8467-463f31f2b6a1.PNG)

**Comment by ergo720** [comment]
Fixed it: it seems that the digital signature generated by nxdk is all zeros, I modified the xbe by filling it with all 0xAA and now it works again. You will probably have to tell to nxdk to fill the digital signature with some bytes instead of all zeros.

**Comment by PatrickvL** [comment]
It might have something to do with calling conventions

**Comment by Fisherman166** [comment]
Nxdk does set the signature to 0 by default in tools/cxbe/Xbe.cpp:

        // nobody has the private key yet, so zero this out
        memset(m_Header.pbDigitalSignature, 0, 256);

Without submitting a pull request to NXDK I don't think this is possible to change in user code since the Xbe variable is created locally. Is it possible to modify Cxbx-R to handle a DigitalSignatue of 0 correctly?

**Comment by ergo720** [comment]
Well, detecting if the signature is all zero with memcmp and skipping the check should be enough

**Comment by Luca1991** [comment]
Wow I missed this issue. @ergo720 I've recently used (even today) various version of CxBx to test my newly implemented tests in KTS, and I haven't experienced any crash. So maybe the problem experienced by @Fisherman166 isn't caused by the digital signature?

I'm asking that because in the past (can't remember when) I had to manually remove the APPDATA cxbx folder to make cxbx to work again, and I know that @x1nixmzeng (and possibly others) had this problem too.

**Comment by Luca1991** [comment]
@ergo720 I'm not saying that this isn't real, but still I don't understand why it is working in my case

**Comment by ergo720** [comment]
No idea either ;)

**Comment by x1nixmzeng** [comment]
So @ergo720 introduced and fixed it quickly with the signature checks. If you aren't pulling remotely, or grabbing latest every other day this could be missed?

With the corrupted appdata I have a theory the last state isn't flushed before Cxbx crashes, or any legacy data (like the generated EEPROM) isn't fully compatiable as it changes.

Either way this bug should be closed off now :)

**Comment by PatrickvL** [comment]
@ergo720 fixed this in pull request https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1084
