### ISSUE TITLE
controller issues

### ISSUE THREAD

**Issue by powerpuffboysz** [Cxbx-Reloaded/Cxbx-Reloaded#1086]
I cant map the dpad on my controller. its a ds4 emulating a 360 pad with ds4windows. every other button maps fine but if I actually try to load a game the entire controller is unresponsive

**Comment by zebranco** [comment]
use Dualshock 4 controllers without an XInput Wrapper , and everything ends up being configured as axis -x
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770
Cxbx-Reloaded: Detected Negative RotaþÒo X on Wireless Controller770

**Comment by PatrickvL** [comment]
Do not use the controller configuration dialog when x-input is enabled - that dialog is only meant for keyboard controls. X-input works out of the box with most controllers
