### ISSUE TITLE
Visual Studio 2015 build failure

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1088]
Visual Studio 2015 does not compile current master. You will get:
Some (more than 5) C2872 errors.
Two abc errors - missing brackets in FUNC_EXPORTS (where is MUST be bracket - I don't know, FUNC_EXPORTS also called before and later, but VS2015 doesn't find errors there).
I already removed VS2015 from my PC, so I can't say exactly which files and strigs are with errors. You can check it yourself.
So maybe you should remove Visual Studio 2015 from README (prerequisites)?

**Comment by x1nixmzeng** [comment]
This is correct, we lost VS2015 compatibility fairly recently due how namespaces are (mis-)used.

Note to myself to upgrade cs_x86

**Comment by Margen67** [comment]
@x1nixmzeng `The older 2015 version works too.` Should be removed from here?
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Developer-notes#developer-environment

**Comment by Margen67** [comment]
It says right here VS2015 is not officially supported: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded#prerequisites-1

**Comment by gandalfthewhite19890404** [comment]
Here is commit which cause it - https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/1685ef4a08e86a46860802a73d82203367ad6a48

**Comment by LukeUsher** [comment]
I don't have visual studio 2015 and therefore have no way to test it. I only officially support 2017.
2015 support did work for a while, purely because we didn't make use of any new features yet, we can't guarantee this will always be the case.

That being said, if one wants to fix VS2015 support, I'll gladly accept a pull-request that does so.

**Comment by RadWolfie** [comment]
@gandalfthewhite19890404 Pretty sure we already know the problem. LukeUsher want to get rid of extra namespace on variables and declarations.

I'll work on pull-request to fix VS2015 support. Since it's only affecting EmuD3D8.cpp file.
