### ISSUE TITLE
Regression (Deathrow) no longer booting to menu.

### ISSUE THREAD

**Issue by Crimsom13** [Cxbx-Reloaded/Cxbx-Reloaded#1091]
![capture](https://user-images.githubusercontent.com/38405862/39326258-62b0f08e-4962-11e8-8c41-46ec7fa4da9f.JPG)

Just experienced regression in death row no longer boots to menu, crashes instantly.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1952602/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1952603/KrnlDebug.txt)

**Comment by Voxel9** [comment]
Report compatibility issues in the official tracker here https://github.com/Cxbx-Reloaded/game-compatibility/issues

This tracker is for issues about the emulator in general.

**Comment by PatrickvL** [comment]
Indeed. Although there isn't a compatibility issue for this title to compare to, so it's kind of hard to determine what sort of regression this is...

**Comment by Crimsom13** [comment]
Just putting the regression out there as soon as possible while it's fresh, maybe you can move it or close it.

**Comment by PatrickvL** [comment]
You should describe what the regression is about, as we currently can't compare this against a state-report that was better than now.

**Comment by PatrickvL** [comment]
In general, report all compatibility status on the game-compatibility issue tracker.

Regressions go there too, unless it's clear the error affects multiple titles, and wasn't happening before. Then a report in the main repository is helpful. But do include links to the compatibility reports that are related to it
