### ISSUE TITLE
Keyboard input not being registered (maybe issue with registry settings?)

### ISSUE THREAD

**Issue by yebelt** [Cxbx-Reloaded/Cxbx-Reloaded#1095]
In the registry on my system (Computer\HKEY_CURRENT_USER\Software\Cxbx-Reloaded\XBController), I notice that DeviceName 0x00 is a USB joystick (PS2 controller I was experimenting with, using "Config Controller..." menu instead of xinput to configure it), and DeviceName 0x01 is the SysKeyboard. 

When I try to use just the keyboard as input instead of the joystick (unplugged from system), the keyboard input never gets registered when running a game. I suspect this is because Cxbx only sees the 1 keyboard input device, but there's 2 input devices saved in the registry (I see the "Device Mapped to %s was not found" warning in the console log).

Is this a SW bug, or an issue with my registry settings?

**Comment by yebelt** [comment]
Forgot to mention that switching the device names around fixes the issue for me. Just thought I'd bring up the issue in case it was a SW bug.

**Comment by GHXZTBOY** [comment]
Try this:
Settings < Config Xbox Controller Mapping < Xbox Port 0 < DirectInput Port 0
Hope this helps, worked for me

**Comment by yebelt** [comment]
IIRC, that menu wasn't available when I filed this issue, so it might no longer be an issue anymore (am too lazy to try to reproduce it myself).

**Comment by ergo720** [comment]
Closing this for now, can be reopened if it's still an issue
