### ISSUE TITLE
Support progressive resolutions

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1096]
The XDK sample called "field render" renders odd and even scanlines at 60 Hz, at half resolution - get this to render correctly

**Comment by PatrickvL** [comment]
Within my viewport-scaling branch, the following fixes this issue : https://github.com/PatrickvL/Cxbx-Reloaded/commit/a08601d63150e59ba592298593dc77c4642e9ab3

**Comment by LukeUsher** [comment]
I think you mean interlaced ;)

Progressive scan is normal, all pixels are displayed

Interlaced is when you alrernate rendering the odd fields and sven fields and is how non-hd television process their signal.

**Comment by PatrickvL** [comment]
It's not entirely the same as interlaced, as interlaced displays still have the same backbuffer height as progressive. The "Field render" XDK sample however uses X_D3DPRESENTFLAG_FIELD, which halves the height of the Xbox backbuffer. 
On Xbox, this half-height backbuffer is displayed stretched (effectively doubling each scanline), so it still covers the entire screen.
Even frames and odd frames are drawn differently however, as they use an y offset of 0 versus 1, so that when swapping between these two types of frame ("fields"), the display is still perceived to be drawn at full resolution.
