### ISSUE TITLE
Cars NTSC-U Failed on uc_emu_start() with error returned: 6

### ISSUE THREAD

**Issue by chrisderwahre** [Cxbx-Reloaded/Cxbx-Reloaded#1106]
Game: Cars
Version: NTSC-U

Error: Failed on uc_emu_start() with error returned: 6
Configs:
EEPROM:
![screenshot_11](https://user-images.githubusercontent.com/23343464/39406303-fbc14518-4bb4-11e8-8b39-d269b2fdb2d0.png)
Video:
![screenshot_12](https://user-images.githubusercontent.com/23343464/39406313-11c6c63a-4bb5-11e8-8dba-7f41390f98d0.png)

**Comment by x1nixmzeng** [comment]
The unicorn code was reverted by #1111 so worth trying again on master @chrisderwahre

**Comment by LukeUsher** [comment]
This should no longer be a problem since unicorn was reverted.
