### ISSUE TITLE
My cxbxDon´t start  the game.

### ISSUE THREAD

**Issue by Peterson157** [Cxbx-Reloaded/Cxbx-Reloaded#1115]
When i put to play the game, he don't start the game and bring only black screen, even when i adjust the config video,audio. I am with the latest emulator version that you launched.

**Comment by Margen67** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)#a-game-stopped-working-after-i-updated-cxbx-reloaded

**Comment by LukeUsher** [comment]
This is not a support forum, but a place to report issues with the emulator itself

If you need help, please use one of the chat channels suggested in the readme
