### ISSUE TITLE
Lookup Xbox D3D state variables via OOVPA XREF's

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1120]
Our current OOVPA structures are already prepared to be used for looking up additional XREF symbols.

For this issue
* Enable these XREF's
* Extend them as much as possible (especially regarding D3D state variables)
* Make it so that these XREF's are derived from detected symbols
* Remove all custom lookup code which can be replaced by derived XREF's

**Comment by RadWolfie** [comment]
Moved the issue to XbSymbolDatabase repo.
