### ISSUE TITLE
Validate EndVisibilityTest_0

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1137]
Test cases:

* Conker: Live and Reloaded
* Riddick
* Test Drive: EOD
* Yager

**Comment by jarupxx** [comment]
I've validated EndVisibilityTest_0. Thank you all the testers!

**Comment by PatrickvL** [comment]
Fixed by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1140
