### ISSUE TITLE
Iron Phoenix - Recieved Exception Code 0xC0000005 @ EIP := 0x0023368C

### ISSUE THREAD

**Issue by fuhuan416** [Cxbx-Reloaded/Cxbx-Reloaded#114]
When i was checked LLE->GPU and start the game, i will get this dialog.
Recieved Exception Code 0xC0000005 @ EIP := 0x0023368C

When i was unchecked any LLE, then i will get iDirect3D8::CreateDevice failed(Invalid Call)

For the game Iron Phoenix.

**Comment by BenNottelling** [comment]
@LukeUsher I get a CreateDevice fail every time I use hardware Video mode.

**Comment by LukeUsher** [comment]
The 'use hardware video mode' checkbox probably doesn't do what you think it does. Cxbx-Reloaded is hardware accelerated regardless of that option. What this checkbox actually does, is force Cxbx-Reloaded to run in exclusive full-screen mode at the selected resolution. If this is not supported by your graphics card/monitor combination (very likely, if a low resolution is used by the emulator and game) then it won't work.

It's best to leave that disabled.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#189
