### ISSUE TITLE
Allocate and AllocateZeroed memory functions

### ISSUE THREAD

**Issue by ghost** [Cxbx-Reloaded/Cxbx-Reloaded#1145]
These two functions are currently used in various places in the code and I have seen that they usually request very small amounts of memory so, perhaps, the pool manager is more indicated in those cases since it's designed to allocate small amounts of memory. Also, why are they needed in the first place? They don't exist as Xbox APIs, they are a construct from us, could they be dropped now?

**Comment by PatrickvL** [comment]
I agree, good thinking

**Comment by LukeUsher** [comment]
They are used for when we need to allocate memory in the Xbox address space, rather than the host address space, allocations that the VM Manager can keep track of. They could be replaced with Kernel APIs, but they do need to be tracked by the VM Manager.
