### ISSUE TITLE
XBE .text altered after loaded with no reason

### ISSUE THREAD

**Issue by jackchentwkh** [Cxbx-Reloaded/Cxbx-Reloaded#1148]
[0x2078] INIT: Title : Crimson Skies
[0x2078] INIT: XBE TitleID : 4D530021
[0x2078] INIT: XBE TitleName : Crimson Skies

a rdtsc instruction located at 
.text:001C4F98 0F 31                                   rdtsc

this opcode 0F will be altered after to 03 once the XBE is loaded into emu.
which resulted in failure of rdtsc pattern search and patch.

It's not the FS patching's problem. 
need further investigation.

**Comment by jackchentwkh** [comment]
find the source, it's subhook, the rdtsc code belongs to QueryPerformanceCounter, and our OOVPA identified it, then subhook patched the function. 
so it's safe

**Comment by PatrickvL** [comment]
Good find! If there's no related problem still to be investigated, then please close this issue.
