### ISSUE TITLE
Popup issues

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1157]
**NOTE: Please sort by ticket number from newest to oldest.**

---
This issue is not an actual issue, but a collection of all issues that are about LOG_TEST_CASE popups.
(the corresponding [list of test-case-popup issues can be retrieved here](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues?q=is%3Aissue+label%3Atest-case-popup))

* requested value for pTimeStamp In EmuPatch_D3DDevice_GetVisibilityTestResult https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1875
* PushBuffer has fixups In EmuExecutePushBuffer https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1874
* Register < 0 In EmuPatch_D3DDevice_SetVertexData4f https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1873
* CONST https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1787
* X_D3DVSD_TOKEN_CONSTMEM https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1786
* Skipping Release of active Xbox Render Target https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1779
* RegNum > NumTemps https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1777
* Xbox CreateDevice did not call SetRenderTarget https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1733
* Shader uses undeclared Vertex Input Registers https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1724
* pViewport = null In EmuPatch_D3DDevice_SetViewport https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1659
* Existing RenderTarget width/height changed In ValidateRenderTargetDimensions https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1658
* Too many mip-map levels https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1587
* Pushbuffer COMMAND_FLAGS_RETURN with additional bits?! #1480
* Pushbuffer COMMAND_FLAGS_LONG_NON_INCREASING_METHODS [IB-mode only] not available on NV2A #1479
* Pushbuffer COMMAND_INSTRUCTION unknown #1478
* Pushbuffer COMMAND_INSTRUCTION_JUMP #1477
* D3DDevice_SetVertexData4f with active VertexShader #1476
* Pushbuffer COMMAND_TYPE unknown #1475
* Pushbuffer COMMAND_TYPE_CALL while another call was active #1474
* Pushbuffer COMMAND_TYPE_CALL #1473
* Last pushbuffer instruction exceeds END of Data #1472
* Pushbuffer COMMAND_TYPE_JUMP_LONG https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1471
* Verify X_D3DVSDT_NONE In ConvertStream https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1206
* Invalid VertexCount In EmuPatch_D3DDevice_DrawVertices https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1185
* X_D3DPT_POLYGON In Apply https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1177
* X_D3DVSDT_NORMSHORT4 In ConvertStream https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1173
* Validate D3DDevice_EndVisibilityTest_0 https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1172
* using CxbxActiveTextureCopies In SwitchTexture https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1159
* X_D3DPT_QUADLIST StartVertex > 0 https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1156
* CreateDepthStencilSurface failed https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1108
* CreateDevice failed https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1107
* dwHeight < dwMinSize https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1075
* dwDepth != 1 https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1070
* CreateTexture Failed https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1064
---
**NOTE: Please sort by ticket number from newest to oldest.**

**Comment by ObiKKa** [comment]
I think I saw a couple recent game issues where the wording 'EndVisibility' or similar was shown in screen captures. Can you explain what that means?

**Comment by PatrickvL** [comment]
Do create an issue for that too

**Comment by RadWolfie** [comment]
Added "Too many mip-map levels" issue to the list.

**Comment by ergo720** [comment]
Do we still need this issue? Since now all pop-up issues have the `test-case-popup` label, they can easily be found on the issue tracker by searching for issues with that label. Thus, we no longer need to link them here to find them.

**Comment by PatrickvL** [comment]
I agree - there's no real benefit of maintaining this overview manually, when the test-case-popup label can produce the same list, which would always be up-to-date as well. Closing.
