### ISSUE TITLE
SetRenderTarget background information

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1158]
Here a hardcopy of some background information on SetRenderTarget, explaining what's wrong with it currently;

SetRenderTarget often fails
This is because the render target surface that is passed to SetRenderTarget isn't created correctly
There's code already that can create acceptable render target surfaces
But it's disabled, because once these get passed to SetRenderTarget, the entire screen stays black
This happens because SetRenderTarget causes all drawing to go to those render target surfaces, meaning nothing gets drawn to the host backbuffer anymore

Thus, the backbuffer stays black
Thus, nothing is visible on screen anymore
The ugly truth is, that we currently see graphics appear only because SetRenderTarget fails
As long as SetRenderTarget fails, by default all drawing goes to the host backbuffer
That's the reason many titles show squares in the top-left corner of the screen, often filled with silhouettes or shadows - these are effects that should have been drawn to separate render targets
Those render targets should have received the draw output, so that their textures would be used in following draw calls as shadow masks and whatnot 
So, because those render targets currently aren't targeted, not only does the host backbuffer gets unintended draws to it's top-left corner, but the rest of the drawing is missing effects that should have been present in the intended render targets
Now, as I said above, the fix is already available, but if that's enabled, nothing appears on-screen anymore.
Instead, render targets are used correctly (I presume), thus actual drawing uses correct render target contents, but it just isn't visible
And everything being invisible is due to this https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1118
The main problem is, how to discover which Xbox surfaces are used as backbuffer
If we know what Xbox surface is used as backbuffer, then we could copy it's (host counterpart) contents to host backbuffer during swap 
Xbox has at most 3 surfaces reserved for backbuffer
Our SetRenderTarget patch currently calls host SetRenderTarget, but it fails on host, so nothing is actually changed on host - it keeps targeting host backbuffer for all following draws
The code that results in a successful host SetRenderTarget call, which is currently disabled, is the call to CreateRenderTarget
Everything will be a test-case, as all XDK based software uses this approach - it's part of the d3d base code linked into all these xbe's

In our swap/present patch, the contents of the host counterpart of the Xbox backbuffer surface (which had received all drawing output) should be copied to the host backbuffer using CopyRects or something like that
Also, in our SetRenderTarget patch, avoid passing null to host SetRenderTarget, as that would keep targeting the host backbuffer (until a non-null surfaced is passed to host SetRenderTarget after the previous swap)
One thing I already tried, was to set a Boolean to true in our swap/present patch, assuming that when this Boolean is set, the very next Xbox call to SetRenderTarget would give us the Xbox backbuffer. (Obviously, the boolean needs to be reset once handled) Alas, that didn't give me a reliable result (everything stayed black, even though I called CopyRects from the host counterpart of the Xbox surface I got via that way, towards the host backbuffer) 

A totally different approach could be to pass in our own fake Xbox backbuffer surfaces via the initial D3D creation parameters (there's a member for user-supplied backbuffers in there)

And yet another way would be to derive the memory location of the Xbox D3D global variable where Xbox code stores it's backbuffer pointers. 
For that last idea, we would need to extend our OOVPA database, but since Radwolfie is currently busy with a major redesign of the symbol detection code, that wouldn't be good timing

Luke has another suggestion to get the Xbox backbuffer : call Xbox GetBackBuffer via a trampoline. However, that requires this function to be linked into the Xbe, which might not always be the case (unless it's always available of course).

**Comment by jackchentwkh** [comment]
the XBOX D3D back buffer can be derived from D3DDEVICE directly.
by reversing the GetBackBuffer2(int a1) functions of OTOGI as example:

```
int __stdcall D3DDevice_GetBackBuffer2(int a1)
{
  int v1; // esi

  if ( a1 == -1 )
  {
    v1 = *(_DWORD *)(D3DDEVICE + 5624);
    D3DResource_AddRef(*(_DWORD *)(D3DDEVICE + 5624));
  }
  else
  {
    v1 = *(_DWORD *)(D3DDEVICE + 4 * (a1 != 0 ? 2 : 0) + 5620);
    D3DResource_AddRef(v1);
  }
  return v1;
}
```
a1 is back buffer index, a1==-1 stands for front buffer, a1==0 stands for 1st back buffer.

**Comment by jackchentwkh** [comment]
RalliSport uses different convection

```
int __stdcall D3DDevice_GetBackBuffer(int a1, int a2, _DWORD *a3)
{
  int v3; // eax
  int v4; // eax

  if ( a1 == -1 )
    v3 = 1;
  else
    v3 = a1 != 0 ? 2 : 0;
  v4 = *(_DWORD *)(D3DDEVICE + 4 * v3 + 8316);
  *a3 = v4;
  return D3DResource_AddRef(v4);
}
```
