### ISSUE TITLE
Suggestion - Logging system via Easylogging++

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1166]
Here is Easyloggingplusplus - logging system. Simple - one header and one cpp file.
https://github.com/muflihun/easyloggingpp.

**Comment by RadWolfie** [comment]
@PatrickvL's response to the request.
> Note, that our current logging is already present, so there's not much reason to switch to such a logging library
Therefore, please describe what benefits it brings in the issue itself

I'm not really sure if we need to replace the log system with Easylogging++ due to existence of our own logging system. It can have some improvements on the go.

**Comment by ergo720** [comment]
Considering all the effort that has been put on our logging system, I think we can say that we are not going to rewrite everything just to use a different library. Closing.
