### ISSUE TITLE
Fix Turok backgrounds in Cheats and Artwork menus

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#117]
In Turok, the background images in the Cheats and Artwork gallery menus are garbled differently than before.
Possibly happened when I picked up the conversion of paletized textures (for Battlestar Galactica).
I discovered during tests when I was disabling most of the XG(Un)swizzle patches.

I've checked in an older (my OOVPA refactoring) branch, that these images were already damaged (although garbled differently) before.

**Comment by BenNottelling** [comment]
Still partially affected.
![capture5](https://user-images.githubusercontent.com/17304943/28756902-be414238-752c-11e7-90c3-e63da1ed9ebe.PNG)
![capture](https://user-images.githubusercontent.com/17304943/28756901-be40f274-752c-11e7-802b-ce13e589c639.PNG)
![capture2](https://user-images.githubusercontent.com/17304943/28756903-be438d68-752c-11e7-965b-2dd2f0ffd728.PNG)
![capture3](https://user-images.githubusercontent.com/17304943/28756904-be452862-752c-11e7-9a93-0167540a0e1d.PNG)
![capture4](https://user-images.githubusercontent.com/17304943/28756905-be5aafac-752c-11e7-88fb-adb472ed2485.PNG)

**Comment by PatrickvL** [comment]
These are fixed in one of my WIP brakes

**Comment by BenNottelling** [comment]
Okay

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#188
