### ISSUE TITLE
Verify popup "Validate this function! In EmuPatch_D3DDevice_EndVisibilityTest_0"

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/Cxbx-Reloaded#1172]
**NOTE:** Using similar template as Patrick's other [pop-up message threads](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1157). He, another leading programmer or admin may take over this original post whenever they wish to.

 ---

Verify if the test case pop-up message, "_Validate this function!
In EmuPatch_D3DDevice_EndVisibilityTest_0_" is being handled correctly.

If not, describe here what is wrong with it, and try to fix it.
Once it's deemed correct, disable the popup.

Test cases:
- [Battle Engine Aquila](https://github.com/Cxbx-Reloaded/game-compatibility/issues/251#issuecomment-386817038)
- [Conker: Live and Reloaded](https://github.com/Cxbx-Reloaded/game-compatibility/issues/154#issuecomment-386869459)
- [Rallisport Challenge 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/526#issuecomment-385604414)

**Comment by ergo720** [comment]
This popup was removed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/03921a4b2a9c77acab436bcaae25b5bb9f7ccc75 so closing this now
