### ISSUE TITLE
Cache converted vertex buffers

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1174]
Unlike textures and index buffers, vertex buffers currently aren't cached in Cxbx-Reloaded.

One of the reasons behind that could be that the conversion of vertex buffers depends on the accompanying vertex declaration, which describes how the elements in a vertex buffer are to be interpreted. It's not directly obvious how to implement that in a global cache.

So, for this issue, try to simplify our vertex buffer conversion code a bit more, so that it becomes clearer what's needed for a global Xbox-to host-converted vertex buffer cache.

Then, implement it.

Be careful not to cause regressions, but once this cache is build and active, rendering speed should improve significantly.

**Comment by LukeUsher** [comment]
please see #1277
