### ISSUE TITLE
Eeprom is corrupted if I'd set Xbox Region to Japan

### ISSUE THREAD

**Issue by jeltaqq** [Cxbx-Reloaded/Cxbx-Reloaded#1199]
I'd like to set Xbox Region to Japan but cannot manage to do it by myself.
I've accept Japan but eeprom is corrupted.

Configuration
![config](https://user-images.githubusercontent.com/25340049/40478664-a68f8f4e-5f84-11e8-96d8-ef48e3b3899b.jpg)

Result
![result](https://user-images.githubusercontent.com/25340049/40478669-aa70a116-5f84-11e8-8368-13c2e8dc2fef.jpg)

**Comment by ergo720** [comment]
It works fine here. I'd say the culprit could be the memory corruption that sometimes happens but that should only occur when the emulator is running

Before
![capture](https://user-images.githubusercontent.com/30000751/40480450-d8e0e456-5f4e-11e8-9c5b-645bebf0e902.PNG)
After
![capture2](https://user-images.githubusercontent.com/30000751/40480452-d90b6a00-5f4e-11e8-8301-a3909dc52c52.PNG)
Before
![capture3](https://user-images.githubusercontent.com/30000751/40480454-d94e08a6-5f4e-11e8-8f89-a8aaab320ef5.PNG)
After
![capture4](https://user-images.githubusercontent.com/30000751/40480456-d9786ac4-5f4e-11e8-8863-6350499c11c9.PNG)

**Comment by jeltaqq** [comment]
Works fine North America. It's very strange, but Confounder or HDD key is not 0, eeprom is fine.
before
![before](https://user-images.githubusercontent.com/25340049/40482076-7350f1fe-5f8e-11e8-82b6-7fd1106622bb.jpg)
after
![after](https://user-images.githubusercontent.com/25340049/40482083-76c2e52c-5f8e-11e8-8dc7-14ddb0f5c98c.jpg)

**Comment by ergo720** [comment]
I had seen in the past my eeprom become almost all 1's (see the last 3 comments in #1016), and we thought that happens because of memory corruption in the emu. From your findings, then it seems to happen also in the GUI process. BTW, can you try to hit the reset button and do the changes again to see if it works?

**Comment by jeltaqq** [comment]
When I press the reset button, eeprom appears as before.bin. Does this match your eeprom? When I change the region become EEPROM.bin. First bytes has increased to 15 bytes.
![eeprom](https://user-images.githubusercontent.com/25340049/40516932-e4a997b6-5fed-11e8-909d-47276ee5281a.jpg)

**Comment by x1nixmzeng** [comment]
It occurs 100% with these steps:

1) Delete EEPROM.bin from your AppData folder
2) Open an XBE
3) Close the XBE
4) Open the EEPROM dialog, then Reset, then Accept
5) Open the EEPROM dialog, change to Japan, hit Accept
6) Open the EEPROM dialog to see it corrupted

**Comment by x1nixmzeng** [comment]
It's a wierd one!

I think it's to do with the file mapping (see `CxbxRestoreEEPROM`), which is a memory-mapped file.

Unfortunately, the accept dialog (see `IDC_EE_ACCEPT`) ignores the open memory mapping and trashes the data. The write isn't actually needed as writing to 'memory' is mapped to the file:

```cpp
WriteEepromInMemory(hWndDlg);

// vv not needed
std::basic_ofstream<uint8_t> EepromFile(szFilePath_EEPROM_bin, std::ios::out);
if (EepromFile.is_open()) {
	EepromFile.write(reinterpret_cast<uint8_t*>(pEEPROM_GUI), EEPROM_SIZE);
	EepromFile.close();
}
// ^^ not needed
```

**Comment by RadWolfie** [comment]
@x1nixmzeng Don't worry about it. I found the source of cause.

**Comment by AlfredoDore** [comment]
I have this problem
![imagem](https://user-images.githubusercontent.com/90729203/172008648-225f82de-4552-4644-9f31-5640616e6d4f.png)

**Comment by PatrickvL** [comment]
@AlfredoDore This issue is closed for quite some time already, and you seem to have a different issue as well. But before you create a new issue, first check if there's another CxbxReloaded process lingering around (which sometimes happens when it didn't close correctly) - in that case, killing it might help.
