### ISSUE TITLE
To the CXBX-R Team:

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/Cxbx-Reloaded#1203]
This emulator is really amazing and swell done for low PC's as well. I played Dead Or Alive 3 & Jet Radio Future, and they where running pretty excellent! I'm getting at least 45 to 60fps by those 2 games from using the "Use Hardware Video Mode." But in the next update, Is it possible that you guys can fix these Resolution Option for weak PC's from the next update, please? Because I tried them out by using windowed mode instead of using the "Use Hardware Video Mode." to see can my games run better, so I tried to turn the graphics down to 640x480 by config the Resolution to make my games to run smoother, but their all running the same like is on 1920x1080 for some reason. But, A BIG Thanks to you guys for putting all that hard work to this. That acceleration was a Jaw Dropping Amazing.

![untitled](https://user-images.githubusercontent.com/39503785/40543590-18498496-5ff3-11e8-9b02-87af4e98b900.png)

**Comment by SonicThePS4** [comment]
Oh okay, my apologies. I thought it didn't go through.

**Comment by RadWolfie** [comment]
Sorry, I thought this was on game compatibility list repo.

Providing PC specs isn't needed as it is impacting high-end computer anyway. 😉

**Comment by HyperScorpio** [comment]
The problem is a few maps of JSRF constantily continue to be slow, even with boost Dash doesn´t help a lot. In the Stadium map the boot Dash works amazing not even a break throw the fps. 😢

**Comment by SonicThePS4** [comment]
@HyperScorpio Yeah but don't worry, Pal I'm sure the CXBX-R team is hearing us out lol They'll fix these problems in the next update. I just mainly want them to fix the Resolution Option so we can turn down the graphics. So our games can run smoother for the weak PC users as well. But a big thanks and a big shout out towards the CXBX-R team :D

**Comment by SonicThePS4** [comment]
@RadWolfie Yeah, I figure that much lol ;) I'm glad I got Jet Set Radio, and Dead or Alive 3, & Dead or Alive 1 Ultimate, including Auto Modellista working. I just hope they'll fix the Resolution Option in the next Update for the weak Graphic Card users, as all :)

**Comment by SonicThePS4** [comment]
@HyperScorpio Ah, I see. Well, I'm sure it'll be a worth wait. Because they had that excellent acceleration on point back in April. So Is a possibility they'll work on more games while they're trying to fix the Resolution Options bug for weak PC's.

**Comment by HyperScorpio** [comment]
@SonicThePS4 Intel Core i7 920 i don´t see why my potato is that bad if the games of today run 100%.

**Comment by SonicThePS4** [comment]
It is a new Emulator, we just have to wait and see what they can do My PC is running like sack of potato's as well because, my AMD Vision Graphic Card is so low.
