### ISSUE TITLE
Review old code in EmuXapi.cpp regarding Xinput api

### ISSUE THREAD

**Issue by jackchentwkh** [Cxbx-Reloaded/Cxbx-Reloaded#1209]
New implementation for Xbox controller port to host port assignment marked out lots of old XInput api code in EmuXapi.cpp, and tag them with Old_Code. 
Need to review these code whether they are still needed or not. If not needed, removed them completely.

Edit : origin : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1196#issuecomment-390977125

**Comment by ergo720** [comment]
`EmuXapi.cpp` was renamed to `Xapi.cpp` in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1425 and the `OLD_XINPUT` tagged code was removed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1713, so closing this.
