### ISSUE TITLE
Burnout Revenge freeze

### ISSUE THREAD

**Issue by TotalCaesar659** [Cxbx-Reloaded/Cxbx-Reloaded#121]
Burniut Revenge freezes without a reaction (black screen only).
Version https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/92fa6d9ecad408f0d10cc80df4feaea164752eda.
Windows 7 x64.
KrnlDebug.txt:
>[0xA0C] EmuMain: Cxbx-Reloaded Version 95884ee (Jan 20 2017)
[0xA0C] EmuMain: Debug Console Allocated (DM_FILE).
[0xA0C] EmuMain: Debug Trace Disabled.
CxbxDbg> Found
Skipped
Found
Skipped
Found
Skipped
Skipped
Skipped
Skipped
Found
Skipped
Found
Skipped
Found
Skipped
Found
Skipped
Skipped
Skipped
Skipped
Found
Skipped
HalRegisterShutdownNotification unimplemented!
KeSetTimer forwarding to "KeSetTimerEx"...
NtOpenFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
NtCreateFile forwarding to "IoCreateFile"...
[0x154C] EmuWarn: EmuKrnl: IoCreateFile Failed! (0xC000003A)
>
>NtWaitForSingleObjectEx forwarding to "KeWaitForMultipleObjects"...

**Comment by PatrickvL** [comment]
I suspect this will happen to many other titles too. Perhaps these type of reports can better be done in the compatibility database on the Cxbx reloaded website

**Comment by TotalCaesar659** [comment]
Re-test for checking a progress.
It's LTCG title:
![87](https://user-images.githubusercontent.com/14265316/28735865-f43e4cc0-73ef-11e7-9cfb-4ab550367da0.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1184242/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
We can't support LTCG titles using HLE, so I'll close this issue for now.

**Comment by TotalCaesar659** [comment]
Please, edit the compatibility list (https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/222) then.

**Comment by PatrickvL** [comment]
I will, as soon as I can

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#192
