### ISSUE TITLE
(Temporary) Website-Web "recommendation" (Temporary)

### ISSUE THREAD

**Issue by AzurikRiseOfPerathia** [Cxbx-Reloaded/Cxbx-Reloaded#1219]
**# (Temporary)**

Website-Web **recommendation**

Hi everybody. This issue will be removed, I ask you a recommendation on the construction of the website in the recordable games.

I have a construction that would be

Like in Dolphin, but each game has dashboard and a site that leads on the game's Git-Up page.

**5 X** would then be present

**X**: The game starts, but does not work on the intro.

**XX**: The game works until the intros

**XXX**: The game works, but a lot of graphics bug and slowdown until the crash of the game are present

**XXXX**: The game works very well, but the risk of slowing down, or crash or mini graphic problem remains

**XXXXX**: the game works PERFECTLY

On each game a window will appear once click on 3 small dots which will contain

The links of this GIT-UP page, and are dashboard, the X accounting note and description of the problem and until where the game works.

That's all it is to do, but I could be a great help because I personally manage the commercial site of my father's brand. that is all.

**Comment by BenNottelling** [comment]
GIT-UP? Do you mean GitHub? 
And just to clarify, you think that each game should have an individual page to describe how well it works with an "x"? Kind of like how Amazon has ratings in stars?

**Comment by AzurikRiseOfPerathia** [comment]
Yes I fail ^^ But if not yes, the X would just note if the game and playable or not No problem i delete this issus
