### ISSUE TITLE
Antivirus False Positive: Some scanning engines detect Cxbx-Reloaded as Gen:Varient.Zbot.78

### ISSUE THREAD

**Issue by xana43** [Cxbx-Reloaded/Cxbx-Reloaded#1225]
I'm not sure if this is a problem with the program, or with the anti-virus i'm using (bull guard) and i'm not sure if i'm the only one encountering this, but Recently I've been getting this warning from my anti-virus that Cxbx.exe has a what appears to be a trojan in it, again, i'm not sure if i'm the only one encountering this.

**Comment by PatrickvL** [comment]
Please add a link to a web page explaining this apparent virus vector.

Most likely, Cxbx is flagged because we're using low level nt.dll functions.

**Comment by xana43** [comment]
this is the information on this detection

https://www.symantec.com/security-center/writeup/2010-011016-3514-99

**Comment by LukeUsher** [comment]
VirusTotal confirms that 8/64 virus scanning engines wrongly detect Cxbx-Reloaded as dangerous: This is most likely caused by the fact that Cxbx-Reloaded uses some unusual APIs/doesn't look like a normal windows application.

It may be worth sending samples to these vendors and opening communication to prove we're not malicious.

![image](https://user-images.githubusercontent.com/740003/40689017-41af81de-6398-11e8-8365-d74f3295d9d1.png)

**Comment by x1nixmzeng** [comment]
It used to be any EXE packers would be flagged as some generic malware. If we're still using UPX we could keep it unpacked. Since it's zipped up anyway it won't increase the download size.

**Comment by x1nixmzeng** [comment]
Whatever is detected, it's been introduced fairly recently.

This released ZIP is clean:
https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/d74dc7dc524ddc916dffe1f5eb26e7d7004d694a/job/q42lb8migrc4u6tm/artifacts

**Comment by x1nixmzeng** [comment]
I'm not sure anything can be done about false positives. Most of the release ZIP files I've tested are clean on VirusTotal - there isn't anything to narrow down.

I'd be worth uploading the artifacts and checking a build before tagging any releases though. Otherwise, :man_shrugging:

**Comment by LukeUsher** [comment]
This seems to no longer be an issue.
