### ISSUE TITLE
Some titles does not accept gamepad

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1234]
Test cases:
* Star Wars Knights of the Old Republic
* Star Wars Knights of the Old Republic 2
* There are few other titles has the same problem.

Source of cause:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/2b52b6f91832a26bc74afa7c394f424d2c7af632/src/CxbxKrnl/EmuXapi.cpp#L756

For some reason device info internally with variable named subType from XID_TYPE_INFORMATION could be wrong.
Value obtained from source:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/2b52b6f91832a26bc74afa7c394f424d2c7af632/src/CxbxKrnl/EmuXapi.h#L179

It might be possible to obtain the value directly from hardware device or some sort of switch/conversion in the official xdk.

Real sample obtain from kotor:
```
DeviceTable[0]->ucType = 1, ucSubType = 4
DeviceTable[0]->XppType = 0x003DEF8C (XDEVICE_TYPE_GAMEPAD)
----------------------------------------
DeviceTable[1]->ucType = 3, ucSubType = 1
DeviceTable[1]->XppType = 0x003DEFF0 (Unknown device type)
```

Gamepad's SubType for XAPI level is 1, not 4 by the way.

**Comment by PatrickvL** [comment]
Duplicate of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1222

**Comment by RadWolfie** [comment]
Oops, thanks @PatrickvL! 😆
