### ISSUE TITLE
Turok menu : two poles show normals instead of textures

### ISSUE THREAD

**Issue by Paradise12314** [Cxbx-Reloaded/Cxbx-Reloaded#1237]
The Regression that happened with Turok has been fixed. I'm not sure which version was the fixer, but all the textures now show. There's just 2 big pole things in the Menu that are showing the Normals instead.

![menu](https://user-images.githubusercontent.com/24655069/40836409-8e5f1d08-658e-11e8-9c4c-626446fb1419.jpg)
![ingame](https://user-images.githubusercontent.com/24655069/40836414-93a850c2-658e-11e8-8823-c885b0886c97.jpg)

It's actually better now. Because ingame, the HUD and Crosshairs are also showing.
So this issue can be closed:
#991

**Comment by PatrickvL** [comment]
Actually, let's keep this open for the "two columns" issue

**Comment by Paradise12314** [comment]
I'm not sure what those Poles/Pillars do differently to show Textures. I was thinking perhaps they are just flat Sprites? But then the Normals would be flat color too. But looking at them, the Normals show obvious curvature. So they are 3D Models.

Would any of the CXBX Logs show signs of missing Textures or Shaders to help?

**Comment by RadWolfie** [comment]
Two poles are rendered correctly, we can close the issue. It's been fixed for awhile. I'm not sure which pull request fixed it.
