### ISSUE TITLE
"Run Xbox threads on all cores" Can't be disabled.

### ISSUE THREAD

**Issue by Paradise12314** [Cxbx-Reloaded/Cxbx-Reloaded#1238]
There is currently a problem with the Multithreaded hack. If you disable it, you'll find all Cores are still maxed out. Now I'm not sure what the behavior was when the hack was introduced, but I'm guessing disabling it should run just 1 Core?

![settings](https://user-images.githubusercontent.com/24655069/40836665-7905d798-658f-11e8-83aa-a85b64c699ab.jpg)
![osd](https://user-images.githubusercontent.com/24655069/40836669-7c5bf3be-658f-11e8-856b-4b96ab5d1d78.jpg)

**Comment by LukeUsher** [comment]
All cores can be used by Cxbx-Reloaded regardless: All the hack does is determine on which CPU the Xbox game code runs. Emulator code is still free to run anywhere

**Comment by HyperScorpio** [comment]
It doesn´t change anything to me.
