### ISSUE TITLE
[DEV] TAS input Fonctionnality [DEV]

### ISSUE THREAD

**Issue by AzurikRiseOfPerathia** [Cxbx-Reloaded/Cxbx-Reloaded#1239]
**## IDEA**

Hi all, I propose an idea of ​​functionality that is TAS input. (Tool Assist Speedrun) with a recording system which takes into account all the images at the same time, 

**## WHAT IS THE TAS ?**

The TAS and a practice in speedrun which is done with a tool entered TAS, which consists image by second make the performance the most optimal as possible.

So the TAS entry could be set up on games already in a state of perfect reliability.

**Comment by ergo720** [comment]
From what I learned, TASing a game requires that the state of the emulated machine must be deterministic with respect of the saved inputs. Because of the way cxbxr works, there's mostly no xbox machine state to begin with, so I'm tempted to close this as impossible to implement.
