### ISSUE TITLE
HLE scanning order

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#124]
The order in which OOVPA's are scanned, greatly influence the correctness of the outcome. With the right order, most of not all functions are located correctly, resulting in correctly placed patches, resulting in better emulation than when the order is wrong. When the order is wrong, functions are located incorrectly, leading to incorrectly placed patches, leading to crashes and otherwise incorrect emulation. 

Currently, there's an effort underway to order the OOVPA's in code alphabetically, giving a well defined ordering, and as a result, duplicates or omissions can be easily spotted and corrected.

Alphabetical ordering is however a 'wrong' order to use during scanning, as described above. 

So, we should devise a scanning order, leading to the highest possible ratio of correctly located functions. 

One such scanning order could be to scan for big functions first, smaller functions later. 

Also, we could scan for xrefs first, patches later. 

Another idea is to scan with one OOVPA version per xref/patch first, ideally the version linked into the executable.
Keep the current approach in which the memory is scanned again until no more symbols are found.
Then, for any symbol not yet found in the first phase, scan using the nearest OOVPA version available. 
Once that's done, either stop or repeat one last time with the next-nearest OOVPA versions.
Any symbol still not found, must be deemed not present. 

Let's discuss this idea, and if possible, others, please.

**Comment by x1nixmzeng** [comment]
Would this problem be solved by knowing the precise API number used to build the game? If so, is this not detectable from the XBE headers?

**Comment by PatrickvL** [comment]
The XBE indeed contains a version number per linked library. We might have OOVPA signatures for that exact version, otherwise we have OOVPA signatures for one or more other version numbers.
What I'd like to discuss, is which scanning approach will give the best results.

**Comment by x1nixmzeng** [comment]
Ok, so alphabetically sorted signatures are pointless. The search algorithm needs to prioritise signatures with the most context over part-matches - so we might want to include wildcard bytes and update the signature bytes.

How are the APIs currently identified? Marked up from known XBE files with specific API linkage?

How are APIs linked? Do they exist as source files (which may be differently optimized) or are they part of the XDK as recompiled OBJs? It might be possible to restrict the search for certain areas of memory, and certainly only looking in executable sections!

**Comment by PatrickvL** [comment]
Keeping OOVPA registration alphabetically sorted is a wise thing to do, as it quickly gives an overview of what's registered with which versions, and how. It can easily be kept up to date using an IDE sorting function.

Wildcard bytes are already present, or more accurately : implied, as the OOVPA's only specify a few fixed offset + value tuples, just enough to make the OOVPA unique and reasonably reliable detectable in memory.
 
Adding more offset+value pairs to weak OOVPA's is one method to reduce false positive hits, but we don't want to go too far with that, as it would enlarge the OOVPA database included in the emulator, and would slow down scanning speed even more.

XBE's are linked to binary library objects files, originally distributed with Xbox Development Kits (XDK's). 
Other software, like homebrew is sometimes linked to the OpenXDK library files - Cxbx doesn't offer support for these.

Detecting API's manually can be done with a tool like IDA Pro, when using the right signature files. IDA Pro is an expensive tool however, so another approach can be to obtain a dump of binary XDK library object files in a more readable output format, like the so-called pattern-files. These are parsed by the PatternTrieBuilder tool I build for Dxbx, which in turn creates a trie of signatures, which is used by Dxbx to scan for functions. Other Cxbx developers have used other tooling - I don't know which. In the end, all that matters (for HLE emulation) is that Cxbx contains enough OOVPA's so all the required patches can be placed to support an XBE.

As for the scanning - the current method already scans just the memory range in which code can reside.

All this is 'just'background information, which must surely be known, but instead of in an issue like this, should belong in a wiki, so no repeated explanations have to be written.

The actual discussion needs to be about which search method is best, in a concise but detailed manner.

**Comment by PatrickvL** [comment]
Let me add this : an OOVPA is all about the predictable locating of a function. Functions normally appear unmodified in an XBE, so by definition wildcards that could make multiple locations in an XBE become a possible match don't belong in OOVPA's.

**Comment by jarupxx** [comment]
Is there a game that uses older versions only for certain functions? If not, I think that by first scanning xrefs we will get the best results. 

Since xrefs has functions to detect using multiple xrefs, so we need to scan in exact order (Example: IDirectSoundBuffer8_SetMixBins).

**Comment by LukeUsher** [comment]
I think that scanning in order of function size is a good idea, that way we can identify large functions and mark the area they cover as 'matched' so it should not be searched in future. This would reduce the amount of space the smaller OOVPAs have to scan, hopefully leading to a lower chance of false positivies

**Comment by PatrickvL** [comment]
I just realized Cxbx is already equipped with a hard-coded set of functions that are detected first.
In the bXRefFirstPass case of EmuHLEIntercept, it tries to find two functions;

First, it calls EmuLocateFunction for D3DDevice_SetRenderState_CullMode, in order to derive D3DDeferredRenderState from that, which is used to determine XRef's like XREF_D3DDEVICE, XREF_D3DRS_MULTISAMPLEMODE, and a few others.

Second, it calls EmuLocateFunction for D3DDevice_SetTextureState_TexCoordIndex, in order to derive EmuD3DDeferredTextureState from that.

These two Deferred-State symbols point to global XBox data structures that are needed during rendering.

What we can learn from this is, that there are already a few symbols that are scanned for first. We might just as well do something similair ourselves, with a select few OOVPA's that describe not only the "bigger" OOVPA's, but also the most central ones. Especially if these are XRef-checked during the scanning for other OOVPA's, results will be (much) better.

**Comment by PatrickvL** [comment]
For that to work, we need a scanning function that doesn't take single OOVPA's a input, but the entire available set of OOVPA's for that given symbol, or at least the best and fallback versions of it

**Comment by jackchentwkh** [comment]
one quick thinking is to scan the OOVPA within the section the library belongs to. ie. scan D3D8 oovpas withing section/segment D3D. with this approach, the scan speed and accuracy should be improved.

**Comment by RadWolfie** [comment]
Moved to XbSymbolDatabase repo.
