### ISSUE TITLE
star wars jedi knight: jedi outcast

### ISSUE THREAD

**Issue by medievil1** [Cxbx-Reloaded/Cxbx-Reloaded#1242]
Video/graphic issue with HLE (no output/black screen - Audio is present)
last known working version(that I have access to) is release build b62af3df (may 8) 
the may 10th build does NOT work (same black screen but audio is present)

**Comment by PatrickvL** [comment]
Unless a bisect is done and documented, this report is not useful enough (plus game-specific, which is avoided here) so will probably just be closed

**Comment by PatrickvL** [comment]
Please m mine these details to the relevent issue in the game compatibility tracker, so at least the above information doesn't get lost
