### ISSUE TITLE
JSRF not recieving input // lag issues

### ISSUE THREAD

**Issue by GHXZTBOY** [Cxbx-Reloaded/Cxbx-Reloaded#1249]
I tried playing JSRF today but it wasn't recieving input. I even tried re-mapping the controls, i'm just using a keyboard. (Also the game is a lot slower than the older versions of CXBX-R such as early april-late march. I used to get 60FPS but now its hovering around 20-30.)

SPECS:
GTX 1050
Ryzen 3 1200
8GB DDR4

**Comment by PatrickvL** [comment]
For title-specific questions/support, go to our discord channel or check the compatibility tracker.
