### ISSUE TITLE
On Wine, Xbox Controller dialog gets cut off

### ISSUE THREAD

**Issue by Sarkie** [Cxbx-Reloaded/Cxbx-Reloaded#1254]
![image](https://user-images.githubusercontent.com/283203/41091271-12eda96e-6a3e-11e8-9bfc-4058af908efc.png)

**Comment by PatrickvL** [comment]
No only that, but it'd be logical if the DirectInput configuration dialog was removed as a main-menu item, and added as a button at the bottom of the above dialog.

This button should only be enabled if DirectInput was selected on any Xbox port.

**Comment by Sarkie** [comment]
Agreed.

I'd also say, it's probably worth having some defaults set up for DirectInput.

e.g. 
D-PAD, all Front Buttons

**Comment by jthecodebuilder** [comment]
I think it would be safe to close this issue since the input GUI had gotten a major overhaul.
