### ISSUE TITLE
XInput to DirectInput needs restart

### ISSUE THREAD

**Issue by Sarkie** [Cxbx-Reloaded/Cxbx-Reloaded#1255]
On a default install XInput is chosen.

Select DirectInput.

Configure DirectInput.

Game still won't take input.

You will have to restart the emulation to take the changes.

**Comment by PatrickvL** [comment]
Good spot!

**Comment by LukeUsher** [comment]
That's normal and has always been this case: Changing input mode requires a restart of the emulator and will until we implement support for dynamically adding/removing controllers at run-time. It's never been a supported feature, so it's not an issue.

A good feature request though ;)

**Comment by PatrickvL** [comment]
To fix this, the `m_ObjectConfig` copy in the emulating process should be refreshed from the 
`m_ObjectConfig` contents changed from within the configuration GUI.

**Comment by ergo720** [comment]
Closing, as this was a bug of the old input GUI where you had to select the proper input API. With the [new one](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1713), all APIs will work in tandem so you don't have to switch between them.
