### ISSUE TITLE
[Suggestion] External/Modular OOVPA Tables

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#127]
What of the possibility of use external INLs that override existing internals in .\Patches? This would allow us to implement a system where patches can be hosted in a database and periodically updated when the need arises instead of requiring an entirely new build of Cxbx. Just a thought. This paradigm can be seen across emu's, like Dolphin, PCSX2, Project64, etc.

**Comment by PatrickvL** [comment]
Could you add a few links for the examples you mentioned, please?

**Comment by LukeUsher** [comment]
The INL files are just C source code,so do need to be compiled in to the application. Unless we create a new format that can be loaded by Cxbx at runtime, there's not much we can do.

That said, a possible approach would be to split the HLE Database into it's own project/DLL.

This would allow the HLE Database to be updated independently from Cxbx-Reloaded, and to be used in other applications.

**Comment by BiatuAutMiahn** [comment]
@PatrickvL, In the emulators I mention...more specifically they have a list pf patches/inis for title specific configuration and/or patches

**Comment by BiatuAutMiahn** [comment]
Considering this, there would be no point in having a workaround/patch to enable a small sample size of titles to work for the internal database. (Like a single title for instance) This is where an external patch would be most preferred.

**Comment by PatrickvL** [comment]
I'm all for game specific settings, but as long as or HLE scanning code can still be improved (a lot), it's no use to work on external, user configurable OOVPA definitions. Perhaps the most useful user configuration option would be to skip HLE scanning altogether, and read the function locations from config/cache, much like how Xeon emulate Halo. This would give non coders an opportunity to meddle with this, and potentially come up with fixed address maps to get some titles running

**Comment by LukeUsher** [comment]
We've had this for a while now
