### ISSUE TITLE
Implement vertex buffer caching

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1277]
Currently, Cxbx-Reloaded converts vertex buffers at each draw, even when nothing changed in the contents of this buffer.
This causes massive slowdowns that could be improved by caching the result of vertex buffer conversion.
Like with textures and index buffers, make sure conversion is redone when anything changed in the contents of a vertex buffer (or the declaration of the vertex stream / Flexible Vertex Format for a vertex buffer).

**Comment by LukeUsher** [comment]
Tagged as High Priority due to the massive performance impact not having such a cache causes. 2D titles like Metal Slug would benefit greatly, as would any title using Quads

**Comment by LukeUsher** [comment]
We did used to have a Vertex Buffer cache so old versions of Cxbx-R could be looked at for inspiration.
It was removed because it was extremely buggy, and caused more issues than it solves.

A vertex buffer cache needs thorough testing to avoid this situation again!
