### ISSUE TITLE
Logged test-cases count

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1278]
I suggest to print at end of log how much times test-cases are logged (each with own count).

**Comment by PatrickvL** [comment]
Good idea except there's no real "end" to discern - F6 Just terminates the emulator process

**Comment by PatrickvL** [comment]
Also, what counts as a duplicate... completely identical text lines, or the same printf format-string (barring the arguments rendered in there)?

**Comment by ergo720** [comment]
Personally, I don't think counting the number of test cases triggered by title is useful information, we just need to know that the title has triggered the condition, so I'm keen to reject this and close it.

**Comment by PatrickvL** [comment]
Agreed. There's little use to this for now. Of we really want statistics, we can resor to using an external profiling tool
