### ISSUE TITLE
Emulation State Becomes Stuck After A Soft Crash

### ISSUE THREAD

**Issue by Kumoashi** [Cxbx-Reloaded/Cxbx-Reloaded#1283]
This issue happens with any game that will crash, but not cause the emulator itself to crash as well.
You load a game, but at some point it well crash. If you try to start emulation of the same game, or close the game and try to start emulation on any other game, including working ones, you will get an error message.
![image](https://user-images.githubusercontent.com/24490104/41386883-eee7ee76-6f51-11e8-825c-c39e5ca4be7f.png)
The only way to clear the emulation state is to exit the emulator and open it again. This did not happen in previous builds.

I tested this on CXBX-Reloaded build number b5db64924962fd31336409a48f495b79f903218f.
Some of the games I tested are:
Animaniacs - The Great Edgar Hunt
CRAZY TAXI 3 High Roller

**Comment by RadWolfie** [comment]
Can you test #1284 to see if issues still occur.

**Comment by Kumoashi** [comment]
Sure, I can test it!
