### ISSUE TITLE
Silent crash when open xbe file (until reset to default)

### ISSUE THREAD

**Issue by kanelakis** [Cxbx-Reloaded/Cxbx-Reloaded#1292]
Hi, I have the version Jun 14 2018, as soon as I select the .xbe file of a game, the emulator closes without giving me errors, what could be the problem?

**Comment by Sarkie** [comment]
Does it produce anything in the logs?

Getv another version?

**Comment by kanelakis** [comment]
The log file does not create it, it happens when I go to "File / Open Xbe" and select the game, and I close them, I do not even start, because I do not give way.
Orima worked well, I did some game tests, it happened to me suddenly.

**Comment by RadWolfie** [comment]
Please perform the task below:
1. Open Cxbx-Reloaded
2. `View > Debug Output (GUI) > File...` (Save it to a place where you can easily find and upload.)
3. Reproduce your issue
4. Attach CxbxDebug.txt file from step 2 to here.

**Comment by kanelakis** [comment]
The Cxbx Debug file is empty, if I do Console, it gives me everything OK until it loads, then it closes.
I send you a video hoping you can see the Consul.
https://youtu.be/9eLbs3I4fHg

**Comment by RadWolfie** [comment]
Base on the youtube's console. Something happened between `Xbe::Xbe: Reading Signature Header...OK` and expected `WndMain: Buffy The Vampire Slayer loaded.` output. Plus the window's title didn't update to show it is loaded nor show image of title's logo.

Source of cause is either:
* Recent Xbe files list is corrupted.
* XbeLoaded function cause the crash.
  * M$ logo, title logo, update caption, and refresh menus are called in XbeLoaded function.

Can you check see if your Recent Xbe files list is shown correctly? Then try `Settings > Reset To Defaults` next.

If issue still persist, I will make more verbose output to console/log after opened xbe file to get more information.

**Comment by kanelakis** [comment]
Ok it was solved by doing the reset in default, thank you very much. :)

**Comment by RadWolfie** [comment]
I believe it is best to keep the issue open until we are able to isolate which user's configuration cause the problem.

My suggestion for anyone who may have this problem in the future is to export whole Cxbx-Reloaded registry key/folder. Then attach to this issue for review and attempt to reproduce the issue.

To locate where Cxbx-Reloaded registry. Open regedit executable, then go to `Computer\HKEY_CURRENT_USER\Software\Cxbx-Reloaded`. For export, use `File > Export...`

**Comment by kanelakis** [comment]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Cxbx-Reloaded]
"LLEFLAGS"=dword:00000000
"XInputEnabled"=dword:00000000
"HackDisablePixelShaders"=dword:00000000
"HackUncapFrameRate"=dword:00000000
"HackUseAllCores"=dword:00000000
"HackSkipRdtscPatching"=dword:00000000
"HackScaleViewport"=dword:00000000
"HackDirectBackBufferAccess"=dword:00000001
"CxbxDebug"=dword:00000000
"KrnlDebug"=dword:00000000
"RecentXbe"=dword:00000000
"CxbxDebugFilename"=""
"KrnlDebugFilename"=""

[HKEY_CURRENT_USER\Software\Cxbx-Reloaded\XBAudio]
"AudioAdapter"=hex:00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"PCM"=dword:00000001
"XADPCM"=dword:00000001
"UnknownCodec"=dword:00000001

[HKEY_CURRENT_USER\Software\Cxbx-Reloaded\XBController]

[HKEY_CURRENT_USER\Software\Cxbx-Reloaded\XBVideo]
"VideoResolution"="Automatic (Default)"
"DisplayAdapter"=dword:00000000
"Direct3DDevice"=dword:00000000
"Fullscreen"=dword:00000000
"VSync"=dword:00000000
"HardwareYUV"=dword:00000000

**Comment by RadWolfie** [comment]
Your export data appear to be default settings.

I'm talking about the "current" settings when Cxbx-Reloaded start perform a silent crash attempt to open xbe file.

**Comment by kanelakis** [comment]
Ah ok, but now that I have managed to solve the problem, I have to wait for me to recapture. Perhaps some modufica happened when I did the tests of Buffy and Gladius, I had only modifiying LLE on on and the graphics engine on software.

**Comment by kanelakis** [comment]
For the time being I made those changes to activate LLE and the engine on software, and bring it back to the basic setting without resorting to reset in default, now it seems that it supports, if you had to resubmit the register.

**Comment by Sarkie** [comment]
@RadWolfie 

Maybe set those keys to invalid data types or min or max values to reproduce?

**Comment by kanelakis** [comment]
I just downloaded the version Jun 22 2018, at the first start, keeping the basic settings, then after and left without problems.

**Comment by kanelakis** [comment]
Download version Jul 1 2018, for the time being stable.

**Comment by RadWolfie** [comment]
It is happening again? Then perform the task below as described in previous post.

>To locate where Cxbx-Reloaded registry. Open regedit executable, then go to `Computer\HKEY_CURRENT_USER\Software\Cxbx-Reloaded`. For export, use `File > Export...`

Finally upload the export file here.

**Comment by kanelakis** [comment]
Maybe I explained myself badly, I tested the new version jul 27 2018 the problem did not arise, if I recapitulate it.

**Comment by LukeUsher** [comment]
No respose or feedback for several months, closing
