### ISSUE TITLE
Move registry data to settings.ini file

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1312]
Since issue wasn't created, I'm creating one to keep track on things to do.

We had discussed in the past and the present. In order to support both cross-platform and portable, we need to move registry data to settings.ini file in the same directory Cxbx's executable is in.

Progress: (Last update: **2018/8/04**)

- [X] GUI
- [X] Core
- [X] Controller DirectInput (Map keyboard/dinput controller to emulate Xbox Controller)
- [X] Controller Port (XboxPortHostMapping)
- [X] Video
- [X] Audio
- [X] Hack

EDIT: **DONE (for Windows only, need QT support for other platforms)**
The steps it should take to verify if a settings file exist...
1. Check current directory executable is in.
   * If found, use it.
2. Check "central" app storage such as AppData (Windows), `~/.cxbxreloaded` (linux), maybe `~/Library/CxbxReloaded` (Mac/unix).
   * If found, use it.
3. When both steps above are not found. Then create a settings file in current directory executable.
   * Or ***ASK*** user where they want to put the settings file at.

**Comment by LukeUsher** [comment]
There's also this option, for a platform independent implementation of an INI reader/writer
https://github.com/brofield/simpleini

**Comment by RadWolfie** [comment]
Looks interesting. Though I see a line below with no mention of Mac OS X support.
`multi-platform (Windows 95/98/ME/NT/2K/XP/2003, Windows CE, Linux, Unix)`

Simpleini do support Mac? (I don't have a Mac computer)

**Comment by LukeUsher** [comment]
It will work, Mac is based on Unix

**Comment by CakeLancelot** [comment]
For MacOS, the equivalent of AppData on Windows or a hidden directory in the home folder on Linux/Unix would be the user's 'Application Support' folder. So while Unix support will probably cover MacOS as-is, we might want to make some changes regarding storage location in order to make the application feel more 'native'.

**Comment by RadWolfie** [comment]
Yeah, the first thing it should do is check current directory for settings file. Then check for central app storage most likely take place as @CakeLancelot mention. If settings file is not found in both locations, then create one within current directory by default.

**Comment by RadWolfie** [comment]
Settings class is being work on with SimpleIni's API.

Currently, the basic functions will be:
* `void SetDefault();`
  * Can be used reset to default functionality without need to restart Cxbx-Reloaded.
* `bool LoadFile(std::string file_path);`
* `bool Save();`

All of member variables will be public. Since they will be transfer onto EmuShared for kernel process to use. And editable for config dialog window.

Feel free to comment below for any *basic* function request. The goal is to keep it simple.

**Comment by LukeUsher** [comment]
Rather than using global variables that are exposed, why not have a key/value map, where the key is a setting name, and the value is a struct containing all possible data types we will store (eg: bool, std::string, int), and then use getters and setters. For example:

```
std::string path = Config::GetString('core:emudisk');
uint32_t audioVolume = Config::GetInt('audio:volume');
```

This way configuration can be expanded to add new values at anytime, without updating the config class, and instead, only updating the areas where the configuration is reused.

**Comment by RadWolfie** [comment]
@LukeUsher It would be nice, except strings will hoard more file size. That's bad for non-virtual CPU emulation since Windows/Wine/ReactOS/Third-party modules and our own executable are taking more memory spaces out of 4GB memory limit for a single process.

Plus for optimization reason, it needs to be a member variables. Using a lot of string takes more CPU processing.

I am currently splitting the variables into their own structure for easy finding/accessible/updating. With ability to set directly to EmuShared class once instead of each variable on start of emulation.

**Comment by ergo720** [comment]
For @RadWolfie: please also add an option to skip the admin check every time if the user doesn't mind about it. I know that as long as cxbxr is running it won't ask it again, but it will if I close it and relaunch it, which quickly becomes annoying if the user doesn't care about the risks.

**Comment by RadWolfie** [comment]
@ergo720 Thanks for the reminder, it is implement in the pr #1370.
