### ISSUE TITLE
Make kernel mode self-dependent without relying on GUI

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1313]
Since @LukeUsher wants to use apitrace tool which require to use kernel mode process without GUI mode on first launch. We need to ensure all uninitialized variables, user configuration, etc are initialized inside kernel mode on first launch.

This method will also allow other programs to launch titles without current GUI requirement.

**Comment by Sarkie** [comment]
If I ever get a chance, I'd like to build a tool line Dolphin's fifoci.

So this will lead into this

**Comment by RadWolfie** [comment]
Since kernel mode is initialized without GUI. We can go ahead close this issue.

I believe pull request #1370 has implement standalone kernel process support.
