### ISSUE TITLE
"Turok" No Input

### ISSUE THREAD

**Issue by Paradise12314** [Cxbx-Reloaded/Cxbx-Reloaded#1315]
Testing the latest version from "v0.1", games aren't accepting any Input. Controllers and Keyboard can be mapped in CXBX settings just fine. But once Emulation starts, nothing. "Develope" Branch is working fine though.

**Comment by RadWolfie** [comment]
Our tester report it works fine by:
1. "Reset to defaults" from menu (re-open Cxbx-Reloaded afterward)
2. Then re-map the DirectInput's controller
3. Start emulation

Please try the method above then try again. Both develop and v0.1 branches are not in constant 1:1.

**Comment by RadWolfie** [comment]
Hmm... I am seeing an old code still being used. XInputEnabled menu is currently removed. If we are supporting both XInput and DirectInput at same time. We should not have this option at all.

Kernel side:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/1df336fdaa938d07ede8e851538915ee2275bd54/src/CxbxKrnl/CxbxKrnl.cpp#L1278-L1283
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/1df336fdaa938d07ede8e851538915ee2275bd54/src/CxbxKrnl/EmuXapi.cpp#L292-L301
GUI side:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/1df336fdaa938d07ede8e851538915ee2275bd54/src/Cxbx/WndMain.cpp#L200-L204
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/1df336fdaa938d07ede8e851538915ee2275bd54/src/Cxbx/WndMain.cpp#L1467-L1470

**Comment by Paradise12314** [comment]
I'm sorry, I was slightly wrong. It isn't a problem with CXBX, it's a problem with Turok only. Other games are accepting input. So it looks like Turok will need disecting.

**Comment by Paradise12314** [comment]
Hope you don't mind, I changed the Title to reflect latest findings. I tried the latest V0.1 also. Turok still accepts no input. All other games are fine.

**Comment by RadWolfie** [comment]
A tester from discord also report 2002 World Cup (FIFA?) title has the same issue too.

**Comment by Paradise12314** [comment]
So we may need another Title? Also testers needed and a list of Games affected.

**Comment by RadWolfie** [comment]
I can confirm pull request #1300 is causing Turok Evolution title to regress. If perform uncomment if statement below and comment both lines of force set variables. Then Turok is able to response input.
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/6a0805278545ca65e83335bc82d35e1eb5046172/src/CxbxKrnl/EmuXapi.cpp#L430-L439

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/6a0805278545ca65e83335bc82d35e1eb5046172/src/CxbxKrnl/EmuXapi.cpp#L471-L473

**Comment by Paradise12314** [comment]
@RadWolfie I can confirm that your change has fixed the Input of Turok.
