### ISSUE TITLE
Not Recognizing Laptop GPU

### ISSUE THREAD

**Issue by zebolt** [Cxbx-Reloaded/Cxbx-Reloaded#1316]
My laptop has a 940MX mobile GPU and the 'Display Adapter' dialog in the 'Video Configuration' menu does not list it, only my Intel HD Graphics 520 integrated graphics card. I get about 15fps on most games this way, but am sure I could find much better performance if it recognized my real card.

**Comment by RadWolfie** [comment]
Duplicate of #784

Currently dxd9 wrapper, such as D3D8to9, is removed from the repo. Hence the reason you do not see 2nd GPU on a laptop (and desktop too I think). See LukeUsher's [comment for resolution](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/784#issuecomment-374229545).

**Comment by LukeUsher** [comment]
Yeah known issue: Cxbx-Reloaded still uses DirectX8 which is too old to trigger switching to high performance mode on multi GPU systems. The solution is to either use a DirectX8 to 9 wrapper such as d3d8to9, or just wait until we eventually move to a newer API

**Comment by zebolt** [comment]
Okay, thanks much.

**Comment by zebolt** [comment]
d3d8to9 fixed it! Thanks.
