### ISSUE TITLE
Main window's background corrupt

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1319]
Main window's background corrupts if you drag and move main window (tested twice):
![image](https://user-images.githubusercontent.com/24764335/42016588-b9c7a2d6-7ab4-11e8-8f4a-377a82c26a8c.png)
![image](https://user-images.githubusercontent.com/24764335/42016768-6cc3a498-7ab5-11e8-9490-48edc2370fc4.png)

It could be GPU/driver/OS issue - need to confirm.

**Comment by CakeLancelot** [comment]
Try dragging the window offscreen and back, reproduces the issue for me.

**Comment by gandalfthewhite19890404** [comment]
@CakeLancelot - NVIDIA or AMD GPU?
