### ISSUE TITLE
Alternative title ID

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1321]
Please add additional alternative (for example for Indigo Prophecy - 4947007B) title ID to log - diffucult to manage(copy between PCs, clean) saves not via Dashboard.

**Comment by RadWolfie** [comment]
Old TitleID, before replaced with real Title ID, has been renamed to TitleIDAlt.

**Comment by RadWolfie** [comment]
Closing since #1328 had been merged to meet the request.
