### ISSUE TITLE
All my hopes and best wishes for this project

### ISSUE THREAD

**Issue by AlexN64gamer** [Cxbx-Reloaded/Cxbx-Reloaded#1322]
I just want to say to the Xbox emulation as there is gamecube with dolphin or playstation 2 with pcsx2, has always been my dream, I really encourage you guys to keep the great work :) and please dont stop this project untill there is really a friendly user and almost every exclusive xbox game perfect emulation, thanks A LOT for making this possible

**Comment by PatrickvL** [comment]
Thanks!
