### ISSUE TITLE
Pixel shader cause crashes in some titles

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1323]
Pixel shaders causes crashes in some titles, disabling them make game to skip crashing moment and get into game process. Crash happens without popup window with crash, but you can get it in log file. Sometimes crash happen without any exception in log file.
I suggest to post here titles, if game issue exist - make related link to it.
About log (from trace build) files - they are needed, if yes - where we should keep it - in game issue or here? I suggest to keep it in game issues, this issue just consolidates titles with common issue.

Titles:
- [LEGO Star Wars](https://github.com/Cxbx-Reloaded/game-compatibility/issues/101)
- [LEGO Star Wars II The Original Trilogy](https://github.com/Cxbx-Reloaded/game-compatibility/issues/688)
- [TOCA Race Driver 3](https://github.com/Cxbx-Reloaded/game-compatibility/issues/839) 
- Van Helsing
- [WWE Wrestlemania 21](https://github.com/Cxbx-Reloaded/game-compatibility/issues/820)

**Comment by RadWolfie** [comment]
OP user from discord report: (for record purpose)

> Reverting #1060 fixes crashes (with turning on Pixel shaders - without hack) in WWE WM21, LEGO SW series, TOCA3, Van Helsing(game needs d3d8 wrapper anyway, ingame graphic is missing, but you can hear swings etc). I know - its wrong (such reverting) - so need to findout more elegant (and proper) solution than reverting (reimplement by different way, rework etc)

**Comment by ergo720** [comment]
Now that we have [HLSL pixel shaders](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2136), is this issue still relevant today?

**Comment by PatrickvL** [comment]
Nope, you're right, this can also be closed
