### ISSUE TITLE
Manhunt

### ISSUE THREAD

**Issue by mkultimate** [Cxbx-Reloaded/Cxbx-Reloaded#1329]
graphic problems intel hd

![image](https://user-images.githubusercontent.com/16367065/42248766-e9e5cfce-7eec-11e8-9d03-550c26a4464f.png)

![image](https://user-images.githubusercontent.com/16367065/42248707-a67d0fc2-7eec-11e8-8f8b-ba931efe2673.png)

![image](https://user-images.githubusercontent.com/16367065/42248773-f4ada09e-7eec-11e8-90bb-8903a4319e3b.png)

![image](https://user-images.githubusercontent.com/16367065/42248783-003029f0-7eed-11e8-993a-b128778394ed.png)

![image](https://user-images.githubusercontent.com/16367065/42248797-102b1252-7eed-11e8-8334-d7eae4a60753.png)

![image](https://user-images.githubusercontent.com/16367065/42248811-1d28cdbe-7eed-11e8-9a61-dd4f22dc66b0.png)

![image](https://user-images.githubusercontent.com/16367065/42248830-3a4d3420-7eed-11e8-87f7-a6cc68274adb.png)

**Comment by RadWolfie** [comment]
Please report single title issues in https://github.com/Cxbx-Reloaded/game-compatibility/ only.

There is a Manhunt issue created: https://github.com/Cxbx-Reloaded/game-compatibility/issues/783
