### ISSUE TITLE
Tony Hawk's Pro Skater 2x graphics characters

### ISSUE THREAD

**Issue by mkultimate** [Cxbx-Reloaded/Cxbx-Reloaded#1331]
it works without problems except for players who do not show the sound is perfect the intros without any audio cut
![image](https://user-images.githubusercontent.com/16367065/42291349-be4a2b40-7f90-11e8-86fb-9805e647040b.png)

![image](https://user-images.githubusercontent.com/16367065/42291363-d38bac4a-7f90-11e8-8eff-af84b6d58aa8.png)

![image](https://user-images.githubusercontent.com/16367065/42291378-e063608e-7f90-11e8-9e1b-c0a616b85a80.png)

![image](https://user-images.githubusercontent.com/16367065/42291392-edadb7c6-7f90-11e8-8004-03240ae9ac05.png)

![image](https://user-images.githubusercontent.com/16367065/42291399-fac81f46-7f90-11e8-93c9-74f2c33b91de.png)

![image](https://user-images.githubusercontent.com/16367065/42291412-0bbc6e88-7f91-11e8-8e5e-2b1600215592.png)

**Comment by RadWolfie** [comment]
Please report **single title issues** in https://github.com/Cxbx-Reloaded/game-compatibility/ only.

Do not violate our guideline to report issues: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded#bug-reports

An issue had been created for it. Use the search bar provide by GitHub: https://github.com/Cxbx-Reloaded/game-compatibility/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Pro+Skater+2x
