### ISSUE TITLE
graphic improvements

### ISSUE THREAD

**Issue by mkultimate** [Cxbx-Reloaded/Cxbx-Reloaded#1338]
when these options are active the game has graphic improvements
I do not know if it affects other games by activating these options

affected games
Fifa Street 2
Silent Hill 2 Restless Dreams

on hack
Fifa Street 2
note: the audio on fifa street 2 is heard too low

![image](https://user-images.githubusercontent.com/16367065/42421712-b55c760c-829f-11e8-9b84-b11807b60e17.png)

![image](https://user-images.githubusercontent.com/16367065/42421727-fc40201e-829f-11e8-856b-47d85022b473.png)

![image](https://user-images.githubusercontent.com/16367065/42421728-0b1bd5f6-82a0-11e8-89a3-fc535fe5b228.png)

![image](https://user-images.githubusercontent.com/16367065/42421736-18f59bc6-82a0-11e8-8d62-e04083187868.png)

![image](https://user-images.githubusercontent.com/16367065/42421743-38e9452c-82a0-11e8-8694-7a6eed6c42c5.png)

Silent Hill 2 Restless Dreams
![image](https://user-images.githubusercontent.com/16367065/42421761-9a59405a-82a0-11e8-9d16-915fd2bb7b07.png)

![image](https://user-images.githubusercontent.com/16367065/42421765-b19c5a4a-82a0-11e8-9beb-97c49d7e0ec1.png)

![image](https://user-images.githubusercontent.com/16367065/42421769-be027dd2-82a0-11e8-8696-7ec1ee47cddd.png)

![image](https://user-images.githubusercontent.com/16367065/42421771-c8f166fe-82a0-11e8-955b-bacfaf84bb94.png)

OFF HACK
![image](https://user-images.githubusercontent.com/16367065/42421785-f4e145ae-82a0-11e8-8b19-929577268e20.png)

![image](https://user-images.githubusercontent.com/16367065/42421792-12a03398-82a1-11e8-84be-d714b45c0d9f.png)

![image](https://user-images.githubusercontent.com/16367065/42421798-1ee76e3c-82a1-11e8-8c00-55036ce60291.png)

**Comment by gandalfthewhite19890404** [comment]
Its just a hacks - its not intended to make graphics better.
