### ISSUE TITLE
Game freezing while playing -> being stucked on a random moment of the game

### ISSUE THREAD

**Issue by Nalkei** [Cxbx-Reloaded/Cxbx-Reloaded#1339]
Hello !

(french dude with weird english, sorry in advance)

First: Well job for the work done on this emulator, i'm following the projet since 3-4 months and i'm so hyped

I'm a huge fan on JSRF and i would like to play again w/ cxbx, i've already installed the latest build (from July 5 i think).

So ! I can play for 10-15mn and after that the game will freeze randomly (screen stuck), the sound is looping; I can hear the rollers roll to infinity for example or when the DJ are speaking -> screen freezing -> he's stopping speaking and the background music will continue to be played with either a black screen or just with an image.

I've recorded some of my gameplays and this is what is happening exactly: 

https://youtu.be/rfK_xJK18Wg

Thanks !

**Comment by BenNottelling** [comment]
Does it work on older game builds? Also, can you provide logs, and does this issue only effect JSRF? If it only effects that title this issue should really be moved to the compatibility listing for the game

**Comment by Nalkei** [comment]
Hello.

Hm, it's actually not causing the problem with the alpha release, ima play longer and see what happens...

I'm keeping your idea somewhere in my brain btw.

Thank you man, and have a nice day.
