### ISSUE TITLE
Regression after PR 1152 in WWE RAW2 (may affects other titles)

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1340]
PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1152 cause render issue in [WWE RAW2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/61), verified on wireframe mode.
<details><summary>PR1149</summary>

![raw2_pr1149](https://user-images.githubusercontent.com/24764335/42498885-163e8b58-8436-11e8-8724-3dcb6bd3045f.png)

</details>
<details><summary>PR1169 (between 1149 and 1169 exist critical "CreateTextureFailed" bug so I couldn't test on 1150 for example) </summary>

![image](https://user-images.githubusercontent.com/24764335/42498860-001b299e-8436-11e8-84c4-ff3ce45f644d.png)

</details>

**Comment by ergo720** [comment]
According to https://github.com/Cxbx-Reloaded/game-compatibility/issues/61, this is no longer an issue so closing this.
