### ISSUE TITLE
Jet Set Radio Future doesn't work

### ISSUE THREAD

**Issue by superori33** [Cxbx-Reloaded/Cxbx-Reloaded#1353]
I try to emulate that game, and every time this message pop up 
![captura](https://user-images.githubusercontent.com/41758391/43282884-a042e180-9117-11e8-91a6-a0acb2ea28f1.PNG)

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forums on [Gitter](https://gitter.im/Cxbx-Reloaded/Lobby) or [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and closed.
