### ISSUE TITLE
I don't know if this is a problem of the emulator or my computer or what

### ISSUE THREAD

**Issue by superori33** [Cxbx-Reloaded/Cxbx-Reloaded#1354]
(someone deleted my original issue without helping at all)
![captura](https://user-images.githubusercontent.com/41758391/43304055-c3c8ba20-9172-11e8-9566-c156f202ba79.PNG)

**Comment by LukeUsher** [comment]
Nobody deleted your original issue: They told you to report it in the right place. This issue tracker is for problems with the emulator in general, not for game specific bugs. It is also not a support forum.

If you want to report issues with a specific game, use the issue tracker at https://github.com/Cxbx-Reloaded/game-compatibility/issues. 

First, check if an issue for your game exists: If it does, post in the same thread, if not, create one. We do not accept duplicate issues for a game.

If you want help and support, please talk with us somewhere more focused on support, such as [Discord ](https://discord.gg/26Xjx23), we'll gladly help if you ask in the right places.

**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ))**
