### ISSUE TITLE
D3DFMT_LIN_D24S8 is using wrong texture conversion..

### ISSUE THREAD

**Issue by bass3** [Cxbx-Reloaded/Cxbx-Reloaded#1356]
EDIT: I was mixing apples with oranges, please check post below
which contains kernel debug.
Also I am confused with this.

> **[0x21A4] WARN: Applying screen space vertex shader patching hack!**
> **[0x21A4] WARN: Xbox Surface Format 12 will be converted to ARGB**

**Comment by PatrickvL** [comment]
Please link the affected code, and how to test / reproduce the problem.

**Comment by bass3** [comment]
Here: 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2238158/KrnlDebug.txt)

Note everything is converting to ARGB as you can see, this is wrong. It should be RGBA.
As I said also, depending on scale since textures are 640x480 DXT5 is best compresion also both DXT5 and RGBA8 are 32bit alpha and should be enough, specially D3DFMT_LIN_D24S8 file.

Source: https://wiki.beyondunreal.com/Legacy:Unreal_Engine_Versions/2

2048x2048 size texture support (Builds 633+)
4096x4096 size texture support (Builds 2500+)

**Comment by bass3** [comment]
Sorry It was my fault, I was testing OPEN_GL LLE, and changed game to OPEN_GL Rendering in .ini file of game which didn't work. **I updated my KrnlDebug.txt** in post up.

I am truly sorry for wasting your time.


But speaking of Open_GL I noticed this in your code, running game in DirectX it pushes ARGB(OpenGL) instead using DirectX, is this supposed to do it like this?
I know Pixel and VertexShader is not written yet. But I found this 2 lines strange.


Sorry again, for mistake from my side,
I spent around ~10 hours testing and noticed my kerneldebug was wrong today, I also downloaded Visual this morning and will try help with pixel and vertex shaders...

```
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 640)LOG_TEST_CASE: Last pushbuffer instruction exceeds END of Data
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 594)LOG_TEST_CASE: Pushbuffer COMMAND_TYPE_CALL while another call was active!
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 635)[0x21A4] WARN: Applying screen space vertex shader patching hack!
LOG_TEST_CASE: Pushbuffer COMMAND_TYPE unknown
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 648)LOG_TEST_CASE: Pushbuffer COMMAND_FLAGS_RETURN with additional bits?!
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 679)LOG_TEST_CASE: Pushbuffer COMMAND_INSTRUCTION unknown
In EmuExecutePushBufferRaw (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8\pushbuffer.cpp line 666)[0x21A4] WARN: Locking host Texture failed!
[0x21A4] WARN: Locking host Surface failed!
**[0x21A4] WARN: Applying screen space vertex shader patching hack!**
**[0x21A4] WARN: Xbox Surface Format 12 will be converted to ARGB**
[0x21A4] MAIN: Received Exception (Code := 0xC0000005)

 EIP := 0x00000000(=unknown+0x0)
 EFL := 0x00010206
 EAX := 0x0FE481D0 EBX := 0x0FC590C0 ECX := 0x0FE486B4 EDX := 0x00000000
 ESI := 0x00000000 EDI := 0x0FE486AC ESP := 0x1247E108 EBP := 0x1247E120
 CR2 := 0x00000000
```

[0x21A4] MAIN: Aborting Emulation

**Comment by LukeUsher** [comment]
ARGB has nothing to do with DirectX or OpenGL, it's just a surface/texture format that is available in either API.
