### ISSUE TITLE
D3D9 Port: Fix vertex declarations

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#1358]
Fix EmuRecompileVshDeclaration to generate declarations in the D3D9 compatible format.

Dxbx already had this at least partially working, it might be worth looking at that for some inspiration.

Resources:
D3D9 Vertex Declarations
https://docs.microsoft.com/en-us/windows/desktop/direct3d9/d3dvertexelement9

Migration Info:
https://docs.microsoft.com/en-us/windows/desktop/direct3d9/converting-to-directx-9#vertex-declaration-changes

https://docs.microsoft.com/en-us/windows/desktop/direct3d9/mapping-between-a-directx-9-declaration-and-directx-8

**Comment by LukeUsher** [comment]
Solved as of  8ffdc11.
Missing pieces were back-ported from Dxbx (Thanks PatrickvL)

**Comment by LukeUsher** [comment]
Oops I was too hasty on this. It’s partially implemented not fixed

**Comment by PatrickvL** [comment]
Yeah it's unfinished work, even in Dxbx. For more inspiration, d3d8to9 is a valuable resource too

**Comment by LukeUsher** [comment]
Fixed for real this time., there may be some remaining issues, but Dashboard, JSRF, PSO, and many other titles work again with D3D9 port!
