### ISSUE TITLE
Create or find a kernel regression test suite

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#136]
Getting our kernel completely implemented is an important prerequisite for stable and dependable emulation. Both low level and high level emulation will benefit greatly from a correctly functioning kernel.

In order to prove our kernel behaves correctly, and shows no regressions, we require a kernel regression test suite.

For Fedora Linux there's a similar project here : https://fedoraproject.org/wiki/KernelTestingInitiative

Ideally, this test suite offers one or more executables that can be run on actual hardware and in an emulator.
Results of the tests can be written to file and/or using the DbgPrint kernel function, which Cxbx logs the arguments of. The output of a run on the original hardware can be captured and compared to the output of the same test executable when running in an emulator.
Any difference in kernel behavior must either be fixed or a rationale must be given why the difference could be acceptable.

If no prior art can be found, start out small, test a few basic kernel calls, and build from there.

Eventually, all kernel API's should be put under test, so this can be used as a regression test during kernel development and at each milestone.

**Comment by x1nixmzeng** [comment]
A slight tangent, but the Dolphin emulation team do fantastic tests for graphics which they have explained a bit about here: https://dolphin-emu.org/blog/2015/01/25/making-developers-more-productive-dolphin-development-infrastructure/

Essentially they have a CI hook to test their rendering code, doing comparisons between builds: https://fifoci.dolphin-emu.org/about/

Back to the original issue, what sort of software is needed to do something like this?

**Comment by PatrickvL** [comment]
To build a regression test suite, a cross compiling environment is needed. Some people use a pre-installed virtual machine for this.

**Comment by PatrickvL** [comment]
Regarding testing the rendering output, we're a long way off from that, but eventually we could surely make good use of the Dolphin tooling. Right now however, our rendering is still HLE based, calling into DirectX8. Every once in a while I try to get a step further in LLE rendering, which will probably be using opengl. When that is implemented will enough to replace HLE rendering, we could start recording pushbuffer command streams and replay them in a similar fashion as to what Dolphin does.

**Comment by PatrickvL** [comment]
Here another OS level emulation project comparing tests on real hardware to their emulated output: https://www.ppsspp.org/development.html

**Comment by PatrickvL** [comment]
A potentially even more suitable project under test is Wine, which also implements the same type of API's as the Xbox kernel we're implementing. See https://wiki.winehq.org/Reverse_Regression_Testing for more details.

**Comment by PatrickvL** [comment]
@Luca1991 started this project : https://github.com/Luca1991/xbox_kernel_test_suite

Let's continue this issue there.
Closing.
