### ISSUE TITLE
D3D9 Port: Use Pixel Shader Model 2.0 or higher

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#1360]
This will allow the use of more instruction slots and registers, allowing Xbox pixel shaders to be more accurately converted to the host. 

Shader model 2.X preferred over 2.0, 3.0 would be better, but is more work to implement.

**Note**: This issue is stand alone, it doesn't depend on any other issue in this project, and no other issue in this project depends on this one

Resources:
https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx9-graphics-reference-asm-ps

Edit PatrickvL : This is currently assigned to revel8n

**Comment by PatrickvL** [comment]
Can we close this now?

**Comment by LukeUsher** [comment]
No, only vertex shaders are using Shader Model 2.0 at the moment

**Comment by bass3** [comment]
Can you finish implementation of Hardware TnL and Hardware VS? I can't seem to boot Unreal Championship at all anymore...

**Comment by LukeUsher** [comment]
As of #1400 we have been using shader model 2.0 for Pixel Shaders too, so this issue can be closed

@bass3 not sure what you're asking? Vertex Shaders and TnL has ALWAYS been hardware accelerated, we've never had support for software rendering of any kind.

**Comment by bass3** [comment]
Exactly what I am reading about D3D9 and TnL when its creating device, also XBOX is just weird when it comes to this... also here is full leaked code which will help you, cause it includes Unreal C 1 code including libraries for XBOX including nv23a, the site is not mine, so idgf:

http://talonbrave.info/files/software/games/unreal_tournament_2003/source/

**Comment by LukeUsher** [comment]
@bass3 The game crashes because it is LTCG and we don't have a working patch for the LTCG version of D3DDevice_Create, that's all: LTCG games are problematic with HLE and there is nothing we can do to fix this.

Unreal Championship 2 will likely require LLE to be playable.

Also please refrain from posting illegal content. You put us and the project at serious risk by doing that.
