### ISSUE TITLE
D3D9 Port: Remove CXBX_USE_D3D9 checks

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1367]
D3D9 Port: Remove all #ifdef CXBX_USE_D3D9 checks, keep contained code, remove #else code block up until #endif.

**Comment by RadWolfie** [comment]
The code still exist. Source: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/search?q=CXBX_USE_D3D9

**Comment by PatrickvL** [comment]
Thanks for that link - it'll help verify completion

**Comment by Sarkie** [comment]
<PreprocessorDefinitions>NOMINMAX;_WIN32_WINNT=0x0601;WIN32;CXBX_USE_D3D9;_DEBUG;_WINDOWS;_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>

**Comment by PatrickvL** [comment]
Damn @Sarkie

**Comment by LukeUsher** [comment]
aha shit, may have been too hasty on the merge. It's still been removed from the codebase, though, so that's fine?
