### ISSUE TITLE
Crashes with common EIPs after D3D9 port

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1382]
D3D9 brings crashes to some titles, these crashes often has same EIP (unimplemented function in D3D9 yet for example). EIP may be different for every tester (even after each reboot), but you can easily verify it- just test two games, they would crash with same EIP. 
You can get title from my list and get crash EIP for your PC (until reboot) and get another title (not from my list) and if it crashes with same EIP - then post it here.
Why is that issue - tracking is much easier, if one game game from pack have got fix, other would be fixed too.
Title list (please update it if necessary):

- EIP 1: Legends of Wrestling, Van Helsing, GTA: Vice City.

**Comment by PatrickvL** [comment]
Each EIP needs to be resolved to a module and offset within that module - together leading to a function name. For this, debug symbols are needed for the given module (like d3d9.dll for example). So, there's more to it than "just" reporting corresponding address.

**Comment by LukeUsher** [comment]
#1403 fixed a crash that could happen when DeleteVertexShader was called on a declaration-only shader, so it might be worth re-resting these titles.

**Comment by ergo720** [comment]
The D3D9 port has been completed years ago now, so this is probably obsolete by now.

**Comment by RadWolfie** [comment]
Closing as we haven't heard of this problem so far.
