### ISSUE TITLE
Properly initialize vertex attributes

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1385]
In https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1384 @Voxel9 fixed an issue with the diffuse color attribute (it wasn't initialized properly before, causing random color gradients in XDK Cartoon sample, and white shadows in JSRF).

Besides the diffuse color attribute, other vertex attributes also need correct initialization.
* Specular
* Back diffuse (not supported yet)
* Back specular (not supported yet)
(TODO : specify all others here too.)

Another thing we don't support yet, are the persistent vertex attribute usage flags:
* D3DUSAGE_PERSISTENTDIFFUSE
* D3DUSAGE_PERSISTENTSPECULAR
* D3DUSAGE_PERSISTENTBACKDIFFUSE
* D3DUSAGE_PERSISTENTBACKSPECULAR
The default values for the corresponding attributes must be read from somewhere (not sure from where exactly).

This issue will be used to keep track of these problems, to solve them, to gather a set of test-cases, and to keep communication about these problems centralised.

**Comment by LukeUsher** [comment]
Fixed by #1386
