### ISSUE TITLE
OG XBox Controller support

### ISSUE THREAD

**Issue by literalmente-game** [Cxbx-Reloaded/Cxbx-Reloaded#1390]
After talking with both @RadWolfie and @LukeUsher, I was asked to make an issue covering the details about what I've found when searching the SDL source code. For starts, SDL _does_ support the device (at least it seems like it), but keep in mind that the mirror of the source code in Github is outdated and doesn't have the support.
The line that implies the support is this one https://hg.libsdl.org/SDL/file/eb2820ee52ee/src/joystick/SDL_gamecontrollerdb.h#l447. Another detail is that, if you go back in this database, you can see that the support is behind a "#if defined(__LINUX__)"

The up to date library source code can be found here: https://hg.libsdl.org/SDL/
Latest build (from where I've taken this info): https://hg.libsdl.org/SDL/file/eb2820ee52ee/
Direct link to the controller database: https://hg.libsdl.org/SDL/file/eb2820ee52ee/src/joystick/SDL_gamecontrollerdb.h

**Comment by LukeUsher** [comment]
On Windows, the Original Xbox controller requires installation of an unsigned driver, so that's out of the question for HLE..

However, for LLE OHCI, we can simply implement USB-passthrough, which would allow *any* xbox accessory using the controller ports to 'just work' out of the box.

**Comment by ergo720** [comment]
Is this issue still relevant? There is now the [mayflash](https://www.s-config.com/xbcd-mayflash-xbox-joystick-driver/) driver which is signed, and thus solves the signed driver issue. This makes USB-passthrough unnecessary and unlikely to happen since it would require LLE OHCI.

**Comment by PatrickvL** [comment]
At the very least, we should document prerequisites for this in our readme/installation guide

**Comment by ergo720** [comment]
This has now been implemented in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2290 with libusb.
