### ISSUE TITLE
Slower performance on full screen Nvidia Optimus Laptop

### ISSUE THREAD

**Issue by ivanmestre** [Cxbx-Reloaded/Cxbx-Reloaded#1391]
Hello, I'm getting slower performance on full screen than on windowed mode. I have a Laptop with an Intel Core i5 6300HQ, 8 GB of RAM and a GTX 960M. The Laptop has Nvidia Optimus switchable graphics technology. The integrated GPU is an Intel HD 530. I'm using a 14 of August development build 0b0c3429.

I added CXBX-R exe to the Nvidia Control Panel and selected the High Performance Nvidia GPU for it:

![untitled](https://user-images.githubusercontent.com/6786286/44186811-f30bcf00-a0f1-11e8-8977-378c3ff603cb.png)

Testing Dead or Alive 2 Ultimate I get a locked 60 FPS gameplay on windowed mode. When on windowed mode the Nvidia GPU stays at around 30% utilization at 135 Mhz, while the Intel GPU stays at around 5% utilization (the first line in the overlay is the Nvidia GPU, the second line is the Intel GPU):

![untitled3](https://user-images.githubusercontent.com/6786286/44186885-5bf34700-a0f2-11e8-82e0-a9c7aa6a898f.png)

On full screen I get slower performance, around 10% to 20% less performance, dropping to the low 50s and high 40s FPS. When on full screen the Nvidia GPU stays the same at around 30% utilization at 135 Mhz, while the Intel GPU jumps to around 35% utilization:

![untitled2](https://user-images.githubusercontent.com/6786286/44186934-affe2b80-a0f2-11e8-9dfe-9afbf0ba95d9.png)

I also tested Dead or Alive 3 and got similar results. I'm sure that this a very specific Optimus related issue, but I hope the cause can be identified and be fixed.
Thanks in advance.

**Comment by LukeUsher** [comment]
What emulator settings are you using, and what hacks do you have enabled (if any?)

**Comment by gandalfthewhite19890404** [comment]
Hack Run Xbox threads on all cores should be turned ofа - it brings instability and hangs.

**Comment by LukeUsher** [comment]
Closing this as no response for a long time.
