### ISSUE TITLE
Spy Vs Spy 2005 Game does not work

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1429]
This game boots correctly, and plays the intro videos, but crashes before it gets to the main menu

Please fix this game

**Comment by GXTX** [comment]
This is the wrong place to report this. Please close your issue and provide a proper report at [Cxbx-Reloaded/game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility).
