### ISSUE TITLE
D3DDevice::BeginPushBuffer() has not been implemented yet

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1430]
Please work on implementing this function. It will fix a lot of games that currently do not work in CXBX, and it will further progress the emulator

**Comment by PatrickvL** [comment]
Please report reproduction scenarios (also known as "test cases") and log files

**Comment by niko1point0** [comment]
![1](https://user-images.githubusercontent.com/7824443/45097818-b2e8ac80-b0f1-11e8-9837-fb60590fd0cd.PNG)

Here is a screenshot of the error. I apologize, but I am having difficulty with uploading the logs. I will upload them as soon as I can

**Comment by niko1point0** [comment]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2353036/KrnlDebug.txt)
Here is the log

**Comment by PatrickvL** [comment]
You mentioned "a lot of games" - we'd like to get a list of those. For now, you've reported "Spy Vs Spy" (but missing it's Xbe dump)

**Comment by PatrickvL** [comment]
By coincidence, I've been working on improving our HLE push buffer code, here : https://github.com/PatrickvL/Cxbx-Reloaded/commits/d3d_work

**Comment by niko1point0** [comment]
Another game with this problem is Metal Gear Solid 2: Sons of Liberty. I do not have this game anymore though. I will upload logs if I can re-download the game.

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2353322/Xbe.txt)

Here is the Xbe dump for Spy Vs Spy. Thank you for all of your hard work.

**Comment by FabxBs** [comment]
https://github.com/Cxbx-Reloaded/game-compatibility/issues/74  same message in this title

**Comment by PatrickvL** [comment]
@niko1point0 You mean rip it again? Please refrain here from even the bare mention of piracy.

**Comment by niko1point0** [comment]
I'm sorry. Let me give a little more detail. I ripped the ISO from a copy of the game that I legally own, and I put the ISO on a private server, that I own, that is not publicly available on the internet. I need to re-download the game from my private server, because I do not currently have the game on my gaming PC. There is no piracy here

**Comment by niko1point0** [comment]
Now I realize the reason it isn't working right, @PatrickvL, I downloaded the source code and I found a lot of functions that are unimplemented, and actually marked with LOG_UNIMPLEMENTED(); in Direct3D9.cpp 

This makes me feel better because now I know that the functions haven't been forgotten about, but only put aside to be implemented later

**Comment by PatrickvL** [comment]
Exactly. We've tried to at least be clear on the status of the code. Luke's been working recently on the removal of SetRenderState patches - instead reading the corresponding values from the NV2A pgraph registers (which is where they eventually end up).

**Comment by PatrickvL** [comment]
Please use discord for development related talk

**Comment by niko1point0** [comment]
Sorry, I'm new to this emulator, like I literally saw it for the first time yesterday.  I will use discord @PatrickvL
