### ISSUE TITLE
CXBX utilizes 1 thread at 100% when booting a game (I think it's a bug)

### ISSUE THREAD

**Issue by Trogdor8freebird** [Cxbx-Reloaded/Cxbx-Reloaded#1433]
![image](https://user-images.githubusercontent.com/43056070/45197172-7c13b300-b225-11e8-830b-e20c14a571bd.png)
^ This image shows an example of what I'm talking about. The first thread is always used at 100% when booting any game but when I disable/re-enable the thread (hence why it dips down then goes to a normalized value half way through) it appears to work like all other threads.

**Comment by RadWolfie** [comment]
Relative to https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1238

xbox's threads will always use single core usually at 100% unless enabling all cores hack will spread evenly with risk of destabilize the emulation.

**Comment by LukeUsher** [comment]
That and when first starting a game, We scan and patch the game.
