### ISSUE TITLE
CDROM0: not mapped as $XbePath

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/Cxbx-Reloaded#1438]
found this in [Xbox Music Mixer](https://github.com/Cxbx-Reloaded/game-compatibility/issues/379)
Title passes only "CDROM0:" without prefix
The path is not corrected properly.

Log snippet:

> [0x27A4] RTL     RtlInitAnsiString(
>  OUT DestinationString  : 0x113BF1DC
>    SourceString         : (char *)0x113BF210 = "CDROM0:"
> );
> [0x27A4] NT      NtCreateFile forwarding to "IoCreateFile"...
> [0x27A4] IO      IoCreateFile(
>  OUT FileHandle         : 0x113BF1E4
>    DesiredAccess        : 80100080
>    ObjectAttributes     : 0x113BF1C8 -> OBJECT_ATTRIBUTES* {
>    .RootDirectory        : FFFFFFFD
>    .ObjectName           : 0x113BF1DC -> STRING* {
>    .Length               : 7
>    .MaximumLength        : 8
>    .Buffer               : (char *)0x113BF210 = "CDROM0:"}
>    .Attributes           : 40}
>  OUT IoStatusBlock      : 0x113BF1D4
>    AllocationSize       : 0x00000000
>    FileAttributes       : 80
>    ShareAccess          : 1
>    Disposition          : (CREATE_DISPOSITION)0x00000001 = FILE_OPEN
>    CreateOptions        : (CREATE_OPTION)0x00000060 = FILE_SYNCHRONOUS_IO_NONALERT|FILE_NON_DIRECTORY_FILE|FILE_NON_DIRECTORY_FILE
>    Options              : 0
> );
> [0x27A4] FILE    IoCreateFile Corrected path...
> [0x27A4] FILE      Org:"CDROM0:"
> [0x27A4] FILE      New:"$XbePath\CDROM0:"
> [0x27A4] WARN : IO      IoCreateFile Failed! (STATUS_INVALID_HANDLE)

I think it should map this to $xbepath
Also the ':' is not a allowed character for file and folder names

**Comment by LukeUsher** [comment]
This is somewhat intentional. Cxbx-Reloaded doesn’t emulate the DVD drive just yet, it runs games as if they are run from the hard drive, with no CD-ROM present. Redirecting cdrom0 to the xbe path does weird behaviour in some titles. It even makes the dashboard reboot infinitely because it thinks you inserted a game and relaunches itself. This will be addressed properly once we have proper dvd drive emulation

**Comment by hotzenplotz3000** [comment]
I see. That makes sense.
Thanks for clarifying 👍
