### ISSUE TITLE
Star Wars - Jedi Starfighter - Unknown TexCoordIndex Value (0x7FFFFFFF)

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#144]
Star Wars - Jedi Starfighter XDK 4361 with Unknown TexCoordIndex Value (0x7FFFFFFF) before title screen in 85e35b1.
Part of log:
>[0x4338] EmuD3D8: EmuD3DDevice_Clear
>   Count               : 0x00000000
>   pRects              : 0x00000000
>   Flags               : 0x000000F0
>   Color               : 0x00000000
>   Z                   : 1.000000
>   Stencil             : 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetPixelShader
>   Handle              : 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_ZEnable
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x00040304
>   Value               : 0x00000000
>[0x4338] D3DRS_ALPHABLENDENABLE := 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x00040344
>   Value               : 0x00000302
>[0x4338] D3DRS_SRCBLEND := 0x00000005
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x00040348
>   Value               : 0x00000303
>[0x4338] D3DRS_DESTBLEND := 0x00000006
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x00040300
>   Value               : 0x00000000
>[0x4338] D3DRS_ALPHATESTENABLE := 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x00040340
>   Value               : 0x00000000
>[0x4338] D3DRS_ALPHAREF := 0.000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_Simple
>   Method              : 0x0004033C
>   Value               : 0x00000000
>[0x4338] D3DRS_ALPHAFUNC := 0x00000001
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_FillMode
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_CullMode
>   Value               : 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_StencilEnable
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetRenderState_EdgeAntiAlias
>   Value               : 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetTexture
>   Stage               : 0x00000000
>   pTexture            : 0x00000000
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x00000016
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x00000017
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x00000018
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x00000019
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x0000001A
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_BumpEnv
>   Stage               : 0x00000000
>   Type                : 0x0000001B
>   Value               : 0x7FFFFFFF
>[0x4338] EmuD3D8: EmuD3DDevice_SetTextureState_TexCoordIndex
>   Stage               : 0x00000000
>   Value               : 0x7FFFFFFF
>[0x4338] EmuMain: Recieved Fatal Message:
>
>* EmuD3DDevice_SetTextureState_TexCoordIndex: Unknown TexCoordIndex Value (0x7FFFFFFF)
>
>CxbxKrnl: Terminating Process

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#187
