### ISSUE TITLE
Exception Code 0xC000005

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1446]
![capture](https://user-images.githubusercontent.com/7824443/45889543-bb4a1400-bd8e-11e8-9dc3-f670e17c6bfe.PNG)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405892/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405893/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405894/Xbe.txt)

This happens when I try to boot Crash Bandicoot: The Wrath of Cortex
Thank you for taking the time to fix this issue

**Comment by LukeUsher** [comment]
For game-specific issues, please post to https://github.com/Cxbx-Reloaded/game-compatibility
