### ISSUE TITLE
Breakpoint Exception (int 3)

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1447]
![capture](https://user-images.githubusercontent.com/7824443/45889811-593dde80-bd8f-11e8-87b4-a450df9b60e3.PNG)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405919/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405920/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2405921/Xbe.txt)

This error happens when I try to boot Halo: Combat Evolved. The error only takes a few seconds after boot to show up. Thank you for taking the time to fix this issue

**Comment by LukeUsher** [comment]
For game specific issues, please update the relevant record in https://github.com/Cxbx-Reloaded/game-compatibility
