### ISSUE TITLE
Some titles hangs with enabled LLE GPU

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1448]
After PR #1440 some titles started hangs when LLE GPU is enabled without any rendering on screen.
I noticed in logs two common unhandled instructions - 117 and 347, they appears with HLE too, but games does not stucks by that way.

Title list (may be larger, need more testing):
- GTA San Andreas - hang, LTCG title
- Indifo Prophecy - hang
- LEGO Star Wars - hang
- LEGO Star Wars II The Original Trilogy - hang
- Mafia - hang
- Need for Speed: Most Wanted Black Edition - hang, need to get logs
- Need for Speed: Underground - hang, need to get logs
- Obscure - hang
- Pirates Of The Caribbean -  hang
- The Sims - different behaviour, crashing without error instead of hang
- WWE Raw 2 - hang

Logs, debug level:
[GTA San Andreas log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410554/inst_sa.zip)
[Indigo Prophecy log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410238/inst_indigo.zip)
[LEGO Star Wars log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410239/inst_lsw.zip)
[LEGO Star Wars II The Original Trilogy log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410558/inst_lsw2.zip)
[Mafia log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410557/inst_mafia.zip)
[Obscure log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410556/inst_obscure.zip)
[Pirates Of The Caribbean log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410555/inst_poc.zip)
[The Sims log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410241/inst_sims.zip)
[WWE RAW 2 log](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2410240/inst_raw2.zip)

This issue created for tracking.

**Comment by LukeUsher** [comment]
Can you provide before/after hang  logs for comparison? I assume these titles didn't hang before

**Comment by PatrickvL** [comment]
Running WWE RAW 2 with LLE GPU hangs on this sequence :

> [0x3724] DEBUG: X86     Disassembly : 001AA910 89 8F 00 01 60 00    MOV         dword ptr [EDI+00600100h],ECX
> [0x3724] DEBUG: X86     Disassembly : 001AA916 85 87 00 01 00 00    TEST        dword ptr [EDI+00000100h],EAX
> [0x3724] DEBUG: X86     Disassembly : 001AA91C 75 F2                JNZ         001AA910h

**Comment by LukeUsher** [comment]
#1454 fixed this for WWE Raw 2 and some XDK samples.
Can you please re-test the other titles?
