### ISSUE TITLE
Ease up- and down streaming of xqemu code

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1467]
We could fork xqemu and import (part of) that into Cxbx-Reloaded, to ease up- and down streaming of code changes.

The main motivation for this is, that we currently maintain a copy of the xqemu NV2A emulation code.

Although it's simple to do a manual file-by-file comparison between the two to quickly see which parts are different (have changed on either side), the downside is they don't share git commit history, which makes it impossible to pull code in or out from one another.

Reaching this situation requires carefully planning, as we previously had to overcome quite a few obstacles to get the xqemu NV2A emulation code compiling and running in Cxbx-Reloaded;
* The use of GCC C language extensions not available in MSVC (like ranged case statements, indexed array initializers and scoped initialization blocks)
* The use of qemu tooling code not present in Cxbx-Reloaded (like various locking primitives and string construction)
* Differences in (debug) logging
* Fixes of compiler warnings
* Bug fixes (some caused by us while porting, others also present in xqemu)
* Extending register declarations
* Renaming functions and variables for readability and/or avoiding collisions
* Hardware accelerated overlays
* Render plug-in refactorings
* Circumventing the absence of VGA emulation in Cxbx-Reloaded
* Fixing interrupt related issues in Cxbx-Reloaded (like the vblank thread)
* Disabling texture caching because it uses tooling that doesn't compile under MSVC
* Different device framework
* No Mac OS OpenGL extensions

... And probably more.

**Comment by ergo720** [comment]
Is this still valid? Xqemu is dead now, and I think we are going to replace the xqemu's nv2a code with our own implementation in the future.

**Comment by PatrickvL** [comment]
You're correct, this issue will not be worked upon since the new plan is to implement our own NV2A pushbuffer handling (so, a total rewrite of what we currently have copied over from xqemu)
