### ISSUE TITLE
I will pay you to make Spy Vs Spy work

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1469]
I really want the game Spy Vs Spy to work on this emulator. It is the only game I want, and I will pay anyone who can make the game run flawlessly in four-player split screen mode. The amount I am willing to pay can be discussed.

**Comment by AzurikRiseOfPerathia** [comment]
Gice me 1 500 000 000 000 000 000 000 $ PLEASE XD

**Comment by niko1point0** [comment]
I uploaded a report
