### ISSUE TITLE
save states anyone?

### ISSUE THREAD

**Issue by Demir2007** [Cxbx-Reloaded/Cxbx-Reloaded#1484]
the title explains itself
save states?

**Comment by PatrickvL** [comment]
Save states would be very hard to achieve because of HLE - we can't predict where thread stack ends up, timing isn't predictable, Windows directs thread switching, etc

**Comment by Demir2007** [comment]
then wat is "save xbe" and "save xbe as"

**Comment by PatrickvL** [comment]
It's obsolete, a Cxbx remnant. It saves the Xbe including any patches

**Comment by LukeUsher** [comment]
It's impossible to implement save-states with the current design of Cxbx-Reloaded: We don't emulate the hardware at a low enough level to properly save/restore state. 

It's not that we don't want to implement save-states, it's that we simply can't.

Sorry,
