### ISSUE TITLE
Cheats?

### ISSUE THREAD

**Issue by Demir2007** [Cxbx-Reloaded/Cxbx-Reloaded#1498]
the title explains itself........agin
CHEATS

**Comment by LukeUsher** [comment]
Cxbx-Reloaded does not emulate CPU and memory in the same way as a traditional emulator, making it difficult to implement cheats how they would usually exist in emulation. 

You can, however, use tools designed for cheating on PC games (such as Cheat Engine) with no issues, if you know how to use it.

**Comment by x1nixmzeng** [comment]
Cxbx does include a debugger which can load Cheat Engine (.CT) files to apply memory patches.

The setup just needs a bit of developer love :)

**Comment by LukeUsher** [comment]
Closing as won't fix (for now, at least): Cheating can be achieved by using Cheat Engine
