### ISSUE TITLE
Black Bars?

### ISSUE THREAD

**Issue by Azkuzku** [Cxbx-Reloaded/Cxbx-Reloaded#1501]
Hey devs, can we someday have the feature to NOT have the video stretched? It's really annoying how I have to manually set my resolution to 4:3 on Intel Control Panel (even tho i use a geforce 650m to run the games).
So, can this be worked upon?

**Comment by PatrickvL** [comment]
Please add test cases and screenshots to explain what you mean

**Comment by Azkuzku** [comment]
> Please add test cases and screenshots to explain what you mean

**Comment by Margen67** [comment]
Duplicate of #1059
