### ISSUE TITLE
i need some help black screen infinite and loading  infinite fatal frame 1 and 2

### ISSUE THREAD

**Issue by kosmoshion** [Cxbx-Reloaded/Cxbx-Reloaded#1506]
i need some help im new im learning and i want play fatal frame 1 and 2 but when im starting the software in fatal frame 1 show the loading screen and dont do anything else and in FF2 freeze in a black screen what can i do? i need some help pleaseeee  1 thing when im starting the program is a little slow when i configure thr controller of xbox 360 or 0ne

**Comment by LukeUsher** [comment]
Those games don't work yet, there's nothing you can do except wait. See https://github.com/Cxbx-Reloaded/game-compatibility for details on what we can (or can't) run.

**Comment by MAIDAMY** [comment]
![image](https://user-images.githubusercontent.com/95846681/177733583-067ca907-8219-4f91-9c82-6dc3f1eeaa2a.png)
There is a wraith here, the camera can't shoot without blue light, ask for support
![image](https://user-images.githubusercontent.com/95846681/177734167-5e777673-5c27-46d3-92a8-10ecdf216ea8.png)
There is a ghost here, the same camera can't shoot without Blu-ray, please support me. I downloaded the Japanese version, but I saw that there is a Japanese version on the Internet. There is a camera that can shoot the ghost's Blu-ray normally.

**Comment by ergo720** [comment]
> I downloaded the Japanese version, but I saw that there is a Japanese version on the Internet.

We can't support piracy here, and the issue you posted is a known bug of the emulator, there's nothing you can do about it.
