### ISSUE TITLE
64 bit Windows 7 problems.

### ISSUE THREAD

**Issue by Azkuzku** [Cxbx-Reloaded/Cxbx-Reloaded#1513]
I've done everything, reinstalled, installed the latest visual c++ and .net frameworks, but no avail.
I always get an error that says "this application is not able to start correctly, 0xc000007b"¨
please help

**Comment by j0nnay-aw83n** [comment]
Get visual studio and Cologne the get hub source code should work

**Comment by LukeUsher** [comment]
@Azkuzku Where did you get your emulator from? It sounds like you're using the old Cxbx emulator that does not work on modern computers, Cxbx-Reloaded is a different emulator!

**Comment by Azkuzku** [comment]
> @Azkuzku Where did you get your emulator from? It sounds like you're using the old Cxbx emulator that does not work on modern computers, Cxbx-Reloaded is a different emulator!

I got it from right here, I tried both stable, and development versions. They worked on my 64 bit Windows 10 laptop, which had GeForce 650m (which isn't capable enough for JSRF). The computer I'm currently using it on is a 64 bit Windows 7 with a GeForce 560 Ti (which most likely will be able to run it better)

**Comment by RadWolfie** [comment]
> I always get an error that says "this application is not able to start correctly, 0xc000007b"

0xc000007b error code state as invalid image format.

For depth information of what it is: https://blogs.msdn.microsoft.com/dsvc/2017/09/20/diagnosing-status_invalid_image_format-c000007b-errors/

Hmm.... I'll check with my Windows 7 machine in couple hours.

**Comment by RadWolfie** [comment]
Can you try again by transfer known working downloaded zip file from your Windows 10 laptop to your Windows 7 computer? Via USB drive would be easier.

If you are able to run Cxbx-Reloaded after a copy zip file from USB drive to your computer's hard drive. Then the probability are:
* Third-party network filtering corrupted it.
* Web browser didn't get all the parts of file downloaded.

If issue do persist, then the probability are:
* Didn't installed Visual C++ 2015 and 2017 redistributables of x86 version requirement.
* Bad sector(s) of the hard drive.
* Corrupted file system.

We did had couple users with error code "0xc000007b" reported on discord. It turn out they were using external drive which is cause of corrupted file system.

Then one other user didn't installed x86 version of Visual C++ 2015 and 2017 redist (did installed x64 version instead).

**Comment by Azkuzku** [comment]
Finally! the emulator starts up! I accidentally installed the 64 bit versions of visual studio c++ 2017 and 2015, but now I installed the 32 bit versions, and it works. Thank y'all for your help. I just need to test JSRF on it, currently moving it to my usb stick.
