### ISSUE TITLE
Couldn't map contiguous memory.bin to 0x80000000! on Wine 3.0.4 macOS

### ISSUE THREAD

**Issue by jthecodebuilder** [Cxbx-Reloaded/Cxbx-Reloaded#1524]
I have a feeling it has something to do with Cxbx being forced to run with administrative privileges (and me failing to figure out how to disable it), or maybe that memory address is being reserved by some feature of Wine, or something else I can't figure out.

**Comment by PatrickvL** [comment]
There's a tool called "SysInternals VMMap" (downloadable from Microsoft's website) that shows which address ranges are occupied, and by what. I'm not sure it'll run under your configuration, but if it does, that might shed some light on the situation you're describing. Please tell what you discover!

**Comment by LukeUsher** [comment]
@jthecodebuilder as an additional note, make sure that you are using a 64-bit wineprefix. 
Cxbx-Reloaded, despite being a 32-bit executable, cannot run on 32-bit Windows (or wine) installations, because it requires use of a memory > 0x80000000, which is reserved on 32-bit Windows platforms.

**Comment by jthecodebuilder** [comment]
My Wine installation and prefix are 64-bit (although it's kinda mainly 32-bit because 64-bit support is an optional feature in the WINE installer (but rest assured I do have 64-bit installed)), so I'm still at a loss as to why the 0x80000000 address is reserved. And I'm pretty sure VMMap won't help me in a situation such as this (mainly because I've never used it until now, and don't know how to use it).

**Comment by GXTX** [comment]
I was able to reproduce this.

Started from a base macOS 10.14 install, installed wine stable with 64. During the launch of CXBX-R I allowed wine to install all needed packages. Attempted to run JSRF and this was the result.

![image](https://user-images.githubusercontent.com/858612/51133333-b9ef9c00-1802-11e9-84ce-fca24784d6fe.png)

**Comment by jthecodebuilder** [comment]
Wine 4.0-stable now seems to fix the issue, but every xbe I've tried to run so far (Blinx and Xbox Dashboard) gives me a "Fatal error. The console was instructed to reboot to this error screen. This error screen will persist indefinitely. Stop the emulation to close it" message.

**Comment by jthecodebuilder** [comment]
I'm pretty sure I have already made sure of that, but it still causes the emulated kernel to go into a fatal error.

**Comment by jthecodebuilder** [comment]
I'm closing this issue for now, since I'm experimenting with using Boot Camp, and I'm kinda impatient with me waiting for my new computer, and waiting for a new Wine release to fix the issue. Plus it's partially resolved, as I have mentioned.
