### ISSUE TITLE
Unable to remap emulated control in dialog

### ISSUE THREAD

**Issue by medievil1** [Cxbx-Reloaded/Cxbx-Reloaded#1525]
found a bug...in the settings ini, if you reconfigure input device it SHOULD erase the old section and place the new stuff in, it isn't doing that.. it seems to only save if you remove the old config manually.. for testing I sometimes just config a few keyboard keys (x,y,a,b and start as well as u,d,l,r mapped to arrows) latest commit it was a no go . Setting shad my currently unplugged controller mappings and the u,d,l,r keyboard maps that were already in it from before the controller..rest of the keys would not save. Once I removed the whole section (controller and keyboard) and saved it, then booted cxbx, configured and quit, the mapping showed up and then worked correctly when I started cxbx back up

EDIT: Last tested was PR 1523/commit c24f83f (probably earlier, but thats the one I tested)

**Comment by RadWolfie** [comment]
NOTE: I moved extra info from the header into the OP post. Then simplify the issue topic.

**Comment by ergo720** [comment]
I believe this was a bug of the old input GUI. Since that was removed, this issue should no longer apply. @medievil1 can you confirm it?

**Comment by medievil1** [comment]
Yes as far as I know this was squashed...not found any issues since the new interface was deployed...forgot this was here....
