### ISSUE TITLE
"Store with Executable" incorrectly storing files with XBE location

### ISSUE THREAD

**Issue by GXTX** [Cxbx-Reloaded/Cxbx-Reloaded#1528]
Appears to be a longstanding issue with changing storage location to current directory.

The issue is when on first launch you change the setting to be current directory the actual directory set by `GenerateCurrentDirectoryStr()` will be that of the XBE location. I think the function checks what the last open location in Windows was NOT where the executable is launched from.
![unknown](https://user-images.githubusercontent.com/858612/51357498-3c8b8c00-1a8d-11e9-9d8f-eb8bb31bb5b4.png)

On 2nd launch open XBE and attempt to launch the `DataStorageToggle` will remain unchanged thus skipping the 2nd check of `GenerateCurrentDirectoryStr()` and will have the correct location.
![reboot](https://user-images.githubusercontent.com/858612/51357547-81afbe00-1a8d-11e9-9f9d-4c5acef6671b.png)

**Comment by RadWolfie** [comment]
Since I'm not getting similar result from @GXTX. Although, I do see a different issue when a user drag & drop the XBE file on top of cxbx.exe file. Which then lead current working directory to XBE's directory instead of executable's directory.
