### ISSUE TITLE
CxbxDebugger Form1 doesn't open in Visual Studio

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1536]
When opening CxbxDebugger's Form1.cs in Visual Studio, it shows the following error message:
![image](https://user-images.githubusercontent.com/461930/51745860-81727c80-20a4-11e9-9576-71f5c5ba197a.png)

In text:

> :clipboard: :x: To prevent possible data loss before loading the designer, the following errors  must be resolved:
>
> :x: **Could not find type 'CxbxDebugger.RicherTextBox'. Please make sure that the  assembly that contains this type is referenced. If this type is a part of your  development project, make sure that the project has been successfully built  using settings for your current platform or Any CPU.**
>
> **Instances of this error (1)**
> `1.`   There is no stack trace or error line information  available for this error.
>
> **Help with this error**
> Could not find an associated help topic for this error.  [Check  Windows Forms Design-Time error list](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/design-time-errors-in-the-windows-forms-designer?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(DTELErrorList)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5)%26rd%3Dtrue)
>
> **Forum posts about this error**
> Search the MSDN  Forums for posts related to this error
>
> :x: **The variable 'txDisassembly' is either undeclared or was never assigned.**
>
> **Instances of this error (1)**
> 1.   CxbxDebugger  Form1.Designer.cs Line:331 Column:1   [Show  Call Stack]
>
> **Help with this error**
> [MSDN Help](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/4008y84t(v=vs.100))
>
> **Forum posts about this error**
> Search the MSDN  Forums for posts related to this error

For this issue, either describe the required steps in the README, or otherwise prevent the issue to appear.

**Comment by PatrickvL** [comment]
This might shed some light on it : https://stackoverflow.com/questions/19009386/could-not-find-type-xxx-xxx-xxx-please-make-sure-that-the-assembly

**Comment by LukeUsher** [comment]
I am able to open the project with no issues on Visual Studio 2017.

![image](https://user-images.githubusercontent.com/740003/51747524-a4e7f800-20a1-11e9-8370-87ffcfe4af0d.png)


I think I found the issue: You must compile the project before you can edit it, otherwise the MSVC GUI designer cannot find the RicherTextBox import.

**Comment by LukeUsher** [comment]
It might be worth updating the Readme to specify that MSVC requires the project to be compiled before it can find the RicherTextBox object, but otherwise there is no issue here

**Comment by PatrickvL** [comment]
Alas, Rebuild, close solution, open solution, open Form1 designer still complains...

**Comment by LukeUsher** [comment]
@PatrickvL right click on the debugger project and build there: Rebuilding the solution does not rebuild the debugger

**Comment by PatrickvL** [comment]
Okay, messing around with Project Dependencies, cleaning everything, doing a Release build, closing Visual Studio, and reopening it finally fixed this...

**Comment by x1nixmzeng** [comment]
I've just seen this issue (thanks Patrick!).

Glad you resolved this it is a common issue with C# projects which define a component and include it as a reference.
