### ISSUE TITLE
CXBX unresponsive to keyboard input

### ISSUE THREAD

**Issue by MirzaTaimoorBaig** [Cxbx-Reloaded/Cxbx-Reloaded#1539]
So i am new to CXBX... Downloaded it today, and tried to run Read Dead Revolver.. Started emulation and everything was going fine.. I watched the whole intro and then the games says "PRESS START".. I went to keymapping and mapped START to ENTER..... The key was successfully mapped as prompted by CXBX.

![dsds](https://user-images.githubusercontent.com/47132915/51885021-95bbbf80-23ab-11e9-94c3-a5c573e02cda.png)

 I applied the changes went back to game... Pressed enter but nothing happened..... The games was fine because the "PRESS START" was continuously blinking with some animation..... I tried mapping different keys but none of them responded.... PLEASE HELP.

I am running the latest release version...

And Windows 10 Home x64 Build 1809

**Comment by CakeLancelot** [comment]
Be sure to go to Settings > Config Xbox Controller Mappings and switch Xbox Port 0 to DirectInput Port 0:
![image](https://user-images.githubusercontent.com/5341136/51885846-f965ce80-2352-11e9-8bac-972b019ffc8c.png)
After doing that restart the game and your changes should be applied. DirectInput handles older joysticks and keyboard input, so by switching that to port 0 (the first port) it should allow you to control the game.

**Comment by MirzaTaimoorBaig** [comment]
> Be sure to go to Settings > Config Xbox Controller Mappings and switch Xbox Port 0 to DirectInput Port 0:
> ![image](https://user-images.githubusercontent.com/5341136/51885846-f965ce80-2352-11e9-8bac-972b019ffc8c.png)
> After doing that restart the game and your changes should be applied. DirectInput handles older joysticks and keyboard input, so by switching that to port 0 (the first controller port) it should allow you to control the game.

Thanks for the reply! It worked... BUT now i have this :(
![fdfd](https://user-images.githubusercontent.com/47132915/51886809-2944be80-23b3-11e9-97e1-07e1a28d0000.png)

**Comment by MirzaTaimoorBaig** [comment]
@CakeLancelot 

![hyhghh](https://user-images.githubusercontent.com/47132915/51887739-9a39a580-23b6-11e9-9bae-877055if i try debugger i get this :(

**Comment by MirzaTaimoorBaig** [comment]
> Be sure to go to Settings > Config Xbox Controller Mappings and switch Xbox Port 0 to DirectInput Port 0:
> ![image](https://user-images.githubusercontent.com/5341136/51885846-f965ce80-2352-11e9-8bac-972b019ffc8c.png)
> After doing that restart the game and your changes should be applied. DirectInput handles older joysticks and keyboard input, so by switching that to port 0 (the first controller port) it should allow you to control the game.

If i try debugger... I get this:

![hyhghh](https://user-images.githubusercontent.com/47132915/51887802-ce14cb00-23b6-11e9-9d77-8cb9438a9b0d.png)

**Comment by literalmente-game** [comment]
The original problem was "solved", this issue can be closed. The second problem doesn't have a solution yet and is game specific (should be reported to the compatibility tracker here https://github.com/Cxbx-Reloaded/game-compatibility/issues/795)

**Comment by mrTerryBogard** [comment]
Good day!

It costs Cxbx-Reloaded c7e75d7 and there is also a problem with the controls. Games do not see the keyboard, although the settings are specified.
