### ISSUE TITLE
Vcop3 and ATI CARD

### ISSUE THREAD

**Issue by xbrunox76** [Cxbx-Reloaded/Cxbx-Reloaded#1540]
Hello and thank you for this wonderful emulator.

I have problems with ATI video cards , I have 2 mamecab on which I installed an ATI HD5770 and an ATI HD7970, on both machines when loading virtual cop3 I see the initial screen, the first written and the writing insertcoin, when the game  start to load the 3D graphics I only see a blue screen, BUT I hear the sound.

the game instead starts regularly on another machine where I have an nvidia card.

**Comment by LukeUsher** [comment]
Closing as this is covered by #355
