### ISSUE TITLE
When I select the option "Use hardware video mode" happen a error

### ISSUE THREAD

**Issue by Peterson157** [Cxbx-Reloaded/Cxbx-Reloaded#1542]

**Comment by RadWolfie** [comment]
The issue will only happen when a monitor's resolution doesn't support it. Such as modern monitors doesn't support 640x480, 480p, resolution.

You will either need to set higher resolution compatible with your monitor **or** use alt+enter (also bind to F10 key as well).

We currently do not recommend to use hardware mode option.

**Comment by LukeUsher** [comment]
This menu option should be renamed also, since it's purpose is unclear. By 'hardware video mode' we mean 'Exclusive fullscreen': Your graphics hardware is *always* used regardless of this setting.

**Comment by jthecodebuilder** [comment]
If you really want to use the Hardware Video Mode, you will have to add the following resolutions to your video card control panel's Custom Resolutions (if it has such a feature):

You might need to change the refresh rates to 50Hz if you run any PAL games, but you might want to add the same resolutions with 60Hz if one or more of your games support PAL60, if so. Or have both the same 50Hz and 60Hz resolutions if you play both NTSC and PAL games.

NTSC(/PAL?) 320x240 at 60Hz/fps (possibly?) 
NTSC 640x480 at 60Hz/fps 
NTSC 720x480 at 60Hz/fps
PAL 704 and/or 720x576 at 50 or 60Hz/fps (if your games are PAL)

Both of these resolutions are probably already supported on your computer, but I will include them anyway.
NTSC/PAL 1280x720 at 60Hz/fps
NTSC/PAL 1920x1080 at 60Hz/fps

It is recommenced that you have the timing settings set to Auto, and depending on your monitor/computer, you either need CVT or the DVT (may have forgotten it's proper abbreviation there but I'm certain it starts with a D) timing settings on all of those custom resolutions.

I recommend that you have your scaling settings to GPU (if any), as it will not only allow your monitor to display any unsupported resolutions, but it will also potentially reduce any latency. Oh, and set your scaling method to Aspect ratio (unless you're playing any 480/576 widescreen games).

Also, some games might not work with Hardware Video Mode at all. I think.

**Comment by Peterson157** [comment]
![load](https://user-images.githubusercontent.com/37941917/52526548-1e3a3a00-2ca1-11e9-8763-852892bdcdae.jpg)
Thats happening when i try load Mech assault 2

**Comment by CakeLancelot** [comment]
> 
> 
> ![load](https://user-images.githubusercontent.com/37941917/52526548-1e3a3a00-2ca1-11e9-8763-852892bdcdae.jpg)
> Thats happening when i try load Mech assault 2

Please comment on the existing game compatibility issue [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/500), as the error appears to be unrelated to this issue.

**Comment by ergo720** [comment]
> Please comment on the existing game compatibility issue [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/500), as the error appears to be unrelated to this issue.

Actually don't, the screenshot of the OP shows a well known downloading site, which suggests that the game was likely downloaded.

**Comment by PatrickvL** [comment]
Closed for suspected piracy
