### ISSUE TITLE
Parallel Emulation Support

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1551]
To able support parrallel emulation, we should be following...
* Dynamic assign EmuShared to bind with GUI (base on passdown CLI value or existing).
  * (I had left some codes in EmuShared's function for `guiProcessID` usage)
  * **NOTE:** Standalone emulator needs a different method. Maybe by current working directory string into a hash?
* Create a temporary file with read-only flag shareable in Cxbx-Reloaded's data directory.
  * If: the file exists and does not have writable permission.
    * Then: do not attempt to start a 2nd instance.
  * Else: Proceed file creation or open the file.

Known side-effect in the past making:
* Run 2 emulations using same data directory can corrupt various of things in it.
* Corrupted visual output to GUI's window and standalone for two emulations.
  * Likely cause by using same data directory for certain files being in used. Had not tested in different data directory.

**Comment by LukeUsher** [comment]
Just to clarify: By Parallel emulation, we mean being able to run multiple instances of Cxbx-R simultaneously, on the same computer,

**Comment by RadWolfie** [comment]
Resolved in #1741 pull request.
