### ISSUE TITLE
Disk support 

### ISSUE THREAD

**Issue by j0nnay-aw83n** [Cxbx-Reloaded/Cxbx-Reloaded#1555]
Are you going to be adding the original disk support? I own all my favorite Xbox games still on disk and I have a dvd/Blu-ray drive and I would love to just put my disk in and play, every time I try to get the xbe file I can’t run any of the games even my halo or conker live and reloaded.

**Comment by j0nnay-aw83n** [comment]
And they work on my Xbox 360 so i know they are not damaged

**Comment by PatrickvL** [comment]
Nearly all PC DVD drives aren't physically capable to read Xbox media. You'd need very specific hardware and firmware for that. So, no. The most we can do, in the far future, is support loading binary dumps (instead of reading files, like we do now).

**Comment by PatrickvL** [comment]
More info here : http://xboxdevwiki.net/Xbox_Game_Disc#Dumping
