### ISSUE TITLE
JSRF Soft Crashing now.

### ISSUE THREAD

**Issue by DensestBalloon** [Cxbx-Reloaded/Cxbx-Reloaded#1569]
JSRF is randomly soft locking now and wasn't doing this before hand. I was able to actually beat the game and now launching and playing for just around 7-10 minutes the game will soft lock and I have to restart the emulation. Clearing the HLE cache didn't do anything and changing video settings isn't working.
https://gyazo.com/ebcf67deaec04d1734ca3cb4f5d59957 Here's exactly what happens. Audio will still play but the game becomes soft locked.

**Comment by LukeUsher** [comment]
@DensestBalloon make sure you are using the latest build of the emulator: You haven't given us any information at all: we have no idea what build of the emulator you are using, or what version of the game you have. Both of these pieces of information are shown in the emulator titlebar,

Also make sure to check your settings: Having the 'Use all cores' speedhack enabled is known to cause this behavior randomly: Sometimes you can go a whole game without any issues, but this hack *will* cause hangs/deadlocks. 

If you do not have that hack enabled, then yes, this is a real issue that needs investigating.

**Comment by HyperScorpio** [comment]
And what about the constant drop fps in that map when i go very close to the dragon?
And there is a nother constant drop fps in the first level after we change the charather backwards and then i change the câmera using the L button and we move forward.  
Fps drops from 60.0 to 47 and slowly goes to 52, but not that much.

**Comment by LukeUsher** [comment]
It’s not the GPU that’s the problem, Cxbx-R is not GPU bound, it’s your processor/cpu that matters. And yes cxbx-R gets more demanding as accuracy increases. There are a few areas that can be optimised but emulating the Xbox is a demanding activity.

**Comment by PatrickvL** [comment]
Cough. Vertex buffer cache. Cough. ;)

**Comment by LukeUsher** [comment]
Original Author didn't respond and others users are playing JSRF fine, closing for now.
