### ISSUE TITLE
[🐟] Window at each opening to introduce the emulator. [🐟]

### ISSUE THREAD

**Issue by AzurikRiseOfPerathia** [Cxbx-Reloaded/Cxbx-Reloaded#1576]
### **GOAL**

Start by creating an official Facebook and Twitter page, then on a window every time the emulator is run (check or uncheck this box to disable this permanent function) Long presentation of the emulator

**Title at the top in bold at the center of the text**
--------------------------------------------------
Long descritpion in medium size
--------------------------------------------------
**Put the contact links + Social Networks (Facebook & Twitter + Gitter + DISCORD + MAIL PRO (I have already created one) bold and Small-medium text size + Patreon Text & Icons.**
-------------------------------------------------- -
_Legal notice in italic very small_
-------------------------------------------------- -
A funny little sloger

**Comment by jthecodebuilder** [comment]
april fools?

**Comment by BenNottelling** [comment]
> april fools?

I think so lol
