### ISSUE TITLE
Superman The man of steel error log - HELP

### ISSUE THREAD

**Issue by ChoupoJohn** [Cxbx-Reloaded/Cxbx-Reloaded#1580]
LOG_TEST_CASE: Non-standard overlay dimensions in cxbx_gl_render_overlays
C:/projects/cxbx_reloaded/src/devices/video/nw2a.cpp
VERY NOOB so the issue could be something easy to solve. Thanks in advance

**Comment by LukeUsher** [comment]
This isn't an error, it's a notification that the game hits some incomplete/unknown functionality, it's expected behavior, there's nothing you can do to 'fix' it, unless you are a developer.

Also: This should have been put on the game-compatibility tracker, rather than this repo
