### ISSUE TITLE
Steam controller?

### ISSUE THREAD

**Issue by iymeko** [Cxbx-Reloaded/Cxbx-Reloaded#1585]
First, let me just say I'm so glad I have a way to play Jet Set Radio Future! Thank you for that! Now, on to the issue...

I can't completely get my Steam controller to work with cxbx. I'm probably doing something wrong since several issues here suggest Steam controllers are supposed to work fine (without even changing any settings?)

I've tried resetting cxbx to defaults and just loading my JSRF xbe, and the emulation works, but I have no idea what button on the Steam controller is supposed to be the start button, and I need to press start to start the game. All I know is B and the right arrow button next to the Steam button take me out of fullscreen. If I set xbox port 0 to directinput port 0 and only set the start button to some keyboard button, I can start the game, but only that start button works. If I do the same and also set A and B to the Steam controller's A and B, it seems like both my start button (enter) and A act as both A AND the start button. B seems to act as B as well as... I dunno, a back button? It still takes me out of fullscreen. The right button (next to the Steam button), which I haven't set to anything, also acts like a back button, I guess, and still exits fullscreen.

The best I can do is set xbox port 0 to directinput port 0 and change a lot of controls to keyboard ones, since apparently a lot of the Steam controller input isn't detected. It can detect the d-pad, joystick, left/right arrows, A and B (though as I've said they both do 2 things), and that's it. I might be able to cope if X and Y could be detected. So, I'm playing with my left hand on the controller and my right on my keyboard. It's weird and I'm having a hard time getting used to it.

I have Cxbx-Reloaded e9afda2f (Apr 11, 2019). Any help is appreciated!

**Comment by RadWolfie** [comment]
Either use x360ce third-party software to correctly map DirectInput controls instead of our DirectInput mapping. Or add Cxbx-Reloaded to steam's non-steam library then map your steam controller with steam's big picture setup.

We do not have a steam controller on us, so the above suggestions may will work.

**Comment by iymeko** [comment]
I knew it was something I was doing wrong. I changed some stuff in Big Picture Mode and I now have the joystick, A/B/X/Y, both bumpers, and the left arrow (my start button since the right arrow still exits fullscreen) working. I'm still using DirectInput since I can't seem to get XInput to do anything at all. For whatever reason I can't get it to detect the d-pad anymore, but I don't need it for JSRF anyway. Only annoying thing now is I can't get DirectInput to do anything very useful with the right touchpad thing. It treats it like one big button. Not that I'm complaining--I can live with this, and it's definitely way more comfortable playing now than it was before. Thank you for the help!

I'll close this but if anyone else uses a Steam controller and could share their setup, I'd really appreciate it.
