### ISSUE TITLE
Direct host backbuffer hack - positive and negative effects

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1598]
Here is list of titles affected by enabled Direct Host backbuffer hack, not speedup - only rendering effects;
This issue is going to be our go-to list of test cases while working on fixing backbuffer related issues.
This, to document games that experience issues that are solved by this hack, because we want to fix them and eventually remove said hack.

**POSITIVE**
- Grand Theft Auto III - without hack it render to a part of screen,  squeezing it, i'll upload screenshots later. (Fixed by PR #1599)
- [Tom Clancy's Splinter Cell: Double Agent](http://github.com/Cxbx-Reloaded/game-compatibility#448) - While this hack is activated, this game renders extra menus, such as new game, difficulty selection, load game section, and select level section.

**NEGATIVE**
- Red Faction 2 - Doesn't show FMVs after boot.
- Call of Duty: Finest Hour - Doesn't show FMVs after boot.

PLEASE, Also update the current status of each reported game to our https://github.com/Cxbx-Reloaded/game-compatibility/ tracker (we'll remove comments once they've been processed, since we want to avoid chatter in our issue trackers)

**Comment by BenNottelling** [comment]
Is the GitHub issues really the right place for this kind of conversation? Feels better suited for something like Reddit, unless you're including info on why they either are helped or fixed with the intent of finding a proper solution to problems.

**Comment by LukeUsher** [comment]
@BenNottelling it’s more to document games that experience issues that are solved by this hack, because we want to fix them and eventually remove said hack

**Comment by RadWolfie** [comment]
I had documented the issue, without the hack, of [DoA 3 Demo](https://github.com/Cxbx-Reloaded/game-compatibility/issues/881). However, both DoA 2 and 3 are affected (even with demos) base on the feedback in the past.

With the hack enabled, there are some titles not showing the FMVs. I'll have to go through the titles I have to find out which one then document here.

**Comment by FabxBs** [comment]
POSITIVE:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/448  
While this hack is activated, this game renders extra menus, such as new game, difficulty selection, load game section, and select level section.

**Comment by PatrickvL** [comment]
@FabxBs please update that compatibility report to reflect current status (I'll remove this comment once you've done that, since we avoid chatter in our issue trackers)

**Comment by LukeUsher** [comment]
@PatrickvL rather than remove the comment please add it to the list in the first post: This issue is going to be my go-to list of test cases while working on fixing backbuffer related issues.

**Comment by gandalfthewhite19890404** [comment]
Crash Bandicoot: Wrath of Cortex - hack is required for HUD(apple counter, lives etc) rendering.
Shenmue II - hack is required for main menu rendering.

**Comment by LukeUsher** [comment]
Hack is no longer required for Crash Bandicoot Hud, the Shenmue Menu or DOA2/3.
Other games need testing and reporting back

**Comment by Margen67** [comment]
This hack makes Reshade able to access the depth buffer for things like Ambient Occlusion, Depth of field, etc.

**Comment by LukeUsher** [comment]
> This hack makes Reshade able to access the depth buffer for things like Ambient Occlusion, Depth of field, etc.

It is not our job to support third party enhancement software. The problem with this hack is it ignores the Xbox created backbuffer and depth buffer, it breaks high resolution rendering and makes emulation of the Xbox swap chain much more difficult. 

We don’t want to sacrifice accuracy / keep known incorrect behaviour just to support third party enhancement software. It’s not our fault that reshade can’t find the correct depth buffer.

**Comment by ergo720** [comment]
This hack was removed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1667 so closing this.
