### ISSUE TITLE
halo 2

### ISSUE THREAD

**Issue by mohamednadir** [Cxbx-Reloaded/Cxbx-Reloaded#1600]
halo 2:
![38322821-c7e5730e-383b-11e8-877d-dab77305cb39](https://user-images.githubusercontent.com/50266170/57179174-21f7db80-6e0e-11e9-925a-6314dd76a14b.png)

with enable the LLE GPU.
 Only the introduction of the game play.
Then exit the game.
I hope you fix it well in the next release

**Comment by FabxBs** [comment]
Please report this issue in this compatibility list https://github.com/Cxbx-Reloaded/game-compatibility/issues
