### ISSUE TITLE
Collect valuable resources here

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#162]
Let's build a list of valuable (developer) resources, everyone, by adding links to this issue!

Chat :
* https://gitter.im/Cxbx-Reloaded/Lobby

Xbox Software Development Kit (XDK / SDK) info :
* http://codeasm.com/xbox/Kernel_Dash_versions.htm#classic

XBox Executable (XBE) tools :
* [Decode mangled symbol names into readable declarations](https://demangler.com/)
* http://dxbx-emu.com/information/xbeexplorer/

Learn from other working XBox emulators:
* https://github.com/espes/xqemu
* https://github.com/mamedev/mame/blob/master/src/mame/machine/xbox.cpp
* https://github.com/PatrickvL/Dxbx

NV2A info:
* https://cgit.freedesktop.org/mesa/mesa/plain/src/mesa/drivers/dri/nouveau/nouveau_class.h?id=69f54d2a7e06210f28b46d20f74a906d9750a36e
* http://neuralyte.org/~joey/hwimirror/hwi.ath.cx/src/keep/svnc_zoom/svgalib-1.4.3/src/nv3ref.h
* https://github.com/espes/xqemu/blob/fix-fifo/hw/xbox/nv2a_int.h
* https://github.com/espes/xqemu/blob/fix-fifo/hw/xbox/nv2a.c

Kernel info :
* https://en.wikipedia.org/wiki/Win32_Thread_Information_Block

Debugging info:
* [Hexadecimal x86 opcode decoding](https://www.onlinedisassembler.com/odaweb/)
* [Translate C gibberish to English](http://cdecl.ridiculousfish.com/)

Timing :
* https://msdn.microsoft.com/en-us/ms682485(v=vs.85)
* https://msdn.microsoft.com/en-us/library/windows/desktop/ms682492(v=vs.85).aspx
* https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx
* http://stackoverflow.com/a/11743614/12170
* http://www.windowstimestamp.com/description
* http://www.virtualdub.org/blog/pivot/entry.php?id=272

Preemptive thread switching :
* http://www.pavius.net/implementing-a-preemptive-kernel-within-a-single-windows-thread/
* https://github.com/cjlano/freertos/blob/master/FreeRTOS/Source/portable/MSVC-MingW/port.c
* http://web.mit.edu/freebsd/head/sys/compat/ndis/subr_hal.c
* [Emulating Operating System Synchronization](https://msdn.microsoft.com/en-us/library/ms810431.aspx)

Hardware components:
* [SMBUS datasheet](http://smbus.org/specs/smbus20.pdf)
* [USB controllers](http://euc.jp/periphs/xbox-controller.ja.html)

**Comment by PatrickvL** [comment]
Once they start pouring in, we can organise all suggestions into a wiki page.

**Comment by BenNottelling** [comment]
I don't know if you already have them, but I've found two sources for the XDX.
http://codeasm.com/xbox/files/Xbox%20XDK%20Rare%20Samples%20-%20BlueShogun96/
and
http://www.theisozone.com/downloads/xbox/tools/xbox-developers-kit-5933/
I believe The Iso Zone link has more compiled.

**Comment by PatrickvL** [comment]
https://github.com/ocornut/imgui seems like The library to use for adding a GUI on top of the Xbox output...

**Comment by ergo720** [comment]
Is this still valid? The [xboxdevwiki](http://xboxdevwiki.net) now has such information

**Comment by PatrickvL** [comment]
If everything listed in this issue is also present there, then sure, this issue could be closed. If not, it would be best to either directly copy over what's missing over there, or write down here what still needs to be copied over.

**Comment by LukeUsher** [comment]
This information is better suited to a Wiki (either XboxDevWiki, or our own wiki in Github depending on if the info is relevant to everyone or just us).
