### ISSUE TITLE
"Couldn't not open the xbe file" keep showing

### ISSUE THREAD

**Issue by HutDave** [Cxbx-Reloaded/Cxbx-Reloaded#1628]
Hi everyone, I downloaded the latest Cxbx release.

I downloaded the recommended dashboard (the 4920) from a site, and put all the files in the "Second Partition" folder. However, when I try to start the dashboard from the emulator it continually gives me the error message "Couldn't not open the Xbe file xboxdash.xbe". How is it possible? I followed all the steps also from the FAQ on GitHub regarding Cxbx. I tried with some google search, and nobody seems to have my problem: I only read about people who have problems regarding the graphical display of the dashboard, my dashboard don't even start, let alone! =D

So I don't know if you can give me a hand, maybe I also attach a "Second Partition" screen where you will see all the files that are regularly placed, including the Xbe file that the emulator says it can't open.

Finally, I wanted to ask you, is it possible with this emulator to run the Halo 2 map packs? Killtrocity, remapped, etc. I don't know if anyone has ever heard of it.

Thanks in advance, I'm waiting for news!
![Immagine](https://user-images.githubusercontent.com/51442695/59027382-22debb80-8859-11e9-80e9-1d749e66def1.png)

**Comment by PatrickvL** [comment]
Closing due to the mention of piracy.
