### ISSUE TITLE
Keys I mapped are not responding

### ISSUE THREAD

**Issue by Kingus1** [Cxbx-Reloaded/Cxbx-Reloaded#1638]
Hey I'm having a problem with the keys I mapped
They aren't responding after I start the emulation. I have even tried to change the Controller Mapping to  DirectInputPort0 and I'm still having no luck

At first I tried to use my Gamecube controller/Adapter piece and the Emulator recognizes the controller but any time I try to map the inputs it all gets mapped to the same button as if I'm holding down on my controller. (I have to fully working controllers so it's not my controller that's messed up)

So then I tried to use my Keyboard and it was at least mapping the inputs correctly but when I go and try to use the start button in game it doesn't work at all. Pls help

**Comment by Kingus1** [comment]
![Help 1](https://user-images.githubusercontent.com/51933333/59642473-1bf65980-9133-11e9-9bc0-bf657d691c82.JPG)
![Help 3](https://user-images.githubusercontent.com/51933333/59642521-56f88d00-9133-11e9-8784-2675b1c48529.JPG)

**Comment by ergo720** [comment]
Known problem. Just use an XInput wrapper such as x360ce to map any controller to XInput (as long as x360ce can detect it), so that you don't have to mess with DInput. Also, to ask for help, you should use our [discord server](https://discordapp.com/invite/26Xjx23) instead of here. Closing.
