### ISSUE TITLE
DOA2U and DOAX corrupting the saves

### ISSUE THREAD

**Issue by Hadocem** [Cxbx-Reloaded/Cxbx-Reloaded#1643]
DOA2U and DOAX corrupting the saves

Description:

When I change the Dead or Alive 2 Ultimate or Dead or Alive Xtreme Volleyball location Saves, the game saves corrupt. Now I changed the PC and the saves did not work, the saves of the other games worked correctly. Dumps are divided into two modes: Dump, Store with Executable (Dumb of Test saves normal) and Dump, Store in Appdata (Dump Test with corrupted saves).

Dumps: Normal saves

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322512/KrnlDebug.txt)
![Sem título](https://user-images.githubusercontent.com/28853392/60050456-0a6aff80-96a7-11e9-9ff9-aa953cd0e1fa.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322514/Xbe.txt)

![DOAX](https://user-images.githubusercontent.com/28853392/60050518-2e2e4580-96a7-11e9-93f3-e1e6b2351c75.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322516/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322517/Xbe.txt)

Dumps: Corrupted Saves

![DOA2U_c](https://user-images.githubusercontent.com/28853392/60050570-5453e580-96a7-11e9-8fcd-d528379a0ead.png)
[KrnlDebug_corrompt.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322520/KrnlDebug_corrompt.txt)
[Xbe_corrompt.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322521/Xbe_corrompt.txt)

![DOAX_c](https://user-images.githubusercontent.com/28853392/60050601-603fa780-96a7-11e9-8b30-3bf1f4c405c0.png)
[KrnlDebug_corrompt.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322523/KrnlDebug_corrompt.txt)
[Xbe_corrompt.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3322524/Xbe_corrompt.txt)

Additional Information

In this system the same problems happened.

Notebook: Dell XPS L502X
Operational system: Windows 7 Ultimate 64bit SP1
CPU: Intel Core i7 2620M @ 2.70Ghz // Sandy Bridge 32nm Technology
RAM: 6GB Dual-Channel DDR3 @ 665Mhz (9-9-9-24)
Motherboart: Dell Inc. 04X7VP (CPU)
Graphics: Intel Driver version 9.17.10.4229 // NVIDIA GeForce GT 525M // GPU GF108 //
DirectX Support 11.0 // OpenGL Support 5.0 // Driver version 23.21.13.9135
Physical Memory 1023 MB // Virtual Memory 1024 MB

Current system.

System Window 10 Home 64bit (Build 17763)
DirectX 12.0
Intel Core i5 8400 
Motherboad: ASUS Prime Z390-P Chipset Intel Coffee Lake
RAM: 8GB DDR4 Frequency 3200Mhz
GPU: GTX 1050 TI  4GB

**Comment by LukeUsher** [comment]
These two games are known to lock savedata to a specific console: You cannot share savedata for these games between different Xbox's or between different Cxbx-R installations. 

This is not a Cxbx-Reloaded bug,, but the games working as designed.

**Comment by Hadocem** [comment]
Thank you. I did not know that!
