### ISSUE TITLE
Weird light bleed. Haunted Mansion

### ISSUE THREAD

**Issue by Modeltrainman** [Cxbx-Reloaded/Cxbx-Reloaded#1645]
When fighting an enemy, or using the Beacon of Souls, there's weird light effects. And when saving, it thinks the non existent disc is dirty.
[hmissue.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3331368/hmissue.zip)

**Comment by ergo720** [comment]
Game specific issues should be reported in the [game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) repository instead. For this game, there is an entry already [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/366). Closing.
