### ISSUE TITLE
Linux (Wine) : Passing an xbe as a command line parameter causes crash

### ISSUE THREAD

**Issue by 7oxicshadow** [Cxbx-Reloaded/Cxbx-Reloaded#1653]
As per the title really. I use CXBX-R on Linux via Wine.

If I pass a .xbe file as a command line parameter the GUI will open and the correct icon for the game will be displayed in the bottom right but when it tries to auto launch it results in a crash. 

Note: The crash does not close the GUI, it just halts execution. Whilst the GUI is still open if I try to start the emulation again it results in the same crash. 

The interesting this is that even after a crash, if I keep the GUI open and goto file > open and select the same .xbe and then start the emulation it works fine.

It almost suggests that the file > open procedure is doing something different to the command line processing. I currently do not have access to a windows environment so I am unable to test if it effects windows as well.

If someone tests on Windows and it works fine, this is probably a Wine bug and the issue can be closed.

**Comment by Margen67** [comment]
I don't have the same issue on Windows 10. Try adding `/load` before the path of the game in the launch parameters.

**Comment by 7oxicshadow** [comment]
Thanks for testing on Windows. It helped me to focus more on the Wine side of things.

The /load didn't have any effect but thankfully I have managed to solve the problem. I was passing the path to the xbe in Linux format /mnt/blah/blah/blah/default.xbe. I was of the impression that Wine would automatically resolve linux style links to the equivalent wine based drive mapping (z:/ in this instance) but for some reason cxbx-r doesn't like it.

If you pass a Linux style link, cxbx-r does load it (as indicated by the game icon in the corner) but appears to have issues during the run stage.

If I pass the parameter as z:/mnt/blah/blah/blah/default.xbe it works fine and runs without any problems.
