### ISSUE TITLE
D3D Resources are erronously freed under certain conditions.

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#1665]
If D3DResource_Release is called such that it sets the reference count to zero, we free the associated host resource and reset any variables containing the referenced resource.

However, it has been discovered that it is incorrect to free the host resource at this point: If the internal reference count (not returned by D3DResource_Release) is > 0, then the freeing of the resource is delayed until the internal reference count reaches zero.

The correct point to do this free operation would be when the XDK calls DestroyResource(); At this point the Xbox resource is freed and the host resource should be too.

Fixing this issue depends on https://github.com/Cxbx-Reloaded/XbSymbolDatabase/issues/82, as we currently have no method to hook the DestroyResource function.

This is the cause for `LOG_TEST_CASE("SetRenderTarget fallback to backbuffer");`

And also potentially the cause for some of the remaining black screen issues, so I consider this quite important.

(Documenting the issue so it doesn't get forgotten, but I'll address this as soon as XbSymbolDatabase allows)

**Comment by ObiKKa** [comment]
> This is the cause for `LOG_TEST_CASE("SetRenderTarget fallback to backbuffer");`

He's referring to the issue put up recently before this issue here: #1663

**Comment by PatrickvL** [comment]
I believe Luke fixed this in merged pull request #1701

**Comment by LukeUsher** [comment]
Yes this issue is resolved
