### ISSUE TITLE
No 3D Graphics

### ISSUE THREAD

**Issue by fuhuan416** [Cxbx-Reloaded/Cxbx-Reloaded#1691]
Intro is perfect.
All audioes are almost perfect.
Menu perfect.
Ingame only display 2D Graphics, no any 3D Graphics, but audioes are normal.
CPU: E3-1230 v3
Video Card: GTX 1060

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3489765/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3489766/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3489767/Xbe.txt)
![01](https://user-images.githubusercontent.com/6281757/62832181-2463a000-bc5d-11e9-80c0-98dc5a2626cb.png)
![02](https://user-images.githubusercontent.com/6281757/62832182-24fc3680-bc5d-11e9-939e-89820e938952.png)
![03](https://user-images.githubusercontent.com/6281757/62832184-24fc3680-bc5d-11e9-871e-3be2bbf7da67.png)
![04](https://user-images.githubusercontent.com/6281757/62832185-2594cd00-bc5d-11e9-941c-68a36db1c5eb.png)

**Comment by ergo720** [comment]
Game specific issues should be reported in the [game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) repository instead. For this game, there is an entry already [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/117). Closing.

**Comment by PatrickvL** [comment]
@fuhuan416 thanks, and please update that issue with the above information - and we always like to see a few screenshots over there too!
