### ISSUE TITLE
NtDuplicateObject creates invalid handles for NtReadFile

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#1718]
Test cases:
* Project Zero 1
* Project Zero 2

Here is my original message on the issue for Project Zero 2:
>I understood the problem: it's an issue with ```NtDuplicateObject```. The offending handle was first created with a call to ```NtCreateFile``` for the file "bin\\data\\tim\\font.pk2", which does exist in the game files and the function succeeds. Then it calls ```NtDuplicateObject``` on this handle, which succeeds as well and creates a duplicate of it (note that ```IsEmuHandle``` returns false for this call). After that it calls ```ObReferenceObjectByHandle``` on the duplicate and this one fails with ```STATUS_INVALID_HANDLE```, which is expected as our ```NtDuplicateObject``` simply forwards to its Windows counterpart ```Ntdll::NtDuplicateObject```, and thus our kernel Ob functions will never know about the duplicate. Finally, it calls ```NtReadFile``` on the duplicate (which simply forwards to ```Ntdll::NtReadFile```), which forever fails and hence the hang. So, it seems that the duplicate handle created by ```Ntdll::NtDuplicateObject``` is rejected by ```Ntdll::NtReadFile``` for some reason.

And here are the relevant kernel function calls extracted form the kernel log:
```
[0x0950] NT      NtCreateFile forwarding to "IoCreateFile"...
[0x0950] IO      IoCreateFile(
 OUT FileHandle         : 0x0B32FDFC
   DesiredAccess        : 80100080
   ObjectAttributes     : 0x0B32FDE0 -> OBJECT_ATTRIBUTES* {
   .RootDirectory        : FFFFFFFD
   .ObjectName           : 0x0B32FDF4 -> STRING* {
   .Length               : 18
   .MaximumLength        : 19
   .Buffer               : (char *)0x00362900 = "D:\\bin\\data\\tim\\font.pk2"}
   .Attributes           : 40}
 OUT IoStatusBlock      : 0x0B32FDEC
   AllocationSize       : 0x00000000
   FileAttributes       : 0
   ShareAccess          : 1
   Disposition          : (CREATE_DISPOSITION)0x00000001 = FILE_OPEN
   CreateOptions        : (CREATE_OPTION)0x00000048 = FILE_NO_INTERMEDIATE_BUFFERING|FILE_NON_DIRECTORY_FILE
   Options              : 0
);
[0x0950] DEBUG: IO      IoCreateFile = 0x00003E38
[0x0950] IO      IoCreateFile returns 0

[0x0950] NT      NtQueryInformationFile(
   FileHandle           : 00003E38
 OUT IoStatusBlock      : 0x0B32FDF4
 OUT FileInformation    : 0x0B32FDBC
   Length               : 38
   FileInformationClass : (FILE_INFORMATION_CLASS)0x00000022 = FileNetworkOpenInformation
);
[0x0950] NT      NtQueryInformationFile returns 0

[0x0950] NT      NtDuplicateObject(
   SourceHandle         : 00003E38
   TargetHandle         : 0B32FE34
   Options              : 0
);
[0x0950] NT      NtDuplicateObject returns 0

[0x0950] OB      ObReferenceObjectByHandle(
   Handle               : 00003F04
   ObjectType           : 0451C024
 OUT ReturnedObject     : 0x0B32FE38
);
[0x0950] OB      ObReferenceObjectByHandle returns C0000008

[0x2998] NT      NtReadFile(
   FileHandle           : 00003F04
   Event                : 00000000
   ApcRoutine           : 042F96C0
   ApcContext           : 0010D7C0
 OUT IoStatusBlock      : 0x003642FC
 OUT Buffer             : 0x83417000
   Length               : 20000
   ByteOffset           : 0x0DBBFE64 -> LARGE_INTEGER* {
   .QuadPart             : 0}
);
[0x2998] WARN : NT      NtReadFile Failed! (0xC0000022)
```

**Comment by LukeUsher** [comment]
The proper fix for this issue would be to entirely avoid forwaring to Windows NT APIs, and instead use our own implementation for the entire thing: That way we can implement correct behavior for all APIs and correct interaction between them, but obviously, this is an absolutely massive amount of work.

**Comment by ergo720** [comment]
I can confirm that Project Zero also has this same problem: it duplicates an handle with `NtDuplicateObject` and then calls `NtReadFile` on the duplicate, which fails with the error code 0xC0000022 (STATUS_ACCESS_DENIED).
