### ISSUE TITLE
Command line crashes cxbx

### ISSUE THREAD

**Issue by anchounio** [Cxbx-Reloaded/Cxbx-Reloaded#1734]
Starting a game in command line crashes cxbx. For example
Enter CMD
type:
Cxbx.exe ".\roms\Virtua Cop 3\vc3.xbe"

cxbx will crash after this.

**Comment by RadWolfie** [comment]
Relative path isn't supported in Cxbx-Reloaded. Absolute path to the xbe file is currently a requirement. Otherwise, the emulator will not work correctly.

**Comment by RadWolfie** [comment]
We will investigate the crash then may will either simply terminate emulation or maybe also include a dialog message.

**Comment by anchounio** [comment]
Works fine using absolute path. 
Thank you !

**Comment by x1nixmzeng** [comment]
This can be closed

**Comment by PatrickvL** [comment]
Fixed by PR #1766
