### ISSUE TITLE
Overview of unmerged pull request

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1739]
Below, all pull request that are currently closed, with an indication on their status.

This overview should be kept up to date, to prevent uncertainty. Also, having this up to date overview avoids spending repeated  efforts to ascertain the state of closed pull requests.

Possible states per pull request:
* Invalid (explain why it wasn't good)
* Obsolete (should reference replacement pull request)
* On-hold (should be revived once the reason it's been paused was resolved)
* Cherry pick (mention which pieces are worthy)
...

**Comment by ergo720** [comment]
I think we are never going to do this, since the reason for the closure is usually written in the PR or discussed among devs. Also, closed PRs can easily be searched for on github with the filter `is:unmerged is:closed`, so they don't need to be linked here.

**Comment by PatrickvL** [comment]
Yeah, true. But perhaps we can still do something about this by introducing "closed-for-good", "closed-obsolete", "closed-on-hold", "closed-but-revisit" labels, assigning the most appropriate one to each closed pull request that isn't yet labelled with one such.

**Comment by ergo720** [comment]
I did it. A added the above labels to all closed PRs, so closing this now.
