### ISSUE TITLE
Convert Xbox vertex shaders to HLSL

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1751]
Xbox vertex shaders are currently converted by Cxbx-Reloaded to shader (model 2) assembly. This has a few downsides, like register limitations, complicated register (re)allocation, instruction limits, etc.

For this issue, implement a converter for binary Xbox vertex shaders towards HLSL.

HLSL on Direct3d 9 (our current render API) allows a higher shader model, less limitations, more flexibility and easier conversion code.

One of the possible approaches discussed between current developers suggests to declare predefined functions for every operation Xbox shader assembly is capable of. Then, include this set of functions in a converted shader, and generate HLSL calls to those functions for each Xbox operation present in the Xbox shader that's being converted.

Obviously, the resulting shaders must be compiled, preferably once using a caching mechanism (initially in memory, later on disc to survive across reboots). Using cached shaders reduces the stutter/lag that results from shader conversion and compilation.

**Comment by PatrickvL** [comment]
Note : It'd be nice if we could use precompiled shader linking (https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/using-shader-linking) for the predefined functions, so that only the actual converted shader (which would entirely consist of calls to these predefined functions) needs to be compiled during run-time (hopefully reducing the amount of time needed for this).

**Comment by LukeUsher** [comment]
@PatrickvL Shader linking is supported starting with Windows 8.1, but we must keep supporting Windows 7 for the forseable future (many users refuse to upgrade due to increased telemetry and other privacy concerns)

**Comment by PatrickvL** [comment]
Let's decide later if we want to differentiate between Windows versions (regarding the use of precompiled shader linking under Windows 8.1 and up, vs generating the entire shader in lower Windows versions) or not.
