### ISSUE TITLE
Dino crisis 3 Black Screen No sounds

### ISSUE THREAD

**Issue by Neltharionx** [Cxbx-Reloaded/Cxbx-Reloaded#1760]
I downloaded cxbx-reloaded, then dino crisis 3.xbe and it start, but nothing appear only black screen and no sounds.
![Dino crisis](https://user-images.githubusercontent.com/57038627/67620340-fcb8b880-f805-11e9-8512-719fa3a9bbf6.PNG)

**Comment by RinMaru** [comment]
dude that build is old update your build to the dev build

**Comment by ergo720** [comment]
Game specific issues should be reported in the [game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) repository instead. For this game, there is an entry already [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/114). Closing.

**Comment by PatrickvL** [comment]
Also, when you mention downloading a commercial game, realise you're not going to get any support
