### ISSUE TITLE
Dead Or Alive 2 Ultimate Eject the control

### ISSUE THREAD

**Issue by Hadocem** [Cxbx-Reloaded/Cxbx-Reloaded#1773]
After I finish Time Attack the emulator loses the connection with the controller, and after a few minutes or seconds of game scenes the emulator crashes.

**System**

CPU:  Intel Core i5 8400 2.8GHz (4.0GHz Turbo) 6-Core 6-Thread
RAM: DDR4 Crucial Ballistix Sport Lt, 16GB 3200MHz
Placa de Video: GTX 1050Ti
Motherboard: Asus Z390-p
Fonte: Gamemax GM600 600W
Water Cooler:  Mymax Algor, LED Red 120mm.

![uuuuyyyyggtt](https://user-images.githubusercontent.com/28853392/68624822-757e6c80-04b6-11ea-82ff-c7c5f6e0a124.png)

**Comment by LukeUsher** [comment]
Please report game-specific issues in the Game Compatibility tracker or update the existing entry if one already exists: https://github.com/Cxbx-Reloaded/game-compatibility/issues
