### ISSUE TITLE
Popup "Skipping Release of active Xbox Render Target"

### ISSUE THREAD

**Issue by JusicP** [Cxbx-Reloaded/Cxbx-Reloaded#1779]
LOG_TEST_CASE: Skipping Release of active Xbox Render Target
In DestroyResource_Common (C:\projects\cxbx-reloaded\src\core\hle\D3D8\Direct3D9\Direct3D9.cpp line 8567)

- Half-Life 2
- [Kameo: Elements of Power](https://github.com/Cxbx-Reloaded/game-compatibility/issues/728#issuecomment-615327344)

**Comment by infinitephantasm** [comment]
Jet Set Radio Future triggers this popup when boost dashing.

**Comment by ObiKKa** [comment]
This game, Cold Fear, consists of 8 different test case messages according to an April 2020 update in its issue.

- [Cold Fear](https://github.com/Cxbx-Reloaded/game-compatibility/issues/728#issuecomment-615327344)

**Comment by CookiePLMonster** [comment]
#2036 removed those test cases so the issue can be closed I believe.

**Comment by ObiKKa** [comment]
One comment from October 18, 2020 for the game Metal Dungeon had a popup with a similar message to the popup message for this issue (Just with the word '**Texture**' switched in place of '**Target**'). Hopefully, it will have been solved by the PR # 2036 in the last comment above.

Message:
"Skipping Release of active Xbox Texture in DestroyResource_Common"

**Oct 2020:**
- [Metal Dungeon](https://github.com/Cxbx-Reloaded/game-compatibility/issues/463#issuecomment-711034522)
