### ISSUE TITLE
Still life minor graphical issues

### ISSUE THREAD

**Issue by LuismaSP89** [Cxbx-Reloaded/Cxbx-Reloaded#1794]
Still life is nearly 100% playable, the only issue is that some texts are not shown "The text decission when you need to press L or R buttons" you can see this in the very start of the game, in the first conversation with the policeman.

Note: Tested with latest build from december 02.

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forums on [Gitter](https://gitter.im/Cxbx-Reloaded/Lobby) or [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
