### ISSUE TITLE
AMD RX 5700 (XT): Attempting to start any game hangs emulation

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#1804]
While using my RX 5700 to run Cxbx-R, it will fail to start any game (even simple 2d homebrew) but the application itself will not crash.  Swapping back to my older GPU: an AMD R9 Fury, fixes the issue immediately. So it appears that this issue only affects the newer RDNA series cards (so 5700, 5700XT, 5500, etc.).

I've reported this issue to AMD back in August, however I have gotten no response since then and the updated drivers released since then haven't made a difference. Using a wrapper such as dxvk does allow some games to work, but it comes with its own problems and shouldn't be considered a long-term solution.

Tested versions: ``4ff4fd1a`` (Nov 25th)  initially, updated to ``76d45fdd`` (Dec 19th) - no change
Tested games: Crimson Skies HRTR, Jet Set Radio Future (Combo Disc), Zapper: One Wicked Cricket

Screenshot:
![2019-12-22_06-32-28](https://user-images.githubusercontent.com/5341136/71321832-e8e7a680-2484-11ea-8429-7164a92c2a8b.gif)

[KrnlDebug.txt for Zapper, all logging options enabled, Info level selected](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/3992423/KrnlDebug-5700.txt)

Let me know if I can provide any further info or assist with troubleshooting.

**Comment by ergo720** [comment]
Shouldn't this be part of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1803 instead of having its own issue?

**Comment by RadWolfie** [comment]
The other issue is to verify which AMD cards are affected by HLSL pull request change.

AMD RX 5700 (or 5500?) and later always produce a crash. It is also affecting PC games using D3D9 to crash as well afaik. **AMD didn't fix the issue for months, hence the issue creation here for awareness.**

**Comment by CakeLancelot** [comment]
Yep, as RadWolfie said this is different - trying to start any game with the RX5700 will fail. Older AMD cards will at least boot the game, but with graphical issues (this is detailed in #1803).

**Comment by LukeUsher** [comment]
This needs retesting now that #1865 is merged. It's thought to be an unrelated issue but nobody knows for sure.

This issue only impacts newer RDNA series AMD cards

**Comment by evelyndooley** [comment]
This is still an issue. Just upgraded to the 5700 XT and can't play any games.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/4958304/KrnlDebug.txt)

**Comment by MIuIddy** [comment]
Seems to be fixed in latest GPU drivers (v2020.11.2).

**Comment by FuZzCasT** [comment]
It crashes for me when I get up to Chuo Street. It gets to loading screen screen then CXBX just closes the game. This is further progression than before because it wouldn't show that loading screen in last years build of CXBX it'd just error out.

**Comment by JacqylFrost** [comment]
This is occurring for me on an RX Vega 64 with the most recent driver: 21.10.4, it also happened with 2021.0929.0048.1438

I have tried with a large variety of builds, including the most recent at the moment, 94f0258.

Lego Star Wars 2, works, as well as a demo disc launcher for Sega GT 2002 and JSRF, but not the games themselves
Star Wars The Clone Wars works
Tetris Worlds boots up, encounters an error, but does show a bit of the game first
Star Wars Obi-Wan also boots up fine.

Sega GT 2002 does not work, launching only to a black screen.
Jet Set Radio Future, both the demo disc version, and the NTSC retail release, also launch to a black screen.

These are both known-good rips from known-good discs that used to play in CXBX just fine around a year ago.

Doom 3 (Collector's Edition, if it matters) also boots to a black screen

Please let me know if there are any logs or other information that would be helpful.

**Comment by CakeLancelot** [comment]
While I no longer possess the card to test it myself, others have been able to confirm that you can at least boot up games with the 5700XT.
For compatibility issues in specific games or situations, I think creating a new ticket would be more applicable.

Closing as resolved.
