### ISSUE TITLE
Controller binding displays wrong keys.

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#183]
Although It isn't much an issue on some keys such as white, black, x, a, b, and y the text it displays is in the wrong key (at the bottom). Meaning if I set the white key "space" it would say the back was binded. Not a big deal, but it is confusing and it means it will take people longer to setup the emulator.

**Comment by jarupxx** [comment]
Please test if PR # 186 fixes Controller binding.

**Comment by PatrickvL** [comment]
PR#186 did fix it, but it also changed the enum XBCtrlObject. Instead, it's better to fix the real cause of the problem : the ordering of the values in m_DeviceNameLookup. I've done that in PR#188 commit https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/188/commits/b869667538a3b1e0d448624b79a1e5b6d4f60763
