### ISSUE TITLE
Dead or Alive: Xtreme Beach Volleyball - Crashing when it was fine before.

### ISSUE THREAD

**Issue by redness2** [Cxbx-Reloaded/Cxbx-Reloaded#1831]
Starting crashing while playing DOAX at random loading times now when before there were none. I thought it was because of the newer CXBX versions but reverting to older versions still causes crashing (tried the Oct and Dec versions). Nothing has changed with my system between the time when it wasn't crashing and when it started happening.

i7 8700k
MSI GTX 1070
16GB RAM

The crashing would only happen in the start of certain (not all) loading screens. I can't pinpoint what is causing this exactly and I've tried multiple video settings and as far as I could tell it has nothing to do with that.

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
