### ISSUE TITLE
error while building: Failed to run MSBuild command

### ISSUE THREAD

**Issue by DemonExposer** [Cxbx-Reloaded/Cxbx-Reloaded#1841]
`C:\Users\KelvinBouma\Documents\Cxbx-Reloaded\build>cmake .. -G "Visual Studio 16 2019" -A Win32
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 10-3-2020 17:48:34.
    Project "C:\Users\KelvinBouma\Documents\Cxbx-Reloaded\build\CMakeFiles\3.14.19050301-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
    PrepareForBuild:
      Creating directory "Debug\".
      Creating directory "Debug\VCTargetsPath.tlog\".
    InitializeBuildStatus:
      Creating "Debug\VCTargetsPath.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
    PostBuildEvent:
      echo VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\
      :VCEnd
    FinalizeBuildStatus:
      Deleting file "Debug\VCTargetsPath.tlog\unsuccessfulbuild".
      Touching "Debug\VCTargetsPath.tlog\VCTargetsPath.lastbuildstate".
    Done Building Project "C:\Users\KelvinBouma\Documents\Cxbx-Reloaded\build\CMakeFiles\3.14.19050301-MSVC_2\VCTargetsPath.vcxproj" (default targets).

    Build succeeded.
        0 Warning(s)
        0 Error(s)

    Time Elapsed 00:00:00.39

-- Configuring incomplete, errors occurred!
See also "C:/Users/KelvinBouma/Documents/Cxbx-Reloaded/build/CMakeFiles/CMakeOutput.log".`

**Comment by RadWolfie** [comment]
I had encounter this issue before, can you verify if you had installed the [prerequisites](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded#prerequisites-1)?

If you do have installed the prerequisites, then verify your anti-malware software are not running visual studio's tools, including CMake's tools as well, in a sandbox environment. You will need to exclude directory/applications in order not to send into sandbox environment.
