### ISSUE TITLE
Loading Screen Dark on several games.

### ISSUE THREAD

**Issue by KPreston2900050** [Cxbx-Reloaded/Cxbx-Reloaded#1878]
Destroy all Humans One and Two for instance.
I suspect this is do to a video player issue because these are pre-rendered video.
I could mention other games but being as DAH one and two must use the same codec?  WMV?

Missing graphics during attract screen.

I would also love to request a radio switch in the menu to turn off the warning every time I load a game.
You are not going to get an unpatched game that uses an unpatched XBE.
You can't use original disks and this is annoying.
If it is my machine and I take the risk then please stop doing things for my own good.
Linux does that and have gone through great lengths to stop every patch and sudo in order to make you type in a password every time you take a pee.

So if those two lines of code that shuts off the warning message could be added in that would be great.

**Comment by ergo720** [comment]
> Destroy all Humans One and Two for instance.

Those are game-specific issues and don't belong here.
>I would also love to request a radio switch in the menu to turn off the warning every time I load a game.

There is already: Settings -> Allow Admin Privilege and it won't warn you every time.
>You are not going to get an unpatched game that uses an unpatched XBE.

You can? You can either dump them with a kreon drive of by transferring them from your Xbox with FTP. 
>You can't use original disks and this is annoying.

See https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1555#issuecomment-465758921

**Comment by KPreston2900050** [comment]
Game specific issues were just two examples so YOU can take a look at the codec.
It is system wide and is not about the games themselves.
Did I say game play? No.
And yes, we all know about FTP'ing from original XBox's done some 17 years ago.
The point was about the XBE getting an error and the suppression of warning.
Thank you for the admin rights.  Somewhere along the line I would love to see the manual about the various options.
Admin rights to me and every other windows power user means admin rights to specific locations so maybe "Disable Warnings" may be a better choice of words.

Either way, I'm going to let this go and address CXBX in 10 years from now when it actually works.  Then again, I said the same thing about 10 years ago.

**Comment by deadair3210** [comment]
You seem pleasant...
