### ISSUE TITLE
Recent builds cannot boot games

### ISSUE THREAD

**Issue by Tromzy** [Cxbx-Reloaded/Cxbx-Reloaded#1883]
With Cxbx-Reloaded v0.1, Jet Set Radio Future boots fine ; but with any of the other available builds, the game does not launch ; I get no error, no message, just a black screen for about 5 seconds then the game closes and I'm back at the emulator screen. I tried to play with the settngs a bit, then I reset everything to default and nothing changes. My specs are :

- Ryzen 5 3600 stock
- GeForce 1080
- 16 GB DDR4
- Windows 10
- 2560*1440 @ 144Hz Gsync monitor.

I just tested with JSRF and DOA 3 because these are the only games I have. None of them work on recent builds, JSRF works on Cxbx-Reloaded v0.1 and not DOA 3 but I think it was not yet supported yet so I guess that's normal.
Let me know if you need any other information.

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

**Comment by RadWolfie** [comment]
The issues you're experiencing are from your end. Still, you should contact support in discord for further assistance. 🙂

P.S. v0.1 release is outdated build.
