### ISSUE TITLE
Real Xbox to CXBX save tranfer

### ISSUE THREAD

**Issue by ruthan** [Cxbx-Reloaded/Cxbx-Reloaded#1893]
Hello,
i know that is in FAQ, that is not easy, but i thing that even than issue should be open and should exists in tracker.
  For me its big blocker, i would like to transfer my Xbox or Xbox 360 (Xbox classic compatibility) saves and play my games on PC, without Xbox noise, with digital clean picture and in higher resolution.

**Comment by LukeUsher** [comment]
Transferring saves is already supported, you can just copy the savedata from your Xbox HDD to the correct EmuDisk folder in Cxbx-Reloaded.

It does, however, require that you have a dump of your xboxes keys, keys.bin, in your data folder.

There's nothing we can do to fix that: Sharing the keys with the emulator is illegal, so we can't include them.

**Comment by ruthan** [comment]
Ok thanks, but it that case FAQ should be adjusted.
  How to dump keys.bin ? Is it working only for Xbox, or its possible to make it also for Xbox game save from Xbox 360?

**Comment by LukeUsher** [comment]
Dumping the keys is not quite an easy process right now, but there are few tools/scripts for doing so.
The keys for OG xbox save-data are the same on every single Xbox, so once you have them, you can use save data from anywhere.

However, the keys are not legal to share with others.

Two options for dumping the keys from an original xbox are the Dump Keys python script https://github.com/JayFoxRox/xbox-tools/blob/master/python-scripts/dump-keys.py (requires XboxPy)

Or dump-xbox (requires compilation with openxdk) https://github.com/JayFoxRox/xbox-tools/tree/master/dump-xbox

**Comment by ergo720** [comment]
Closing, as this is an already supported feature and the wiki was updated with the new information for dumping the keys.
