### ISSUE TITLE
Pop-up "Applying 3925 alpha test disable hack"

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1899]
LOG_TEST_CASE: Applying 3925 alpha test disable hack
In ApplySimpleRenderState (D:\a\Cxbx-Reloaded\Cxbx-Reloaded\src\core\hle\D3D8\Direct3D9\RenderStates.cpp line 283)

Titles:
- Airforce Delta Storm

**Comment by doug-clayton** [comment]
This also appears for Dead or Alive 3.

**Comment by ergo720** [comment]
Closing because this test case was removed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2052/files
