### ISSUE TITLE
Pop-up "Applying 3925 fog disable hack"

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1900]
LOG_TEST_CASE: Applying 3925 fog disable hack
In ApplyDeferredRenderState (D:\a\Cxbx-Reloaded\Cxbx-Reloaded\src\core\hle\D3D8\Direct3D9\RenderStates.cpp line 337)

Titles:

- Airforce Delta Storm

**Comment by doug-clayton** [comment]
This also appears for Dead or Alive 3.
