### ISSUE TITLE
CI Releases not Linked to Released Commit Correctly

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1903]
I am noticing some CI builds are not link to correct GitHub commit. The issue is from `actions/create-release`'s action. Our CI build's commit tag is accurate by the way. From the issue report in action's repository describe each release created is tag to whatever the head of the current branch it was built from. If later release is made, then new release is move before previous released for same, aka the `HEAD` of the branch, commit.

References of the issue:
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-2a23634
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-555f240
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-f3d7ae6
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-ca0b978

**Only workaround solution: Wait until each merged pull request is fully done building and created a release. Then repeat the step for next pull request merge.**

**Comment by GXTX** [comment]
Separate runner which only runs on pushes to master should fix this.

**Comment by GXTX** [comment]
*On push* should take the latest HEAD aka the one you're pushing to the branch. So even if you're merging multiple PRs in quick succession it should just buffer and run for say 2 or more times to create the builds.

I'm not sure I see the problem in this scenario.
