### ISSUE TITLE
Nothing happens when I press F5 in most games + Render Resolution not working

### ISSUE THREAD

**Issue by ENunn** [Cxbx-Reloaded/Cxbx-Reloaded#1907]
I'm not sure what happened but when I load an xbe and press F5 it'll go to a black screen for a few seconds and then crash. Crash being "going back to the CXBX screen". I'm able to get DoomX running but not any of my other games.

Another issue I have is where the render resolution is basically locked at 1x even though I have 4x selected. I have NTSC 480p selected in the EEPROM settings so I'm not sure what the deal is. I'm using the latest CXBXR.

Any help?

**Comment by gandalfthewhite19890404** [comment]
Addition (if it means something) - vga read/write operations after DEBUG INIT Calling XBE entry point does not happens (or fails and not logged).

**Comment by ENunn** [comment]
i guess that's basically what's happening, here's the console log
https://pastebin.com/u3jbCw9N

**Comment by ergo720** [comment]
This is not a support forum to ask for help, you should go on our Discord server for that instead.

**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
