### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by Bryaneitor69** [Cxbx-Reloaded/Cxbx-Reloaded#1909]
I start a game and it has no audio
I start marvel nemesis rise of the imperfects and nothing is heard

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
