### ISSUE TITLE
Cxbx Reloaded does not start.

### ISSUE THREAD

**Issue by AlanRibas** [Cxbx-Reloaded/Cxbx-Reloaded#1910]
I tried to run the emulator in the last few days and it just won't open after I try to run the "cxbx.exe" file. I double-click but nothing happens.
I downloaded the latest versions. of both files below:
CxbxReloaded-Release-VS2019
CxbxReloaded-Release-VS2017

But nothing has changed. And I have no idea what it might be. I thought it might be anti-virus in some way. But I checked that and there is no record of the cxbx reloaded on it.

I downloaded and installed the "32-bit (x86) Visual C ++ 2019 Redistributable" program.

It is a very strange thing. Until yesterday it was working. I tried to open it the other day and found that.

Can anyone tell me what's going on?

my computer configuration:
Windows 10 (updated)
motherboard: Drives Z170N Gaming 5
video card: GeForce GTX970
ram memory: 16 GB.
Processor: Intel core i5 6600

<img width="960" alt="cxbx" src="https://user-images.githubusercontent.com/16063712/82696164-dabcd280-9c3c-11ea-9002-527c011dd7e5.png">

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
