### ISSUE TITLE
Cxbxr GPU 100%

### ISSUE THREAD

**Issue by dante3732** [Cxbx-Reloaded/Cxbx-Reloaded#1912]
Emulator use gpu on 100% .
https://steamuserimages-a.akamaihd.net/ugc/1037463386295679118/31E10D9AE25B043E8A864FD1D896D807923D3406/

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.

**Comment by ergo720** [comment]
I deleted the posted image because, translating with Google Translate the linked page, shows that it talks about how to download games, which we don't allow here.
