### ISSUE TITLE
Fsp drops

### ISSUE THREAD

**Issue by Bloonkq8** [Cxbx-Reloaded/Cxbx-Reloaded#1920]
So i am trying to run this game (buffy the vampire slayer) which apparently is supposed to run well on cxbx emulator.. Everything goes well up until the game actually starts and then the fsp drops to 2. Is there a way to prevent that from happening?

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
