### ISSUE TITLE
avira is detecting cxbxr-ldr.exe as malware

### ISSUE THREAD

**Issue by firebird5555** [Cxbx-Reloaded/Cxbx-Reloaded#1924]
sorry if this is the wrong place to post this but for a month now avira has been detecting this file as malware. I dont remove it or move it to quarantine cause i know its a false positive just wanted to let the devs know 

![Capture](https://user-images.githubusercontent.com/2887522/85220162-5d899800-b377-11ea-9139-c758944903a5.PNG)

**Comment by ergo720** [comment]
Yes, we are aware of this, but other than adding an exception for the file in Avira there's nothing we can do about it.
