### ISSUE TITLE
CXBXR Not Opening

### ISSUE THREAD

**Issue by AntifyTTV** [Cxbx-Reloaded/Cxbx-Reloaded#1926]
I was having issues with CXBXR and had to end it with the task manager. After doing that, the emulator now refuses to open. I've cleared system cache and even reinstalled the emulator (deleting the old files) and it still will not open. Can someone help me with this please?

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
