### ISSUE TITLE
Cxbx-R is broken under Wine since the introduction of the loader

### ISSUE THREAD

**Issue by barolo** [Cxbx-Reloaded/Cxbx-Reloaded#1937]
## Quick summary

Emulation of any game doesn't start.

## Details

GUI launches fine, configuration too, after pressing start emulation nothing happens or memory related error pops out:

![image0](https://user-images.githubusercontent.com/1215421/90330560-f1f62c80-dfad-11ea-9b4f-f851d8002e25.jpg)

Switching to the mode without the loader doesn't help.
Games are ripped properly, they work fine under Windows.

I seems that the bug was introduced during the transition to loader and the commit:
```
52f0d6f03b38c79cbffeb92de43968ae402a3fe0
Author: ergo720 <45463469+ergo720@users.noreply.github.com>
Date:   Fri Jul 12 16:00:52 2019 +0200
```

### System Configuration:

Linux 5.8.0
AMD RAVEN APU 2400G
Wine versions: any, up to 5.14

**Comment by PatrickvL** [comment]
The "failed to reserve required memory ranges" popup message indicates that the available virtual memory ranges under wine don't correspond to those under windows. So there's a fair chance the problem lies with wine

**Comment by PatrickvL** [comment]
About a year ago, we had a similar problem with wine, that didn't allow loading executables at the lowest possible address (0x0001 0000), which was fixed specifically for our use-case.

**Comment by PatrickvL** [comment]
First thing we need to establish, is which virtual memory address range(s) cannot be reserved. Perhaps we can work around that one(s). And if not, maybe we can file another report in the wine issue list...

**Comment by ergo720** [comment]
The wine hack was related to the tiled memory region, so adding this code `(Start == TILED_MEMORY_BASE) ? MiB(64) : Size` at https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/71dc7e988ee9861f2d1c30ef8e968e7dd88e25d7/src/common/ReserveAddressRanges.cpp#L104 should fix it. Reserving 128 MiB for the tiled region on 128 MiB systems is actually not needed in the first place so we can avoid detecting wine at this point. Also, the tiled region does not have the MAY_FAIL flag and so it will lead to that error if it fails reservation.

**Comment by ergo720** [comment]
Actually, the above might not be the problem since line https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/e6b2ed88af52207e3df544b692ee7acb2ef521f3/src/common/AddressRanges.cpp#L58 shows that the tiled region is already using a 64 MiB size, so it's probably something else.

**Comment by barolo** [comment]
It's hard to debug as kernel debugging either to file or console doesn't seems to work, or to file works once in a thousand tries

**Comment by PatrickvL** [comment]
It might be possible to add details on all failed memory range reservations to the popup message, so that we can start investigating those specific ranges

**Comment by RadWolfie** [comment]
For loader process, it will some work in order to do that. As for non-loader, should be easy to do than loader method.

However, non-loader shouldn't fail since it does already reserved 64MiB space in the placeholder variable from the executable itself. The issue might be elsewhere.

---

To be clear what I had experienced when I was testing with wine (5.6 dev) in VM during loader pull request to main branch.

- Half or most of the time produce "failed to reserve required memory ranges" message.
  - Then unable to restart emulation unless restart GUI.
-  Log to console does work except doesn't work to file.
  - After system and wine (5.14) updates, both console and file logs doesn't work.
- Loader method can lockup at 100%. I'm unable to determine the cause, since it occur within loader executable than emulator module.
  - (I had confirmed it by debug emulator entry point with a test popup message.)

**Comment by barolo** [comment]
As an enduser I care for it to run, no matter which way ;)

**Comment by barolo** [comment]
I've basically bisected it, checking how far up I could go with the builds until it's broken. After 2a23634c770241ef2f211bf4b49bea2eaca124d7 it breaks. Aprill 14 2020 one still works, even with newest wine.
So yeah, the loader.

**Comment by Loomeh** [comment]
When I use CXBX-R On Wine (Pop!_OS) and click 'Start' on the 'Emulation' tab nothing happens, not even a single error message, just nothing. I've tried builds from September 2020, August 2020 and July 2020 and none of those work either.

**Comment by barolo** [comment]
Erm, the comment right above you says athat you can't go beyond April 14, so it's not surprise that yours aren't working @Loomeh

**Comment by RadWolfie** [comment]
**UPDATE: After some discussion from the group and attempt to try something different.
Here's the result:**

@ergo720 was able to determine which address range did not allocate whole range. An attempt to try comment `FLASH_DEVICE4_BASE` out did not work. The next thing I did is comment out `FLASH_DEVICE3_BASE` which no longer cause loophole issue with loader method.

Further suggestion is to add `MAY_FAIL` flag to `FLASH_DEVICE3_BASE` range. I do not get any loophole from loader and is able to enter emulator's entry point. So... there is an issue from cxbxr-ldr's codebase for the loophole.

P.S. double click cxbxr-ldr.exe directly does output to console window with a popup message dialog for incorrect usage.
