### ISSUE TITLE
THPS2X ghosting issue, bad graphical artifacting when filling special.

### ISSUE THREAD

**Issue by cleggorz** [Cxbx-Reloaded/Cxbx-Reloaded#1939]
### System Configuration:

*windows 10 pro
* Intel i7 9700k
* Radeon 5700xt
* etc.

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
