### ISSUE TITLE
Turok freeze on second level load (second load screen)

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#194]
Turok: Evolution now freezes upon loading the second level, but a few builds back it worked. Now when you go to the second level it just freezes. EDIT:This is while loading a autosave from the start of the game, but even but starting a new game it still freezes. (like this)
![freeze](https://cloud.githubusercontent.com/assets/17304943/23343149/adf50da4-fc1b-11e6-9bef-b4a225d447d8.PNG)
But in the older build, it goes on and loads the next level/next part of the level
![nonfreeze](https://cloud.githubusercontent.com/assets/17304943/23343179/1782e714-fc1c-11e6-8c03-367b8f1758f2.PNG)
Just to show when in the game I'm talking about and what it's supposed to do:
https://youtu.be/hU1L2p7hzKY?t=180
The build from that video also isn't the latest for that day. It was recorded hours before a new update.
**xbe info dump:**
> XBE information generated by Cxbx-Reloaded (Version -Trace (Feb 21 2017))
> 
> Title identified as "Turok Evolution"
> 
> Dumping XBE file header...
> 
> Magic Number                     : XBEH
> Digitial Signature               : <Hex Dump>
>                                    AE9751DA74E01600E72D99744ABCD04E
>                                    B9D901B768F50D33D54DA3427D5B0185
>                                    D8372A01F374D3B5421C438A9513D1B0
>                                    281296543E2F703641231C72C40D0FF1
>                                    B101B1169DB77AB4D9DFF06E18C5163D
>                                    A90576A7EFDC9BA9622BDC1FDE607C0C
>                                    278058FA111E55BB23703D5B353577E8
>                                    0079BA002BCC9DDDBFE1E657EBDFE346
>                                    B7E208BD6E355541B6A22D9547DB2EB3
>                                    C3F4178D211CC08B24E0204883793A13
>                                    85B8E7D220FECC9B9E554479309E8834
>                                    F69F8B3EF4A54426C3A73B2B85BE7A97
>                                    8F64D51C58829792A722734E60DFC280
>                                    186684F5262F78BD9D3E119FC8D50F16
>                                    14E11C16094CF07E95E184D7012541F2
>                                    F501ED0AE0F88F50C1CA2739F05D3902
>                                    </Hex Dump>
> Base Address                     : 0x00010000
> Size of Headers                  : 0x000009A0
> Size of Image                    : 0x00252380
> Size of Image Header             : 0x00000178
> TimeDate Stamp                   : 0x3D5421FC (Fri Aug  9 13:11:40 2002)
> Certificate Address              : 0x00010178
> Number of Sections               : 0x0000000B
> Section Headers Address          : 0x00010354
> Init Flags                       : 0x00000001 [Mount Utility Drive] [Format Utility Drive] [Limit Devkit Run Time Memory to 64MB] [Setup Harddisk] 
> Entry Point                      : 0x94848D24 (Retail: 0x3C78DA8F, Debug: 0x0001106F)
> TLS Address                      : 0x001FA8DC
> (PE) Stack Commit                : 0x00010000
> (PE) Heap Reserve                : 0x00100000
> (PE) Heap Commit                 : 0x00001000
> (PE) Base Address                : 0x00010BE0
> (PE) Size of Image               : 0x002702E0
> (PE) Checksum                    : 0x00000000
> (PE) TimeDate Stamp              : 0x3D5421FB (Fri Aug  9 13:11:39 2002)
> Debug Pathname Address           : 0x000106B6 ("C:\Projects\NewTech\Turok4\RXBOXDEV\Game_ForXBOX.exe")
> Debug Filename Address           : 0x000106DA ("Game_ForXBOX.exe")
> Debug Unicode filename Address   : 0x00010694 (L"Game_ForXBOX.exe")
> Kernel Image Thunk Address       : 0xEFAE5252 (Retail: 0xB4C312E4, Debug: 0x001FA300)
> NonKernel Import Dir Address     : 0x00000000
> Library Versions                 : 0x00000008
> Library Versions Address         : 0x00010614
> Kernel Library Version Address   : 0x00010624
> XAPI Library Version Address     : 0x00010614
> Logo Bitmap Address              : 0x000106EC
> Logo Bitmap Size                 : 0x000002B2
> 
> Dumping XBE Certificate...
> 
> Size of Certificate              : 0x000001DC
> TimeDate Stamp                   : 0x3D5AB621 (Wed Aug 14 12:57:21 2002)
> Title ID                         : 0x41430004
> Title                            : L"Turok Evolution"
> Alternate Titles IDs             : 0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
>                                    0x00000000
> Allowed Media                    : 0x00FFFFFF
> Game Region                      : 0x00000001
> Game Ratings                     : 0x00000002
> Disk Number                      : 0x00000000
> Version                          : 0x00000001
> LAN Key                          : 55E48566C13A52818A7A785E687182A9
> Signature Key                    : 9A3E0FFAFE44F22614121B13778AFEF7
> Title Alternate Signature Keys : <Hex Dump>
>                                    32606C5858425E5854F3709F5BE53C1F
>                                    2A98F0B06FC10CDE72A7D76F884593CD
>                                    91E7B8E0ABD12C728BC914B37F2A535E
>                                    FE488225CBDBF2EE28D85EDCF777F717
>                                    105724E4DFD9DE58BB534DA4EB972D99
>                                    D2A0970EFDBA7A5C23A6BBA62B1C6883
>                                    0CCB418566B7E4E3BD1674E17B8C29E5
>                                    8D1BB47F5973AC476F711571D983F433
>                                    ACAF89B5221438701BC77FD13E1231CF
>                                    3D890373CE48FEFA9BDAB2C83F506B85
>                                    EFE0993A4FE571B758776EC2D8ADEA96
>                                    B423D187A413D4D2A5A67E2BEDF126EE
>                                    20E86E1D51740373B427E7D90CAE8503
>                                    711E608F483890D569EE3EA3CF93B142
>                                    A206A5E1A31E334C9E71E9026BA2E90E
>                                    B137B514E895B5F85E9685BBCC1732EC
>                                    </Hex Dump>
> 
> Dumping XBE Section Headers...
> 
> Section Name                     : 0x000105D2 (".text")
> Flags                            : 0x00000000 (Preload) (Executable) (Head Page RO) 
> Virtual Address                  : 0x00011000
> Virtual Size                     : 0x00181470
> Raw Address                      : 0x00001000
> Size of Raw                      : 0x00181470
> Section Name Address             : 0x000105D2
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105BC
> Tail Shared Reference Count Addr : 0x000105BE
> Section Digest                   : C608DA7CEFA37168B63601B180673216200FAD4F
> 
> Section Name                     : 0x000105D8 ("D3D")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x00192480
> Virtual Size                     : 0x00012C9C
> Raw Address                      : 0x00183000
> Size of Raw                      : 0x0000F630
> Section Name Address             : 0x000105D8
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105BE
> Tail Shared Reference Count Addr : 0x000105C0
> Section Digest                   : B70AD383085C7D7271FE2F31A260C9BB8CC834F3
> 
> Section Name                     : 0x000105DC ("D3DX")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x001A5120
> Virtual Size                     : 0x00000540
> Raw Address                      : 0x00193000
> Size of Raw                      : 0x00000540
> Section Name Address             : 0x000105DC
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C0
> Tail Shared Reference Count Addr : 0x000105C0
> Section Digest                   : 3B84E9B1FC5E7828399A6B129E76DC1ECA7214B0
> 
> Section Name                     : 0x000105E1 ("XGRPH")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x001A5660
> Virtual Size                     : 0x00008EB0
> Raw Address                      : 0x00194000
> Size of Raw                      : 0x00008238
> Section Name Address             : 0x000105E1
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C0
> Tail Shared Reference Count Addr : 0x000105C2
> Section Digest                   : 17F97EAF9A568D7E277986FDB4B37A6567C203F9
> 
> Section Name                     : 0x000105E7 ("DSOUND")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x001AE520
> Virtual Size                     : 0x0001D9BC
> Raw Address                      : 0x0019D000
> Size of Raw                      : 0x0001D774
> Section Name Address             : 0x000105E7
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C2
> Tail Shared Reference Count Addr : 0x000105C4
> Section Digest                   : F635FBA657B5736C471E06CD449B2DD9D7C2D5B1
> 
> Section Name                     : 0x000105EE ("XMV")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x001CBEE0
> Virtual Size                     : 0x000272B4
> Raw Address                      : 0x001BB000
> Size of Raw                      : 0x000272A4
> Section Name Address             : 0x000105EE
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C4
> Tail Shared Reference Count Addr : 0x000105C6
> Section Digest                   : CCBEBE09A03E0B068855B77410DA73DF6D494F7C
> 
> Section Name                     : 0x000105F2 ("XPP")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x001F31A0
> Virtual Size                     : 0x00007144
> Raw Address                      : 0x001E3000
> Size of Raw                      : 0x00007144
> Section Name Address             : 0x000105F2
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C6
> Tail Shared Reference Count Addr : 0x000105C8
> Section Digest                   : 12F4D54DDA94F4A22538C5ABF549DC53E02660AB
> 
> Section Name                     : 0x000105F6 (".rdata")
> Flags                            : 0x00000000 (Preload) (Executable) 
> Virtual Address                  : 0x001FA300
> Virtual Size                     : 0x0003C34C
> Raw Address                      : 0x001EB000
> Size of Raw                      : 0x0003C33C
> Section Name Address             : 0x000105F6
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105C8
> Tail Shared Reference Count Addr : 0x000105CA
> Section Digest                   : 2DBABC42361E44E49521B9E3B619BCF315D62D43
> 
> Section Name                     : 0x000105FD (".data")
> Flags                            : 0x00000001 (Writable) (Preload) (Executable) 
> Virtual Address                  : 0x00236660
> Virtual Size                     : 0x00022394
> Raw Address                      : 0x00228000
> Size of Raw                      : 0x00018438
> Section Name Address             : 0x000105FD
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105CA
> Tail Shared Reference Count Addr : 0x000105CC
> Section Digest                   : C79CB018B20179BE1C76C78B801C2A82657C2507
> 
> Section Name                     : 0x00010603 ("DOLBY")
> Flags                            : 0x00000000 (Preload) (Executable) (Tail Page RO) 
> Virtual Address                  : 0x00258A00
> Virtual Size                     : 0x00007180
> Raw Address                      : 0x00241000
> Size of Raw                      : 0x0000716C
> Section Name Address             : 0x00010603
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105CC
> Tail Shared Reference Count Addr : 0x000105CE
> Section Digest                   : C8C9142DCCBD31BDCA9A2D94E0ACC47C2048D615
> 
> Section Name                     : 0x00010609 ("$$XTIMAG")
> Flags                            : 0x00000000 (Inserted File) (Head Page RO) (Tail Page RO) 
> Virtual Address                  : 0x0025FB80
> Virtual Size                     : 0x00002800
> Raw Address                      : 0x00249000
> Size of Raw                      : 0x00002800
> Section Name Address             : 0x00010609
> Section Reference Count          : 0x00000000
> Head Shared Reference Count Addr : 0x000105CE
> Tail Shared Reference Count Addr : 0x000105D0
> Section Digest                   : BC358C3909F8063FEDC3F09F7427C704583A6007
> 
> Dumping XBE Library Versions...
> 
> Library Name                     : XAPILIB
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : XBOXKRNL
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : LIBCMT
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : D3D8
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : D3DX8
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : XGRAPHC
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : DSOUND
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Library Name                     : XMV
> Version                          : 1.0.4627
> Flags                            : QFEVersion : 0x0001, Retail, Approved
> 
> Dumping XBE TLS...
> 
> Data Start Address               : 0x00000000
> Data End Address                 : 0x00000000
> TLS Index Address                : 0x0024EAA0
> TLS Callback Address             : 0x00000000
> Size of Zero Fill                : 0x0000000C
> Characteristics                  : 0x00000000
>

**Comment by BenNottelling** [comment]
Now the game runs too fast so I can't manage to get past the first bit :D I'll get there some day

**Comment by LukeUsher** [comment]
Turn on VSYNC in the video settings, that will limit the games frame rate. On the Xbox some titles rely on VSYNC for timing, Turok seems to be one of them.

**Comment by BenNottelling** [comment]
@LukeUsher I have VSYNC on, it locks to 60FPS, but the speed is way too fast. (i'd say twice to three times)

**Comment by DisorderIy** [comment]
@BenNottelling Could that be because the game doesn't run at a consistent 60FPS on real hardware? With Burnout, which runs at 60FPS at all times, the game plays at exactly the right speed with V-Sync on. With V-Sync off, it plays **as fast as it possibly can.**

**Comment by BenNottelling** [comment]
@DisorderIy I'm sure that's exactly what it is, I tried locking it to 30fps with the AMD settings pane, but it didn't lock the fps. Do you know how I could lock it to 30fps? Also just a thought, but perhaps choosing between 30 and 60 fps VSYNC would be a good option to add?

**Comment by BenNottelling** [comment]
Retested and it now makes it past the load screen, can other people test (I am using the JIT LLE)

**Comment by PatrickvL** [comment]
Actually, JIT LLE shouldn't matter, as it isn't implemented yet

**Comment by BenNottelling** [comment]
Passed second load screen for me (no LLEs)

**Comment by ObiKKa** [comment]
I tested Turok (US version) on the last build two days ago before the newest PR with libyuv video & pitch fixes that was pulled in just now. And I see that vertex shading or the whole in-game graphics look absolutely rock-solid or at least I think so. No black textures. Tested on Nvidia GeForce GTX 750 Ti (Not recently updated driver).
My test of Futurama (US version) cannot be helped as like some others an exception code error message stopped it going past the first intro screen.

![2017-04-16_1st-test](https://cloud.githubusercontent.com/assets/18428108/25069464/b7ecb0a8-22c4-11e7-972c-79099f0affd4.png)

**Comment by PatrickvL** [comment]
It seems you're lucky then, as other tests do show render bugs. The latest report on Frogger is a good example. Anyway, thanks for reporting this, we love getting good news and nice screenshots!

**Comment by BenNottelling** [comment]
Turok is being emulated much better, i test it on most every build, the only issue is with being underwater and the HUD. I also experience some vertexes not being rendered on my RX480 so it would seem the emulator favors Nvidia GPUs

**Comment by BenNottelling** [comment]
This stone always seems to render wrong.
![ytsettings](https://cloud.githubusercontent.com/assets/17304943/25072932/a960f286-228f-11e7-8c42-1af4bafd50e2.PNG)

**Comment by blueshogun96** [comment]
... that's been that way since Cxbx first started running Turok.

Shogun

**Comment by blueshogun96** [comment]
I've given up on that rock, lol

**Comment by ObiKKa** [comment]
I may re-use this issue page if that's OK. But I seem to have a similar problem as Battlestar Galactica. On the first one or two go the game didn't show the movie video except for the splash screen and Acclaim intro. But after getting to the menu and ingame I restarted the game again but was never able to enter the menu again, like in BG.
I think this seems to be a caching problem introduced by the new PR #384 (Implement HLE cache).

Below is the corrupted video (which seemed to run indefinitely) after the previous time when I was able to reach the menu):
![2017-apr-21 _caching-problem_can t-enter-menu- -game](https://cloud.githubusercontent.com/assets/18428108/25255077/54216428-266c-11e7-9d5c-28995970a752.png)

**Comment by PatrickvL** [comment]
It's okay - I appreciate the effort. Most regressions are probably due to the HLE cache, but overlay changes have given me headaches too. One thing I did notice: overlays work much better in debug builds then in release builds - I don't​ know why...

**Comment by ObiKKa** [comment]
Oh, hell, yes. I was finally able to get in-game in this game! I don't know which PR may have enabled that but I got the latest master with PR #450 (Pushbuffer related improvements).

**Comment by BenNottelling** [comment]
It would seem that this has happened again.. 
![capture](https://user-images.githubusercontent.com/17304943/28750006-380a8bee-7490-11e7-9e59-e436c1a662ce.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#186
