### ISSUE TITLE
YSE - possible HLE audio plugin

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1980]
## Quick summary
LibYSE, audio engine, could be another possible option to use for HLE.

## Details
LibYSE could be another option to use as audio engine for HLE.
For complete details go to http://attr-x.net/yse/ for features list.
One of them do have advanced DSP. Which in theory should allow us to read xbox's DSP object. Of course we would need to make a custom DSP reader in order to do that.

### System Configuration:
N/A

### Additional Information (if any):
Repo link: https://github.com/yvanvds/yse-soundengine

**Comment by medievil1** [comment]
yea mine got closed, didn't realize the bot would close it that easy

**Comment by RadWolfie** [comment]
I realize YSE is licensed under EPL 1.0. According to license compatibility with GPL-2.0 or later... It is not compatible.

References:
 - https://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE
 - https://www.fsf.org/blogs/licensing/eclipse-public-license-version-2-0-added-to-license-list-1

In summary, we cannot use YSE.
