### ISSUE TITLE
Rtl string initialization potentially wrong

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/Cxbx-Reloaded#2006]
## Quick summary

The implementations of `RtlInitAnsiString` and `RtlInitUnicodeString` both incorrectly do not make a copy of their source strings.

## Details

The string objects `ANSI_STRING` and `UNICODE_STRING` are setup using the source string pointer as their buffer:

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/9a773ef7ac61f05632a7471433e31998ffd8ed1b/src/core/kernel/exports/EmuKrnlRtl.cpp#L1077-L1081

This is incorrect, as

1. The lifetime of these string objects are tightly coupled to the source string (this is an issue whenever the string objects and source buffers are used outside of the same scope)
2. The buffers of these string objects are expected to be freed in `RtlFreeAnsiString` and `RtlFreeUnicodeString` - but the source strings can be allocated on the stack

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/9a773ef7ac61f05632a7471433e31998ffd8ed1b/src/core/kernel/exports/EmuKrnlRtl.cpp#L1016-L1027

This could be throwing failures from *PoolManager::DeallocatePool*

### System Configuration:

N/A

### Additional Information (if any):

Found by accident

**Comment by PatrickvL** [comment]
These implementations are functionally identical to what a disassembled xbox kernel does, so the above assumption (that source can reside on stack) is likely a misunderstanding.

Closing.
