### ISSUE TITLE
[regression] Auto Modellista

### ISSUE THREAD

**Issue by jenci8888** [Cxbx-Reloaded/Cxbx-Reloaded#2009]
## Quick summary
Unable to load "intro state" and crashes on Auto Modellista

## Details
The #1913 has problem only loadable state because it crashes. Previously PR (1934) is still playable state.

### System Configuration:
* OS: Windows 10 Enterprise 64-bit
* CPU: Intel i5-4690k @ 4.4ghz
* GPU: Nvidia GTX 1050Ti 

### Additional Information (if any):
Log: 
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/5435878/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/5435880/KrnlDebug.txt)

Before: (Aug 15th)
![image](https://user-images.githubusercontent.com/40495799/97117422-f6546980-1703-11eb-82db-35c418501adb.png)
After: (Aug 18th)
![image](https://user-images.githubusercontent.com/40495799/97117428-fbb1b400-1703-11eb-99b5-7529575cc597.png)

**Comment by RadWolfie** [comment]
Any regressions should be report in both pull request and Game Compatibility repository (if pull request was merged).
