### ISSUE TITLE
Magic the Gathering Battlegrounds (NTSC)

### ISSUE THREAD

**Issue by TH3GOD88** [Cxbx-Reloaded/Cxbx-Reloaded#2027]
## Quick summary

When trying to run Magic the Gathering Battlegrounds, it throws an error.

## Details

Received Exception Code 0xC0000005 @ EIP:=
0x0007C825(D3DCubeTexture_GetCubeMapSurface+0x56e85

### System Configuration:

* OS
* CPU
* GPU
* etc.
OS= Windows 10
CPU= AMD Ryzen 7 2700x
GPU= Nvidia Geforce GTX 1060 6GB

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or to ask for support . You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
