### ISSUE TITLE
Black screen when starting

### ISSUE THREAD

**Issue by Ryantowolf** [Cxbx-Reloaded/Cxbx-Reloaded#2066]
## Quick summary

Black screen when starting a game

## Details

When I start the emulator, there is a black screen and there is no fps rendering. The game is working per the compatibility list. any ways to fix? 

### System Configuration:

Intel core i3, CPU @ 1.2 GHz, 1190 Mhz

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
