### ISSUE TITLE
Failed compile 

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#209]
Every time I compile the application VIA VS 2015, no errors, but every time glew32.dll isn't compiled. I've tried resetting it and still, no glew32.dll, I can even copy it over and it then works perfectly. Am I compiling it wrong?

**Comment by PatrickvL** [comment]
I think this is fall-out from the merger of the DLL into the executable, since build events were accidentally lost, this could be another

**Comment by LukeUsher** [comment]
Fixed as of b446d21
