### ISSUE TITLE
Super MonkeyBall Delux

### ISSUE THREAD

**Issue by johnshadow** [Cxbx-Reloaded/Cxbx-Reloaded#21]
It makes a whole bunch of stuff then stops. Blank screen. I have an Iso for testing if needed. Most emulators seam to have trouble emulating this game...

**Comment by PatrickvL** [comment]
> **Bug Reports**
> 
> Cxbx-Reloaded is in the early stages right now and most games will either crash or do nothing, please do not submit issues for these games.
> 
> I want to know what games actually do something, so if a game displays graphics before crashing, please submit a bug reports containing the error message displayed (if any), screenshots and an Xbe dump (This can be created via [Edit -> Dump Xbe Info To -> File]).

**Comment by johnshadow** [comment]
I never said it didn't do anything? I get a black screen after a file dump Its "working", when it isn't. Also thanks for noticing this issue. I really would like some one to work on this game, or use if for testing most emulator (again) have trouble with this game, because of it using a newer format of directx I guess? Any way I could send you the dump file (its literally thousands of lines long.) and even the ROM. Please ask if you would like to take a look. So far I really like the emulator keep it up! 
~Scenically John

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#193
