### ISSUE TITLE
Issue: Some sounds don't work on certain games

### ISSUE THREAD

**Issue by RiskiVR** [Cxbx-Reloaded/Cxbx-Reloaded#2111]
## Quick summary

I'm emulating Mortal Kombat Armageddon, and for some reason some audio doesn't want to work (mostly music and dialogue) when playing the game.

## Details

Most sound effects work fine, but most music and dialogue isn't working. I even tried setting compatibility to Windows 7.

### System Configuration:

OS: Windows 10
CPU: Intel i5 9300H @2.40GHz
GPU: NVIDIA GTX 1650
Machine: Acer Nitro 5 Laptop

### Additional Information (if any):

None.

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

**Comment by RiskiVR** [comment]
This wasn't about game compatibility. I want to know why some sounds are not working, if it has to do with drivers or specific settings.

**Comment by ergo720** [comment]
Probably because sound emulation is simply broken for this particular game, it's not something you can fix by changing drivers or settings.
