### ISSUE TITLE
Import save games # part 2 (asking for keys.bin)

### ISSUE THREAD

**Issue by ElektroStudios** [Cxbx-Reloaded/Cxbx-Reloaded#2113]
## Quick summary
6 months ago I published this question: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1950

## Details
Since then, i still struggling my head trying to "import" (copy/paste) any save game downloaded from gamefaqs.com by pasting the save game files (TDATA / UDATA) in the corresponding 'partition1' directory of my Cxbx installation. However when I try to load any of those downloaded save games in Cxbx, the game (all of the games that I tried) says the save game is damaged/corrupted.

From what developers and other people said (references on the linked issue above) it seems the "keys.bin" file is all what I need in order to be able load those save games in my Cxbx...

I searched every corner of the world wide web for the "keys.bin" with no luck. I also searched inside the known source-code leak from Xbox to find it with no luck neither.

Just... please... any hint about how to load the save games will be very appreciated... how/where to obtain the keys.bin or how could I build the file... I don't have a physical Xbox console...

I'm not sue if I can publish my e-mail address but... please...
**if you have the keys.bin consider to send it anonymously to: CSG1986@hotmail.com**
( I have no intention of sharing or hosting that file publicly with anyone )

I'm like 6 months searching for it... not every day but weekly and monthly I try to investigate on Internet with no luck...

I tried to search for download links of the keys.bin, and investigated general information about Xbox system and HDD, and also I searched a lot for the Xbox signature key (which I still didn't found) to try build the required bytes of the keys.bin file by myself (although I don't know if I could do that, because neither I don't know how to obtain the missing Xbox LAN key...), I visited a lot of modding scene forums and asked for the keys.bin with literally no response from anyone.

I just need the keys.bin file to load save games, my intentions are not bad...

I'm really sorry if I inflict any rules, I'm desperate, I've been building a personal collection of Xbox ISOs for over a year (most of the physical games I had) and I really need to be able to import / load these save games to say that my collection is complete ... I don't know how many months and years could pass if none of you help me get that damn keys.bin

Thanks in advance.

### System Configuration:

Windows 10

**Comment by Masamune3210** [comment]
Unfortunately, the only way to get the keys to sign Xbox saves is from something that requires them. That means a OG Xbox, a 360, a XBONE, or a Series X. 

You might get lucky and someone send you the keys, but anyone who does is doing it on their own danger. It's the same issue with any keys involved in the scene.

**Comment by ElektroStudios** [comment]
> 
> 
> Unfortunately, the only way to get the keys to sign Xbox saves is from something that requires them. That means a OG Xbox, a 360, a XBONE, or a Series X.
> 
> You might get lucky and someone send you the keys, but anyone who does is doing it on their own danger. It's the same issue with any keys involved in the scene.

Thanks, but I don't understand at all... as it is supposed (as one dev commented in the  #part 1) that the Xbox signature key is the same for every Xbox console, then no one could "danger" (except the devs of this project for legal reasons) for sharing something that is NOT unique.

**Comment by Masamune3210** [comment]
It's dangerous for the same reasons that sharing any other key for the other consoles that implement encryption. Those are just a string as well, but quite literally anything is a string. The only reason that it's relatively easy to get the other consoles keys is they are either more commonly emulated or are extremely broken security wise. The og xbox has not been paid much attention to by the general populace emulation wise because until recently it wasn't stable enough for most people. The Wii is extremely popular to emulate and even some of its keys require some pretty deep internet digging to find. 

Comes down to this. It's not going to be posted here for obvious reasons. If someone wants to help you, they can go right ahead. But sharing of cryptographic materials tends to get on the bad side very quickly of companies. 

BTW, just because you can download something off the internet doesn't make it immediately legal. Literally the first few strings in the ps1 bios is a copyright notice

**Comment by PatrickvL** [comment]
Keys.bin contains the certificate and eeprom key. The certificate key is the same on every single Xbox and is used to sign save data. The eeprom key is the same for all 1.0 units. Then all 1.1-1.6 share a different eeprom key.

Also, search in our discord channels, there's more info to be found in there on both the contents and methods to retrieve your keys.bin

**Comment by nictse2013** [comment]
where put the file keys.bin?

**Comment by ElektroStudios** [comment]
> where put the file keys.bin?

In the main directory where the cxbx.exe file is.

**Comment by nictse2013** [comment]
> > where put the file keys.bin?
> 
> Put it in the main directory where the cxbx.exe file is:
> 
> ![image description](https://camo.githubusercontent.com/482e9f61cf4a1f96fae152564fe419d0cc5d6321067c051aca58952863cea8a5/68747470733a2f2f692e696d6775722e636f6d2f6b5866483159632e706e67)

I found my old og xb backup,it contain hddkey.bin,eeprom.bn,disk.bin,bios.bin. How use them to cxbx?
