### ISSUE TITLE
The debugger triggers both windows defender and virustotal.

### ISSUE THREAD

**Issue by OdelinT** [Cxbx-Reloaded/Cxbx-Reloaded#2143]
## Quick summary

The debugger triggers both windows defender because of "Trojan:Win32/Wacatac.D6!ml"

And is also considered as unsafe by Virustotal.

## Details

(I don't know how long this access will last)
https://www.virustotal.com/gui/file/2764fc3f9672734411226f03fde5e0a18f7aad918bd7a412f9df6b80f690744f/detection

![image](https://user-images.githubusercontent.com/32901446/108901323-08dfa080-761b-11eb-94ee-b97fe9edd7ce.png)

The details in english: This program is dangerous and executes commands from a malevolent person.

It have been so at least since 2021-02-12
And it is still the case with the current lastest release [CI-c36da13](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-c36da13)

### System Configuration:

* OS: Windows 10 20H2 19042.804
* CPU: i7-9750H
* GPU: GTX 1660 TI

**Comment by ergo720** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1963
