### ISSUE TITLE
Verify patch on XGetLaunchInfo can be removed

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#216]
The patch on XGetLaunchInfo  can be removed once we're sure all XAPI library functions indirectly reference our xboxkrnl::LaunchDataPage variable.
For this, we need a test-case that hits this function, and run that with and without this patch enabled. Behavior should be identical.
When this is verified, this patch can be removed.

A tip from @LukeUsher : https://github.com/grayj/Jedi-Academy/blob/master/code/win32/win_main_console.cpp calls XGetLaunchInfo

**Comment by LukeUsher** [comment]
Fixed in #221, the behavior of Innocent Tears and DOA is identical with and without this path
