### ISSUE TITLE
Several games crashing on boot after #2179

### ISSUE THREAD

**Issue by AphelionWasTaken** [Cxbx-Reloaded/Cxbx-Reloaded#2191]
## Quick summary

As the title says, several games are crashing on boot after #2179

## Details

Several games including Crash Tag Team Racing, Need For Speed Hot Pursuit 2, and Outrun 2 are crashing on boot on recent builds. These games initially regressed to crashing on boot after #2140, but they were fixed by #2171.

They begin crashing on boot again after #2179. I'm not sure how that would cause this issue, as it's a minor and seemingly unrelated change, but these games work fine on [CI-6d187f1](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-6d187f1) and are broken again on [CI-f3aaea3](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases/tag/CI-f3aaea3).

### System Configuration:

* OS - Windows 10
* CPU - 9900K
* GPU - RTX 3080

### Additional Information (if any):

N/A

**Comment by PatrickvL** [comment]
Just checking: do clear symbol cache and the contents of temporary Xbox partitions, just to make sure it's not related to lingering data...

**Comment by AphelionWasTaken** [comment]
Nice catch. Clearing the symbol cache solved the issue and these games boot fine for me on #2179 and after.

**Comment by PatrickvL** [comment]
That on itself is still an issue,  but glad that at least this helps
