### ISSUE TITLE
KeSuspendThread and KeResumeThread are not implemented

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#2216]
## Quick summary

The kernel resume/suspension functions need an implementation.

## Details

This becomes an issue if the title ever calls `PsCreateSystemThreadEx` to create a thread in the suspended state. In this case, the title will probably call `KeResumeThread` later to resume the suspended thread, but because we don't implement it, the xbox thread will never start. This will likely cause deadlocks, infinite waits or other issues.

### System Configuration:

N/A

### Additional Information (if any):

N/A

**Comment by PatrickvL** [comment]
We'll have to find a few test cases for this

**Comment by ergo720** [comment]
> We'll have to find a few test cases for this

Or we can just add a test for `PsCreateSystemThreadEx` to the xbox kernel test suite to trigger this case.

**Comment by ergo720** [comment]
I found a partial test case: Phantasy Star Online. The game spawns 6 threads: the first one is not created suspended, but the following five are instead. It then calls `NtResumeThread` and `NtSuspendThread` to repeatedly resume and suspend these threads, which apparently works fine since those calls are forwarded to their corresponding Ntdll functions. However, it still deadlock later when creating a new game save because the `IoCreateFile` forever fails to open the file "PSO_SYSTEM".

**Comment by ergo720** [comment]
> In this case, the title will probably call KeResumeThread later to resume the suspended thread,

Actually, the game is probably going to call `ResumeThread`, which is just a wrapper around `NtResumeThread`. This because `KeResumeThread` requires a kthread argument, which is an opaque kernel structure which I doubt games have access to, while `(Nt)ResumeThread` only require a thread handle. Since we already have https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/65 to track the kernel implementation, I'm going to close this.
