### ISSUE TITLE
A problem with Jet set Radio Future

### ISSUE THREAD

**Issue by HenryArat** [Cxbx-Reloaded/Cxbx-Reloaded#2229]
## Details
 I'm trying to play JSRF and the game enter normally, but the thing is nothing beside the character models looks black 

### System Configuration:
 Windows 10
AMD Ryzen 3 3200g
Radeon Veag 8
* OS
* CPU
* GPU
* etc.

**Comment by PatrickvL** [comment]
This is a know issue with AMD GPU drivers, that don't accept mixed shader versions. We're working on this in the hlsl_ps branch.

**Comment by HenryArat** [comment]
Ok, thank you
