### ISSUE TITLE
The black screen video regression in some games

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#225]
Xdescentv1.1 regression - 

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/23828811/fc1117b6-0720-11e7-8007-24cd23d4514b.png) 

And Xbe dump below
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/836272/Xbe.txt)

This problem ( regression) has appearead on the EmuCR-Cxbx-Reloaded-20170216, until that date the emulation has been normal 

And i have recorded fast proof of the progress on the build EmuCR-Cxbx-Reloaded-20170214 

https://www.youtube.com/watch?v=AFRoHGXRxLM&feature=youtu.be  
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/23828872/4702f8fa-0723-11e7-9fac-6f632d84a47b.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/23828871/47026b74-0723-11e7-92bd-c97f70c71c4b.png)

Same sort of the regression  i have  seen on the same similar games like Xhexenv1.1, Xhereticv1.1, Zelda-OniLinkBegins, Zelda-OniLinkBegins

I guess that some sort of commits on 16 febraury  broke this

**Comment by PatrickvL** [comment]
Thanks for reporting this. Any help is welcome!

**Comment by furrya** [comment]
Oh, I completely forgot to mention, the game has black screen but music and game emulation seems working < but black sreen

**Comment by PatrickvL** [comment]
I suspect this is related to https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/195 : black textures in Turok and Outrun 2.

**Comment by PatrickvL** [comment]
Looking at commits from 16 februari, this one stands out : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/105ee92d14d857b7083cf95af875a263ae1ef4de - it calls `Clear()` with a `Z` argument set to `0.0f`, while before it was `1.0f`, correcting this doesn't help however.

**Comment by LukeUsher** [comment]
So the original code there set Z to 1.0f if a Z-Buffer was present, and 0.0f if not where the newer code is using 0.0f regardless, we should restore that behavior at least.

**Comment by furrya** [comment]
With the latest commit #242 , I think  Z-Buffer fix-ups helped , Now Xdescent back to  the normal state and fully emulated 
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/24025197/68a01db2-0afc-11e7-9b9e-dd53e309c45d.png)

And it's affected also on the other titles like XBermuda, Divi-Dead, Zelda - Oni Link Begins and probably some
![screenshot_9](https://cloud.githubusercontent.com/assets/25540784/24026004/869d3aa2-0b01-11e7-9d37-028fe0223162.png)
 more
![screenshot_8](https://cloud.githubusercontent.com/assets/25540784/24025640/f8116cf6-0afe-11e7-8307-e7be59715c0c.png)
 and howewer some others now can reach and game and playable 
![screenshot_7](https://cloud.githubusercontent.com/assets/25540784/24025337/171037d8-0afd-11e7-8b71-5d98558f51e8.png)

**Comment by PatrickvL** [comment]
Thanks for the update. It's strange though, that there's no git hash visible in the title bar...

**Comment by furrya** [comment]
@PatrickvL Hm.. I don't know why.. But  git hash not visible for me, when I compile a build from source with Visual studio enterprise 2017..

**Comment by PatrickvL** [comment]
Could you please create a new issue for that?

**Comment by furrya** [comment]
@PatrickvL Yes,of course
