### ISSUE TITLE
Show short SHA git version number in caption bar to ease debugging

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#226]
Given more and more issues get a screenshot attached, showing the short SHA git version number in the caption bar would help ease debugging.

**Comment by LukeUsher** [comment]
We already do this in the main UI before a game is launched
Commit hash (or tag, if present)  and the build date are included in the Version string.

This is a very easy fix for whoever wants to do this, all changes need to be made within EmuD3D.cpp

First, the buffer needs extending to be able to fit a larger string. As the version string consists of a hash and a date string, it needs to be made significantly larger.

Line 323:
`char AsciiTitle[50];`
Should be changed to
`char AsciiTitle[MAX_PATH];`

MAX_PATH might be a little overkill size wise, but it's better than risking a crash if the version string becomes long.

Line 365:
`sprintf(AsciiTitle, "Cxbx-Reloaded : Emulating %s", tAsciiTitle);`
Should be changed to:  
`sprintf(AsciiTitle, "Cxbx-Reloaded %s : Emulating %s", _CXBX_VERSION, tAsciiTitle);`

**Comment by LukeUsher** [comment]
#232

**Comment by PatrickvL** [comment]
This turns out to be very useful; screenshots now indicate exactly what version is captured, making it easier to reproduce issues
