### ISSUE TITLE
Black screen in the rain levels in the crimson Skies

### ISSUE THREAD

**Issue by etanol-volatil** [Cxbx-Reloaded/Cxbx-Reloaded#2262]
## Quick summary

In the rain levels like Spider bot or Van Essen Assault Chicago, the game stay in the Black screen

## Details

When i'm Enter in the level, him stay in the black Screen, and only when pause the game, i can see something

https://user-images.githubusercontent.com/87213940/125849361-7749879c-6cb2-461d-9758-ef1f7f8fad1c.mp4

### System Configuration:

* OS - Edition	Windows 11 Pro
Version	21H2
Installed on	‎29/‎06/‎2021
OS build	22000.71
Experience	Windows Feature Experience Pack 421.18201.0.3

* CPU - Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz   3.50 GHz
* GPU - only Processor
* RAM - 8 GB Ram

### Additional Information (if any):

The same happens when i'm use the Plane Boost

**Comment by ergo720** [comment]
Pleas stop opening invalid issues. As the instructions in the template say: "Remember, the GitHub Issue Tracker is not the place to ask for support or to submit game compatibility https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md reports. You must use our forum on Discord https://discord.gg/26Xjx23 for that."
