### ISSUE TITLE
No visual indication of game loading, very long black screens, which could look like freezes..

### ISSUE THREAD

**Issue by ruthan** [Cxbx-Reloaded/Cxbx-Reloaded#2270]
Hello,
we need some progress indication in main windows, or in console.. because lots of game loading is very long, before Title screens and there is not any indication what is going on.. In console is nothing, only game title and emulation is started.

   Good example is xHexen2 - Hexen2 game port.

**Comment by PatrickvL** [comment]
Small reassurance : we (the devs) are aware and have been discussing ways to approach this - it's just that no-one picked this up yet

**Comment by PatrickvL** [comment]
Issue #2260 addresses the symbol scanning phase
