### ISSUE TITLE
Obscure regressed

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#229]
https://github.com/elfogames reported in issue #222 :

Tested on: a7ad492
Obscure Regressed,crash after the first Intro with Exception Code 0x0000005
Was able to reach menu and almost in-game(black screen with sound,not sure if is in-game) on a bit older build from Jan 19,2017 (92fa6d9)

**Comment by elfogames** [comment]
Tested On: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/0f1ee7746d335d3e781a9885a37723e56fa62c9a
Obscure regression is partially fixed,now its possible to get to menu again,but the controller doesn't work

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#200
