### ISSUE TITLE
Smashing Drive regression - nothing but black screen

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#230]
At one time, Smashing Drive was playable - see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/doc/ShogunChangelog.txt#L7
Later, this was broken - see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/doc/ShogunChangelog.txt#L219

Quotes from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/222 :

@elfogames
> uh.... smashing drive isn't working ...just a black screen with Exception Code 0x0000005

@LukeUsher 
> Smashing Drive is an interesting one, it seems to be dependant on what graphics hardware is used. On my laptop with duel graphics, it crashes when using either the Intel or AMD GPU, however on my desktop running on NVIDIA, it actually boots. It doesn't run properly and graphics is heavily corrupted but it boots.
>I have never actually had smashing drive playable in Cxbx myself, it was playable in one of blueshoguns versions way before 64-bit was fixed and way before I even started working on emulation

**Comment by furrya** [comment]
Smashing Drive Exception Code 0x0000005 after two splash screens  - 
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/23882136/6a14933e-08aa-11e7-8eb4-574eaada8f46.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/23882101/40e6c89c-08aa-11e7-979e-9c75ced37a2e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/23882102/4116a7c4-08aa-11e7-96b4-a4b4dc862110.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/23882103/412351d6-08aa-11e7-8d96-495f95645deb.png)

**Comment by LukeUsher** [comment]
Definitely an improvement, a good sign we are making progress

**Comment by elfogames** [comment]
just black screen for me
![sem titulo](https://cloud.githubusercontent.com/assets/16784631/23917954/e06b85b8-08cf-11e7-8994-b6d76a0b90f5.jpg)

**Comment by furrya** [comment]
With the Latest Commits Smashing Drive Goes In Game Now with the  broken sound
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24202599/d21b87f0-0f56-11e7-824d-f0edc0599649.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24202594/d08680a2-0f56-11e7-921f-4d96d367955c.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24202595/d0874078-0f56-11e7-87a0-b3d127f500df.png)

**Comment by LukeUsher** [comment]
Yes! Thanks @jarupxx

**Comment by elfogames** [comment]
doesn't work for me,i guess the game files are currupted
![sem titulo](https://cloud.githubusercontent.com/assets/16784631/24210616/6e891b6a-0f08-11e7-98e8-6a885004e894.jpg)

**Comment by PatrickvL** [comment]
All-white graphics also appeared in Dxbx when emulating this game. It might be related to a specific type of graphics card. Try software rendering...

**Comment by elfogames** [comment]
with software its just a black screen

**Comment by LukeUsher** [comment]
Software rendering almost never works, I've been tempted to remove it. (It just uses DirectX 8's internal software renderer, which is missing a lot of functionality)

The white graphics is most likely graphics card specific, things like this will improve as the emulator develops and we get away from using so many patches

**Comment by jagotu** [comment]
Just a black screen for me on f018efd5 and AMD Radeon HD 7700 Series with Windows 10.

**Comment by LukeUsher** [comment]
Same here on my laptop. I believe Smashing Drive requires an NVIDIA card. (My desktop has NVIDIA, but I barely use it, my laptop has duel Intel & AMD)

**Comment by elfogames** [comment]
i tested on Nvidia gt 750m and intel HD graphics 4400 and Windows 10,both have the same problem,so....

**Comment by ObiKKa** [comment]
How it should look in these recorded videos with the DXBX emulator from 6.5 years ago...

- Intro: https://www.youtube.com/watch?v=HYL53Qs6gcU
- Gameplay: https://www.youtube.com/watch?v=6fRk9TD71sA
- Intro and 3 levels: https://www.youtube.com/watch?v=6T5NXgdb0AU

**Comment by PatrickvL** [comment]
I'm not convinced that my old Dxbx videos of the game would qualify as a source of "how it should look" ;)

**Comment by blueshogun96** [comment]
Just confirming that I have the same issue on Intel HD 4000, and later on I can try the Quadro K1000.  I'll see what else I can look into once I get home.

Shogun.

**Comment by gandalfthewhite19890404** [comment]
Here is recent logs, made with this settings (if it is wrong - what i should use):
![image](https://user-images.githubusercontent.com/24764335/44249192-7bc06300-a1f7-11e8-8a82-49594bb7f3a8.png)
[SD_missing_graphics.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2296081/SD_missing_graphics.zip)
