### ISSUE TITLE
Build fails with VS2022

### ISSUE THREAD

**Issue by Margen67** [Cxbx-Reloaded/Cxbx-Reloaded#2300]
## Quick summary
Build fails with Visual Studio 2022.

## Details
```
distorm.lib(distorm.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(distorm.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
distorm.lib(decoder.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(decoder.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
distorm.lib(prefix.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(prefix.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
distorm.lib(instructions.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(instructions.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
distorm.lib(operands.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(operands.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
distorm.lib(insts.obj) : warning LNK4099: PDB 'distorm.pdb' was not found with 'distorm.lib(insts.obj)' or at 'D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\distorm.pdb'; linking object as if no debug info [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\projects\cxbxr-emu\cxbxr-emu.vcxproj]
  cxbxr-emu.vcxproj -> D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\bin\Release\cxbxr-emu.dll
Error: Process completed with exit code 1.
```

### System Configuration:
N/A

### Additional Information (if any):
https://github.com/Margen67/Cxbx-Reloaded/runs/4591541281?check_suite_focus=true#step:4:1091
https://github.com/Margen67/Cxbx-Reloaded/runs/4591541302?check_suite_focus=true#step:4:1095

**Comment by RadWolfie** [comment]
To clarify the issue at this time base on the log from additional information section's links:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\import\cs_x86\cs_x86\cs_x86.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\a\Cxbx-Reloaded\Cxbx-Reloaded\build\src\CxbxDebugger\cxbxr-debugger.csproj]
```

Please disregard warning message about `distorm.pdb` not being found. PDB file is not a requirement to compile and warning is a not a fatal error. On the side note, local installation of Visual Studio 2022 with .NET desktop development does work just fine out of the box.

**Comment by RadWolfie** [comment]
After some checking for what reason `error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found.` appear. It turns out Visual Studio 2022 no longer support v4.5 .NET framework, minimal support is v4.6 base on installer's list of .NET Framework support.
![image](https://user-images.githubusercontent.com/3938312/146893934-61932c7c-a3bf-4dbd-b70d-d0f4ca75c8c5.png)

With that said, somehow Visual Studio 2022 is able to detect previous Visual Studio's installed v4.5 framework which work fine locally.

**Comment by Margen67** [comment]
Upgrading to 4.5.2 (the minimum framework present on [`windows-2022`](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions)) fixes the error:
https://github.com/Margen67/Cxbx-Reloaded/runs/4600139781?check_suite_focus=true

**Comment by RadWolfie** [comment]
We're not going to follow base on github CI's availability for v4.5.x . Chances are we will move to v4.8 with less worry about need to re-update minor version of main version of .NET Framework. However, discussion is currently bare and haven't receive feeback from most team members at the moment.
