### ISSUE TITLE
No audio in MVP Baseball Series (03-07)

### ISSUE THREAD

**Issue by snarkypuppy1** [Cxbx-Reloaded/Cxbx-Reloaded#2307]
## Quick summary

Sound for games in MVP Baseball series is missing.

## Details

No sound loads at all when these games are played. Sound being added would make these games very close to perfect on here.
MVP Baseball 2003
MVP Baseball 2004
MVP Baseball 2005
MVP 06: NCAA Baseball

### System Configuration:

* OS Windows 10 Pro
* CPU AMD Ryzen 5800X
* GPU AMD Radeon 5600 XT

**Comment by ergo720** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**

Remember, the GitHub Issue Tracker is not the place to submit [Game Compatibility](https://cxbx-reloaded.co.uk/compatibility) reports or to ask for support . You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.

**Comment by PatrickvL** [comment]
Heh, it depends on how snarky interpreted this line from the FAQ : 
> For emulation issues that are not specific to any single piece of software, a bug report can be submitted at the Cxbx-Reloaded issue tracker.

... as the mentioned titles are not a "single piece of software", but rather a subset of titles 😜 

So, if more titles have no audio, and there's no existing ticket to track that issue with, then maybe it'd be acceptable to keep this one for that purpose?
