### ISSUE TITLE
WWE SmackDown vs. Raw 2009 / WWE Legends of WrestleMania - sys_mutex_destroy failed

### ISSUE THREAD

**Issue by JohnGodgames** [Cxbx-Reloaded/Cxbx-Reloaded#231]
Tested by https://github.com/RPCS3/rpcs3/commit/ed711c0e59abab4900f0ea2b30c084f4dacd8100

Both of these games have the same issue and hangs at the same point (after movies)

**WWE SmackDown vs. Raw 2009**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00a3d84c]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!uE0w1BzR!YW4WxX8esFR8lvo62QUHD9Qa7ayIkgvTRu6upaFk2IU)

**WWE Legends of WrestleMania**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00946ac4]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!zMUDmKKR!nd1wtBpkXw8U2W-jg9-1EBD0p8zmGubIgI1SzZ6Pc4A)

**Comment by LukeUsher** [comment]
Wrong emulator I believe, did you mean [rpcs3](https://github.com/RPCS3/rpcs3) ;)

**Comment by JohnGodgames** [comment]
hah sorry...next time

**Comment by PatrickvL** [comment]
This became https://github.com/RPCS3/rpcs3/issues/2526
