### ISSUE TITLE
Black doesnt work. Regression

### ISSUE THREAD

**Issue by UserGit-2021** [Cxbx-Reloaded/Cxbx-Reloaded#2317]
![изображение](https://user-images.githubusercontent.com/91757058/151580181-4809dcba-e41f-4e55-b617-cbe59fb9208a.png)
Build from  [Updated Ps kernel functions to use Ob handles + unpatch thread XAPI functions + added APC support to kernel via Ob #2315 ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/actions/runs/1759041703)

**Comment by ergo720** [comment]
This should have been reported on the PR instead of here. However, I notice it freezes in master as well, and it's only possible to boot it with the all cores hack turned on, which makes the report invalid anyway.
