### ISSUE TITLE
[Ingame crash] Bloody Roar Extreme NTSC-J got crash !

### ISSUE THREAD

**Issue by pftmclub** [Cxbx-Reloaded/Cxbx-Reloaded#2322]
## Quick summary

Bloody Roar Extreme got crash at CXBX-reloaded

## Details

Whenever i try to run Bloody Roar Extreme, it's keep crash when i access player select screen. See the screenshot below
![image](https://user-images.githubusercontent.com/19551146/154285593-19ce4dc1-1bd4-4e6f-abe4-3d01089e594a.png)

### System Configuration:

* OS : Windows 10 Pro 21H2
* CPU : Intel Core i5 3470 3.5Ghz
* GPU:  Nvidia Geforce GTX 750ti
* RAM: 8GB

### Additional Information (if any):

Game XBE Info !
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/8080631/Xbe.txt)
Cxbx version:
![image](https://user-images.githubusercontent.com/19551146/154286017-799d83f9-bd85-4258-bfbb-208103629217.png)

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://cxbx-reloaded.co.uk/compatibility) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
