### ISSUE TITLE
Virtua Cop 3: Heat wave effect doesn't clear properly

### ISSUE THREAD

**Issue by legend800** [Cxbx-Reloaded/Cxbx-Reloaded#2333]
## Quick summary

![2022-03-14_22_59_49-xemu___v0 6 2-80-g5d02cdf512](https://user-images.githubusercontent.com/20983844/159197280-bca29ba5-28ce-4168-a33c-feb71300bfc4.png)

**Comment by PatrickvL** [comment]
This issue list is for CxbxReloaded, not xemu

**Comment by PatrickvL** [comment]
https://github.com/mborgerson/xemu/issues/815

**Comment by legend800** [comment]
Yeah I know, that's why I closed it immediately. ;)

CXBX has a similar issue where it renders black spots on the screen at this spot and it also persists for rest of level.
