### ISSUE TITLE
Crash Twinsanity Missing Shadows

### ISSUE THREAD

**Issue by JOHN30011887** [Cxbx-Reloaded/Cxbx-Reloaded#2335]
## Quick summary

The shadows dont show up correct in this game.

## Details

When looking very close you can see the shadows have a very faint looking yellow tint instead of the usual black shadows.
In the other crash bandicoot games on this emulator like the wrath of cortex, tag team racing there shadows work/look perfect (doubt that might help but hopefully narrows down the issue)
i tried native resolution and others but nothing makes them show.

### System Configuration:

windows 11 pro
intel i7 8700k @4.7ghz
nvidia rtx 2080
16gb ddr4 ram

### Additional Information (if any):

Image of the missing shadows (my own image)
![cxbxr-ldr_2022_03_24_17_14_20_018](https://user-images.githubusercontent.com/12979984/159973036-358e7059-cf63-412c-81ff-9a30e5c17d56.png)

How the shadows should look (image took from google for reference but not my own image)
![68747470733a2f2f692e696d6775722e636f6d2f7149753038786d2e6a7067](https://user-images.githubusercontent.com/12979984/159974409-dd2095f2-4389-4fa6-b9d6-5a34532c2390.jpg)

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://cxbx-reloaded.co.uk/compatibility) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
