### ISSUE TITLE
Red Dead Revolver - full emulator crash while loading first level. (regression ?)

### ISSUE THREAD

**Issue by Gomam0n-afk** [Cxbx-Reloaded/Cxbx-Reloaded#2338]
## Quick summary

Game crash while loading the first level (see image below)
![cxbxr-ldr_CCgJCmsJR3](https://user-images.githubusercontent.com/59240947/160477419-55d6c1a9-da0e-40ed-8874-d838d613b45a.png)
- Continuing execution only stops emulation. 
- most likely not an issue with the game itself, as i tried it with Xemu and it worked perfectly fine (by making an xiso out of the folder), 
- trying to play the game in english is even worse as the game crashes even sooner with a different error
![cxbxr-ldr_8Myn6exORR](https://user-images.githubusercontent.com/59240947/160500686-6ae12dab-1a84-406f-ba18-f214d9349a5c.png)

- i also tried a REDUMP iso of the US version just in case, and ended up with even worse issues as seen here :
![cxbx_F1OChNx4LF](https://user-images.githubusercontent.com/59240947/160499508-613942f1-1c85-4162-8b1a-58bbb23c7a25.jpg)
The menu is visible for a short time before the menu becomes controlable, after that, the textures are blank.
and exactly the same crash later on, minus textures.
![cxbx_B9NaiLb31U](https://user-images.githubusercontent.com/59240947/160500375-34be4db4-8ad0-44cf-b54a-7441690ced95.png)

EDIT:
Showdown mode goes further but crashes when picking up a power up it seems.
![cxbx_EYrsIXEtTM](https://user-images.githubusercontent.com/59240947/160502737-9b545617-d197-4882-8572-68c2841614d3.jpg)

## Details

I already completed the game on a earlier version of the emulator, the only problem i had back then was that audio was weirdly mixed, and i couldn't or barely hear the sound of me shooting or explosions. i left the emulator alone for around a year, i upaded it to the latest version as of yesterday and tried booting the game up again, which is when this issue happened.

I also tried to play some GTA 3 just to be sure that it wasn't my copy of the emulator going insane, and the game ran perfectly fine. albeit with the known lighting / overexposure issues that everyone has.

### System Configuration:

* OS Windows 10 Enterprise 21h2
* CPU i7-7700
* GPU GTX 1060 6gb
* etc.

### Additional Information (if any):

Game version: European
Emulator version : 6788bf1
Emulator settings :
![cxbx_YvKEFdNSwB](https://user-images.githubusercontent.com/59240947/160477757-0170d460-5ccb-49cf-899f-1906853a0a3d.png)
Note about audio settings : this was only a test, i wanted to see if i could fix that weird audio bug on my own, but i could not proceed past that loading screen anyway.
![cxbx_DqIeuaLklh](https://user-images.githubusercontent.com/59240947/160477766-f849992b-c318-45e5-b391-676e4df556fa.png)

What i tried to do to fix it :
Restarting.
Clear symbols cache and cache partitions
remove everything inside EmuMu and EmuDisk
Software Direct3D (that just crashes the emu on startup)

**Comment by ergo720** [comment]
According to the most recent compatibility report [here](https://cxbx-reloaded.co.uk/compatibility/title/1664/report/1367), the game is no longer playable but only in-game, so it's likely just a regression, there's nothing you can do.
