### ISSUE TITLE
Blinx - The Time Sweeper - laggy and slow intros and it stucked on third

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#235]
Blinx - The Time Sweeper - laggy and slow intros and it stucked on third with very laggy sounds
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/23929607/aa403100-096a-11e7-9506-1582e2f1d84a.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/23929608/aa40aa18-096a-11e7-8a3f-0549d26f637b.png)

Xbe Dump Below
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/843182/Xbe.txt)

**Comment by furrya** [comment]
Now the game has regression - black screen with an exception code 

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24031807/f4a5ab30-0b27-11e7-9b96-f34a8a14e3ec.png)

And  here  two KrnlDebug files 
First with graphic progress, from earlier build and 2 - from a latest build
1)
[KrnlDebug — graphics.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/849831/KrnlDebug.graphics.txt)
2)
[KrnlDebug - no graphics.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/849833/KrnlDebug.-.no.graphics.txt)

**Comment by PatrickvL** [comment]
The first real difference between those two logs is that `EmuD3DDevice_SetRenderState_YuvEnable` is present in build a7ad4921 (Mar 11 2017) and absent in 64aac86d (Mar 16 2017).

Alas, the older log doesn't contain the HLE log, so it can't be compared, but the newer log mentions `HLE: 0x00134BB0 -> D3DDevice_SetRenderState_YuvEnable_4134`. It's possible this is the wrong location.

**Comment by furrya** [comment]
It's fixed with the latest commit, intro videos returned ^^
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24506753/73540744-1599-11e7-9a42-885c0292ad34.png)

**Comment by furrya** [comment]
Cxbx-Reloaded Version 77933ad8 (Apr 18 2017)
_________________________________________________________________________
Video in the game is broken now ..  in the latest build 77933ad8 . Just black screen with laggy sounds on background 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25129213/0147229c-2478-11e7-8274-025e1a776f18.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/929171/KrnlDebug.txt)

**Comment by furrya** [comment]
Blinx - the time sweeper not showes any videos anymore, instead this the game shows loading screen now and crash after it. Cxbx-Reloaded Version 9173d4ab (May  3 2017)

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25694341/21a0964a-30e9-11e7-993c-3a99c85b33fa.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25694339/219b3fd8-30e9-11e7-89b1-e6926bef8d33.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25694340/219c487e-30e9-11e7-8f30-8b2315345a53.png)
______________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/975455/KrnlDebug.txt)

**Comment by Casuallynoted** [comment]
Huh, interesting. So it skips the intro videos altogether?

**Comment by furrya** [comment]
@Casuallynoted Yes, that so

**Comment by Casuallynoted** [comment]
That's so bizarre. In some ways it's hard to tell if this is a regression or not because it looks like people couldn't get to menus before right? Weird. (Not one of the people working on this btw, but have been following this game hoping to see it reach in-game status someday in the near future)

**Comment by Casuallynoted** [comment]
Can't seem to get this game (or any game really) to run in the latest build, getting the error:

"[0x1550] EmuMain: Received Fatal Message:

* IDirect3D8::CreateDevice failed"

It does this no matter what settings I use :O

**Comment by Casuallynoted** [comment]
Regression over here!

![image](https://user-images.githubusercontent.com/6272557/28804874-2dd32960-7634-11e7-8a67-1965d28f1674.png)

**Comment by Casuallynoted** [comment]
Same problem as referenced in issue #622 . Game currently flashes a loading screen and then crashes, looks like it's unable to create some sort of file in the debug log.

**Comment by CakeLancelot** [comment]
@Cxbx-Reloaded/developers : this issue should be closed, I will update the game-compatibility page tonight with current status.

**Comment by Casuallynoted** [comment]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1367518/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1367517/CxbxDebug.txt)

Looks like the issue isn't resolved atm, got updated logs attached.

**Comment by BLiNXthetimesweeperGOD** [comment]
the loading screen background appears correctly now.
![demo](https://user-images.githubusercontent.com/33909717/33146137-192978aa-cf91-11e7-82bc-c602770d9bc7.PNG)
the demos do the same thing as the full game
