### ISSUE TITLE
Sega GT Online has shader and audio issues

### ISSUE THREAD

**Issue by HunterTheReckoning** [Cxbx-Reloaded/Cxbx-Reloaded#2354]
## Quick summary
 Sega GT Online has a shading issue in the car menu for Sega GT 2002 Mode, and Time Attack. It also has an audio issue within game.

## Details
 When selecting a car in Time Attack or Sega GT 2002 Mode, the reflections get messed up and spew out random colors. In game is much worst as the audio for the cars are very loud, this cannot be turned down or turned off.

Visual Issues:
![segagtonlineshadingissue](https://user-images.githubusercontent.com/104789763/166306995-dea39916-7723-46cd-bf8f-7abedd636530.png)

Audio Issues:
https://user-images.githubusercontent.com/104789763/166308847-ab970e5f-eb0b-470f-bf7e-edda363f7856.mp4

### System Configuration:

* OS Windows 11
* CPU 11th Gen Intel(R) Core(TM) i5-11600KF
* GPU Nvidia Geforce RTX 2060
* etc.

**Comment by HunterTheReckoning** [comment]
Wait what? I followed the template.

**Comment by RadWolfie** [comment]
We do not accept title specific report here. Please read the readme file for what kind of reports we do accept: <https://github.com/Cxbx-Reloaded/Cxbx-Reloaded#bug-reports>
In this case, it should be report on compability website.

**Comment by PatrickvL** [comment]
When rephrasing this issue, please make note of the rainbow coloured texture which might be the result of an unsupported U/V texture format or bump mapped rendering mode
