### ISSUE TITLE
No titles works when kernel logging is set to file

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#2367]
## Quick summary

No titles works when kernel logging is set to file

## Details

No titles (even dashboard 4920)  works when kernel logging is set to file.
Regressed commit - https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/5e928e508ac8c3c01d6b11c64e55a541d78484fa
Tested several times, e8f943e - good, 5e928e5 - bad.

### System Configuration:

N/A

### Additional Information (if any):

N/A

**Comment by PatrickvL** [comment]
It appears that the logging to file issue is not reproducible.

Try to clear partitions, symbol cache and resetting settings and/or whatever else can be tried
