### ISSUE TITLE
Massive slowdowns in TES III: Morrowind

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#2368]
## Quick summary

Massive slowdowns in TES III: Morrowind

## Details

Massive slowdowns in TES III: Morrowind. Appears when player is moving.But when you're changing camera angle -all things are OK, NPC moving (and player is standing) - OK.
Very noticeable at Seyda Neen,FPS drops from 55 to 7 after you're start moving, after you'd stopped at place - it gonna be normal again (until starting move).
That commit cause slowdowns - https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/95b789eb2776543f3c287f6b494e0a2d577c7f9f. Tested several times, https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/5e928e508ac8c3c01d6b11c64e55a541d78484fa - good, https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/95b789eb2776543f3c287f6b494e0a2d577c7f9f - bad.

### System Configuration:

OS - Windows 10 Pro
CPU - Intel Core i5-10400
GPU - NVIDIA RTX 2060 Super 8 GB
RAM - 32 GB DDR4

### Additional Information (if any):

N/A

**Comment by RadWolfie** [comment]
Please ignore above mentioned to the pull request, it is completely irrelevant to this issue. Later pull request may will resolve this problem.
