### ISSUE TITLE
Marvel vs. Capcom 2 - Missing HLE Patch

### ISSUE THREAD

**Issue by UlsterRose** [Cxbx-Reloaded/Cxbx-Reloaded#237]
`[0x1C74] EmuWarn: EmuX86_Write32(0xFD714178, 0x0F39F518) Unexpected NV2A access, missing a HLE patch. Please notify https://github.com/Cxbx-Reloaded/Cxbx-Reloaded which title raised this!`

This line gets spammed in the console, albeit with varying addresses.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/846120/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
The debug log doesn't show all details, so it's hard to tell, but it seems like this is an LTCG title

**Comment by jarupxx** [comment]
I found it from the dxbx compatibility list. This title using non-LTCG version 5028.

**Comment by jarupxx** [comment]
@DisorderIy I maked HLE Patch for this game. I am pleased if you can test it https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/267 .

**Comment by DisorderIy** [comment]
The game now crashes after this gets printed to the console:
`[0x15A8] EmuWarn: SetRenderTarget Failed! (0x8876086C)`

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/868497/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#182
