### ISSUE TITLE
JSRF | Jet Set Radio Future fails to emulate

### ISSUE THREAD

**Issue by Redstorm3265** [Cxbx-Reloaded/Cxbx-Reloaded#2376]
## Quick summary
Jet Set Radio Future fails too emulate on CXBXR versions using VS2022

## Details
When emulation begins a black screen is shown for ~2 seconds then emulation ends/closes. This occurs only on CxBxR versions using VS2022. System has the required redist. packages.
The same game can be ran on cxbxr versions using vs2019.

### System Configuration:
* OS Win10 x64 19044
* CPU Intel i9-10900KF
* GPU nVidia RTX 2080
* RAM 128GB 

### Additional Information (if any):
No hacks are enabled and cache has been cleared.

**Comment by ergo720** [comment]
I tested Jet Set Radio Future with build b43f6bbcdfbd87319c805a7d6d4a67f456276aec and it works for fine for me (except that it freezes when attempting to close, but that's caused by another issue we already know about), so the issue is on your end.
