### ISSUE TITLE
Pro Skater 4 shadows are missing or flickering and game colors are washed out

### ISSUE THREAD

**Issue by PunishedFiddle** [Cxbx-Reloaded/Cxbx-Reloaded#2396]
## Quick summary

Player's character shadow is missing or flickering two meters behind him, colors are washed out.

## Details

* Game tested: Tony Hawk's Pro Skater 4 [AV-023]
* Cxbx-Reloaded Version: 42ff76c

Player's character shadow is missing or inaccurately flickering two meters around him. Game looks washed out and the gamma option doesn't really change anything.

### System Configuration:

* OS: Windows 10 Enterprise x64 LTSC
* CPU: Intel Xeon E5-2689 2.60 GHz
* GPU: Radeon R7 360 2gb

### Additional Information (if any):

It seems like an old problem
https://youtu.be/HpbnQjZTG6k?t=529
https://www.youtube.com/watch?v=LDQczeI4JN8
https://www.youtube.com/watch?v=owgq8MJeMNA
Og Xbox
https://www.youtube.com/watch?v=ylaYPghMfqs

**Comment by ergo720** [comment]
Sorry, but this tracker doesn't accept game-specific issues at this time.
