### ISSUE TITLE
Cxbx-Reloaded Keeps Giving This Error On Wine

### ISSUE THREAD

**Issue by CubixTwist** [Cxbx-Reloaded/Cxbx-Reloaded#2402]
## Details
While trying to run Jet Set Radio Future, i keep getting this your xbox requires service error. I've tried older builds, but nothing. Any way to fix this?

### System Configuration:

* OS GailumOS
* CPU Celeron N3350
* GPU HD 4000
* RAM 4GB

**Comment by CubixTwist** [comment]
![Screenshot_2022-09-28_06-27-40](https://user-images.githubusercontent.com/114561247/192704472-1f4429f6-a598-4774-88f6-f81e2bc76899.png)

**Comment by Masamune3210** [comment]
13 is Dashboard Launch Failed, make sure your files work and everything is in the right place. Make sure cxbx-reloaded is set up correctly

**Comment by CubixTwist** [comment]
> 13 is Dashboard Launch Failed, make sure your files work and everything is in the right place. Make sure cxbx-reloaded is set up correctly

**Comment by CubixTwist** [comment]
ok thanks, will do.

**Comment by CubixTwist** [comment]
I tried everything, even installing the dashboard but still the same error.

**Comment by ergo720** [comment]
User support is provided in our discord channel [here](https://discord.com/invite/26Xjx23)
