### ISSUE TITLE
Please add a Version for Android Users

### ISSUE THREAD

**Issue by joelos1111** [Cxbx-Reloaded/Cxbx-Reloaded#2405]
## Quick summary

Please try to compile a version for Android users like me, right now the Emulator looks amazing but i'd love to try it on my phone or Tablet. I hope you are able to make it work on the vast majority of Android Devices whether they are ARMV7 or ARMV8 and that you can compile an official version of your wonderful Emulator in the upcoming days or months, if you offer some support for this then we all mobile/tablet users would highly appreciate it
### System Configuration:

* OS        Android 8
* CPU     4x 1.5 GHz ARM Cortex-A53, 4x 1.0 GHz ARM Cortex-A53, Cores: 8.
* GPU      ARM Mali-T860 MP2, Cores: 2.
* etc.

**Comment by PatrickvL** [comment]
Dear @joelos1111, please read the background information in our wiki to understand why your request cannot be picked up : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Cxbx-Reloaded-overview#cpu-emulation

**Comment by PatrickvL** [comment]
PS, I see you requested the same from xemu: https://github.com/mborgerson/xemu/issues/1281

**Comment by RadWolfie** [comment]
duplicate of #19, #495
