### ISSUE TITLE
A git hash is  not visible for me, when I compile a build from source 

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#243]
A git hash not visible for me, when I compile a build from source with Visual studio enterprise 2017..
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24032725/d031ef02-0b2c-11e7-9d49-94e6c680e167.png)

**Comment by LukeUsher** [comment]
It looks like you downloaded the source code zip direct from github, instead you should checkout the code with git, otherwise the information used to generate the version string is missing.

**Comment by furrya** [comment]
@LukeUsher  Thanks for the explanation. =) Now  git hash appeared 
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24042233/647f6898-0b54-11e7-9cb6-3d7705d4dbac.png)
