### ISSUE TITLE
CNK hasn't worked since July 5th, 2022

### ISSUE THREAD

**Issue by CountessElle** [Cxbx-Reloaded/Cxbx-Reloaded#2435]
## Quick summary

Crash Nitro Kart no longer works in versions past CI-b2f6391 Tue, Jul 5, 2022 2:57 PM

## Details

Game freezes during boot before FMVs can load in.

### System Configuration:

* OS Windows 10
* CPU Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz, 3000 MHz, 6 Core(s), 6 Logical Processor(s)
* GPU GTX 970

### Additional Information (if any):

N/A

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://cxbx-reloaded.co.uk/compatibility) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
