### ISSUE TITLE
Midtown Madness 3 Problems

### ISSUE THREAD

**Issue by WindowsNinetyTen** [Cxbx-Reloaded/Cxbx-Reloaded#2443]
## Quick summary

Midtown Madness 3

## Details

Midtown Madness 3 doesn't show up with the video. Only audio works. Also, I get a warning message about "One or more XBE sections are corrupted".

### System Configuration:

Windows 11 Home
Intel Core i5
Intel Graphics UHD

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://cxbx-reloaded.co.uk/compatibility) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.
