### ISSUE TITLE
Turok Regression (again)

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#245]
Well Turok has regressed yet again and now crashes after a few seconds with the error code bellow. It seems inconsistent.
![freeze](https://cloud.githubusercontent.com/assets/17304943/24075975/f49b3de6-0be3-11e7-980d-2409eaf21667.PNG)

**Comment by PatrickvL** [comment]
There's no git short hash visible in the window caption, so which exact version is this?

**Comment by BenNottelling** [comment]
The latest, 816393fd I believe (I'm new to git so don't quote me on that, but it is the latest build)

**Comment by furrya** [comment]
Same thing.
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24079242/92df5a86-0cc6-11e7-9bd2-5eea0e93114a.png)

**Comment by LukeUsher** [comment]
Looks like my HLE Database changes for 4134 broke something in Turok.
I don't have time to look into this today, but I'm making this note as a reminder.

**Comment by PatrickvL** [comment]
A quick compare of the output of the function address detection phase should indicate what's missing

**Comment by elfogames** [comment]
it regressed even more,not possible to reach menu anymore 
![sem titulo](https://cloud.githubusercontent.com/assets/16784631/24303161/bce0e950-1093-11e7-98a9-c9f3c329b512.jpg)

**Comment by LukeUsher** [comment]
This shouldn't be difficult to sort out, but I don't have Turok to test with.

There will be some functions in the OOVPA Table that are no longer being matched after being updated to work with other games

**Comment by PatrickvL** [comment]
As described in another issue, we should make sure that detected function addresses don't change for any title known to work. The only allowed changes are those that increase accuracy.

**Comment by furrya** [comment]
For me Turok regressed now at the second logo
![screenshot_7](https://cloud.githubusercontent.com/assets/25540784/24317908/b25e72ba-1140-11e7-8de1-f9807e22391a.png)

**Comment by BenNottelling** [comment]
It now gets in-game and seems to play as before, can other people verify (ideally with intel and Nvidia as it works with my AMD)

**Comment by furrya** [comment]
Ingame for me ether- Palit Gt 610
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24318789/c1903490-114e-11e7-96cf-7c73607711ea.png)

**Comment by PatrickvL** [comment]
It seems the fixes to the new memory-manager (in PR #293) fixed this - I can get in-game too now.
