### ISSUE TITLE
GunValkyrie can reach ingame now with some broken graphics and the control  that doesn't work

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#246]
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24077251/ba4b79ba-0c8a-11e7-938b-7dd24efc8666.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24077252/ba4cb938-0c8a-11e7-9b7f-b2f946071068.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24077250/ba498ee8-0c8a-11e7-8817-f884d4f23e27.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/852842/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/852843/KrnlDebug.txt)

**Comment by LavenderMoon** [comment]
***YES!***

**Comment by LukeUsher** [comment]
I believe the broken graphics here is related to the broken graphics in the dashboard & in JSRF, I think a large overhaul of the D3D emulation is needed, at the very least we should port over all the advancements DXBX made.

**Comment by furrya** [comment]
Hmm. Now it's look much better on Windows 7 x64

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24096779/c66645d4-0dae-11e7-9e92-fee4ab64d428.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/24096778/c665c3de-0dae-11e7-906a-9375642e8af2.png)

**Comment by LukeUsher** [comment]
We have an issue with vertex buffer corruption, it seems to depend on where the buffers get allocated in memory, it's the same as the dashboard issue, the behavior is completely random. This time you got lucky, another time it might be broken with the same setup

**Comment by furrya** [comment]
Hmm, I see. However launching game on Windows 7 x64 I always see normal graphics with GunValkyrie unlike I launch it on Windows 10 x64 - with results always broken graphics. Maybe vertex buffer somewhat different -  Win 7 and Win 10

**Comment by furrya** [comment]
With the latest commit, the graphics now is same on Windows 7 and on Windows 10 
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24176820/c6ceb108-0ee1-11e7-81c3-043d8fffbca1.png)

**Comment by furrya** [comment]
GunValkyrie can reach ingame now with some broken graphics and controller doesn't work and  exception code appears after that
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869510/KrnlDebug.txt)

![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24317855/e2e884d0-113f-11e7-8b89-91feb3a38288.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/24317856/e2e9aa54-113f-11e7-88a4-dfc59eca1919.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/24317857/e2ecd706-113f-11e7-8bfb-1e6cc233553e.png)

**Comment by blueshogun96** [comment]
This title has regressed.  Upon launching it, it tries to reboot to the dashboard.  This was the same issue I had with my old branch, and never did figure out why this always happened, but something is probably missing.

Shogun.

**Comment by PatrickvL** [comment]
Note : Wikipedia and Mobygames says about GunValkyrie .. Apparently this is the correct spelling  http://www.mobygames.com/game/gunvalkyrie

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#180
