### ISSUE TITLE
Internal and External Display Resolutions Settings are the Same!!

### ISSUE THREAD

**Issue by SyphonF** [Cxbx-Reloaded/Cxbx-Reloaded#2464]
## Quick summary
All emulators that I've tested so far follow a very simple rule:
"Internal and external display resolutions are separate from each other." 

CXBX is the ONLY emulator that breaks this simple rule!! (otherwise it's a bug)

## Details
I've been working on this simple option for hours and I still failed to find the solution!

To get the highest resolution in full screen, it seems like adjusting the Render Resolution is not enough, you'd also need to adjust the Display Resolution as well, otherwise it won't have any single effect when you switch to full screen (I was so confused at first and had no idea what was going on!!!!). and the problem is, when I set the Display Resolution to 1920x1080 it would also resize the WINDOW to 1920x1080 which would fully cover/block the whole desktop screen!! and if I were to pause the game and check something on my desktop real quick I'd have to press Alt + Enter/F10 first to exit the full screen mode and then click on CXBX to minimize it and once I'm done, repeat the whole process which is absolutely annoying!! not to mention that sometimes I mod a game and I need to have the emulator in window mode if I wanted to to compare something, say, a texture on my desktop with the running game.

What makes it so weird is that when the Display Resolution is left at its default "Automatic" resolution and the window size doesn't exceed its normal size, I can clearly see the Render Resolution applied to the whole scene while the game is running. but as soon as I switch to full screen, it all gets pixilated!! it has to be a bug, otherwise there's no single option to resize the window mode. the ONLY info that I could find in google results regarding resolutions was: [What does "Set resolution for internal and external display" do?](https://steamcommunity.com/app/1675200/discussions/0/3416557114768840174/)

...and it seems like, CXBX used to have separate options for internal and external resolutions! but this option is non-existent in the Aug 25 2024 version. (I also checked all Eeprom settings and none of them had anything to do with resolutions)

I came up with a temporary work around if anyone else is experiencing the same issue. just set the resolution to 1280x720 so it doesn't cover the whole desktop screen but don't expect the full screen quality to be as good as 1920x1080 (or whatever your full screen size is)!

Xemu has no such an issue at all  but on the other side it neither supports running games from .xbe files nor does it offer a very simple GUI like CXBX's. 

Hopefully we'll see this problem fixed in the future.

### System Configuration:

* OS = Windows 11
* CPU = Intel(R) Core(TM) i7-10700K
* GPU = GeForce 1070
* Emu = CXBX Aug 25 2024 version
* etc.

**Comment by SyphonF** [comment]
It doesn't show my post. why?!

**Comment by RadWolfie** [comment]
I recommend you to use discord server to seek user support (which can be found on readme page) and better understanding how xbox system work. There is a configuration in EEPROM setting for different resolution option from user request. However, not every title respect this request.

For a reminder, `Display Resolution is left at its default "Automatic" resolution` is a title's display resolution size and not your monitor display resolution. The same for Render Resolution as well.
