### ISSUE TITLE
D-PAD not emulated.

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#247]
Title speaks for itself, the D-PAD emulation doesn't seem to work for me. It tells me that is has been bound, but pressed the keys does nothing

**Comment by PatrickvL** [comment]
I've had a similar issues which went away when I reset and reconfigured all control buttons. Please try that and tell your results. Oh, and please backup your current and new CxbxReloaded registry contents. If reconfiguring fixes this issue, then a comparison between old and new registry contents will tell us more about a probable cause.

**Comment by LukeUsher** [comment]
Can you retest this? I suspect #250 was the same issue as this.
It might be a good idea to reconfigure your controller settings again first.

**Comment by BenNottelling** [comment]
@LukeUsher I noticed it with this tool as well as some homebrew games that didn't navigate the menu with the joystick:
http://www.theisozone.com/downloads/xbox/tools/controller-test/
I will retest when I get the chance.

**Comment by LukeUsher** [comment]
This is a strange one. I'm hearing multiple reports of this from various sources, yet the controller test demo works fine for me (including the dpad).

**Comment by BenNottelling** [comment]
I deleted the registry for the controller and still can't get it to work if I reconfigure it, what is the default controls?

**Comment by PatrickvL** [comment]
See issue #156 for a possible remedy

**Comment by LukeUsher** [comment]
Closing this issue as there is no issue with D-PAD emulation, it's rather an issue with controllers.
We have #477 and other related issues for this already.
