### ISSUE TITLE
[Feature Request] DLL Injector

### ISSUE THREAD

**Issue by mrmaller1905** [Cxbx-Reloaded/Cxbx-Reloaded#2471]
## Quick summary
A suggestion to add DLL injector which allows users to make Xbox games widescreen and log filenames and hashes (e.g. common.dat/ .fat of Far Cry Instincts).

## Details
DLL injector allows users to make games widescreen and trainer to make ammo and health infinite in games such as Halo 2.

### System Configuration:
N/A

### Additional Information (if any):
N/A

**Comment by ergo720** [comment]
This is already possible as far as I know. Also, it's not the job of cxbxr to be injected with DLLs. That's up to third-party programs to perform the injection, such as [this one](https://github.com/nefarius/Injector).

**Comment by mrmaller1905** [comment]
Can you anyone add support for custom XBE injection into Xbox games to Cxbx-Reloaded?
