### ISSUE TITLE
Test Drive: Eve of Destruction - missing HLEpatch

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#248]
Test Drive: Eve of Destruction - missing HLEpatch

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/853009/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/853010/Xbe.txt)

**Comment by PatrickvL** [comment]
This is an LTCG title - meaning it will require LLE to be emulated. We're nowhere near that for a very long time.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#179
