### ISSUE TITLE
Voodoo Vince Black screen with some audio

### ISSUE THREAD

**Issue by bhodg22** [Cxbx-Reloaded/Cxbx-Reloaded#262]
Doesn't boot at all
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/864544/KrnlDebug.txt)

![vdv](https://cloud.githubusercontent.com/assets/5080749/24246131/a385121a-1011-11e7-89c9-0bf47f41046e.png)

**Comment by PatrickvL** [comment]
Thanks for taking the trouble to register this as an issue, but please be aware that nearly identical reports could be made for most of all existing Xbox titles. We're currently more interested in reports on titles doing *something*, either visually or generating sound.

**Comment by bhodg22** [comment]
Sure, ive got some more games that I can FTP off my xbox and can try

**Comment by bhodg22** [comment]
Havent tested this game for a while but the game now produces audio! Still black screen tested on commit https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/d44c3930651a3e08864c2ba63d4ef109df00cf21

**Comment by HyperScorpio** [comment]
Untill is not fixed you can always play the PC version is avaliable for sale on Steam. 👍

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#177
