### ISSUE TITLE
Namco Museum - Loses sound at main menu and graphical glitches at menu

### ISSUE THREAD

**Issue by bhodg22** [Cxbx-Reloaded/Cxbx-Reloaded#265]
Game loses sound once you reach the main menu and has some graphical glitches but apart from that very playable
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/866619/KrnlDebug.txt)
![menu](https://cloud.githubusercontent.com/assets/5080749/24276730/75f9b274-1084-11e7-995b-9545a253cd52.png)
![gameplay](https://cloud.githubusercontent.com/assets/5080749/24276733/7a531c52-1084-11e7-8d46-e618e3e41bc1.png)

**Comment by LukeUsher** [comment]
That's great. I've tested this game many times over the past year and it's never worked. This is a good sign we are making progress!

**Comment by bhodg22** [comment]
After some more testing I did find that Namco museum will crash back to the cxbx screen on certain games
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869872/KrnlDebug.txt)
 
I also noticed that this game gets a significant speed boost to pretty much full speed when I have dota 2 open in the background, when I close dota again the game goes back to about 50% speed

**Comment by ObiKKa** [comment]
After PR #375 (Simple overlay conversion & others) and #376 (Integrated copy OOVPAs), unfortunately, the video previews look like a horror show!

![collage-2017-04-19](https://cloud.githubusercontent.com/assets/18428108/25143739/e55d21f8-24ae-11e7-8f26-6d34a21fb08f.png)
[KrnlDebug_(2017-04-19).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/930520/KrnlDebug_.2017-04-19.txt)

**Comment by PatrickvL** [comment]
I really should get a copy of this game, so that I can make sure it actually works before I submit another problematic commit like this. My apologies - I meant it well, Turok ran okay, I figured other video plays would work too...

**Comment by ObiKKa** [comment]
Oh no, these error messages are spreading like wildfire, interrupting several games before they can even play a movie or get to a menu properly!

![2017-may-03 _error-box_01](https://cloud.githubusercontent.com/assets/18428108/25628854/0c0abe4e-2fab-11e7-801d-a2c6e4d7d5e3.png)

**Comment by bhodg22** [comment]
I also have the same regression

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#176
