### ISSUE TITLE
Miami Vice - the game reaches the title screen, but controller does not work

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#266]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/867702/KrnlDebug.txt)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24292837/51c70188-10d2-11e7-9eb6-f64022e4703b.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24292838/51c7541c-10d2-11e7-9aae-bf57371b5009.png)

**Comment by furrya** [comment]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/867705/KrnlDebug.txt)

**Comment by furrya** [comment]
The game reaches the title screen now, but controller does not work 
_________________________________________________________________________
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25561132/179b7b0c-2da0-11e7-8abe-6059147dd2b0.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25561134/1d27c5bc-2da0-11e7-8706-80a51902e87b.png)
______________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966538/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#175
