### ISSUE TITLE
OOVPA Guidelines needed

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#268]
As there are now multiple people contributing to the OOVPA HLE Database, we need a set of guidelines to follow when creating OOVPAs to reduce the risk of regressions.

Library functions are relocatable, so portions can differ between titles, even those that use the same XDK version. Because of this, the offsets used have to be carefully chosen so that they will be the same even after relocation.

Good candidates to use are:
- Opcodes that use segement registers (these very rarely change)
- Constants (not memory offsets)
- Relative Conditional Jumps (absolute jump addresses may differ)

**Comment by PatrickvL** [comment]
http://ngemu.com/threads/troubleshooting-oovpa.155996/

**Comment by jarupxx** [comment]
Instructions, including memory offsets would like to recommend. This has a low appearance frequency, so it reduces the possibility of false detections.
I think that it is safe to use it after filtering different parts between titles by Dxbx patterns.

**Comment by PatrickvL** [comment]
@jarpuxx Meanwhile, you've become since sort of an OOVPA wizard - perhaps you can write up these guidelines by now?

**Comment by jarupxx** [comment]
Well, generalizing knowledge and writing guidelines is very challenging for me. I'm sorry.

Instead, I will inform you of the process of make OOVPA.
The idea uses a continuous value that matches only one pair on default.xbe. Continuous values can be easily verified with common Hex editor.
![makeoovpa](https://cloud.githubusercontent.com/assets/20138367/24704216/a7191126-1a41-11e7-9219-5d4ee31807db.png)
I hope you find it useful.

**Comment by PatrickvL** [comment]
Thanks for explaining your approach, it might already help others. Because this uses the Dxbx pattern files, there's also a description needed for defining OOVPA four executables that use other versions...

**Comment by LukeUsher** [comment]
The same approach can be used for the most part => There are a high number of functions that are the same between XDK versions, and by identifying strings of bytes that have stayed the same in all known XDKs, there's a high chance these also never changed in the missing ones.

**Comment by BenNottelling** [comment]
@jarupxx I'm confused, where is this text file with the Dxbx patterns?

**Comment by PatrickvL** [comment]
@BenNottelling Here : https://github.com/PatrickvL/Dxbx/tree/master/Resources/Patterns

**Comment by PatrickvL** [comment]
I did write up [a small overview in our wiki](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Maintaining-OOVPA's-for-HLE-function-detection) a while ago

**Comment by LukeUsher** [comment]
Closing as this is now the responsibility of XbSymbolDatabase.
