### ISSUE TITLE
Jet Set Radio Future - Differences in game graphics by video card (?)

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#271]
When I was testing out JSRF I saw some differences in my game's rendering compared to the one posted. Now I still get the graphical errors as described in #251 but my UI seems to be completely black at all times. 

At first I thought this difference was due to my graphics card but I've also tried running it on my iGPU and got the same results. So this might be something else, maybe OS.

From #251 (UI renders correctly)
!["Correct" Rendering](https://cloud.githubusercontent.com/assets/25540784/24176732/25a96c1e-0ee1-11e7-9934-c5b480f2652a.png)

Running on my PC (UI is blacked out)
![cxbx_2017-03-24_18-56-34](https://cloud.githubusercontent.com/assets/5341136/24317278/a68a4c8e-10c3-11e7-831c-94857d816535.png)

Here are my PC's specs:

> MSI Z97-G55 SLI
Intel Pentium G3258 OC'ed to 4.4 ghz
Sapphire Nitro R9 FURY 4GB (Stock)
2 Crucial Ballistix Sport 8GB (total 16GB)

I'm running on Windows 8.1
Build db7da95d (Will update if needed)

**Comment by DisorderIy** [comment]
I also get differences between AMD and Intel with Burnout. Intel looks more accurate than AMD in that game.

**Comment by bhodg22** [comment]
My AMD card also gets the same result with the black menu and UI elements and also fixes up after using graffiti

**Comment by CakeLancelot** [comment]
Also note that the skybox doesn't render on my video card either, it's just blacked out similar to the GUI.

**Comment by PatrickvL** [comment]
This might be related to issue #300.

**Comment by HyperScorpio** [comment]
I got that textures as well.
Here's my specs.

Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz 2.66GHz
RAM 12 GB
Windows 7 Ultimate 64-Bits
ASUS GTX 660 Direct CU II OC 2GB + GPU TWEAK

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#174
