### ISSUE TITLE
Kabuki Warriors - in-game, but has  very buggy graphics

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#273]
Kabuki Warriors - almost reached ingame, but broken graphics and exception code

![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24320174/713f120c-1173-11e7-8e06-7fe6e62e9771.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24320177/71438f26-1173-11e7-8068-dbb37b6ae92e.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/24320178/71440410-1173-11e7-8fc3-50574b0cb5ff.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/25540784/24320176/71435934-1173-11e7-9af1-767376fcf873.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/25540784/24320175/71431730-1173-11e7-8ba7-6ed02e64cc8d.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869799/KrnlDebug.txt)

**Comment by furrya** [comment]
On the latest commit - nearly the minute or two in game and suddenly crashes
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24583802/e8c7e618-1791-11e7-8687-b148743151f7.png)

**Comment by PatrickvL** [comment]
Thanks for reporting this progress. Be aware though that 'latest commit' will change over time, so it's better to be explicit and specify exact build versions

**Comment by furrya** [comment]
The graphics gets more buggy at the latest build 17fedee8fd41cfd21108a8fd0563168aa51101e9 
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24858642/1543e3a8-1e28-11e7-91b5-f5966f0b01cf.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24858643/15444af0-1e28-11e7-9ac6-d69767773b82.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/24858641/1543a276-1e28-11e7-9105-d0c3efdffbf0.png)

**Comment by PatrickvL** [comment]
The garbled graphics are probably due to the introduction of the new FormatInfos array.
A simple test-case that exhibits the same behaviour is X-Marbles.

**Comment by PatrickvL** [comment]
@furrya Did PR #350 fix these buggy graphics in Kabuki Warriors?

**Comment by furrya** [comment]
@PatrickvL Yes, the graphic in the game is working good now with this patch -  #350 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24887532/4c9c6770-1e97-11e7-9609-e4fe7b96e08b.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24887531/4c9866e8-1e97-11e7-9930-bc50cceaa9ea.png)

**Comment by furrya** [comment]
As I have noticed with hardware video mode enabled I can get ingame almost without crashes, but the game runs too fast, even with vsync,  Seems i have ended the first fight and battle menu has appeared that show result of that
![first](https://cloud.githubusercontent.com/assets/25540784/24887782/8ab1a7e4-1e99-11e7-9bc0-a500a105534b.jpg)

**Comment by blueshogun96** [comment]
Are you guys emulating the fix ups?  As in D3DFixup?  The lack of these was what killed it in my old branch.

Shogun

**Comment by PatrickvL** [comment]
Fixups are totally ignored, as they are meant to fill in blanks in push buffers, right before these are submitted to the GPU. This will probably require LLE, or much more work on push buffer emulation

**Comment by furrya** [comment]
Cxbx-Reloaded Version 394aee6b (Apr 29 2017)
______________________________________________________________
Kabuki Warriors - looks better now , but has very buggy graphics 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966534/KrnlDebug.txt)

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25561010/5575cc64-2d9d-11e7-92b2-7deafa6abc97.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25561011/5577a98a-2d9d-11e7-8322-30b79a1de899.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#172
