### ISSUE TITLE
Phantasy Star Online: Episode I & II - lack of textures and other graphics problems

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#274]
Phantasy Star Online: Episode I & II - the game almost reached the menu and has two exception errors before I can start
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24321386/7046206e-118e-11e7-82d2-865d204f30c7.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24321385/70451a66-118e-11e7-886d-56d0a658311c.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869914/KrnlDebug.txt)

**Comment by furrya** [comment]
With the 7760a7d (Apr 9 2017) build of Cxbx Reloaded, KeBugChek warning appears at the start , though I can skip some of them and get to the third intro screen
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24842860/e76e3f6e-1dd7-11e7-88c8-7c4c69c061cf.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908739/KrnlDebug.txt)

**Comment by furrya** [comment]
CXBX - Reloaded Version 488db56077f776b2d6bb75382717c68bddabe8a5
The music in the menu is fully working now but the game crashes upon I try to press a start button  ![screenshot_1](https://user-images.githubusercontent.com/25540784/28961371-002f9654-793d-11e7-8918-d7a5903cb420.png)
![screenshot_1](https://user-images.githubusercontent.com/25540784/28961547-a3752518-793d-11e7-8460-02e7da00914b.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199752/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
Sound serious, I'll investigate what went wrong with DirectSoundBuffer creation.

**Comment by furrya** [comment]
The game is now perfectly loaded. The music in the game is fully played, only the textures are missing and in the intro video half of the screen is not visible

![screenshot_1](https://user-images.githubusercontent.com/25540784/29000339-62e8421c-7aa2-11e7-8c15-c0581f6b49bc.png)
![screenshot_2](https://user-images.githubusercontent.com/25540784/29000340-62e9f864-7aa2-11e7-9111-e2f813d6c8ff.png)
![screenshot_3](https://user-images.githubusercontent.com/25540784/29000341-62eace6a-7aa2-11e7-9132-12e57d59ca18.png)
![screenshot_4](https://user-images.githubusercontent.com/25540784/29000342-62ed70a2-7aa2-11e7-9e0d-1bdb2caaa28a.png)
![screenshot_5](https://user-images.githubusercontent.com/25540784/29000343-62f0507e-7aa2-11e7-9b52-8874cb50ef8b.png)
![screenshot_6](https://user-images.githubusercontent.com/25540784/29000344-62f3d80c-7aa2-11e7-80ba-69ec0ea06323.png)
![screenshot_7](https://user-images.githubusercontent.com/25540784/29000345-63124e7c-7aa2-11e7-8fea-745831c8fb12.png)
![screenshot_8](https://user-images.githubusercontent.com/25540784/29000348-6318ce5a-7aa2-11e7-8130-0b8e3ea0e78a.png)
![screenshot_9](https://user-images.githubusercontent.com/25540784/29000346-63164dba-7aa2-11e7-830e-953ea76a104d.png)
![screenshot_10](https://user-images.githubusercontent.com/25540784/29000347-6316ecac-7aa2-11e7-8a35-71090e3364e0.png)
________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202845/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#171
