### ISSUE TITLE
Return to Castle Wolfenstein Intro

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#275]
![wolfenstein](https://cloud.githubusercontent.com/assets/3212225/24325926/4d7d19ba-1171-11e7-9486-24d928c62545.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870353/KrnlDebug.txt)

System:
AMD Phenom II 945
Win 7 64bit
ATI 7770

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#170
