### ISSUE TITLE
Mechassault shows intro with broken audio

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#276]
![mech1](https://cloud.githubusercontent.com/assets/3212225/24326041/ae7eedea-1173-11e7-9c6b-08949fd62225.png)

Intro screens show with some broken audio.

I have a really old version of Cxbx that I tried this on:
Cxbx-Reloaded Version b7f4b23 (Dec 24 2016)

I also tried it on Cxbx-Reloaded Version 5be759c2 but nothing happens. It would appear we lost some functionality from then to now.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870362/KrnlDebug.txt)

System:
AMD Phenom II 945
Win 7 64bit
ATI 7770

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#169
