### ISSUE TITLE
Psyvariar 2 - Extended Edition - in-game with some errors 

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#279]
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24327124/b00d148a-1203-11e7-838b-7e106fe8690f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24327125/b00d6f98-1203-11e7-8417-42fa0450d30d.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24327123/b00ce960-1203-11e7-9c90-48346590072a.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870471/KrnlDebug.txt)

**Comment by furrya** [comment]
With Cxbx-Reloaded Version 36f9e171 (May  3 2017) dirty disk error has disappeared and  I can reach in-game. But one note I need to mentioned - I get an error immediately if I press start on first intro screen - probably need little wait and press start on second.
 ![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25687589/91f00a5c-30b2-11e7-8afe-8b184b37b7ba.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25687587/91eef270-30b2-11e7-80bd-d9f8fa790047.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25687588/91ef693a-30b2-11e7-91d2-dee64bb6dd0b.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25687590/91f09404-30b2-11e7-88b6-77ac9fd4aeed.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25687591/91f2e0a6-30b2-11e7-8eb4-be20a39b644f.png)
______________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/975060/KrnlDebug.txt)

**Comment by jarupxx** [comment]
If I press start on first intro screen immediately, it seems that the unimplemented function ```IDirectSoundBuffer_Use3DVoiceData``` is called. This will work with PR #443.

**Comment by furrya** [comment]
@jarupxx Great! I confirm that the error has disappeared.

**Comment by furrya** [comment]
I have retested game emulation and now I can play about 3 - 4 minutes, before another error appears
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25769486/6ebe5ad0-3255-11e7-8d32-db14d9566989.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980656/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#166
