### ISSUE TITLE
Blinx - The Time Sweeper crashes due to UpdateOverlay bugs

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#285]
This function seems to crash during full color conversion if ImageSize is large.
Parameters as

Unreal Championship Passed
dwImageSize = 614400, g_dwOverlayP = 1280, g_dwOverlayH = 480
Rayman Arena Passed
dwImageSize = 614400, g_dwOverlayP = 1280, g_dwOverlayH = 480
Blinx - The Time Sweeper Crashed! (issue #235)
dwImageSize = 1048576, g_dwOverlayP = 2048, g_dwOverlayH = 512

**Comment by jarupxx** [comment]
Change Video Resolution to 1280 x 960 32 bit, the movie play.
![blinx](https://cloud.githubusercontent.com/assets/20138367/24350899/e75c3eb8-131e-11e7-80f2-3451a51dca89.jpg)

**Comment by PatrickvL** [comment]
Thanks for testing - good to see it helped;

**Comment by bhodg22** [comment]
I still just get a black screen on Blinx but thats most likely due to GPU

**Comment by PatrickvL** [comment]
@bhodg22 If your GPU supports native yuv overlays, then maybe that's the cause of black screens while playing intro movies. We'll sort it out eventually
