### ISSUE TITLE
Implement D3DDevice_GetLight

### ISSUE THREAD

**Issue by phire** [Cxbx-Reloaded/Cxbx-Reloaded#288]
Needed by Star Wars: KotOR

~~Note: Currently Cxbx-Reloaded fails on a D3DDevice_SetLight call which it fails to detect. Here is a temporary patch which gets past that point:~~

Edit: Removed the SetLight patch, which is no-longer needed to reproduce this bug.

**Comment by PatrickvL** [comment]
Did https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/291 or https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/292 fix this? If so, then please close this issue.

**Comment by phire** [comment]
No, They both fix the detection of `SetLight`. This bug is about the corresponding `GetLight` function

**Comment by PatrickvL** [comment]
Ah, you're right, thanks. Are you still looking into this issue?

**Comment by LukeUsher** [comment]
We determined that it requires a new HLE Patch, we do not have an implementation for GetLight just yet, but it should be a quick fix

**Comment by jarupxx** [comment]
I implemented PR #319 GetLight function and some missing OOVPAs  added in PR #318.
Testing with these two PRs gets a sound on a black screen. I think it was improved a little.

**Comment by PatrickvL** [comment]
@phire Could you test PR #319 with KoTOR?

**Comment by PatrickvL** [comment]
@jarupxx Thanks for this! Let's hope it works without causing any regressions.

**Comment by phire** [comment]
Yep. KotOR gets a lot further now. Doesn't crash and plays some sound, though no graphics.
