### ISSUE TITLE
False HLE positive in Star wars: KotOR

### ISSUE THREAD

**Issue by phire** [Cxbx-Reloaded/Cxbx-Reloaded#290]
Cbcx-Reloaded detects the function D3DDevice_SetTransform (xdk 5558) at address `0x003462ec` in the pal version of KotOR.

It caught my eye because `0x003462ec` is in the middle of 0xcc padded alignment (all functions in the D3D8 library look to be 16 byte aligned). The function that starts at `0x003462f0` might indeed be SetTransform, but, it's not detected as anything.

Quickly looking through the logs, `HLE: 0x00347CE4 -> D3DDevice_PersistDisplay_5558` might also be a false positive. 

Note, KotOR is actually a xde 5455 game, which we don't have dedicated HLE database entries for.

**Comment by PatrickvL** [comment]
Other 5455 titles are : AFL Live 2004, Bistro Cupid 2, Pro Beach Soccer, Project Zoo, Soulcalibur 2, Spawn: Armageddon, The Simpsons Hit & Run

**Comment by phire** [comment]
This appears to be fixed now, I assume 2b1563becac41710a00e7a635a7ddc48da5e23eb is responsible

**Comment by PatrickvL** [comment]
Thanks for verifying this
