### ISSUE TITLE
TD Overdrive regression, when the intro is playing

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#295]
TD Overdrive regression, while the intro is playing 
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24507171/ba3b7d76-159a-11e7-824e-c0ff3c01bef7.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/882477/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
How far did this title go before? And with what exact commit?

**Comment by furrya** [comment]
@PatrickvL at the end of the third intro Cxbx-Reloaded-20170316
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/24508540/ae4b481c-159e-11e7-8caf-6100be2d2a9a.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/24508538/ae3aa494-159e-11e7-9739-693a939cbf21.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/25540784/24508539/ae3b5aba-159e-11e7-8cb6-93a7df34a596.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/882582/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#164
