### ISSUE TITLE
AMF Extreme Bowling breaks at the menu

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#298]
AMF Extreme Bowling breaks down after the first intro
![screenshot_16](https://cloud.githubusercontent.com/assets/25540784/24510284/bf7d06b6-15a3-11e7-812d-cd1d39fa7713.png)
![screenshot_15](https://cloud.githubusercontent.com/assets/25540784/24510292/c433b8c6-15a3-11e7-8fd1-ae66edd65494.png)
![screenshot_17](https://cloud.githubusercontent.com/assets/25540784/24510300/c8d62760-15a3-11e7-8122-374743001f1e.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/882797/KrnlDebug.txt)
Added [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908353/Xbe.txt)

**Comment by furrya** [comment]
With the 7760a7db (Apr  9 2017) build of Cxbx Reloaded,  the game crashes at the start 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24838598/efdd8b70-1d85-11e7-8117-79defccc93a8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24838597/efdd3832-1d85-11e7-97d9-b64c252342a0.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908290/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
The actual function addresses are missing from the attached log files, so we can't compare what patches where previously used versus which ones are currently used...

**Comment by furrya** [comment]
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908352/Xbe.txt)

**Comment by PatrickvL** [comment]
That's nice of you, but we do need the KrnDebug.txt, but there should be more information in it - I don't known why it's missing from your versions... @LukeUsher Can you explain this?

**Comment by jarupxx** [comment]
According to the attached log file ```0x000A44E0 -> D3DDevice_Swap2_5849``` is missing
I seems that regression by #333 ...

```
Library Name: D3D8
Version: 1.0.5849
Flags: QFEVersion: 0x000F, Retail, Approved
```
The D3D8 library uses 0x0001, but this game uses 0x000F (Intergrated Hotfixes library), so detection will fail. I will investigation this version and solve regression.

**Comment by PatrickvL** [comment]
The regression will be fixed in issue #337

**Comment by jarupxx** [comment]
This regression is fixed in PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/347

**Comment by furrya** [comment]
@jarupxx Great! The progress returned to the previous state of the emulation, as been before the crash  with Cxbx-Reloaded Version 17 fedee8 (Apr 10 2017) build
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24856868/2bb92fc8-1e21-11e7-855b-52aa716f8c1f.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/909684/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
@furrya Thanks for verifying this!

**Comment by furrya** [comment]
Cxbx-Reloaded Version 574d1f89 (Apr 21 2017)
_________________________________________________________

An Progress little more then before
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/946491/KrnlDebug.txt)


![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25270215/c6a43978-26ba-11e7-8f48-f420f8b50f7d.png)

**Comment by furrya** [comment]
The game reaches the menu now with Cxbx-Reloaded Version 394aee6b (Apr 29 2017) 
Also, the intro screens before the menu and in the demonstration video now fully plays as it should be
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25560354/82db0428-2d8c-11e7-91ec-f35e0cc6fa59.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25560317/b411b150-2d8b-11e7-821b-57eedb312b56.png)
______________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966496/KrnlDebug.txt)

**Comment by furrya** [comment]
The debugging window has become more informative now at exception code, that says more information -  Cxbx-Reloaded Version 7ede7ecf (May 2 2017)


![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25608641/af5fbb9e-2f56-11e7-91f8-3c43a5b2985f.png)
_________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/969749/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
@furrya Yes, I thought it might be good to add, now that we have the information in the HLE cache anyway.

But a word of caution : Be advised that the mentioned symbol names only the ones we apply patches to, not all we know about.
So, when the offset is kind-of big, the EIP probably doesn't originates from the mentioned function, but from one right next to it.

Luke told me he will fix this later, when the HLE cache will be populated with all symbols we detect (instead of just the ones that are patched).

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#163
