### ISSUE TITLE
Crash Bandicoot: The Wrath of Cortex: Black screen after Logo

### ISSUE THREAD

**Issue by elfogames** [Cxbx-Reloaded/Cxbx-Reloaded#302]
Crash Bandicoot: The Wrath of Cortex show Universal Logo,then stuck on black screen
![sem titulo](https://cloud.githubusercontent.com/assets/16784631/24552324/60b631ee-15fc-11e7-8761-810c59a47523.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/885785/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/885787/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
This is one of the games I regularly test with/work on (almost daily). From my experimenting there seems to be two issues, one being broken paletted textures, the other being the title hanging for a currently unknown reason.

I'll keep looking into it and update when/if I make a discovery.

**Comment by LukeUsher** [comment]
Obviously not the correct behavoir, but the latest build shows the Loading screen briefly then moves on to this:

![image](https://cloud.githubusercontent.com/assets/740003/24567953/cb9c4498-1657-11e7-9b00-cbc427b68af0.png)

**Comment by bhodg22** [comment]
Also just tried the latest build, I still get the same as before, but once a few days ago it managed to stick on the loading screen with the flashing letters like its supposed to do, but never got further

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#162
