### ISSUE TITLE
The Terminator: Dawn of Fate intro screen after ignoring breakpoint

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#306]
Hit the ignore button and the intro screen appeared after it.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887088/KrnlDebug.txt)

![terminator 1](https://cloud.githubusercontent.com/assets/3212225/24571810/5dde7688-1639-11e7-8244-ce9f4a1d5f25.PNG)
![terminator 2](https://cloud.githubusercontent.com/assets/3212225/24571812/60faee5a-1639-11e7-94ab-530587af5932.PNG)

**Comment by NNX3x** [comment]
![terminator 2-2](https://cloud.githubusercontent.com/assets/3212225/24839537/300314e0-1d22-11e7-94b4-eddf525005fc.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908414/KrnlDebug.txt)

Slightly further progress with this build: Cxbx-Reloaded Version 7760a7db (Apr  9 2017)

**Comment by NNX3x** [comment]
![terminator 2-3](https://cloud.githubusercontent.com/assets/3212225/24935224/5a85a12c-1ee6-11e7-8fe8-d2af2d7c9a30.PNG)

Color is now correct using build 4dc8409a.
 I almost forgot what color the text was since I last played it way back then. Glad to see further progress every day. Excellent work!

**Comment by PatrickvL** [comment]
I'm glad to see that RGB colors are now (mostly) correct, although this fix-up currently only applies to registered textures, not to dynamically created textures (yet).

**Comment by PatrickvL** [comment]
@LukeUsher This shows a spelling error : paramAter !

**Comment by LukeUsher** [comment]
Oh, i just copy/pasted the function names from the function definition, so they must've been incorrect there too.

**Comment by blueshogun96** [comment]
EquivAlent was also misspelled, but I'm no grammar nazi here.

Shogun

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#161
