### ISSUE TITLE
All-Star Baseball 2005 - Flashing in Menu

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#308]
The two screenshots are displayed alternately and blinking appears in the menu.
![asb2005-1](https://cloud.githubusercontent.com/assets/20138367/24572170/632e9762-16b1-11e7-861e-d5d0bfc74644.jpg)
![asb2005-2](https://cloud.githubusercontent.com/assets/20138367/24572172/6516c84c-16b1-11e7-9aab-48d94bd776b7.jpg)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887111/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887113/Xbe.txt)

**Comment by PatrickvL** [comment]
This might haver something to do with the number of backbuffers, or a big in our SetRenderTarget emulation

**Comment by PatrickvL** [comment]
This YouTube video shows how menus should look from 1:16 onward : https://youtu.be/ZLiiVLsKvRc

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#160
