### ISSUE TITLE
Starsky And Hutch - reaches the menu but the graphics are broken

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#309]
Merge PR #307 is merged, Starsky And Hutch reaches the menu but the graphics are broken.
![starsky1](https://cloud.githubusercontent.com/assets/20138367/24572534/6ea68d18-16b4-11e7-9699-0697a9294170.jpg)
![starsky2](https://cloud.githubusercontent.com/assets/20138367/24572536/70ec833e-16b4-11e7-8b71-0e59e762f317.jpg)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887128/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887131/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#159
