### ISSUE TITLE
Log sanitize chars

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#31]
Logging char and char * should generate output that could be pasted directly in code.

Thus, unprintable chars (!isgraph) should be shown using the backsplash escape character and accompanying encoding.

A single char should be surrounded by single quote chars, if a single quote is rendered, it should be be backslash-escaped.

A char * should be surrounded by double quote chars, if a double quote is rendered, it should be be backsplash-escaped.

A char * render should be broken off at some point if no zero terminator is encountered until then.

The same should be done for wchar and wchar*.

**Comment by x1nixmzeng** [comment]
The `_log_sanitize` methods could iterate through `arg` and pass to `hex1`/`hex2`, or a variant which explicitly handles `char`/`wchar_t`

**Comment by PatrickvL** [comment]
This is now done in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/215/commits/b61e2f82fdc6a7d881db8164d5bde967b2c7ea25
