### ISSUE TITLE
Crash Twinsanity

### ISSUE THREAD

**Issue by bhodg22** [Cxbx-Reloaded/Cxbx-Reloaded#310]
Fails much sooner on latest build
![cb regression](https://cloud.githubusercontent.com/assets/5080749/24572886/2a767ae8-16c0-11e7-882f-d8f241282129.JPG)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887170/KrnlDebug.txt)

This build: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/6e250dc345f0c538238070ebf9b933dba348a114
Made it further with a different error message

**Comment by bhodg22** [comment]
Tested today with build https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/2a0a1a35d1cb0ff1c1d32d4ef884c1a2e022bb00 and can say that the regression is fixed, it now almost makes it to menu

**Comment by PatrickvL** [comment]
Could you update this issue with some screenshots, please? That way we can compare the current state with future in improvements.

**Comment by bhodg22** [comment]
Currently shows a splash screen and then you can hear all the intro videos but with a black screen, and fails when its about to load menu
![untitled2](https://cloud.githubusercontent.com/assets/5080749/24991178/5a3f4b7e-205c-11e7-85d4-999915035206.png)

![untitled](https://cloud.githubusercontent.com/assets/5080749/24991181/63ce2692-205c-11e7-92ea-fae4c30fd6a9.png)

**Comment by PatrickvL** [comment]
Ah, still some unswizzling issues I see - either the XGIsSwizzledFormat function isn't located, or 'something else' is wrong. Mm

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#158
