### ISSUE TITLE
Otogi Myth of Demons: black screen

### ISSUE THREAD

**Issue by jackchentwkh** [Cxbx-Reloaded/Cxbx-Reloaded#312]
Title Name: Otogi Myth of Demons
XDK: 5558
Current Status: Crash/black screen.
the title crashed after a certain period of black screen. the log shows an unsupported ADPCM sound stream, and some shaders generated. 
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887307/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887308/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#150
