### ISSUE TITLE
Taz: Wanted - reaches the loading screen

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#313]
This title will bootup with 796b06ebd09c79a02e5fe627840554411e51171e or old commits. Next commit 8640ad77ce232d66131a57e2243055374c7987e7 is won't boot.
I found a missing function ```D3DTexture_LockRect_3925```, so we need to add it to D3D 8.1.0.4432.inl.
However, it seems that it will not boot for another reason.

Logs
[796b06eb.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887467/796b06eb.txt) (successful bootup)
[8640ad77.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887470/8640ad77.txt) (won't boot)
[cf4ff0cc.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887474/cf4ff0cc.txt) (latest commit)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/887475/Xbe.txt)

**Comment by PatrickvL** [comment]
Please describe what happened during successful bootup

**Comment by jarupxx** [comment]
@PatrickvL We look intro movie and loading screens.
![taz1](https://cloud.githubusercontent.com/assets/20138367/24585475/3b9a2b6a-17c6-11e7-8afb-84e8494554c4.jpg)
![taz2](https://cloud.githubusercontent.com/assets/20138367/24585451/aaa6f836-17c5-11e7-90e4-797215cdbe9f.jpg)

**Comment by PatrickvL** [comment]
Commit 8640ad7 did contain a few EEPROM-related bugs that were later fixed.

However, looking at the differences between 796b06eb.txt and cf4ff0cc.txt these OOVPA detections are missing:

```
HLE: 0x0016F830 -> XTL::EmuIDirect3DDevice8_SetTextureState_BumpEnv
HLE: 0x0016F280 -> XTL::EmuIDirect3DDevice8_SetRenderState_CullMode
HLE: 0x0016F2F0 -> XTL::EmuIDirect3DDevice8_SetRenderState_FrontFace
HLE: 0x0016FFB0 -> XTL::EmuIDirect3DDevice8_SetRenderState_StencilCullEnable
HLE: 0x00171820 -> D3D_SetFence_1_0_4134 (XRef)
HLE: 0x00181412 -> CDirectSound_CreateSoundStream_1_0_4361 (XRef)
HLE: 0x00185AC7 -> CMcpxStream_Pause_1_0_4361 (XRef)
HLE: 0x00180475 -> XTL::EmuCDirectSoundStream_Pause
HLE: 0x0018114C -> CMcpxBuffer_SetBufferData_1_0_4361 (XRef)
HLE: 0x001811D8 -> CDirectSoundBuffer_SetBufferData_1_0_4361 (XRef)
HLE: 0x001813F2 -> XTL::EmuIDirectSoundBuffer8_SetBufferData
HLE: 0x001851A2 -> CMcpxBuffer_GetStatus_1_0_4627 (XRef)
HLE: 0x001800CB -> CDirectSoundBuffer_GetStatus_1_0_4627 (XRef)
HLE: 0x001851EB -> CMcpxBuffer_GetCurrentPosition_1_0_4361 (XRef)
HLE: 0x0018011C -> CDirectSoundBuffer_GetCurrentPosition_1_0_4361 (XRef)
HLE: 0x00180648 -> XTL::EmuIDirectSoundBuffer8_GetCurrentPosition
HLE: 0x00185645 -> CMcpxBuffer_Play_1_0_4361 (XRef)
HLE: 0x0018002B -> CDirectSoundBuffer_Play_1_0_4361 (XRef)
HLE: 0x001805F0 -> XTL::EmuIDirectSoundBuffer8_Play
HLE: 0x00180EFB -> CDirectSound_SetDistanceFactorA_1_0_4531 (XRef)
HLE: 0x001808BF -> CDirectSoundVoice_SetMaxDistance_1_0_4432 (XRef)
HLE: 0x00180A8D -> CDirectSoundBuffer_SetMaxDistance_1_0_4432 (XRef)
HLE: 0x001808F2 -> CDirectSoundVoice_SetMinDistance_1_0_4432 (XRef)
HLE: 0x00180AE3 -> CDirectSoundBuffer_SetMinDistance_1_0_4432 (XRef)
HLE: 0x00180B39 -> CDirectSoundBuffer_SetPosition_1_0_4627 (XRef)
HLE: 0x00180C83 -> XTL::EmuIDirectSoundBuffer8_SetPosition
HLE: 0x00180977 -> CDirectSoundVoice_SetVelocity_1_0_4627 (XRef)
HLE: 0x00180BA0 -> CDirectSoundBuffer_SetVelocity_1_0_4627 (XRef)
HLE: 0x00180CB8 -> XTL::EmuIDirectSoundBuffer8_SetVelocity
HLE: 0x00184354 -> DirectSound_CMcpxVoiceClient_SetFilter_1_0_4627 (XRef)
HLE: 0x00180925 -> CDirectSoundVoice_SetPosition_1_0_4432 (XRef)
HLE: 0x0020113C -> XID_fCloseDevice_1_0_4361 (XRef)
HLE: 0x0016F2F0 -> XTL::EmuIDirect3DDevice8_SetRenderState_FrontFace
HLE: 0x0016FFB0 -> XTL::EmuIDirect3DDevice8_SetRenderState_StencilCullEnable
HLE: 0x0016F280 -> XTL::EmuIDirect3DDevice8_SetRenderState_CullMode
HLE: 0x00171820 -> D3D_SetFence_1_0_4134 (XRef)
HLE: 0x00181651 -> CDirectSound_CreateSoundBuffer_1_0_4627 (XRef)
HLE: 0x00180F5D -> CDirectSound_SetI3DL2Listener_1_0_4432 (XRef)
HLE: 0x00180E13 -> DirectSound_CDirectSound_SetAllParameters_1_0_4928 (XRef)
HLE: 0x0017FD22 -> CDirectSoundVoiceSettings_SetMixBins_1_0_4432 (XRef)
HLE: 0x0018089B -> CDirectSoundVoice_SetFrequency_1_0_4627 (XRef)
HLE: 0x00180A3F -> CDirectSoundBuffer_SetFrequency_1_0_4627 (XRef)
HLE: 0x0018482D -> CMcpxVoiceClient_SetVolume_1_0_4627 (XRef)
HLE: 0x00180B39 -> CDirectSoundBuffer_SetPosition_1_0_4627 (XRef)
HLE: 0x00180C83 -> XTL::EmuIDirectSoundBuffer8_SetPosition
HLE: 0x00180925 -> CDirectSoundVoice_SetPosition_1_0_4432 (XRef)
```

**Comment by furrya** [comment]
Cxbx-Reloaded Version 9173d4ab (May  3 2017) - the game boot'up again but crashes at loading screen
_____________________________________________________________________

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25692389/15b63562-30dd-11e7-99a9-306836cee0df.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25692392/15b9e00e-30dd-11e7-9572-faa4e60b9efb.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25692390/15b723a0-30dd-11e7-8517-7d45e394b340.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25692391/15b73354-30dd-11e7-9951-11a0fb99bd10.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/975310/KrnlDebug.txt)

**Comment by jarupxx** [comment]
PR #434 boot'up again.
The game now crashes after get this logs.
```
[0x10DC] EmuD3D8: EmuIDirect3DResource8_Register
(
   pThis               : 0x829A22C0 (->Data : 0x00000100)
   pBase               : 0x829A2280
);
[0x10DC] EmuIDirect3DResource8_Register : Creating VertexBuffer...
[0x10DC] MemoryManager.cpp: QueryAllocationSize(
   addr                 : 829A2380
);
[0x10DC] MemoryManager.cpp: QueryAllocationSize returns 47185920
[0x10DC] EmuMain: Received Exception (Code := 0xC0000005)

 EIP := 0x6D624A50(=XID_fCloseDevice+0x6d423914)
 EFL := 0x00010206
 EAX := 0x00000000 EBX := 0x00000008 ECX := 0x00000000 EDX := 0x0002D447
 ESI := 0x84000000 EDI := 0x0BE1ECC0 ESP := 0x088FFB10 EBP := 0x088FFDA0
 CR2 := 0x00000000

  0:          0x6D624A50
  1:          0x00143C62

[0x10DC] EmuMain: Aborting Emulation
```
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/975485/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#149
