### ISSUE TITLE
XIII [XDK 5558] [ID 55530009] - the game crashes at loading screen

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#314]
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/24583777/3a7a5366-1791-11e7-8639-cdd35b4ecb1a.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/24583778/3aa0b59c-1791-11e7-8c37-ee952c7ba1cf.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888133/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888134/Xbe.txt)

**Comment by jarupxx** [comment]
Actually, title is XIII.
Okay, this title uses XDK with Intergrated Hotfixes,
It looks HLE patch pattern is different from a general title, so Cxbx-Reloaded can not detect it correctly. Also missing of DXBX. But I edit a Library Version, DXBX detect lots of HLE patch :)

It might be improved by adding the detected HLE patch.

Dxbx log - Edit D3D8 Library version is 5787 [DxbxKrnl Xiii (1481).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/919563/DxbxKrnl.Xiii.1481.txt)
Difference from Cxbx-Reloaded [diff.xlsx](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/919568/diff.xlsx)

**Comment by furrya** [comment]
The game has regression now - crashes at second splash scree. Has not  reaches the loading screen as  in earlier versions. Cxbx-Reloaded Version 8c9f308f (May 5 2017)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980691/KrnlDebug.txt)

![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25769957/b7d88c1a-3262-11e7-9000-2dc57221f000.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#148
