### ISSUE TITLE
Xheretic  is working only when Debug console is open

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#315]
Xheretic - is working only when Debug Kernel console is open 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24583876/5eddda68-1794-11e7-8cd9-34757d66f72b.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24583877/5eddf6c4-1794-11e7-8cbb-e5d9ecf47464.png)

but when I disabled console, exception error is appears
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888143/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888144/Xbe.txt)

**Comment by PatrickvL** [comment]
It'd be interesting to compare the logs of both runs, to see where the console influences emulation (which it shouldn't of course)

**Comment by furrya** [comment]
@PatrickvL  Перевести

 Here it is. I just copied and pasted log from the console  window in file 
[KrnlDebugConsole.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888203/KrnlDebugConsole.txt)

**Comment by PatrickvL** [comment]
Oh sorry, I was taking about a comparison between kernel log files

**Comment by furrya** [comment]
@PatrickvL   I See. I just copied that log  from kernel log window, when emulator shows graphics, unlike first log - when console was disabled. Sorry me if I misunderstand process

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#147
