### ISSUE TITLE
consolidate OOVPA databases

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#317]
One thing I feel we should already have done, and thus should do as soon as possible, is consolidating all versions of an OOVPA database into one.
* This makes them much easier to maintain.
* It would reduce the required storage capacity.
* It would prevent omissions (forgotten OOVPA mentions).
* It's more compact; Just one line per OOVPA, using a variable number of arguments specifying all available versions of an OOVPA.
* Also, mismatches between versions would disappear, as the entire line would be marked PATCH, XREF or DISABLED.

Only the LTCG wouldn't fit this setup, although those could be specified as a separate registration line. (Ultimately though, LTCG will probably be removed, making place for LLE GPU)

For this to work, we must derive a subset at runtime, consisting only of OOVPA applicable to the library version being scanned. This is a one time operation, as afterwards the subset can be used, so this shouldn't cost more scanning time than what we're experiencing with the current code.

**Comment by jarupxx** [comment]
I agree. The current OOVPA database is difficult to grasp the omission for each version.
> It's more compact; Just one line per OOVPA, using a variable number of arguments specifying all available versions of an OOVPA.

By checking the arguments, we will identify forget OOVPAs between versions, which makes maintenance easier.

**Comment by PatrickvL** [comment]
A complete example showing how this would look for XNet :
```
// ******************************************************************
// * XNet
// ******************************************************************
OOVPATable XNet[] = {

	REGISTER_OOVPAS(XNetStartup, PATCH, 3911, 4627), // same as xonline 4361
	REGISTER_OOVPAS(WSAStartup, PATCH, 3911, 4627), // same as xonline 4361
	REGISTER_OOVPAS(XnInit, XREF, 3911, 4627),
	REGISTER_OOVPAS(XNetGetEthernetLinkStatus, PATCH, 3911),
	REGISTER_OOVPAS(socket, EMUTHIS, 4627),
	REGISTER_OOVPAS(connect, EMUTHIS, 4627),
	REGISTER_OOVPAS(send, EMUTHIS, 4627),
	REGISTER_OOVPAS(recv, EMUTHIS, 4627),
	REGISTER_OOVPAS(ioctlsocket, EMUTHIS, 4627),
};
```
Also, once this is done for all libraries, all current aliassing defines (like `#define Direct3D_CreateDevice_5233 Direct3D_CreateDevice_5028`) can be removed, as they are no longer neccessary.

**Comment by PatrickvL** [comment]
Before this can be done, issue #323 (removal of ALIAS OOVPA registrations) should be done, as otherwise it'd be dificuly to fold ALIAS-es into the above proposed registration of multiple OOVPA versions per registration line.

**Comment by jarupxx** [comment]
I was thinking an example. Specify version to be used as argument.
```
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 3925, {3925, 4034, 4134}),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4361, {4361}),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4627, {4627, 5558, 5788, 5849}),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 5028, {5028, 5233, 5344}),
```

**Comment by LukeUsher** [comment]
Do we even need the registration lines, or even the separation between XRefs and other symbols?

For the OOVPA's, is there really a reason why we cannot just iterate through the OOVPA tables that we have for each library directly?

Also about XRefs: My thoughts here are that any symbol could potentially be an XRef for another symbol, weather or not it is a patch, perhaps we should consider being smarter about how we manage XRefs rather than using a fixed array.

**Comment by PatrickvL** [comment]
@LukeUsher All OOVPA declarations do have to be accessible somewhere, so yeah, there has to be some sort of 'registration'.

XRefs are actually ambiguous, as there are:
1. OOVPA registered as an XREF, which indicates there's no patch for it (I'm aware of your refactoring branch that will lookup patches via exports, which would remove the distinction between an PATCH versus XREF registration)
2. XREFs ID's, indicating unique symbols (no matter if they have patched or not)
3. XREF registration markers in the header of OOVPA, which associates an OOVPA with an XREF ID, which (if present) is used to fill an array with the detected address of an OOVPA, indexed by XREF ID
4. XREF verification in the OOVPA (value,offset)-tuples, used to check if an XREF is valid (if not yet located, symbol detection for this OOVPA has to repeat the address detection run again at a later time)

As for iterating over all OOVPA : No, we can't. We've seen that even a change in the order of OOVPA's in a library can influence the outcome of the function address search runs, so it's important to keep this intact. Also, it's important NOT to search for versions that wouldn't appear in the XBE anyway, as those would only raise the chances of incorrect detection results. And obviously, we can't leave any OOVPA out, as those wouldn't be detected anymore.

@jarupxx  : I don't understand why you would duplicate version numbers - it doesn't make sense to me.
Taking your example, I would like to see :
```
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 3925, 4034, 4134),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4361),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4627, 5558, 5788, 5849),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 5028, 5233, 5344),
```
(Although somehow I'm having a hard time creating a macro that will compile this syntax.)

**Comment by jarupxx** [comment]
```
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 3925, 4034, 4134),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4361),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 4627, 5558, 5788, 5849),
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 5028, 5233, 5344),
```
It is exactly like this. Does we need that use force OOVPA per version?
My thoughts that most functions hit only one version par OOVPA, However few functions hits multiple versions of OOVPA.

**Comment by PatrickvL** [comment]
Oh, sorry, I wasn't paying attention, what I meant was:
REGISTER_OOVPAS(Direct3D_CreateDevice, PATCH, 3925, 4361, 4627, 5028);
Just the versions that are different

**Comment by PatrickvL** [comment]
Most of this issue  has been done in https://github.com/PatrickvL/Cxbx-Reloaded/tree/WIP__HLEDB/src/CxbxKrnl/HLEDataBase (see the *.OOVPA.inl files there).
This branch doesn't run very well though, symbols are not located at their correct location.
This must be fixed such that symbol-detection results become equal to, or better then, results from master.

**Comment by jarupxx** [comment]
@PatrickvL One of the reasons for bad results is related to a new XDK is related to failing to call old version of OOVPA.
Let's see Direct3D_CreateDevice. This function is 5558 or later and uses the generic 3911 version. However, it seems that it is scanning use 5344.

**Comment by PatrickvL** [comment]
@jarupxx Could you please paste a link here to the offending source code line?

**Comment by jarupxx** [comment]
In this case, redirect 5558 to 3911 to get good results.

https://github.com/PatrickvL/Cxbx-Reloaded/blob/WIP__HLEDB/src/CxbxKrnl/HLEDataBase/D3D8.1.0.3925.inl#L38

// ******************************************************************
// * Direct3D_CreateDevice
// ******************************************************************
OOVPA_NO_XREF(Direct3D_CreateDevice, 3911, 18) // Also for 4361, 4627, 5558, 5659, 5788, 5849, 5933 (NOT 5344!)
**#define Direct3D_CreateDevice_5558 Direct3D_CreateDevice_3911**

https://github.com/PatrickvL/Cxbx-Reloaded/blob/WIP__HLEDB/src/CxbxKrnl/HLEDataBase/D3D8.OOVPA.inl#L62

REGISTER_OOVPAS(Direct3D_CreateDevice, 3911, 4432, 5028, 5233, 5344, **5558**), // Was 3925, 4361, 4627

**Comment by PatrickvL** [comment]
Ah, I see what you mean. Judging by the comment I added, the 3911 should be aliassed at least for all versions to which it applies, resulting in :
```
#define Direct3D_CreateDevice_4361 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_4627 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_5558 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_5659 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_5788 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_5849 Direct3D_CreateDevice_3911
#define Direct3D_CreateDevice_5933 Direct3D_CreateDevice_3911
//[...]
REGISTER_OOVPAS(Direct3D_CreateDevice, 3911, 4361, 4432, 4627, 5028, 5233, 5344, 5558, 5659, 5788, 5849, 5933);
```

The same verification should be done for all OOVPA that have more than one version....

**Comment by PatrickvL** [comment]
Here the commit : https://github.com/PatrickvL/Cxbx-Reloaded/commit/6e90f261feab3d71f4bb1f208e19005971db9125

**Comment by PatrickvL** [comment]
There's two approaches possible for this:

1. Review all OOVPA registrations manually
2. Compare the scanning results between this branch and master

I think option (2) could be less work than option (1), although we have to be carefull about not to dismiss a difference too quickly. This entire branch is meant to **improve** scanning results, so some changes might actually be better than before

**Comment by PatrickvL** [comment]
@jarupxx How would you approach this? And what do you think of the consolidated OOVPA tables?

**Comment by jarupxx** [comment]
I think option (1) is best. Option (2) may not complete due to lack of test cases.

**Comment by PatrickvL** [comment]
Wow, that will be a lot of work - there are 625+ REGISTER_OOVPAS to review!!!

**Comment by PatrickvL** [comment]
@jarupxx looking back at the above CreateDevice OOVPA, you right by the way; Anything from 5558 and up will use the same (3911) OOVPA anyway, so could be left out.

**Comment by PatrickvL** [comment]
Work on this is being done by @RadWolfie and @jarupxx here : https://github.com/RadWolfie/Cxbx-Reloaded/commits/WIP_HLEDB_v2 (based on my work [here](https://github.com/PatrickvL/Cxbx-Reloaded/commits/WIP__HLEDB))

**Comment by jarupxx** [comment]
I have completed all verifyed of REGISTER_OOVPA registered in D3D8, XAPILIB, XGRAPHC, XNet, XOnline (PR #691 etc).
However, there were functions that could not be found because test cases were not found. They moved to the provisional registered section.

**Comment by PatrickvL** [comment]
Now that HLE DB V2 is merged, this work is completed. Closing.
