### ISSUE TITLE
Battlestar Galactica. Flickering cutscenes slightly more visible.

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/Cxbx-Reloaded#322]
Thanks to jarupxx's [cc9d474](url=https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/318/commits/cc9d4746bd99d2645903bf2ec988f2556b4c3383) (Added the SelectVertexShader/SetTileNoWait. Apr 1, 2017?) in PR #318 (Apr 03, 2017?) I can now see some contents of the cutscene after you start the initial mission which happens after you go through several menus though it flickers a lot. It was tricky to try to capture the relevant shots.

But there is barely any improvement to the logo and intro cutscenes before you enter the main menu, which are still mostly white screen. Though I could see the logo better.

![apr-03-2017_ flickering-logo_seen-better](https://cloud.githubusercontent.com/assets/18428108/24620728/0dc8dbf6-18e2-11e7-9ffe-401c6c1229b8.png)
![apr-03-2017_flickering-mission-cutscene_seen-better](https://cloud.githubusercontent.com/assets/18428108/24620335/9bd4cfec-18e0-11e7-9dac-991c040c0b9e.png)
[KrnlDebug_(2017-Apr-04).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/890775/KrnlDebug_.2017-Apr-04.txt)
[Xbe_(2017-Apr-04).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/890776/Xbe_.2017-Apr-04.txt)

**Comment by BenNottelling** [comment]
I noticed the intro was flickering in Namco Museum as well, maybe it's related?

**Comment by PatrickvL** [comment]
I've noticed flickering in this title to, albeit weeks ago. This too might be related to the fact we don't emulate number of backbuffers

**Comment by bhodg22** [comment]
Namco museum flickering can be fixed with software rendering, maybe try it in this title too?

**Comment by PatrickvL** [comment]
@bhodg22 Thanks for this remark, it might help us finding the cause

**Comment by furrya** [comment]
For me, I just getting the error in random places with software video rendering , though flickering disappared
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24642409/244be502-1942-11e7-9423-5c70c2f7bef7.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/892107/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
Software rendering does not exist in Cxbx-Reloaded in the traditional sense, all that menu option does is use Microsoft's software directx implementation which is not designed for everyday use. There is nothing we can do to fix bugs with that option, it will never work properly. We should probably remove it

**Comment by ObiKKa** [comment]
Pretty worrying issues after PatrickVL's PR #321 (D3DFormat conversion refactoring). Both Battlestar Galactica and Jet Set Radio Future crashed after going through a few screens.
I see garbled developer's logo in BG before it crashes. Now, let's find out why.

![apr-05-2017_ 2nd-test_d3dformat-conversion-refactor_garbled-logo](https://cloud.githubusercontent.com/assets/18428108/24672345/b254954a-19b7-11e7-90b2-2208a480e8fb.png)

![apr-05-2017_ 2nd-test_d3dformat-conversion-refactor_crash](https://cloud.githubusercontent.com/assets/18428108/24672349/b9a3b5d8-19b7-11e7-90ff-90c779578ae8.png)

[KrnlDebug_(2017-Apr-05).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/894123/KrnlDebug_.2017-Apr-05.txt)

**Comment by LukeUsher** [comment]
Good spot, I thought I'd broke something in my branch... Try the latest master

**Comment by ObiKKa** [comment]
I re-downloaded the latest master (maybe the PR commit you refer to) again (after seeing first two of three comments from Patrick). After a crash or two JSRF does get in-game like before. But BG still exhibits the same problem.

**Comment by PatrickvL** [comment]
Ouch, it seems I didn't try hard enough to avoid differences. Sorry about that. Rest assured, it'll get sorted out.

**Comment by PatrickvL** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/68dedb114e5de9491f04db93eb5301a3c80f9ac8 should fix this issue

**Comment by ObiKKa** [comment]
3 old videos 6.5 years ago showing this game running on DXBX:

- Windowed mode - In-game graphics with the black background are similar to those experienced in CXBX Reloaded currently.
https://www.youtube.com/watch?v=qPQSbRtNAY8

- Full Screen mode - Shows real in-game graphics, including the entire background, ship models, effects, lighting, etc.
https://www.youtube.com/watch?v=wTuazZoZhUo
https://www.youtube.com/watch?v=jRa6fJvhmg0

**Comment by furrya** [comment]
Battlestar Galactica with "hardware video mode' at 9e42bc55176eba25688ff176104b1ffd1e9548e5 build of Cxbx Reloaded
![battlestar galactica](https://cloud.githubusercontent.com/assets/25540784/24874060/3d099ff0-1e5e-11e7-8994-760e610c258d.jpg)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/910906/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
Yes! That looks like the new color conversion is working!

**Comment by ObiKKa** [comment]
Yah! I tested it and confirmed the same result as furrya with the "Hardware Video Mode" option toggled on.
Seriously, though, the resolution selection system's execution is a mess as what's displayed on-screen are pitched to the left side or top-left corner of your monitor's screen. If you toggle that Video Mode on (or even off to keep your windowed mode) with the default resolution then it may be stretched on your widescreen monitor.

**Comment by LukeUsher** [comment]
I agree, the resolution selection system is a mess. A lot of Cxbx code hardcodes 640x480 viewport values, which is likely the main reason the screen is stuck in top-left in higher resolutions

**Comment by ObiKKa** [comment]
After that bunch of 3 PRs (383-385, especially PR #383 [Overlay fixes]) I tried Hardware Video mode in BG and could only see the black background in-game like in the normal mode.
But the 2nd long FMV which is after the developer's logo intro looks like it is sized correctly within the windowed mode. Sure it flickers a lot but you can see more of it. However at times it seems to be unskippable like I cannot press any button to enter the main menu.
Also, even it can be hard to go there - game can freeze on a black screen in-between. So probably try to press any button quickly when the first two intro videos show up. But so far in my multiple tests I have only been able to enter both the menu and in-game once.

![apr-21-2017_ 3rd-test_2nd-long-fmv](https://cloud.githubusercontent.com/assets/18428108/25254559/849a9352-2669-11e7-98ac-e46924732f1f.png)

[KrnlDebug_(2017-Apr-21_Black-screen-Freeze)_Trimmed.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/945600/KrnlDebug_.2017-Apr-21_Black-screen-Freeze._Trimmed.txt) (Normal windowed mode)

**Comment by PatrickvL** [comment]
The overlay flickering is probably caused by the fact that overlays are actually updated at the wrong time. They should be updated when swapping back and front buffers during vsync. I'm contemplating to fix that, but there's a more urgent matter to fix first: many glitches in (presumably indexed) vertex drawing. After a lot of research this seems to be related to the switch to the new memory manager that allowed Xbox-like contiguous allocations at the same addresses as which the Xbox uses. Nothing wrong with that, but it looks like a side-effect is that we're now much more vulnerable to errors in D3D resource data address reconstruction, because Cxbx mixes up Xbox data and native data pointers. This mixup causes so many problems - it isn't funny anymore. Getting this right requires a big refactoring I'm afraid

**Comment by ObiKKa** [comment]
Nope, as with Jet Set Radio Future (Turok does work up till before the loading point of a game mission, which regressed recently.), something's the issue here. A different error message would pop up after a few intro splash screens (Maybe not the developer's logo) were shown.

![2017-may-03 _error-box_01](https://cloud.githubusercontent.com/assets/18428108/25628733/a4783f22-2faa-11e7-91f2-e59905770bda.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#143
