### ISSUE TITLE
Alien Vs. Predator - exception code error on the second intro screen

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#332]
I have an  exception code error on the second intro screen
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24835044/eb9ac622-1d30-11e7-916e-84865a25df5f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24835045/eb9b9034-1d30-11e7-834c-713e92716aac.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/907994/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/907993/Xbe.txt)

**Comment by ObiKKa** [comment]
Which game is this one? The only Xbox original game I can find from the Alien vs. Predator franchise is _Aliens Versus Predator: Extinction_. Is this a port of the original Windows PC game, which it can't be. Perhaps it was emulated over the Xbox system?
https://www.gamefaqs.com/xbox/917829-aliens-versus-predator-extinction
https://en.wikipedia.org/wiki/Aliens_Versus_Predator:_Extinction

The original 1999 Windows game:
https://en.wikipedia.org/wiki/Aliens_versus_Predator_(1999_video_game)

**Comment by furrya** [comment]
@ObiKKa  Yes this is an unofficial port of the PC version of Aliens Vs Predator to the Xbox. 1999  year

**Comment by BenNottelling** [comment]
Is it this
https://m.youtube.com/watch?v=eWjg8gCuNdE

**Comment by hotzenplotz3000** [comment]
goes in game now
fully playable so far
Tested with build 3da1a354

![capture20170726212706551](https://user-images.githubusercontent.com/30478365/28640157-2342cd26-724b-11e7-9b58-98379b83243c.png)
![capture20170726212724669](https://user-images.githubusercontent.com/30478365/28640159-25aae17a-724b-11e7-9a3d-5ef437ac2dcf.png)
![capture20170726213004504](https://user-images.githubusercontent.com/30478365/28640279-7c3a3fae-724b-11e7-805e-90f48c636f66.png)

**Comment by PatrickvL** [comment]
Great news that is! Thanks for testing!

**Comment by LukeUsher** [comment]
Closing this as it's no longer an issue.
Great news!
