### ISSUE TITLE
Gauntlet Dark Legacy. In-game in latest builds (April 2017).

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/Cxbx-Reloaded#335]
Thanks to PR #331 (Apr 8-9, 2017?) & #334 (Apr 9-10?) I can see several stages of intro screens, a long and lovely cinematic movie, the menus and finally in-game graphics in its currently broken status. Others are welcome to test this game in the future.

### Interesting notes:
- The intro movie (CG-animated) is rendered on only a quarter of the screen at the moment. The same is true with another movie when you exit in-game back to the main menu.
- The tutorial cutout screens in-game are garbled so I cannot read anything, therefore do not know what to do in the first level.
- Many effects and shading stuff are missing (Shown as garbled). The menus are not fully coloured and look a bit corrupted.

![2017-04-10_ 01_boot](https://cloud.githubusercontent.com/assets/18428108/24840035/204eca3a-1da9-11e7-86e4-c168f0e8931a.png)
![2017-04-10_ 02_intro-movie](https://cloud.githubusercontent.com/assets/18428108/24840036/20542656-1da9-11e7-9229-ec2d0e5554b9.png)
![2017-04-10_ 03_title-screen_in-movie](https://cloud.githubusercontent.com/assets/18428108/24840046/42fb99e6-1da9-11e7-8199-ec2224ef123b.png)
![2017-04-10_ 04_title-screen](https://cloud.githubusercontent.com/assets/18428108/24840047/42fdb910-1da9-11e7-8087-2020e13cb7df.png)
![2017-04-10_ 05_start-game-profile](https://cloud.githubusercontent.com/assets/18428108/24840048/4302c9c8-1da9-11e7-816c-f0ed30d5d14f.png)
![2017-04-10_ 06_in-game_tute-screens_broken](https://cloud.githubusercontent.com/assets/18428108/24840049/4304e910-1da9-11e7-8ef6-33261458b453.png)
![2017-04-10_ 07_in-game](https://cloud.githubusercontent.com/assets/18428108/24840050/43058546-1da9-11e7-8192-8b02c1c82d76.png)

I tried to get in-game as quickly as possible on the second go to keep the kernel file small but then had to trim off much of the fluff.
[Xbe_(2017-04-10).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908464/Xbe_.2017-04-10.txt)
[KrnlDebug_(2017-04-10_Trimmed).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/908465/KrnlDebug_.2017-04-10_Trimmed.txt)

**Comment by ObiKKa** [comment]
Ah, that was then (6.5 years ago). Wow they look virtually similar! 
http://shogun3d-cxbx.blogspot.com.au/2010/11/gauntlet-dark-legacy.html

**Comment by BenNottelling** [comment]
It's good they are similar, that means the emulator hadn't really made any backwards steps

**Comment by PatrickvL** [comment]
Dxbx, back in 2010 : https://www.youtube.com/watch?v=NWlmKP74LuY

**Comment by PatrickvL** [comment]
To get menu's and in game graphics in a table state would require better support for palletized textures then what we have right now. The Dxbx run I linked to above, used an approach that we can strife for in Cxbx too: conversion of textures at drawing time (as that's the most suitable moment to combine active palettes with active textures)

**Comment by ObiKKa** [comment]
Yes. I've just now taken a look at that channel's old recorded DXBX videos from nearly 6.5 years ago.
Here's also the intro, menu and game video of that game:
https://www.youtube.com/watch?v=27mnsM-n-GU

**Comment by PatrickvL** [comment]
Yeah, it's my channel so I know about that ;)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#142
