### ISSUE TITLE
XInput support?

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#336]
IMO, this would be a quick solution for those with Xbox Gamepads.  As it was already noted, the POV hat just doesn't work, and sadly it has been that way for years.  I tried using the keyboard for the dpad but it still didn't work.

It's not exactly a high priority, just an idea.  Of course, I know that there are other gamepads out there besides the Xbox brand, but that would alleviate some need for additional setup.  Just my two cents.

Shogun.

**Comment by CakeLancelot** [comment]
So essentially #156 ? Xinput would make the most sense with the emulator but a nice longer term goal might be something more universal. 

Currently with Cxbx-Reloaded I can only use a logitech usb controller, my xbox 360 adapter doesn't work properly - so I would be all for this.

**Comment by blueshogun96** [comment]
Oops, missed that one.  I need to read the back logs a bit more carefully.  So on that note, I wanted to mention that XInput could simply be an option to check (enable/disable) because I also like my PS4 controller.  When I get home I can play around a bit with this.

Shogun.

**Comment by CakeLancelot** [comment]
Fixed by f879c40 ?

**Comment by PatrickvL** [comment]
Could be. Let's leave it to @LukeUsher to close this (and/or #156)

**Comment by LukeUsher** [comment]
This issue can be closed, as XInput support now exists.
