### ISSUE TITLE
Issue by merged ALIAS OOVPA with multiple patterns into one #333

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#337]
@Furrya reports that #333 a regression will occur in AMF Extreme Bowling (5849) (https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/298#issuecomment-292793346).
This suggests that the same issue will be caused in newer titles.

I will investigation this version and solve regression.

**Comment by jarupxx** [comment]
This issue is fixed by PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/347. If we pass the test we can closed this.

**Comment by PatrickvL** [comment]
This fix is verified - see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/298#issuecomment-292906839
