### ISSUE TITLE
Dead or Alive Ultimate 1: loading screen

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#339]
![cxbx 2017-04-08 18-19-29-80](https://cloud.githubusercontent.com/assets/5076651/24842856/c80d4f2e-1d51-11e7-944a-6e3a7e4bb5c4.png)

A loading screen shows up with some barely visible textures.  It crashes soon afterwards.  If you have DOA Ultimate, then run DOA1.xbe directly and you should get this.  Also, it's interesting how the game defaults to 480p.

Shogun

**Comment by ergo720** [comment]
In 3ca1a354 the game doesn't show anything anymore, cxbx stops emulating shortly after launching the title without any errors. I have tested Doa1.xbe, DOA2.xbe and default.xbe and the behavior is the same.

[Default.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174573/Default.txt)
[Doa1.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174575/Doa1.txt)
[Doa2.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174574/Doa2.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#140
