### ISSUE TITLE
AeroX2: Repro-ing the unresponsive controller issue, and the 8-bit texture thing too.

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#342]
As some of you have already noticed, Cxbx has a few games that do not respond to controller input for some reason.  I haven't been able to find out why, nor did I have any examples that repro this issue in code that was readily available to me... that is until now.

I could be wrong about this (I'll have to setup my reto gaming/dev machine again to find out) but it looks like Cxbx doesn't like it when XInput functions are called from other threads.  Maybe that's a possibility, I'm not sure as I haven't had a chance to verify and/or prove it.  But the code to AeroX2 (an old 16-bit DOS mini game I ported just for fun about 5 years ago) is linked below, so if you have your XDK setup, have at it.

http://code.shogun3d.net/projects/aerox2.rar

Also, are we using the luminance texture format for 8-bit textures again?  

![aerox2_cxbx](https://cloud.githubusercontent.com/assets/5076651/24844991/632a53f6-1d63-11e7-9a54-cfa8707bcb5d.PNG)

Forgive me for being out of the loop, but I thought someone had already fixed it.

Shogun

**Comment by PatrickvL** [comment]
If I'm not mistaken, there are only four 8 bit texture formats: alpha only, luminance only, alpha and luminance, and palletized. The above screenshot looks like a palletized texture shown as luminance.

**Comment by blueshogun96** [comment]
Right, I meant to specify on the palletization.  For that game, I used a 512x512x8 (D3DFMT_P8) texture to simulate mode X for DOS.

Shogun

**Comment by PatrickvL** [comment]
Pallet textures are only converted to RGB from within `EMUPATCH(D3DResource_Register)`, not in the three `CreateTexture` patches, so that's probably why you're seeing grayscale, as all those choose L8 as fallback

**Comment by blueshogun96** [comment]
I'm curious, why was XGetDeviceChanges disabled?

Shogun

**Comment by LukeUsher** [comment]
Investigating it's functionality it didn't actually looks like it was required. When we did have it patched, the behaviour was quite broken. It seems that Cxbx was reporting a new controller connected on every call for example.

**Comment by blueshogun96** [comment]
Oh really?  I thought it was supposed to report one controller for the duration of the emulation.  Never had any issues with it that I knew of.  Since it didnt get called I assumed that's why things were breaking.  At least, in my code that's why.

Shogun.

**Comment by LukeUsher** [comment]
Just a note: The controller issue also effects Capcom Classics Collection (it hangs on the title screen, waiting for the user to Press Start)

**Comment by PatrickvL** [comment]
@blueshohun96 It'd be better if the second issue you reported (about incorrectly rendered P8, falling back to L8) appeared as a storage issue in our issue tracker, to avoid confusion.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#138
