### ISSUE TITLE
Myst III: Ingame, but a bit stuttery

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#343]
![mystiii](https://cloud.githubusercontent.com/assets/5076651/24849517/055ac170-1d81-11e7-99f6-735bde5377e0.PNG)

So far, not looking too bad.  Although I had to manually copy some files to the proper emu disk folder to get it to work (I didn't look too deep into the issue), it goes ingame for the first room, but then gets stuck on a black screen when trying to progress.  There's some missing textures (the skybox textures randomly disappear), and some stutter sound.

Shogun

**Comment by JayFoxRox** [comment]
>  Although I had to manually copy some files to the proper emu disk folder to get it to work (I didn't look too deep into the issue)

How is this not documented? Without such information this is merely a screenshot of a broken game.
Ideally the game-compatibility issues should contain information about the lacking features and applied patches.

**Comment by PatrickvL** [comment]
@blueshogun96 Could you please describe the steps you took, and the settings you used, so you got this game this far?

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#137
