### ISSUE TITLE
Silent Scope Complete [XDK 5558]: Menus and dirty disc error

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#344]
![cxbx 2017-04-10 00-16-54-95](https://cloud.githubusercontent.com/assets/5076651/24850281/45968898-1d84-11e7-8379-c2604fba9624.png)

![cxbx 2017-04-10 00-16-24-84](https://cloud.githubusercontent.com/assets/5076651/24850282/4597b74a-1d84-11e7-9d06-c9d5e00d731d.png)

In order for the menus to work, I had to add signatures for IDirectSoundBuffer_PlayEx and DirectSound::CDirectSoundBuffer::PlayEx for it to work.  When trying to select a game, the cursor continuously tries to move left, so I had to time things just right to select Silent Scope 1.

SS1: Gives me a dirty disc error.  I attached a KrnlDebug.txt for anyone who wants to see it.
[KrnlDebug2.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/909280/KrnlDebug2.txt)

SS2: Does nothing AFAICT.  Fraps shows that there is a drawing loop going, so it could be another dirt disc error for all I know.

SS3: Crashes on one of Cxbx's internal functions at random points (see IoCreateFile).  I also added D3D::CDevice::KickOff (an internal function called by D3DDevice_KickPushBuffer(), the Xbox version of glFlush()...) in order to get to this point.

Shogun

**Comment by literalmente-game** [comment]
@blueshogun96 can you provide me the build you've used to reach the menu ? I want to confirm the reason behind one specific error

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#136
