### ISSUE TITLE
Investigate partially disabled OOVPA

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#346]
A few OOVPA are registered as a PATCH for almost all versions but DISABLED for one specific version - this seems inconsistent, so these require an investigation.

These OOVPA are :
* D3DVolumeTexture_LockBox
* D3DCubeTexture_LockRect
* XGSwizzleBox
* XGWriteSurfaceOrTextureToXPR

**Comment by nickolesjones** [comment]
this wont work either unless newer api is in place

**Comment by jarupxx** [comment]
D3DVolumeTexture_LockBox is just calls Lock3DSurface, also D3DCubeTexture_LockRect is just calls Lock2DSurface.
I recommend DISABLED those OOVPA for all versions, and registering Lock3DSurface and Lock2DSurface.

**Comment by PatrickvL** [comment]
@jarupxx That depends - if there are no patches for `Lock3DSurface` nor `Lock2DSurface`, the callers need to be patched instead.

As a sidenote, in my WorkInProgress branch, all these functions are no longer patched, so once that's finished and merged, many PATCH-registrations will be marked DISABLED anyway.
Also, in the HLEv2 code, the distinction PATCH/DISABLED/XREF has no functional effect anymore - I already proposed to remove them entirely, or move the distinction into an // end-of-line comment.

Both are other discussions, though.

**Comment by PatrickvL** [comment]
Question to @jarupxx and @radwolfie : What's left of this issue, now that HLE DB V2 are (mostly) completed?

**Comment by RadWolfie** [comment]
I don't think we need to patch XGSwizzleBox. I was testing something with Half Life title for a crash due to bad coding for unswizzling the image I think.

Other than that, I was busy getting DSound OOVPAs into more complete database for all revisions. (It's getting close...) So, @jarupxx might have better answer for this?

**Comment by jarupxx** [comment]
For now, inconsistent of these patches is solved. I do not think the issue remains as an HLE database.
