### ISSUE TITLE
Bejeweled [XBLA]: Ingame w/ corrupt textures..?

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#349]
![cxbx 2017-04-10 11-34-44-36](https://cloud.githubusercontent.com/assets/5076651/24876807/eff24914-1de1-11e7-89e4-efad69a7f75d.png)

For those that have XBLA games, try Bejeweled.  For some reason, you only see the top left pixel of a given quad.  Some code I've written that I've shared in a previous issue has the same problem.  Not sure what causes it.

Shogun

**Comment by LukeUsher** [comment]
I suspect this is the same issue that is effecting X-Marbles and others. I'm investigating

**Comment by blueshogun96** [comment]
Okay, just applied the most recent patch, and unfortunately, it didn't fix Bejeweled (but did fix others, which I'll report later).  Good job either way.

Shogun

**Comment by PatrickvL** [comment]
This might be related to the vertex breakage we're experiencing

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#135
