### ISSUE TITLE
Allow the user to configure Xbox settings, such as connected AV Pack, Region, etc

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#35]
Currently all the values returned by ExQueryNonVolatileSetting are hard coded.
The connected AV Pack is also hard coded to HDTV.

The user should be able to change these settings somewhere in the Cxbx-Reloaded UI, Additionally, settings changed via the Dashboard/ExSaveNonVolatileSetting should be preserved.

**Comment by PatrickvL** [comment]
This has become a possibility, now that we have an array of EEPROMInfo structs - see ExQueryNonVolatileSetting and ExSaveNonVolatileSetting

**Comment by PatrickvL** [comment]
Ergo720 implemented this in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1089
