### ISSUE TITLE
Bookworm [XBLA]: Playable

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#351]
![cxbx 2017-04-10 13-24-56-54](https://cloud.githubusercontent.com/assets/5076651/24880966/35f85b7e-1df1-11e7-9ee6-d202ff485e06.png)

The sound is buggy, but other than that, I have not found any real issues with this game.

Shogun

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#134
