### ISSUE TITLE
Super Collapse! 2: Menus + Crash

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#352]
Before #350 
![cxbx 2017-04-10 12-52-57-24](https://cloud.githubusercontent.com/assets/5076651/24881224/f8bc6cea-1df1-11e7-81c9-b3ff4ab7828d.png)

After #350 
![cxbx 2017-04-10 13-14-28-30](https://cloud.githubusercontent.com/assets/5076651/24881240/0cdf4a58-1df2-11e7-8a01-a9e3be9dfce8.png)

It crashes when trying to go ingame due to a call to XFONT_SetTextHeight @ 0x30E30.  It's quite rare that titles ship with XFONT APIs in use, so I dunno about this one...

Shogun

**Comment by LukeUsher** [comment]
I see no reason why XFONT_SetTextHeight should fail unpatched, there's possibly something missing/broken further back in the call chain

**Comment by PatrickvL** [comment]
Remarkable how the white "options" texts disappear behind the blue bars, in the "After #350" screenshot

**Comment by blueshogun96** [comment]
@LukeUsher yeah, more than likely.  I've written some really basic examples with XFONT before, but never had any issues out of it.

Shogun

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#133
