### ISSUE TITLE
MemoryManager::AllocateZeroed quick fix

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#353]
I was diving into Virtua Cop 3 and came across a bug in MemoryManager::AllocateZeroed.  If the internal call to Allocate (which calls malloc ofc) fails, then it's going to result in a crash when calling a memset on it.

if( addr != NULL )
		memset(addr, 0, num * size);

Adding this helped me get passed the initial issue with Virtua Cop 3.  I dunno if I'm able to make pull requests or submit fixes or not, so just throwing this out there just in case.

**Comment by LukeUsher** [comment]
I had a look at fixing this in pull request #356.

As for contributing:
 We generally don't give out direct write access to the repository (unless you become part of the core team, currently Me and Patrick), but you are very welcome to submit fixes via pull-requests.

Please follow the standard git process for creating pull-requests (Fork => Branch => Commit => Pull-Request). See https://gist.github.com/Chaser324/ce0505fbed06b947d962 for more details.

**Comment by PatrickvL** [comment]
Fixed by @LukeUsher with PR #356

**Comment by PatrickvL** [comment]
Regarding contributions :

Luke and I are actively monitoring all Pull Requests, so everyone : Don't be afraid to submit anything, as it normally won't be on the shelve for more than a few hours.

We do request that submissions are clean, build correctly, not too large, easily reviewable, and if possible, mention test-cases with which the work can be validated.

**Comment by blueshogun96** [comment]
Thanks for the link.  I'm new to pull requests and stuff since I'm used to working on stuff solo.  I'll have to take a read through that and make pull requests regularly as find quick fixes.

Shogun.
