### ISSUE TITLE
Virtua Cop 3 [XDK 5028]: Reaches intros, but requires HD?

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#354]
![vc3_intro](https://cloud.githubusercontent.com/assets/5076651/24885909/ff77479e-1e05-11e7-9fbe-cd7987108a9d.PNG)
![vc3_servicemenu](https://cloud.githubusercontent.com/assets/5076651/24885910/00d69eb4-1e06-11e7-80d1-c62427afb3ac.PNG)

Okay, after adding a couple of signatures (D3D::CDevice::KickOff (called from D3DDevice_KickPushBuffer) and D3DDevice_DrawVerticesUP), I was able to get Virtua Cop 3 working somewhat again.

Now, there's a few important things to remember about Virtua Cop 3.  I have a debug Xbox, so I'm able to play this game on some real hardware.  Without 128mb of Ram as well as HD component cables hooked up, this game will not go any further than this.  IIRC, there is a function used to detect which type of component cable is connected.  It's been ages since I've looked at the XDK functions for this, so it may be a requirement.

Lastly, I was only able to get this to show up in release mode.  Debug builds just give me an infinite black screen.

Shogun

**Comment by LukeUsher** [comment]
We have completely removed patches that software use to detect AV cable, etc. Instead, we implemented the Kernel functionality directly. 

We emulate HDTV connected, but using standard NTSC video mode. Have a play with this to see if you can get it executing futher.

EmuKrnlAv.cpp: AvQueryAvCapabilities()
`return AV_PACK_HDTV | AV_STANDARD_NTSC_M | AV_FLAGS_60Hz;`

Perhaps try playing with the flags. For Example:
`return AV_PACK_HDTV | AV_STANDARD_NTSC_M | AV_FLAGS_60Hz | AV_FLAGS_HDTV_480p;`

**Comment by PatrickvL** [comment]
@blueshogun96 Is this a Chihiro title? (The arcade-like menu seems to indicate that.) Because in that case, this would be the first arcade title (that I know of) that's starting to show something!

**Comment by PatrickvL** [comment]
Also, look in `EMUPATCH(D3DDevice_SetViewport)` - it limits Width to 640 and Height to 480, 

> otherwise crashes occur

**Comment by BenNottelling** [comment]
@PatrickvL Funny, If you comment out the code It doesn't crash.. I tested Turok, even with a custom resolution it didn't crash. Not quite sure why it's there tbh
```
((D3DVIEWPORT8*)pViewport)->Width = 640;
((D3DVIEWPORT8*)pViewport)->Height = 480;
``` 
Stop those from running ^

**Comment by blueshogun96** [comment]
@LukeUsher Unfortunately, it didn't work :(  I tried setting the flags you specified including the widescreen flag also.  I'm not sure which flags are specifically expected, nor am I sure where Virtua Cop 3 verifies this.  Since I have my debug Xbox, I can play around with the settings and see which ones work for sure.  Also, I had a question about HalBootSMCVideoMode.  Do you think it could be checking that?  Do the same flags apply in that new function you wrote?  I copied and pasted those flags to hard code it, but that didn't work either.  Sadly I haven't found much info on that, so I was basically just throwing stuff out there.

Oh, and while I'm at it, I wanted to say that I'm impressed that you've removed my Jvs functions and STILL managed to get it this far.  It's a good thing, as I initially thought that there was nothing I could do to avoid the Jvs and IN/OUT privileged instructions for the Chihiro hardware.  I couldn't get to the JVS error screen without skipping these before.

@PatrickvL yes, that is a Chihiro title.  I managed to get the error screen to show up in my earlier branch years ago, but never to the copyright screen.  See above.

Also, removing the viewport limitation didn't work either.  There's got to be something else stopping it.  Just don't know what it is...

Shogun

**Comment by jackchentwkh** [comment]
the virtual cop 3 requires 128MB ram when running on an original xbox hardware as I remember.

**Comment by blueshogun96** [comment]
As I already mentioned yes but I hear that doesn't become a requirement until you get ingame last I checked.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#132
