### ISSUE TITLE
Azurik: black textures and broken 3D 

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#360]
Okay, there's several issues with Azurik (my favourite Xbox game).

First, textures don't appear to work at all anymore.  On my old branch, the textures were all DXT formatted as opposed to palettized.  So, given that, I dunno if there's been some sort of issue with DXT formatted textures with this branch or not.  That or it has something to do with that one pixel shader that the game creates and destroys every single frame.

Broken 3D when going ingame is still a thing.  I never did find out exactly why all of the push buffer rendering was so broken.  Of course, they are all pre-recorded pushbuffers which aren't exactly a challenge to emulate, but I'm assuming it has to do with the shaders being used (which I will address in a minute).  Typically, when executing a raw push buffer, we depend on the FVF being set to properly decode it.  That doesn't appear to be set for Azurik.

Azurik also uses some unique shader functionality.  While the vertex shaders aren't exactly anything special, they aren't used in the typical PC fashion, that's for sure.  Now, for starters, when Azurik starts creating vertex shaders, you'll notice that the actual vertex shader code is EMPTY.  That's right, you'll get nothing but vs.1.1 in the beginning, and that's it.  This initially caused a crash and stumped me for a while.  I initially created a workaround for this since I didn't understand what was going on, and I believe that workaround was the wrong way to do things here.  For each vertex shader, there's a vertex declaration that goes with it, so there is a possibility that the vertex shader is supposed to be generated from that vertex declaration instead.  IIRC, the DirectX8.1 SDK documentation demonstrates how to do this.  I'll have to look into it later on if necessary.  

But wait, there's more!  If you pay close attention to the debug output here, you'll notice that there are some fairly unique shader functions being called.  One of many include D3DDevice_LoadVertexShaderProgram, _RunVertexStateShader, _Get/SetVertexShaderInput, _SelectVertexShaderDirect, _SelectVertexShaderInputDirect, etc.  These all have one thing in common, when they are called, you'll just get the message saying "NOT YET IMPLEMENTED!" in your debug output.  So yeah, there's a ton of vertex shader functionality not being emulated here.  From an HLE perspective, it's quite a bit of work it looks like, but I'm sure it's doable in the long run.  There's got to be some sort of XDK example that demonstrates how Azurik does it's rendering, I just haven't seen it yet.  Nor have I come across any other games that replicate any of these issues except Sonic Heroes (E3 demo) with the empty vertex shader described above (which is the source of it's crash).

Shogun

**Comment by PatrickvL** [comment]
Could you convert this into clear, small, independent, separate issues, each with a short summary. As right now it's not all that clear what the issue is trying to get fixed.

**Comment by blueshogun96** [comment]
Okay, I think that would be better instead of dumping it all into one issue.

Shogun.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#131
