### ISSUE TITLE
Dosxbox has regression and probably some more emulators too

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#361]
Cxbx-Reloaded Version ba2ae324 (Feb 22 2017)
_______________________________________________________

With this build of the emulator the menu almost appears after the title screen
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/24940403/d562df6c-1f7d-11e7-89a1-324ad1a24f77.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/24940402/d562d7ec-1f7d-11e7-9580-43eec3f4bee8.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/915352/KrnlDebug.txt)

But with latest build of Cxbx Reloaded happens nothing, but exception code appears after the KeBugCheck warning . The version of the emulator is 4dc8409abd2c35eaeb1a749f6aac54c4c9aeae18
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/24940577/e7546bea-1f7e-11e7-951e-0d90de39317c.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/24940578/e7572178-1f7e-11e7-8bd0-f03cbdbc27f2.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/915363/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/916348/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#130
