### ISSUE TITLE
Frogger Beyond: Reaches menus; almost gets in-game, but crashes as soon as first level loads

### ISSUE THREAD

**Issue by Voxel9** [Cxbx-Reloaded/Cxbx-Reloaded#369]
Note: Launching the XBE triggers the KeBugCheck message at first, but continuing execution continues the emulation just fine.

![image](https://cloud.githubusercontent.com/assets/16278868/25041755/20581a72-210a-11e7-8dcb-943db374808a.png)

![image](https://cloud.githubusercontent.com/assets/16278868/25041483/343ec5a6-2108-11e7-81d8-e3cdde27b3a0.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/921953/KrnlDebug.txt)

**Comment by jarupxx** [comment]
EIP is close to the address of VertexShader function. so I think that missing OOVPA related to VertexShader.

**Comment by Voxel9** [comment]
Yeah, I took a quick look myself and did notice that. The EIP seems to be within the D3DDevice_LoadVertexShaderProgram function, which doesn't look like it is implemented just yet.

**Comment by jarupxx** [comment]
Thank you for the tip! I hope that it will improve with PR #370

**Comment by Voxel9** [comment]
It certainly has! :) It now fully goes in-game, albeit the framerate is very low (probably only about 3-5fps) and the Frogger character doesn't seem to render on the screen. Other than that, great job on getting this to go much further!

![image](https://cloud.githubusercontent.com/assets/16278868/25045353/d36e10ee-2123-11e7-9eeb-ae4ed228f88e.png)

**Comment by ObiKKa** [comment]
Great jobs all around! But I think you need to give this page time for Patrick to analyse this game and upgrade its status in his game regression tests issue before being closed. He can even close this issue for you.

**Comment by PatrickvL** [comment]
Open, close, it doesn't matter, I'll update the regression list anyway.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#129
