### ISSUE TITLE
Help wanted: vertex regression search (bisect) 

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#371]
Before starting on this, please discuss first, to prevent needless duplicate work, but here's the deal:

Currently Cxbx is experiencing lots of render bugs, due to a regression in vertex buffer and/or shader conversion. Titles like Futurama, Turok and even the dashboard rendered glitch-free in an older version.

The only problem is: we have no clue what commit caused these glitches. So we're asking for YOUR help: can you find the commit that broke vertex rendering?
There's no price attached, but once we have the culprit, a fix won't be far away, with likely a magnificent result: many of the render problems were currently seeing will go away! (So that's some form of a reward after all).

Before raising false alarms, make very very sure that you report the exact build that caused the regression, as otherwise we would be trying to fix something that isn't broken.

Also, before starting the search, be aware that not all commits lead to running emulation, as there have been other (temporary) regressions the the past few months (my bad).

First, we need to establish a baseline;
Per test executable we must find an old, correctly rendered commit and a recent commit that also runs, but with broken graphics.
Next, a bisect must be done to determine the exact (or if that's not possible, the minimum range of commits) in which the rendering broke.
Doing the same thing with multiple test cases should give comparable or perhaps even an identical outcome.

Good luck, and may the best man win ;)

**Comment by Voxel9** [comment]
I have scouted high and low throughout the older commits, and so far I have taken note that commit 517d411 and any older commits seem to have no problem with vertex rendering, so that's pretty much solved finding a commit that actually gets the rendering right.

![comparison](https://cloud.githubusercontent.com/assets/16278868/25072442/08fd5da2-22c6-11e7-8b09-63adc865cf29.png)

**Comment by PatrickvL** [comment]
Thanks @Voxel9 for finding a "latest known good" for the Cartoon XDK sample - did you find a "first known bad" after that too? (Having that would reduce the number of changes to review considerably)

**Comment by bhodg22** [comment]
Did he not mean that https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/517d411452d3e4748c93d385eb2933f1490420c2 was the last one that did it right?

**Comment by PatrickvL** [comment]
Yes. And now the quest for the first one after that, that did it wrong.

**Comment by Voxel9** [comment]
A handful of commits after 517d411 appear to not begin emulation when you click "start emulation" for some unknown reason (didn't happen after building 517d411 and commits before that, weirdly enough), but after those said handful of commits (namely starting from 1d89b04) the emulator began to start emulation properly again, so as a result I haven't been able to pinpoint a _specific_ build.

However 1d89b04 is actually a build that has the vertex regression, so this is the closest build we have, to the last one that did it right, that shows the regression.

**Comment by PatrickvL** [comment]
Indeed, some commits don't run (well), but having a small range like this will help, so many thanks!

**Comment by bhodg22** [comment]
Looks like there are 6 commits between https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/517d411452d3e4748c93d385eb2933f1490420c2 and https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/1d89b04573025e265aa3978473f6ae6943c0c5f3

**Comment by PatrickvL** [comment]
@Voxel9 Are you absolutely sure on these commits? As I've compared all code between those two commits, and there's almost nothing changed that could influence vertex rendering.

The only (far-fetched) difference, is that `VirtualProtect` is now passed `PAGE_EXECUTE_READWRITE` instead of `PAGE_READWRITE` - I can't imagine that breaks vertex rendering.

**Comment by Voxel9** [comment]
@PatrickvL I re-downloaded, re-built, and re-tested the 2 commits and I am positive that 517d411 gets it right, and 1d89b04 doesn't.

However, I can't say for sure whether or not 1d89b04 is the _exact_ commit which breaks vertex rendering. Again, as I mentioned earlier, I was unable to test any of the six other commits in-between those two due to emulation being unable to start for some unknown reason.

Have you gone through the six other commits' code as well as 1d89b04's?

**Comment by PatrickvL** [comment]
Luke will take a look at this too, but I haven't found anything​ strange in those six commits

**Comment by PatrickvL** [comment]
Like reported that disabling the vertex buffer cache (which effectively causes vertex buffers to constantly be re-converted at each draw), results in much better drawing (at least in Jet Set Radio Future and the dashboard) albeit at a big performance penalty.

**Comment by PatrickvL** [comment]
The gamepad sample still doesn't draw correctly with that, so there's probably also a bug in index buffer emulation.

**Comment by PatrickvL** [comment]
One research direction is to see vertex buffer conversion uses the correct memory addresses, as the Xbox changes the data address back and forth between an GPU addressable memory region vs an CPU addressable memory region.

**Comment by LukeUsher** [comment]
Note that the above behavior works (the highest bit in the data field being set) because 0x8000000 in Xbox Virtual Memory is a window into Physical Memory. The GPU accesses memory directly without going through virtual memory, hence 0x8000000 in Virtual Memory on the CPU side IS 0x00000000 in Physical Memory.

**Comment by PatrickvL** [comment]
As it turns out, this issue was caused by two separate problems; First, vertex conversion was never entirely correct, but a backport of the Dxbx code fixed that aspect. Second, the index buffer conversion code was also broken, another backport from Dxbx paved the way towards a real fix by Luke. With these two fixes in place, many of the vertex rendering issues we were plagued by are now resolved!
