### ISSUE TITLE
Futurama PAL - menue crash - videos added

### ISSUE THREAD

**Issue by frankyfife** [Cxbx-Reloaded/Cxbx-Reloaded#373]
before 17/04/14 build the game does nothing, now i can reach the menue (but only when vsync is disabled). the menue is ridiculous fast (100-200 fps) and scrolls by itself (no controller used nor configured), then the emulator crahes.

![unbenannt](https://cloud.githubusercontent.com/assets/16177808/25071572/31d633e4-22bb-11e7-8591-38d5a65ac8d8.JPG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/924307/KrnlDebug.txt)

**Comment by frankyfife** [comment]
Uploaded 2 vids on youtube. With the build from 23th of april the menue is fully accesible ( controller configuration is needed), options and extras r selectable, choose the new game option let the game crash.

there is also a huge white overlay in the top left corner, which make you think the fmv's are not working but they do (as proved with the vid with 4k res).

https://www.youtube.com/watch?v=CGPId7o7Gls (auto res)

https://www.youtube.com/watch?v=0PllvMIEIKY (4k res)

**Comment by PatrickvL** [comment]
I get network errors on both videos

**Comment by frankyfife** [comment]
fixed.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#128
