### ISSUE TITLE
Gladius USA Issues

### ISSUE THREAD

**Issue by kanelakis** [Cxbx-Reloaded/Cxbx-Reloaded#377]
I also tested Gladius US version, setting the resolution in default, DIRECT3D REF (software), already at the launch comes the fateful message.
Add debug files.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/929862/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/929863/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#127
