### ISSUE TITLE
Cache and reuse detected addresses

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#378]
Addresses for detected functions, FS segment register accesses and media patches should be written to a ".map" or ".ini" file, so next runs can skip these detection phases and load the previously detected addresses from the cache file.
Once loaded from cache, the usual patching should still be done of course.

An added benefit of caching this to a file is, that manual updates can be done. One use case for this would be: to investigate if a correction to a wrongly detected function leads to better emulation. (In which case the OOVPA for that function should be improved.)
Also, the​ old Halo cache could be ported and tried out.
Cache files could be shared to speed up the initial booting of titles.
Repeated debugging iterations will become much quicker.

Do make sure the caching associates the right file with the right xbe (especially important for multi part titles, or software with a non-unique titleid).

**Comment by LukeUsher** [comment]
I'll handle this on, it requires a rework of the patching method as with the current approach, a HLE cache would only work for a single build of Cxbx-Reloaded, as the oovpa addresses currently  contain the addresses of functions within the Cxbx executable which could change at compile time. This would need a method of mapping function names to patches without hardcoding the address, i did begin to implement this using GetProcAddress so I believe I should resume that branch

**Comment by blueshogun96** [comment]
This would be a good feature to have.  I thought Caustik implemented it once before way back in the day (saw some comments on it), but don't know what became of it.

Shogun.

**Comment by LukeUsher** [comment]
Caching did exist, but it was Cxbx version specific I'm that recompiling the executable could break the cache, as it contained hard coded offsets into the executable, it's been disabled for quite some time for this reason

I'm working on an approach that doesn't hardcoding anything

**Comment by LukeUsher** [comment]
Partially solved in #389
I'll be doing more work on this to extend the functionality in the coming days/weeks

**Comment by LukeUsher** [comment]
Closing this now that #389 was merged.

There is still the need to separate HLE patching and Symbol Scanning, but that's a different issue.
