### ISSUE TITLE
Rayman 3: Hoodlum Havoc. Movie plays. Crashes before menu.

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/Cxbx-Reloaded#386]
The Russian tester on his Youtube channel "Emulators of game console" has uploaded a video test of this game Rayman 3 on April 17, 2017 with the CXBX Reloaded (April14.2017) build.

https://www.youtube.com/watch?v=W3XKLz4FzWI

* Description:
"My Spec:
CPU: Intel i5-3570K@3.6 GHz (MB MSI B75A-G43),
GPU: Nvidia GTX 1050ti 4GB (MSI Gaming X),
RAM 8GB DDR3-1600 MHz (Kingston HyperX),
Windows 10 x64 Pro (ForceWare 378.66)
--
Rayman 3: Hoodlum Havoc (Xbox)
Status: Loadable / Intro
Realtime Footage"

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#126
