### ISSUE TITLE
Hardware Testing

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#39]
I'm looking to spend some time after Christmas writing test programs and running them on real hardware.

My primary goal is to test Kernel functions to make sure they behave the same way between Cxbx-Reloaded and on my Xbox.

I would appreciate it if you all could suggest specific test cases as comments on this issue preferably giving Function names, parameters and expected behavior.

**Comment by StrikerX3** [comment]
In addition to checking if NtCreateFile also creates parent folders in the utility drive, I'd like to know if my File Information struct conversions are doing their job. A test program would consist of a series of NtQuery/SetInformationFile calls with the following classes and structs:

### [NtQueryInformationFile](https://msdn.microsoft.com/en-us/library/windows/hardware/ff567052(v=vs.85).aspx)

FILE_INFORMATION_CLASS | struct | Notes
---------------- | ------------------ | -----
[`FileAllInformation`](https://msdn.microsoft.com/en-us/library/cc232117.aspx) | [`FILE_ALL_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545743(v=vs.85).aspx) | Includes many other structs, but only two need conversion: [`FILE_BASIC_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545762(v=vs.85).aspx) and [`FILE_NAME_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545817(v=vs.85).aspx)
[`FileNetworkOpenInformation`](https://msdn.microsoft.com/en-us/library/cc232078.aspx) | [`FILE_NETWORK_OPEN_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545822(v=vs.85).aspx) | Seems to be used by Panzer Dragoon while loading level data, might as well make sure it works.

File information classes that didn't need conversion:
* [`FileReparsePointInformation`](https://msdn.microsoft.com/en-us/library/cc232086.aspx) - [`FILE_REPARSE_POINT_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540354(v=vs.85).aspx)
* All the inner structs found in `FILE_ALL_INFORMATION` except the two mentioned notes for the struct in the table above.

### [NtSetInformationFile](https://msdn.microsoft.com/en-us/library/windows/hardware/ff567096(v=vs.85).aspx)

FILE_INFORMATION_CLASS | struct | Notes
---------------- | ------------------ | -----
[`FileLinkInformation`](https://msdn.microsoft.com/en-us/library/cc232073.aspx) | [`FILE_LINK_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540324(v=vs.85).aspx) | Creates a hard link to a file. Not sure if any game ever uses this.
[`FileRenameInformation`](https://msdn.microsoft.com/en-us/library/cc232085.aspx) | [`FILE_RENAME_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540344(v=vs.85).aspx) | Rename and move files using absolute and relative paths, with and without a RootDirectory. Moving files might not work on the emulator.


File information classes that didn't need conversion:
* [`FileBasicInformation`](https://msdn.microsoft.com/en-us/library/cc232094.aspx) - [`FILE_BASIC_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545762(v=vs.85).aspx)
* [`FileReparsePointInformation`](https://msdn.microsoft.com/en-us/library/cc232086.aspx) - [`FILE_REPARSE_POINT_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540354(v=vs.85).aspx)
* [`FileDispositionInformation`](https://msdn.microsoft.com/en-us/library/cc232098.aspx) - [`FILE_DISPOSITION_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545765(v=vs.85).aspx)
* [`FileEndOfFileInformation`](https://msdn.microsoft.com/en-us/library/cc232067.aspx) - [`FILE_END_OF_FILE_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545780(v=vs.85).aspx)
* [`FileLinkInformation`](https://msdn.microsoft.com/en-us/library/cc232073.aspx) - [`FILE_LINK_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540324(v=vs.85).aspx)
* [`FilePositionInformation`](https://msdn.microsoft.com/en-us/library/cc232121.aspx) - [`FILE_POSITION_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545848(v=vs.85).aspx)

**Comment by PatrickvL** [comment]
A test per kernel API (like mentioned in issue #68) would be very valuable too,
so we can compare the behaviour of each API between real hardware and our emulated implementation.

**Comment by PatrickvL** [comment]
Perhaps this can best be moved to https://github.com/Luca1991/xbox_kernel_test_suite

**Comment by ergo720** [comment]
Nowadays, we have the [xbox kernel test suite](https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite) to test kernel functions, so closing this.
