### ISSUE TITLE
Shenmue II Demo reaches the loading screen

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#391]
Once again, I am very impressed with your work guys.  You're all doing much better than I ever did.  You're also emulating those Sega titles I had so much trouble with.

For those who have the demo, try running it in the latest build and you'll see the loading screen.  It crashes swiftly after that though.  Have a look.  When I get a chance I'll try the full version of it (haven't played it in years!) as this game is highly sought after emulation wise.

Shogun

**Comment by PatrickvL** [comment]
Thanks for reporting this. Could you add a nice screenshot perhaps? We love those... plus they are good reference material

**Comment by blueshogun96** [comment]
Hey, sorry it took me so long to get back to on you on the Shenmue II demo crash.

![shenmue2_demo](https://cloud.githubusercontent.com/assets/5076651/25502031/cea64902-2b49-11e7-9066-2df63928ba6e.PNG)

I took a quick look, and the issue goes back to the implementation of D3DDevice_Register, where it dies trying to create a vertex buffer (1024 bytes).  

Shogun

**Comment by PatrickvL** [comment]
We're working towards getting CreateDevice and Register to run unpatched. Once that works, many of the current issues will disappear. For this to work, we're going to backport lots of Dxbx code that does resource conversion only at drawing time. That will require significant changes to the way resources are currently handled, but in the end it's a better approach than what's currently been done.

**Comment by blueshogun96** [comment]
Good to know.  But one question I do have is why unpatch CreateDevice?  

Shogun

**Comment by PatrickvL** [comment]
Because it initializes global variables that are used by many other functions that we'd rather see running unpatched too, as these hardly access hardware registers, so there's no point in patching them

**Comment by PatrickvL** [comment]
Btw: Some of the things written here in this issue tracker are not really (game specific) issues, so better discussed on our gitter channel. We'd like to avoid the issue tracker becoming some sort of forum you see.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#125
