### ISSUE TITLE
[PAL] Splinter Cell Pandora Tomorrow freezes at Ubisoft logo (default.xbe)

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#401]
Tested on Cxbx-Reloaded build 7c266ad4 (Apr 26 2017)

(Please note, this behaviour is for default.xbe [mode selection menu], not Offline.xbe [Single-player] or Online.xbe [Multiplayer]). When starting emulation, you can hear the Ubisoft logo before the audio glitches and video freezes, midway through the full logo sequence. Sometimes you can see the Ubisoft logo before it freezes, but the video behaviour is quite temperamental (most of the time you can't, video is usually just a slow pulsing grey/black until it quickly freezes). If you can see the Ubisoft logo, the video should freeze with a frame of the logo before the freeze happens.

Crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25463295/5e21e966-2b49-11e7-8466-c0814dc6da9f.PNG)

Splinter Cell 2 mode selection menu (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985808/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/960129/KrnlDebug.txt)

 

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D REF (Software)
Video Resolution: Automatic (Default)

**Comment by BenNottelling** [comment]
If you add the dashboard files does it act differently?

**Comment by rexcaptain501** [comment]
Just to clarify, is that when you place the ms dashboard inside the Partition 2 folder in AppData/Roaming/Cxbx-reloaded/EmuDisk/Partition2 (I might be mistaken)?

**Comment by BenNottelling** [comment]
@rexcaptain501 should be it!

**Comment by rexcaptain501** [comment]
Almost exact same result with my msdash 5960 inside Partition 2. I got a slightly different log, so here it is ([KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/960540/KrnlDebug.txt)). Note that the only difference I can see between this log and the original test's 2nd boot crash is the '[XxXXXX]' code (e.g. line 441) throughout the whole log, whatever that means. I tried the same test a few times and that code changed every run, I don't know if this is useful, likely not.

Not sure if the case of almost nothing changing in behaviour has anything to do with me not being able to successfully emulate msdash 5960 in Cxbx-Reloaded, even when inside Partition2. I get a fatal error (* EmuD3DDeferredTextureState was not found!), although this might be a completely different issue (I realize that Cxbx-Reloaded is in a very, very early stage of development).

**Comment by rexcaptain501** [comment]
Just remembered that inserting msdash 5960 inside Partition 2 fixed the 1st boot fatal error. Just tested again and it resolves it from coming up. Not sure how it's able to cope with a 2nd boot without the ms dash. I've just done a couple of short tests and the error comes up almost immediately now after the freeze (my CPU was busy earlier at the time of posting the issue, very likely the cause of slowdown between the freeze and the error popping up.) I've edited the original post accordingly.

**Comment by rexcaptain501** [comment]
Did another test and it looks like all games I test throw the 1st boot error, even when quickly starting, stopping and starting emulation (might be something to do with first time emulating Roaming file generation?). So basically, msdash in Partition 2 probably does absolutely nothing.

**Comment by rexcaptain501** [comment]
Splinter Cell Pandora Tomorrow (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/965815/Xbe.txt)

**Comment by PatrickvL** [comment]
Those ever changing numbers are thread ids, as they are handed out by Windows. These change from run to run, so comparing logs is bound to show lots of differences because of that. They are still useful however, as the id indicates which log messages are triggered from which thread, bringing some order into the chaos

**Comment by rexcaptain501** [comment]
Sorry, forget my previous comments on the 1st boot error, that's just when there is no ms dash in Partition 2 for the 1st time booting.

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build 5ab5ee2, Jul 21 2017

Now complaining about XMountMUA. Same behaviour as before.

![1](https://user-images.githubusercontent.com/10300935/28485178-b74cf2fe-6ecb-11e7-8ba5-8dfe7dd0bff8.PNG)

**Comment by rexcaptain501** [comment]
Tested with Cxbx-Reloaded build 3ca1a35, Jul 23 2017

No audio is being output anymore. 
![scpt](https://user-images.githubusercontent.com/10300935/28503803-ff22831e-7060-11e7-9e7a-4ef9a1ab3444.PNG)

**Comment by PatrickvL** [comment]
New audio configuration options have been added, please play around with these settings and if possible report the results here.

**Comment by rexcaptain501** [comment]
I had a fiddle around for several minutes and couldn't get any sound going with a few different games. None of the options in combinations with each other made a difference.

**Comment by RadWolfie** [comment]
Getting no audio at the beginning of boot might be intended if an intro has not start or isn't in menu.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#123
