### ISSUE TITLE
Fatal Frame 2 CreateTexture Failed

### ISSUE THREAD

**Issue by pekocugo** [Cxbx-Reloaded/Cxbx-Reloaded#402]
Just tried to run Fatal Frame 2 Director's cut using latest (7c266ad4) build and when starting game emulator first starts spamming [0x3C0] EmuWarn: EmuKrnl: IoCreateFile Failed! (0xC0000034) in log and then [0x2504] EmuWarn: NtReadFile Failed! (0xC0000022)

After that i get CreateTexture Failed error and game just stays on black screen

On older version (0b09fe3d) i only get IoCreateFile Failed! and sometimes NtReadFile Failed! but i dont get any texture failed errors but the game still stays black, if needed i can upload logs from 0b09fe3d build later

here are logs and XBE dump from 7c266ad4:
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963405/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963406/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963407/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963408/PSDef001.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963409/Xbe.txt)

And here is the screenshot of texture error:
![ff2](https://cloud.githubusercontent.com/assets/28128473/25513605/ac09184c-2bd6-11e7-857f-7bf4a5a6dc93.PNG)

Hope this logs might help improve emulator in future.

If more tests or logs are requierd let me know.

**Comment by rexcaptain501** [comment]
Does the game output any audio or video besides from a black screen? If not, the emulator is in too early of a stage for these crash reports (as stated in README.md).

**Comment by pekocugo** [comment]
Sorry, i didn't read whole readme.md, i did not noticed any sound or video just black screen
I hope this emulator wont get abandoned like previous xbox emulators cause i am really looking forward to this :)

Anyway, sorry for creating issue before reading whole readme.md file, hope at least this logs will be helpful sometimes in future

**Comment by PatrickvL** [comment]
We're slowly working towards removing patches on texture creation functions, once that's done I suspect the above described create texture error will disappear.

**Comment by ergo720** [comment]
It still has a problem with a texture function (the same as seen in #524), but now the error is different.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174187/KrnlDebug.txt)
![project2](https://user-images.githubusercontent.com/30000751/28584072-e678364c-715a-11e7-9542-fa8ab4639196.PNG)

**Comment by ergo720** [comment]
Is this a LTCG title then? It has the same error seen in the game Fable and LukeUsher has said that one is LTCG. If so, why doesn't cxbx shows the error related to LTCG?

**Comment by PatrickvL** [comment]
It's unclear; the D3D library has no LTCG indicator, but still there's not a single D3D function found...

**Comment by BenNottelling** [comment]
@PatrickvL is there any way to tell if a title is LTCG?

**Comment by PatrickvL** [comment]
@BenNottelling LTCG can be recognized by looking for a library called D3D8LTCG in the xbe dump, of present, it's an executable build with LTCG, if absent it's a regular build.

**Comment by ergo720** [comment]
This error is quite common though. I have a couple of other games and the dashboard that show the same error.

**Comment by LukeUsher** [comment]
Later dashboards and quite a few later games are all LTCG and cannot be supported yet, it's normal.

**Comment by ergo720** [comment]
Well, my version of this game is LTGC because in the dump of the xbe I see the library D3D8LTCG is used

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#121
