### ISSUE TITLE
[PAL] Lego Star Wars crashes at language selection screen

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#403]
Tested on Cxbx-Reloaded build 7c266ad (Apr 26 2017)

Pretty self explanatory. In Hardware mode, the loading screen will come up with working video and immediately crash. Software mode has an immediate crash with no audio or video.

Hardware mode crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25513957/280fb6de-2c2d-11e7-8d3d-b958a6f90ab7.PNG)

Hardware mode Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963443/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by rexcaptain501** [comment]
Lego Star Wars .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/965814/Xbe.txt)

**Comment by rexcaptain501** [comment]
Just tested with the latest build (36f9e171, May 3 2017). The language screen now comes up without any error, but eventually skips ahead to the main menu in English. Emulation speed goes up like crazy with an inactivity cut scene video with expected crazy sped up audio. The process loops without any crashes. No buttons work with an Xbox 360 controller. The Kernel Debug log is too big to upload due to all the thousands and thousands of 'EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!' warnings. These warnings seem to be caused by the flashing selection text ingame.

Screenshot: [Photo 1](https://cloud.githubusercontent.com/assets/10300935/25685980/187565ca-30bf-11e7-8317-ff17df99f909.png)

**Comment by PatrickvL** [comment]
@rexcaptain501 Could you please insert your screenshots inlined, instead of as a llink? (It just looks nicer in here, plus we don't have to click through) Thanks.

As for the speed : Have you tried enabling v-sync?

**Comment by rexcaptain501** [comment]
Sure, I've fixed that. When using V-Sync, I could get to the loading screen without any crashes (I think the speed was fine) and now can't do anymore tests due to an 'EmuD3DDeferredRenderState was not found!' error each time I try to emulate a game. Not sure if Lego Star Wars was waiting for me to press A, because I don't think I had set bindings to my 360 controller (nonetheless, I don't think it works anyways).

**Comment by LukeUsher** [comment]
It now gets a little further with the pull-request #439. There is still an unpatched D3D function that I haven't yet been able to identify. (It's inlined in the .text section and Dxbx doesn't identify it either)

If anybody with good D3D knowledge can help, it would be welcome.

![image](https://cloud.githubusercontent.com/assets/740003/25738740/b3b00826-3176-11e7-8483-2c57d7370bc1.png)

**Comment by PatrickvL** [comment]
Make space indicates push buffer usage

**Comment by rexcaptain501** [comment]
Any idea why I can't get any game to work due to 'EmuWarn: EmuX86_Read32Aligned(0xFE820010)' being spammed in the Kernel Log? All games just show a black screen. Reverting to older builds doesn't help.

Example: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/978611/KrnlDebug.txt)

**Comment by rexcaptain501** [comment]
Closing this to make a new report on current progress.
