### ISSUE TITLE
Devkit leak on IPFS?

### ISSUE THREAD

**Issue by caghandemir** [Cxbx-Reloaded/Cxbx-Reloaded#404]
So I came across a devkit leak on IPFS while browsing and first thing that came into my mind was that kid on PCMR subreddit. Fuck, it still hurts. Whatever, I tried to do some research but I couldn't find it anywhere. Of course I'm not going to link it here but if anyone knows about it, did we have it before? If not, could it help us?
p.s. ipfs is a pain in the *ss. fuck whoever designed it.

**Comment by PatrickvL** [comment]
As far as I know you're right; devkit leaks are not to be discussed here. Using them, or even discussing them, could lead to legal ramifications, which we intent to keep well away of. This does bring up the point of how we should approach this matter. Any ideas on that are best documented in a developer guide. These are thing yet to be fleshed out. Any help on that is welcome. For now, I'll close this issue if you don't mind. Thanks for the reminder though.

**Comment by LukeUsher** [comment]
Just reiterating what Patrick has said:

Do NOT discuss leaked devkits/source code/anything else that should have never been made public, or where to find them, doing so could open up a whole plethora of legal issues.

**Comment by PatrickvL** [comment]
On a closing note (and I may be misinformed, so please correct me if I'm wrong) the only way leaked devkits can be used, is for clean room reverse engineering : person A with access to a devkit describes how it works internally (without showing it's actual code) to person B, who hasn't seen the devkit, but implements it's functionality based on the description of person A.

**Comment by PatrickvL** [comment]
And if anyone wonders: Don't​ be alarmed - as far as I'm aware of, this approach isn't used thus far.
