### ISSUE TITLE
Xbox dashboard scrolling up (two versions tested)

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#407]
I tested two versions of the Xbox Dashboard and both of them suffered from scrolling up without me pressing anything (sometimes would scroll down once, but up was more common). Other than that they were both emulated okay up until the memory manager and both about the same result.
![capture](https://cloud.githubusercontent.com/assets/17304943/25558609/1508ea62-2cdf-11e7-9413-b79e7066f385.PNG)
![capture_4](https://cloud.githubusercontent.com/assets/17304943/25558648/e87fce06-2cdf-11e7-8786-9023a25cc12d.PNG)
![capture_5](https://cloud.githubusercontent.com/assets/17304943/25558657/fea7faf0-2cdf-11e7-8de1-0ee37337be4a.PNG)
**And**
![capture_1](https://cloud.githubusercontent.com/assets/17304943/25558620/593427e2-2cdf-11e7-8712-44a08b7437fa.PNG)
![capture_2](https://cloud.githubusercontent.com/assets/17304943/25558636/ac6ea0f4-2cdf-11e7-9d23-ee914143cbe6.PNG)
![capture_3](https://cloud.githubusercontent.com/assets/17304943/25558644/bcde394a-2cdf-11e7-9ed5-f52caebcda90.PNG)

**Comment by PatrickvL** [comment]
What happens when you reconfigure your controllers?

**Comment by BenNottelling** [comment]
@PatrickvL Same issue

**Comment by PatrickvL** [comment]
Sure, you can try that.

**Comment by ObiKKa** [comment]
Nice. Now, can anyone on here mention where to put your dashboard files in to run on this emulator? Is it in the Partition2 folder? But exactly where?

**Comment by Voxel9** [comment]
@ObiKKa The exact path to put the dash files is `C:\Users\**User**\Appdata\Roaming\Cxbx-reloaded\EmuDisk\Partition2\`.

**Comment by blueshogun96** [comment]
I can't get the dash to load anymore.  It fails to find "default.xap" then dies :(

Shogun.

**Comment by BenNottelling** [comment]
@blueshogun96 It still boots for me, check to see if "default.xap" is actually there  :D

**Comment by blueshogun96** [comment]
It isn't, I don't know where it went :(

That HDD has been acting funny ever since it got full last week.  I hope it didn't get corrupted :(

**Comment by LukeUsher** [comment]
CLosing this, as it is purely an input issue, see #28.
