### ISSUE TITLE
Turok Regression (D3D::BlockOnTime not implemented)

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#408]
Can get into the main menu, but when I start a new game it throws up the error 
![capture](https://cloud.githubusercontent.com/assets/17304943/25558742/c24a9ade-2ce1-11e7-9922-ac7713967483.PNG)
Dump/debug:
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966394/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966395/CxbxDebug.txt)

**Comment by NNX3x** [comment]
Same error now appears in The Terminator: Dawn of Fate, before I could get an intro screen.

**Comment by BenNottelling** [comment]
Regressed even more, it now doesn't render anything before crashing.
![capture](https://cloud.githubusercontent.com/assets/17304943/25645561/13bb2e5e-2f64-11e7-8ed7-2db0eacd9755.PNG)

**Comment by PatrickvL** [comment]
This doesn't make sense. We'll look into it

**Comment by blueshogun96** [comment]
Fixed it on my end because I was getting tired of hearing it, lol.  So I made the pull request and we'll wait for the approval.

NOTE: I keep getting a DSoundBuffer_Lock error message now.  Something else must be breaking Turok also.

Shogun

**Comment by PatrickvL** [comment]
Thanks for looking into this. Since Luke commented out an 'int 3', Turok went in-game for me again already. So I just commented them all out, except for two who are followed by a call to that Cxbx kernel panic function (which exists the emulation)

**Comment by LukeUsher** [comment]
Closing as this has been fixed for a while
