### ISSUE TITLE
Tenerezza (JAP) - Crash on Intro splash screen.

### ISSUE THREAD

**Issue by ObiKKa** [Cxbx-Reloaded/Cxbx-Reloaded#409]
Ah, congratulations to jaruppx and his PR #405, this Japanese only game _Tenerezza_ does go into an animated initial loading screen and a crash message immediately shows up after that.
It also boots up much quicker the next time if you don't clear up the HLE cache.

![2017-apr-30_1st-test _01_intro-crash](https://cloud.githubusercontent.com/assets/18428108/25559505/d6d90c18-2d7e-11e7-99a7-d8d8ea55a142.png)
[KrnlDebug_(2017-04-30).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966445/KrnlDebug_.2017-04-30.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#120
