### ISSUE TITLE
Antz Extreme Racing reaches the title screen

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#411]
Antz Extreme Racing reaches the title screen with Cxbx-Reloaded Version 394aee6b (Apr 29 2017)

![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25561842/ec8893c8-2dae-11e7-95a2-ddb751c280b0.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25561843/ecaf41f8-2dae-11e7-8e4f-3055f8367383.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25561844/eccf4174-2dae-11e7-87cd-102b647a645b.png)
__________________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966569/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#119
