### ISSUE TITLE
Test Drive Off - Road Wide Open crashes after the menues

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#412]
Cxbx-Reloaded Version 394aee6b (Apr 29 2017)
_______________________________________________________________________
The game has full sound emulation in the intro videos, but it's has lack of the textures at the menu and instantly crashes before I can start the game 
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25562117/71cf1158-2db7-11e7-9d1e-6faaf3d70684.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25562113/71c8d400-2db7-11e7-9a52-0a4111c03dd5.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25562115/71cd46ca-2db7-11e7-9214-8e98f190dcf3.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25562114/71cc1980-2db7-11e7-8741-8f4c4c46c127.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25562118/71d1beee-2db7-11e7-80ff-e008d19e1e2f.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/25562116/71ceddc8-2db7-11e7-9440-a86419297c2d.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/25540784/25562119/71ee61e8-2db7-11e7-9621-b474600a8931.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/25540784/25562120/71f10894-2db7-11e7-9bc2-898bc2f6bb3a.png)
_________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966585/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
Seeing these scrambled graphics reminded me of something that I forgot to do, which will probably fix this: disable the OOVPA on XgIsSwizzledFormat. Could you try that yourself, and tell us how that affects this title?

**Comment by PatrickvL** [comment]
Oh, wait. The swizzle trick i suggested might not work yet, as my texture conversion improvements are not yet merged (they need to be stabilized first)

**Comment by furrya** [comment]
@PatrickvL  Oh, ok. I will try this trick after the conversion will be implimented. The texture conversion is great work, good luck to you and whole project. ^^

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#118
