### ISSUE TITLE
Iron Phoenix - D3DDEVICE was not found

### ISSUE THREAD

**Issue by fuhuan416** [Cxbx-Reloaded/Cxbx-Reloaded#413]
When i was booted my game, then i recived 'D3DDEVICE was not found!'

**Comment by BenNottelling** [comment]
@fuhuan416 What game?

**Comment by fuhuan416** [comment]
@BenNottelling It's Iron Phoenix.

**Comment by blueshogun96** [comment]
All you gotta do is clear the HLE cache.  You have to do this for each new build to avoid that.

Shogun

**Comment by fuhuan416** [comment]
@blueshogun96 Thank you shogun sama, i did that, then i recieved 'IDirect3D8::CreateDevice failed (Invalid Call)'.
My videocard is Intel HD5000.

**Comment by PatrickvL** [comment]
Sorry, but we can't do much for bug reports like this, without any basic information, like indeed which game you are starting, build number of Cxbx, exact Windows version, log files, etc.

**Comment by PatrickvL** [comment]
So far it seems like your system can't initialize DirectX. If other titles do show something, then it might be an​ issue we could look into. Otherwise it could be that your system isn't capable enough, graphics wise?

**Comment by PatrickvL** [comment]
@blueshogun96 I might be mistaken, so @LukeUsher please correct me if I'm wrong, but under normal circumstances the HLE cache code itself detects if a cache file can be used or not (as it first checks a signature). If I'm right about that, then you've just shared some misinformation, which could cause all sorts of confusion.

Therefore, maybe you're interested to dive into each of these little details, find out how things work, and document it in our wiki? (If you do, I'll even help you when time permits to get the details right.)

**Comment by fuhuan416** [comment]
Guys are great! I updated Cxbx-Reloaded to May 3 version, then i recieved the dialog 'EmuD3DDeferredRenderState was not found!'.
System: Win10 x64
Video Card: Intel HD 5000
Build: [3e872214](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/3e8722149864c0c32a745f2fed5414abfb77ab16)
Logs: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974977/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974978/CxbxDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974979/Xbe.txt)

**Comment by PatrickvL** [comment]
Also see #114

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#117
