### ISSUE TITLE
Xbox Game Disc 18 loads menu and broken sound

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#414]
In this build :  Cxbx-Reloaded Version 394aee6b it appears the xbox game disc is able to load and display its contents with some broken audio. None of the videos show but some audio is heard, the wolfenstein demo does not play either. The credits don't show either on the window. Kernel debug txt is stopped after a few seconds after it loads and sits there.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/967070/KrnlDebug.txt)

First Screen
![xbox game disk 18](https://cloud.githubusercontent.com/assets/3212225/25568665/6166e776-2dcd-11e7-8e04-433a4f703381.png)

Videos
![xbox game disk 18 p2](https://cloud.githubusercontent.com/assets/3212225/25568666/66a51ed8-2dcd-11e7-8f21-33d115936e49.png)

Credits
![xbox game disk 18 p3](https://cloud.githubusercontent.com/assets/3212225/25568679/c91a4232-2dcd-11e7-9bc0-9ce21bd5c8d8.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#116
