### ISSUE TITLE
Breakdown - crash before showing anything

### ISSUE THREAD

**Issue by literalmente-game** [Cxbx-Reloaded/Cxbx-Reloaded#415]
When trying to run the game Breakdown, this shows up:
![err_01](https://cloud.githubusercontent.com/assets/24926584/25570832/1480f050-2dff-11e7-9e2e-1721fb1f69ca.png)

When I choose to ignore the error, the following message shows up:
![err_02](https://cloud.githubusercontent.com/assets/24926584/25570855/4358b96c-2dff-11e7-9d33-0231c51a2fae.png)

Build: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/394aee6b9cf87cd09bb6fad20b27af79b9d8d7c1
Log: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/967258/KrnlDebug.txt)

**Comment by blueshogun96** [comment]
What xdk does it use?

Also, why do debug logs not tell us the XDK version anymore?

Shogun.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#115
