### ISSUE TITLE
Dino Crisis 3 - black screen (with FPS)

### ISSUE THREAD

**Issue by literalmente-game** [Cxbx-Reloaded/Cxbx-Reloaded#416]
No error messages, game stuck at this screen:
![dc3_err_01](https://cloud.githubusercontent.com/assets/24926584/25571089/2fe50d24-2e02-11e7-9edd-3beb29769d88.png)

FPS ranging between 59 to 64.
Build: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/394aee6b9cf87cd09bb6fad20b27af79b9d8d7c1
Log: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/967277/KrnlDebug.txt)

**Comment by BenNottelling** [comment]
Is the fps locked at 63 or does it fluctuate?

**Comment by literalmente-game** [comment]
I've edited the issue with the info, it's ranging from 59 to 64 (no sound, only black screen).

**Comment by BenNottelling** [comment]
@literalmente-game Okay, then that means the emulator hasn't frozen up :)

**Comment by CakeLancelot** [comment]
This title boots fine for me but with abnormally (?) high memory usage (about 3GB).
![cxbx_2017-08-04_09-36-56](https://user-images.githubusercontent.com/5341136/28973493-fcc56668-78f8-11e7-99a3-a6222710a12e.png)


Crashes after selecting difficulty under the new game option. Window becomes unresponsive after closing error messages, have to end task via task manager.
![explorer_2017-08-04_09-41-58](https://user-images.githubusercontent.com/5341136/28973565-35f5b7d0-78f9-11e7-9a23-11560c9649f1.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1200755/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
A question for the title owners... Have you guys let it idle for awhile? Back then, the audio wasn't playing properly. With the current build we have now, it's better. ;)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#114

**Comment by Neltharionx** [comment]
Same for me, black screen , no sounds 
![Dino crisis](https://user-images.githubusercontent.com/57038627/67620316-c7ac6600-f805-11e9-917f-2b8c7ee97857.PNG)
