### ISSUE TITLE
[4847] Dashboard regressed

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#425]
No graphics are rendered before it crashes.

Now:
![capture](https://cloud.githubusercontent.com/assets/17304943/25645491/842b05d4-2f63-11e7-8c21-89192e674ac8.PNG)
Before:
![capture_1](https://cloud.githubusercontent.com/assets/17304943/25645502/99f4f3ca-2f63-11e7-9dd8-3bd6db740cb1.PNG)

**Comment by PatrickvL** [comment]
Hmm. Strange. I'm reasonably sure it was still working with my latest commit to master. We'll look into this

**Comment by LukeUsher** [comment]
I've never seen this version of the dashboard before, I'm actually a little surprised it ever worked ;)
The dashboard I have (3911) still works. We'll look into it, but for now can you try an older dashboard?

**Comment by blueshogun96** [comment]
I never got the dashboard working on Cxbx-Reloaded before.  It keeps complaining about a file "default.xap" that's not even there.  On my old branch, it never seemed to ask for the file.

Kinda strange how certain titles work for some people but not others.  Hmm.

Shogun

**Comment by PatrickvL** [comment]
Often, it turns out we're not all running the exact same binaries.

**Comment by LukeUsher** [comment]
Did you copy the dashboard to the correct location? It needs to be located in EmuDisk/Partition2. 
Old versions of Cxbx just mounted drives as C/D/E/ etc, where Cxbx-Reloaded actually emulated the HDD structure and lets titles setup their own symbolic links. The dashboard specifically creates a symbolic link to EmuDisk/Partition2, and reads files from there.

**Comment by blueshogun96** [comment]
Okay, *that* I didn't know!  So on that note, I'm going to do that tonight.  Not only with Dashboard 3944 but with 4920 so I can continue looking into whether an Xbox Live supported dashboard can actually run.  Thanks.

Shogun

**Comment by PatrickvL** [comment]
We'll get there!

**Comment by blueshogun96** [comment]
Okay, it's confirmed working for me (3944).  Also got 4920 working last night after a couple of quick fixes.

Shogun

**Comment by LukeUsher** [comment]
Updated the title as 3944 and 4920 are working.

**Comment by PatrickvL** [comment]
@blueshogun96 Maybe it's already done, but you mentioned "a couple of quick fixes" - are those committed to master already?

**Comment by BenNottelling** [comment]
Closing as I believe the one of the LLE's was turned on as this was when the check marks were broken for it
