### ISSUE TITLE
[PAL] Madagascar crashes at Activision logo

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#429]
Tested on Cxbx-Reloaded build 36f9e17, May 3 2017

Self explanatory. In Hardware mode, the game will immediately crash at the Activision logo with no video, looping the sound once it has crashed. Software mode has an immediate crash with no audio or video.

Hardware mode crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25686373/c5a5cbca-30c1-11e7-9089-ba953f208053.PNG)

Madagascar (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974961/Xbe.txt)

Hardware mode Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974957/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by blueshogun96** [comment]
Did you ever click ignore to continue?  And see what else happens after that?  That would be more helpful.

Shogun

**Comment by Voxel9** [comment]
@blueshogun96 

![image](https://cloud.githubusercontent.com/assets/16278868/25756998/bf1c072e-31c0-11e7-9ea0-d672f1c09728.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/979834/KrnlDebug.txt)

**Comment by rexcaptain501** [comment]
Tested with 3e5da285 May 8 2017. I don't get any crash, just a black screen with the Activision logo sound, freeze looping (about half a second worth of audio). Nothing else happens.

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build 5ab5ee2, Jul 21 2017.

Still the same sort of thing, but the game seems to output a couple more short audio samples from the start of the Activision logo looping, than before (I think this might be new).

![1](https://user-images.githubusercontent.com/10300935/28485049-ba34e356-6eca-11e7-9386-4338fa7029d0.PNG)

**Comment by rexcaptain501** [comment]
Tested with Cxbx-Reloaded build 3ca1a35, Jul 23 2017

No audio is being outputted anymore. These unimplemented patches look interesting, though.

![1](https://user-images.githubusercontent.com/10300935/28503251-639a5e70-7057-11e7-892a-971e47b18dcb.PNG)

IDirectSound_SetI3DL2Listener
IDirectSoundBuffer_SetHeadroom
IDirectSoundBuffer_SetMixBins



(Relevant Colin McRae Rally 2005 information below)

I noticed that Colin McRae Rally 2005, although not doing anything, crashes with this similar error (CDirectSoundVoice_SetMixBinsVolume):
![cmr05](https://user-images.githubusercontent.com/10300935/28503349-db9dfc96-7058-11e7-907a-60f1f8f922a9.PNG)

**Comment by RadWolfie** [comment]
I'll check this out later this week to see if I can fix audio part unless someone else will beat me to it. :smile:

P.S. The image do shows lots of Read/Write calls, perhaps a patch is missing for audio or something else...

**Comment by RadWolfie** [comment]
@rexcaptain501 please create a new separate issue for Colin McRae Rally 2005, as it is completely different issue from this. I do have a minor update for it.

**Comment by rexcaptain501** [comment]
Thanks @RadWolfie, I've just gone and done that (issue #535). I wouldn't normally post issues of other games in the same report, but I thought it might have been a relevant issue to this game. Thanks for the heads up.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#111
