### ISSUE TITLE
[PAL] Torino 2006 crashes at copyright notice

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#430]
Tested on Cxbx-Reloaded build 36f9e17, May 3 2017

Self explanatory. In Hardware mode, the game will crash after a few seconds. Software mode has an immediate crash with no audio or video.

Hardware mode crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25686442/5878cf06-30c2-11e7-98b8-951b51851d03.PNG)

Torino 2006 (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974968/Xbe.txt)

Hardware mode Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974971/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#110
