### ISSUE TITLE
EmuD3DDeferredTextureState was not found!

### ISSUE THREAD

**Issue by deadair3210** [Cxbx-Reloaded/Cxbx-Reloaded#438]
This appears every time I try to load a dashboard, no matter the version. Am I doing something wrong?
Using version 36f9e171

![dcc](https://cloud.githubusercontent.com/assets/1053504/25731910/030207ec-3110-11e7-9732-efdaaf1bebff.PNG)

**Comment by BenNottelling** [comment]
What versions have you tested? Also are you using the appveyor builds? I noticed this while using an appveyor build and nobody else was experiencing the same issue

**Comment by blueshogun96** [comment]
This only happens for me when running the 5960 version, which happens to be the one he's using.  This does not happen with 3944-4920 for me.

Shogun

**Comment by deadair3210** [comment]
Just this one, and yes its an AppVeyor build

**Comment by LukeUsher** [comment]
Closing this as the dashboards this happens with are LTGC titles and thus unsupported in Cxbx-Reloaded at this moment in time.

Earlier dashboard versions (3944-4920) should be used.
