### ISSUE TITLE
remove exe conversion remnants

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#44]
- Method 1:
```
Steps:
1. Start up Cxbx
2. Open XBE
3. Export Exe
4. Run Exe

Result:
EmuMain (0xXXXX): Recieved Fatal Message:
* Could not map

This error is also thrown if running without Cxbx running.
```

- Method 2:
```
Steps:
1. Go Back to Cxbx, and start emulation
2. Run exe

Result:
<Alias>.exe has stopped working
[Debug] [Close program]
```

- Method 3:
```
Steps:
1. Stop Emulation
2. Run Exe

Result:
Same result as method 2
Upon returning to Cxbx, emulation was started again.
```

- Method 4:
```
Steps:
1. Close and ReOpen Cxbx
2. Run Exe

Result:
Same as Method 1
```

- Method 5:
```
Steps:
1. Load XBE
2. Run Exe

Result:
Same as Method 1
```

- Method 6:
```
Steps:
1. Start Emulation
2. Run Exe

Result:
New Window opens, then same result as method 2
```

- Method 7:
```
Steps:
1. Stop Emulation
2. Run Exe

Result:
Same result as method 6
```
lol, Does not seem to work in any scenario. Where as in Blueshogun's version, the exported exe has the same icon as Cxbx, and works in standalone. The reason I did so many different tries, is that I found on other builds, when starting then stopping the emulation before running the Exe, the Exe would start the emulation in the existing Cxbx instance.

**Comment by PatrickvL** [comment]
Please rename this issue to "remove exe conversion remnants" as you're seeing the remnants of old behavior here.

All related code (including GUI stuff) should be removed, since the xbe is now loaded into memory without conversion, just like Dxbx does.

Exporting xbe to exe is no longer required nor desirable to maintain.

**Comment by BiatuAutMiahn** [comment]
ah ok, noted. I just thought that having a standalone executable would be handy instead of needing the entire emulator.
