### ISSUE TITLE
TechCertGame (5849) - crashes with error

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#445]
Cxbx-Reloaded Version 8c9f308f (May  5 2017)  crashes with error 
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25769737/7cab4e44-325c-11e7-8dfc-d4a03248f9d8.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25769736/7cab5542-325c-11e7-931e-098682d300d2.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25769738/7cab7bee-325c-11e7-862a-4fea27feaf04.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980670/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980671/Xbe.txt)

**Comment by LukeUsher** [comment]
Renamed to include XDK version as there are multiple versions of TechCertGame

**Comment by jarupxx** [comment]
Basically, DirectSound_CDirectSoundVoice_Use3DVoiceData is followed by DirectSound.CDirectSoundBufferSettings.SetNotificationPositions.
Therefore, adding OOVPA of ```IDirectSoundBuffer_SetNotificationPositions``` probably will work.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#107
