### ISSUE TITLE
Metal Arms: Glitch in the System [XDK 5558] [ID - 5655000a] - game crashes at loading screen

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#446]
The game loads, but crashes immediately at loading screen . Cxbx-Reloaded Version 8c9f308f (May  5 2017)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25769844/5d80a480-325f-11e7-8a52-290570ea8ee2.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25769845/5dab17b0-325f-11e7-8fea-d47d78325733.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980679/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980680/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#106
