### ISSUE TITLE
Outlaw Volleyball: Red Hot [XDK 5455] [ ID 53538003] - the game crashes at loading screen

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#447]
Cxbx-Reloaded Version 8c9f308f (May  5 2017) . Outlaw Volleyball: Red Hot crashes at loading screen
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25769931/d00cf7e0-3261-11e7-9f27-4d33320734b2.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980683/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980684/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#105
