### ISSUE TITLE
Alien Hominid [XDK 5849] [ID 5A440004] - the game plays too fast and controller doesn not work

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#448]
Cxbx-Reloaded Version 8c9f308f  Alien Hominid plays too fast and controller doesn not work (May  5 2017)![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25770082/35854910-3267-11e7-8e58-475e56e6c9b6.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25770080/3584aff0-3267-11e7-9d6a-23059a1216e1.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25770081/35854da2-3267-11e7-95fd-2f9307546fd8.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980699/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980701/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#104
