### ISSUE TITLE
NBA Live 2002 [XDK 3948] [ID 45410003] - the game loads only when debug output (kernel) sent to the console

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#449]
Cxbx-Reloaded Version 8c9f308f (May  5 2017). NBA Live 2002 loads only when debug output (kernel) sent to the console
  ![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25770133/605bf6a6-3268-11e7-9524-c11a75f402b4.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980704/Xbe.txt)
[NbaKrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980706/NbaKrnlDebug.txt)

And instantly crashes when debug output (kernel) sent to the file 
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25770193/d4415bf0-3269-11e7-8563-11ec464ba0f0.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/980714/KrnlDebug.txt)

Similar issue is #315

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#103
