### ISSUE TITLE
Unreal Championship: Intro then crash

### ISSUE THREAD

**Issue by Nrw1337** [Cxbx-Reloaded/Cxbx-Reloaded#451]
Displays the intro logos correctly if vsync is forced otherwise the screen will flicker, then plays the wmv logo files in a small panel upper left on the screen. Finally, it reaches the main menu load splash screen and crashes.

Intro logo:

![screenshot_112](https://cloud.githubusercontent.com/assets/25694960/25784171/c134a770-3371-11e7-825f-31fce7367224.png)

Crash point:
![image](https://cloud.githubusercontent.com/assets/25694960/25784285/b0766788-3372-11e7-9957-bb79776c6001.png)

Crash:
![screenshot_113](https://cloud.githubusercontent.com/assets/25694960/25784172/c2cc2d10-3371-11e7-8e1d-d56829f99101.png)

Build: cd50eeba (May 7 2017)
Log: 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/981868/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/981870/CxbxDebug.txt)

**Comment by blueshogun96** [comment]
It doesn't seem to like the way it handles mip map generation.  I'm remains a mystery to me...

Shogun

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#102
