### ISSUE TITLE
[PAL] Lego Star Wars graphical corruptions and no audio

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#454]
Tested on Cxbx-Reloaded build 3e5da285, May 8 2017

Very promising progress. No audio. Menus and ingame have weird permanent speed ups (e.g. characters move around like nuts), but enabling Force VSync helps stabilize the speedup. There's an odd white overlay colour in most places throughout all game features (in most menus and ingame, e.g. main menu, walking around ingame, level mode selection and level crawl intro etc.). Kernel Debug console is constantly whining about 'Trying fixed or recompiled programmable pipeline pixel shader!' and 'EmuD3DDevice_SetScreenSpaceOffset ignored'.

The copyright screen now appears (I don't think it did before?): 
![12](https://cloud.githubusercontent.com/assets/10300935/25830044/450074b6-34ae-11e7-8d59-ad5f945837e1.PNG)

Level crawl intro example: 
![13](https://cloud.githubusercontent.com/assets/10300935/25830128/e9a935a2-34ae-11e7-9844-28ec987a3715.PNG)

Dexter's Diner: ![1](https://cloud.githubusercontent.com/assets/10300935/25828644/6f27395e-34a5-11e7-999d-074be4af472c.png)

The game thinks that two controllers are plugged in and pressing start to pause the game has the side effect of the game thinking that you are now both players (possibly because two controller support hasn't been implemented). Instead of a darkened transparent effect when you pause the game, the pause menu is black.

Pause menu example: 
![14](https://cloud.githubusercontent.com/assets/10300935/25830268/cf3a97dc-34af-11e7-89f4-ff6052866692.PNG)

Some terrain is slightly corrupted and can have transparency problems.

Transparency problem example (note the two red circles placed in the emulation image for example, you might need to click into the image and zoom to see it): ![1](https://cloud.githubusercontent.com/assets/10300935/25842677/eb6a2816-34f8-11e7-9889-625430ac4854.jpg)

Player minifigures don't appear correctly, just showing corrupted feet shadows. NPC minifigures seem to appear, besides from Dexter at the shop (the FLO NPC 'foot' shadow works, identical to player minifigures). Most basic features seem to be working fine (using the Force, breaking objects, collecting studs, speed of walking according to analog stick pull etc.). Weird corrupted drawing in the middle of the screen, it might be related to the player minifigures? Transition fades seem to work when entering the diner for the first time, but don't trigger when entering a different room. When entering a different room, it doesn't stop you from moving your character before the transition effect finishes, likely because there is none. Floor reflections are fine but don't appear for minifigures (likely because none are appearing?). A lot of LEGO objects are invisible.

Minifigures: ![2](https://cloud.githubusercontent.com/assets/10300935/25828754/160ffd8c-34a6-11e7-95f5-8d45fb7e6263.PNG)

FLO NPC minifigure 'foot' shadow example (note red circle placed for example, other two sets of shadows are of the players' characters feet): 
![12](https://cloud.githubusercontent.com/assets/10300935/25829958/bd7f8cd4-34ad-11e7-9aed-614ecd159a89.PNG)

Corrupted drawing example 1: 
![7](https://cloud.githubusercontent.com/assets/10300935/25829294/55095dfa-34a9-11e7-8f68-d8d37e410f2d.PNG)

Corrupted drawing example 2: 
![11](https://cloud.githubusercontent.com/assets/10300935/25829731/45addc8e-34ac-11e7-9d13-0c2a0a3f70f7.PNG)

Force-able object: ![3](https://cloud.githubusercontent.com/assets/10300935/25828878/e46deac2-34a6-11e7-968c-01bd14227466.PNG)

Lightsabers don't have any colour. All actions seem to be working properly.

Lightsabers: ![4](https://cloud.githubusercontent.com/assets/10300935/25828994/9fc3de44-34a7-11e7-8495-9223d944b8da.PNG)

Episode 1 Level 1's starting cutscene will work for a few seconds before crashing (* ClampToEdge is unsupported (temporarily)).

Episode 1 Level 1 crash: ![5](https://cloud.githubusercontent.com/assets/10300935/25829075/2e45986a-34a8-11e7-9cf6-1fb4c1fdd6d8.PNG)

Episode 1 Level 1 crash Kernel Debug log: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985256/KrnlDebug.txt)

Entering most shop menus causes a crash.

Dexter's Diner shop menu crash example (scrolling through characters menu): 
![17](https://cloud.githubusercontent.com/assets/10300935/25831537/14bae218-34b9-11e7-9d8c-f592f02e0acc.PNG)

Scrolling through characters menu crash Kernel Debug log: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985228/KrnlDebug.txt)

Overlay titles seem to be working but usually don't draw correctly.

Bad drawing 1: ![8](https://cloud.githubusercontent.com/assets/10300935/25829421/1b837d9e-34aa-11e7-877e-7c537bbf1371.png)

Bad drawing 2: 
![10](https://cloud.githubusercontent.com/assets/10300935/25829764/a265009c-34ac-11e7-8956-e78e8fd63405.png)

I haven't covered absolutely everything, but this is pretty comprehensive.

Lego Star Wars (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985032/Xbe.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)
Force VSync enabled

**Comment by PatrickvL** [comment]
Old issue : #403

**Comment by LukeUsher** [comment]
Possibly the most detailed bug report I have ever seen, consider myself impressed

**Comment by PatrickvL** [comment]
Thanks for the detail in this report - one thing that stands out is how 'bland' everything looks. That's why I've started to look into render-states, specifically back porting the code I wrote for that in Dxbx. I'll do the same with texture-states after that, and let's see what the output looks like then.

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build 14e59d6e, May 12 2017. Some things have regressed, such as text and 3D graphics colour.

Text on the language screen is gone (if you wait for 20 seconds it skips through to the main menu without selection): ![language screen](https://cloud.githubusercontent.com/assets/10300935/26018404/d8bd2c5a-37c2-11e7-93b5-5595fe746f0b.PNG)

"A long time ago in a galaxy far, far away...." screen has disappeared.

Main Menu has lost text and now fades through a few colours, which shouldn't happen (might be related to other colour problems covered down below in this comment): 

Example 1: ![main menu colour](https://cloud.githubusercontent.com/assets/10300935/26018445/1facb1d0-37c3-11e7-9891-6411b9400d18.PNG)

Example 2: ![colour 2](https://cloud.githubusercontent.com/assets/10300935/26018627/281a310c-37c4-11e7-82bf-ecc0daae6d03.PNG)


When loading the Main Menu inactivity cut scene, the game crashes: ![main menu crash](https://cloud.githubusercontent.com/assets/10300935/26018643/3ab22c02-37c4-11e7-95a5-b11b6114ff33.PNG)

Pause menu has lost text (basically, all text in the game is gone): ![missing text](https://cloud.githubusercontent.com/assets/10300935/26019525/ed1661a6-37c9-11e7-8ae7-ee3a45e9d581.PNG)


Lots of things going wrong in this screenshot and area. Lightsabers and LEGO objects are now black, other objects are black, force field particles don't work and walking into them effect doesn't appear, feet shadows are now gone: ![diff](https://cloud.githubusercontent.com/assets/10300935/26018888/cdcd1c76-37c5-11e7-8a84-ef37bbe15842.png)

Press START text is now gone (unlike previous tested build):
![start](https://cloud.githubusercontent.com/assets/10300935/26018924/0c0f6be2-37c6-11e7-94f4-b5f13a8c1f0a.PNG)


Colours are messed up in pretty much all locations for most objects: 
![colours](https://cloud.githubusercontent.com/assets/10300935/26018953/3c2bdc48-37c6-11e7-8be1-dc005e53a8d9.PNG)

Stud Counter text is missing: 
![stud counter](https://cloud.githubusercontent.com/assets/10300935/26018963/4fa7f86a-37c6-11e7-816f-423bd26b8861.PNG)

In some cases (usually near walls) triangle feet shadows can be faintly seen (more similar than the last tested build to the real game in a way, note red circle for example), also note that the corrupted drawing is now black rather than white: 
![feet](https://cloud.githubusercontent.com/assets/10300935/26019031/9f2e768e-37c6-11e7-8c51-5e9a1eea79c1.PNG)
 
Crawl text is now gone: 
![crawl](https://cloud.githubusercontent.com/assets/10300935/26019134/5704b200-37c7-11e7-93c5-baf327ee4220.PNG)

Textures are now more corrupted than before (they were already pretty corrupted in the previously tested build, though. Note in Example 1 red ship on the left, CIS ship on the right seems to be fairly similar, if not a bit more corrupted, than the last tested build): 

Example 1: ![texture 1](https://cloud.githubusercontent.com/assets/10300935/26019140/62ab2b3e-37c7-11e7-8f2e-be908e9d7356.PNG)

Example 2: 
![texture 2](https://cloud.githubusercontent.com/assets/10300935/26019149/7b780c18-37c7-11e7-8225-392b5c36c98e.PNG)

**Comment by PatrickvL** [comment]
There are two possible reasons I can think of that might have caused this; I DISABLED a patch on Get*Desc, which only reads from the D3D resource, so doesn't need patching - except that we currently alter the textures on the Xbox side. I'm working on an improvement which will fix that. Another reason could be that I unlock more often (at least every time a new lock is required). This also will be fixed by the same changes.
Furthermore, I'm busy back porting all genetic render state conversion code from Dxbx, which will probably improve a few of the visual artifacts you're seeing now.
So, all in all, thing will improve, it just takes time.

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build 2ef0c063. I've been having trouble getting controls to work for the past few builds, including 14e59d6 and 2ef0c063. I can only get controls working with random troubleshooting efforts (hard to explain, usually consists of mashing buttons, getting the game to get past the language screen menu, then stopping and starting emulation). Text looks to be working again and the main menu inactivity cut scene (even though it's still broken) doesn't seem cause a crash anymore.

**Comment by PatrickvL** [comment]
@rexcaptain501 thanks for the feedback. controller input stopped working ​for me too @LukeUsher care to take a look?

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build bceef183 (May 14 2017). Controls seem to be working again. I had a bit of trouble first time around booting getting past the language screen (might be nothing/XInput playing up for a few seconds for some reason?). All behaviour from build 14e59d6 is gone and everything is now back to build 3e5da28 behaviour. One thing that I didn't mention previously is that lightsaber swing colours work properly:
![swing](https://cloud.githubusercontent.com/assets/10300935/26047913/2b7f7172-39a9-11e7-8a41-608044745474.png)


Main menu is still fading through colours. I'm not sure what build this started happening (I don't think it was doing this around the time of issue #403, I'm not entirely sure).

**Comment by rexcaptain501** [comment]
Just a couple of notes. I'm not sure if the main menu colour fading happens in the game on Xbox hardware. In emulator, I noticed that pressing up/down with either the analog stick or d-pad with an Xbox 360 controller in the Options menu causes the selection highlight to skip up to the top/bottom, rather than one-by-one.

Tested on Cxbx-Reloaded build 5ab5ee21, Jul 21 2017

The game is throwing a D3DDevice_EnableOverlay error after pressing New Game on the main menu.

![1](https://user-images.githubusercontent.com/10300935/28484907-71f76e3e-6ec9-11e7-9083-9c0b0e8c1198.PNG)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1166893/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
Weird, the behavior of this title has not changed for me: It works just fine for me. Well, the same has before anyway ;)

As for the DPAD issues, it's probably that the game controller code is running too fast, making it read the controller more often than expected.

**Comment by rexcaptain501** [comment]
Tested with Cxbx-Reloaded build 3ca1a354, Jul 23 2017

The error is gone now, weird. Everything is working as before.

**Comment by RadWolfie** [comment]
@rexcaptain501, not sure if you're aware of this. By default XADPCM codec is set to "silent" or in other word, "disabled". if you do enable it via audio settings, you will get audio, currently it is looping, from it. It is a start yet still incomplete.

**Comment by rexcaptain501** [comment]
Thanks for the tip, I didn't check out LEGO Star Wars. Yeah, I can also confirm that it's working yet looping with XADPCM.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#101
