### ISSUE TITLE
[PAL] Splinter Cell Pandora Tomorrow online mode crashes when finished loading (Online.xbe)

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#455]
Tested on Cxbx-Reloaded build 3e5da285, May 8 2017

(Please note, this behaviour is for Online.xbe [Multiplayer], not default.xbe [mode selection menu] or Offline.xbe [Single-player]). Online mode crashes when finished loading.

Crash: ![1](https://cloud.githubusercontent.com/assets/10300935/25838773/d575f680-34e8-11e7-8db7-aa4b4d3a9581.PNG)

Splinter Cell 2 online mode (Online.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985722/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985740/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by rexcaptain501** [comment]
I should also mention that the green bar in the middle of the loading bars fully "loads" before the other two appear and the whole thing starts again before crashing two seconds after they all finish loading. This doesn't happen on Xbox Hardware.

Looks like this first:
![scpt](https://user-images.githubusercontent.com/10300935/28503860-012e7db0-7062-11e7-9561-7eaf5ce9b72e.PNG)

Then after that bar fully loads, this at the crash (how it appears on Xbox Hardware):
![scpt 2](https://user-images.githubusercontent.com/10300935/28503871-1f09711e-7062-11e7-97bc-873ad14fcaac.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#100
