### ISSUE TITLE
[PAL] MTX Mototrax crashes when loading

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#456]
Tested on Cxbx-Reloaded build 3e5da28, May 8 2017

The game gets to the loading screen and crashes. When it crashes it will also crash Cxbx-Reloaded.

Crash: 
![1](https://cloud.githubusercontent.com/assets/10300935/25838991/d2fc2932-34e9-11e7-9ef8-f24be9790ac9.PNG)

MTX Mototrax (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985782/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/985784/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#99
