### ISSUE TITLE
Sneak King [4D5300D3] - Crashes after initial loading screen

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#457]
~~As of 3e5da28 the game will show a loading screen but crash promptly afterwards.~~
See updated comment

![explorer_2017-05-09_19-46-23](https://cloud.githubusercontent.com/assets/5341136/25878445/51420856-34f0-11e7-9882-b6eafdca66ad.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/988376/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/988380/Xbe.txt)

**Comment by CakeLancelot** [comment]
This game gets slightly further now. Instead of crashing instantly the loading screen will animate for a bit then crash with a different error.
![2017-08-04_07-44-03](https://user-images.githubusercontent.com/5341136/28969111-d896a686-78e8-11e7-810f-e7aca24fdb22.gif)
![cxbx_2017-08-04_07-44-53](https://user-images.githubusercontent.com/5341136/28969112-d89c8a60-78e8-11e7-8e40-b28b7c66ed35.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#98
