### ISSUE TITLE
OpenBORX v4 - EmuXB2PC_D3DFormat: Unknown Format

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#46]
When emulating "[OpenBORX - Beats of Rage for XBox v4](http://www.realmodscene.com/xbins/XBOX/Console%20Based%20Applications/games/BeatsOfRageX)"  an Unknown format is encountered.
```
EmuD3D8 (0x2A90): EmuIDirect3D8_CreateDevice
(
   Adapter                   : 0x00000000
   DeviceType                : 0x00000001
   hFocusWindow              : 0x00000000
   BehaviorFlags             : 0x00000040
   pPresentationParameters   : 0x0FBEA304
   ppReturnedDeviceInterface : 0x0FBEA348
);
BackBufferWidth:        = 640
BackBufferHeight:       = 480
BackBufferFormat:       = 0x00000016
BackBufferCount:        = 0x00000001
SwapEffect:             = 0x00000001
EnableAutoDepthStencil: = 0x00000001
AutoDepthStencilFormat: = 0x00000050
Flags:                  = 0x00000001

EmuD3D8 (0x455C): CreateDevice proxy thread recieved request.
EmuD3D8 (0x455C): CreateDevice proxy thread releasing old Device.
EmuWarn (0x455C): X_D3DFMT_LIN_R8B8 -> D3DFMT_R5G6B5
EmuMain (0x455C): Recieved Fatal Message:

* EmuXB2PC_D3DFormat: Unknown Format (0x00000050)
```

**Comment by PatrickvL** [comment]
This happened a lot in Dxbx too. We're still copying over fixes from there, perhaps one of these could fix this message, don't know for sure.

**Comment by LukeUsher** [comment]
This is especially weird because on the Xbox, the highest D3DFMT in the XDK is 0x41. Perhaps a look in the source code of OpenBORX is in order.

**Comment by BiatuAutMiahn** [comment]
It seems that the source does contain some common xbox headers and source, but when I skimmed all the headers, I see no headers that have formats that resolve to 0x50, odd, and i cannot seem to find any other source for the project with google.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#195
