### ISSUE TITLE
[DEMO OXM 14] Panzer Dragoon Orta, 60 fps, full playable

### ISSUE THREAD

**Issue by zaykho** [Cxbx-Reloaded/Cxbx-Reloaded#467]
The Audio crash in PDO is already a known issue, but by doing some hack inside the game folder, I was able to play the full demo of the game, and this at 60 fps (200+ with v-sync off), here some picture.

http://imgur.com/a/g8DxW

2 things was added in that folder, first one is a d3d8.dll from ninja ripper, that disable lightning and fog, and make the game more easy to play, secondly, a replacement hack as been made to bypass the audio problem, by replacing those files:

oxm_14\pdodemo\media\sound\SoundDragon.pwv
oxm_14\pdodemo\media\sound\SoundStage1.pwv

by 

oxm_14\pdodemo\media\sound\SoundSystem.pwv 

and then renaming to their old name, doing this let the game play normally, with a better speed ( seems the audio issue was also slowing down this part of the game)

Now, the game can crash sometime randomly after, but if you pause the game and don't go too fast from the level, you can actually finish it.

I will try to record a video later if I can, I will also try to see if I can reproduce something like that for the FMV crash on the retail one. Also, speaking about the retail one, I tried to load a save game file (100% completed) to see if we can load any level and bypass the FMV, but for some reasons, impossible to make it work, no matter the same region and ID of the savefile, the game always said the save is damaged.

**Comment by LukeUsher** [comment]
In order to use savedata from a real xbox console, you will need to have the xbox encryption keys dumped and saved as "%AppData%\Cxbx-Reloaded\Keys.bin" 

Keys.bin should be a 32-byte file where the first 16 bytes are your Xbox LAN key, and the second 16 bytes are the Xbox Signature Key. For legal reasons, we cannot distribute the contents of this file.

You should be able to dump the keys from a real xbox with this tool:
https://github.com/JayFoxRox/xqemu-tools/blob/master/dump-xbox.c

**Comment by zaykho** [comment]
Oh nice.

I have my xbox (well 3) but I can't use it right now, since my new screen doesn't support anymore the Av cable and the box converter is dead.

Though, I did made a backup of my main HDD (softmod) on PC, so surely if I can get back those key, I would be able to build the Keys.bin from scratch.

**Comment by zaykho** [comment]
So, I did find back my backup ( HDD + EEPROM backup), and tried to create the Keys.bin from scratch by making a 32-byte file and adding my XBOX ONLINE KEY + XBOX HDD KEY, so 16 bytes + 16 bytes.

Then did put inside the C:\Users\zaykho\AppData\Roaming\Cxbx-Reloaded, where EEPROM.bin and memory.bin are located, but still, it doesn't work.

**Comment by LukeUsher** [comment]
You need the LAN Key and the Signature Key for Keys.bin, the signature key being the most important for SaveData. The HDD key is not the same.

The signature key has to be extracted from RAM on a running Xbox

**Comment by zaykho** [comment]
Ok, so the only way is to boot up the xbox, I will need to buy a new box vga converter for that. : |

**Comment by zaykho** [comment]
EDIT: added a video.

https://www.youtube.com/watch?v=gFVDUUWF-Jo

**Comment by zaykho** [comment]
EDIT: added a picture of the boss battle

http://imgur.com/a/hS4eZ

I will admit, It's pretty tough to fight that boss without seeing much, I will try cheat engine to see if I can get a "god mode" out of it, this will help to record a video about the whole demo....

**Comment by zaykho** [comment]
LAST EDIT:

Beaten the boss and completed the whole demo -- >  http://imgur.com/a/n3cSF

(done with  Cxbx-Reloaded bceef183 (May 15 2017), v-sync on and YUB enabled)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#97
