### ISSUE TITLE
XLoadSection XUnloadSection Unimplemented.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#47]
I encounter this from time to time, and it looks like it functions as follows:

XLoadSection(pLSTR):
-find section in XBE, using pointer to string.
-Load section in memory
-Return pointer to address

XUnloadSection/XFreeSection(pPointer):
-Clear memory

**Comment by LukeUsher** [comment]
We don't currently implement XeLoadSection/XeUnloadSection but for most titles it doesn't seem to matter, I have not yet seen a circumstance that breaks because of this.

We should implement it eventually, but there are other areas that are more important at this point

**Comment by PatrickvL** [comment]
The XeLoadSection and XeUnloadSection kernel API's were recently updated. They now act like they work, even though there's no actual loading/unloading being done (a LOG_INCOMPLETE is hit when this was supposed to happen).

This doesn't matter until we ever encounter an XBE with section that have overlapping virtual addresses.
For now, let's close this issue.
