### ISSUE TITLE
Burnout 1 regression - crashes with "EmuD3DDeferredRenderState was not found!" at startup

### ISSUE THREAD

**Issue by MrDiffin** [Cxbx-Reloaded/Cxbx-Reloaded#472]
Don't know when this started happening, but I do know that I was able to get to the track selection screen before this, but now this error shows up as soon as I try to run the xbe. I don't get any visuals from the game itself. The reason I'm making a separate issue about this is because this crash isn't what's preventing Burnout from going in-game, and is a different issue (by the looks of things.)

![image](https://cloud.githubusercontent.com/assets/8225831/26262786/df7c78b0-3ccd-11e7-9c40-fa7993b9175d.png)

When I try to start the game after clearing HLE cache, I instead get a crash with this error:

![image](https://cloud.githubusercontent.com/assets/8225831/26262804/f6daf810-3ccd-11e7-9bb9-f5e5b11e0e16.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1015263/KrnlDebug.txt)

**Comment by BenNottelling** [comment]
Interesting, I know on my computer everything seems to be broken and it often is a similar error, when I went to compile the project VS complained about missing windows xdx (or it was SDK, I can't remember).
So far I have noticed it is alway an OutputDebugString error for everything I test. as shown by issue #425 and https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/408#issuecomment-298803619

**Comment by PatrickvL** [comment]
@DisorderIy You seem have all experimental LLE support turned on. Turn them all off and try again.

**Comment by DisorderIy** [comment]
I tried it again with an Appveyor build, and I'm not getting that error anymore, but there's a black screen on startup, leading to a crash with no error message. This is with b83cc6f8bc3c816de8ac67a84b07d96bf5050e2d.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1015735/KrnlDebug.txt)

**Comment by francot514** [comment]
Got similar error trying to emulate Commandos Strike Force.
![csferror](https://cloud.githubusercontent.com/assets/6117358/26378724/6825060e-3fdb-11e7-982f-bfc929c0179e.png)

**Comment by LukeUsher** [comment]
Closing this as it appears a bad build was being used for Burnout.
