### ISSUE TITLE
Controls issue on Logitech Dual Action

### ISSUE THREAD

**Issue by nataliejean2412** [Cxbx-Reloaded/Cxbx-Reloaded#477]
The controls setup is not reading both the dPad and left analog stick of the Logitech Dual Action at the same time, instead opting to read one at a time, depending on what the mode switch is set to. It appears to be reading them both as the dPad.

**Comment by CakeLancelot** [comment]
Probably related to #247

**Comment by LukeUsher** [comment]
Are you able to restest this with with the latest commit? Pull request #484 added proper XInput support.

Please not that XInput mappings are currently hardcoded, enabling XInput completely bypasses the Configure Controller dialog.

**Comment by LukeUsher** [comment]
Closing this due to no response: For future discussion use Issue #156

**Comment by nataliejean2412** [comment]
Sorry, computer fried not long after this report, and the controller was lost as well.
