### ISSUE TITLE
Star Wars Kotor II Main Menu Crash

### ISSUE THREAD

**Issue by haradons** [Cxbx-Reloaded/Cxbx-Reloaded#478]
I was able to get KOTOR II boot to the main menu. From starting emulation to the main menu, the beginning video flickers with distorted audio then gives distorted audio at the main menu.
![image](https://cloud.githubusercontent.com/assets/13687549/26430563/04b84db0-40a3-11e7-891b-92be475f50db.png)
![image](https://cloud.githubusercontent.com/assets/13687549/26430567/0f9ceaf6-40a3-11e7-9ce5-e35b952ea666.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1027572/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#96
