### ISSUE TITLE
Start Button Not Working On Xbox One Controller

### ISSUE THREAD

**Issue by JackaJacka123** [Cxbx-Reloaded/Cxbx-Reloaded#481]
I have repeated bound the menu button on the Xbox One controller as start in Cxbx Reloaded, though it never seems to take effect. I am running the latest version of Cxbx Reloaded, Windows 10 Pro Creators Update, and the game I am trying to emulate is Jet Set Radio Future.

![capture](https://cloud.githubusercontent.com/assets/29109131/26658817/6eca66ce-4621-11e7-95ab-2d3f7ba3d8e2.PNG) - Game Running with mapping saying that it was successful. Yes I did press accept.

**Comment by PatrickvL** [comment]
This is probable related to #336

**Comment by LukeUsher** [comment]
Input has a few problems at the minute, it will be worked on as part of the new GUI, which is about third item down on my to-do list.
