### ISSUE TITLE
(PAL) MTV Music Generator 3: Black screen on some hardware

### ISSUE THREAD

**Issue by hinksta47** [Cxbx-Reloaded/Cxbx-Reloaded#482]
UPDATE: Game is playable! I tested it on my PC with an NVidia GTX 750Ti and the graphics show almost perfectly. In game framerate seems to be way too high, but this is fixed by forcing vsync.

![capture](https://cloud.githubusercontent.com/assets/29108562/26661915/eccf3cdc-46c3-11e7-8333-fec2485ac0b6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/29108562/26661916/ecd1ee78-46c3-11e7-8dee-d0795ce3c514.PNG)
![capture3](https://cloud.githubusercontent.com/assets/29108562/26661914/ecce64f6-46c3-11e7-8503-05828e189e22.PNG)
![capture4](https://cloud.githubusercontent.com/assets/29108562/26661917/ecda6364-46c3-11e7-990e-7041ce9b6d8c.PNG)

The game does not show graphics but game music runs and can browse game menus. Once something has been selected in the main menu it shows this. Has not thrown an error code for me yet.
![capture](https://cloud.githubusercontent.com/assets/29108562/26658746/90045546-46af-11e7-82db-61375f54ff47.PNG)

[log.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1043286/log.zip)

**Comment by literalmente-game** [comment]
If you can, run the game again to get the log with more details and add to your issue.

**Comment by hinksta47** [comment]
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1043263/Xbe.txt)
[log.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1043276/log.txt)

the actual log file was over 10mb. Let me know if you'd like me to upload the full file to a file hosting site.

**Comment by literalmente-game** [comment]
Use 7zip do compact it and link it here. Also, you don't need to create another comment, edit your main issue post to add the links.

**Comment by JackaJacka123** [comment]
Also have you tried forcing V-Sync? That may fix the running too fast issue

**Comment by blueshogun96** [comment]
Way to go, but I wouldn't exactly call it playable.  More like ingame, assuming you can get a game session to start.

Shogun

**Comment by blueshogun96** [comment]
Oops, I missed the part where you said it was literally playable, sorry about that.  Do you have fraps installed?  If so, what are your frame rates?

Shogun

**Comment by LukeUsher** [comment]
Updated the issue title to reflect that this title has issues rendering on certain hardware. It would be good if anyone with this game could test it, share their results and tell us what hardware they have

**Comment by literalmente-game** [comment]
I'll test it again later to post my log, so far most of the graphics are showing (with the last public build), music is playing with no problems with correct timing.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#93
