### ISSUE TITLE
(PAL) Magic the Gathering: Battlegrounds demo - intros

### ISSUE THREAD

**Issue by hinksta47** [Cxbx-Reloaded/Cxbx-Reloaded#483]
Title appears to run intro music then crashes. Demo is from OXM23 demo disc, which doesn't run at all.
![capture](https://cloud.githubusercontent.com/assets/29108562/26659290/e3b12554-46b2-11e7-90f8-d8e9b0fed91a.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#92
