### ISSUE TITLE
[NTSC-U] Midway Arcade Treasures 3 - crashes at initial loading screen

### ISSUE THREAD

**Issue by GeekyFerret** [Cxbx-Reloaded/Cxbx-Reloaded#488]
Upon booting, the game will display the loading screen for a few seconds before crashing.
Recieved Exception Code 0xC0000005 @ EIP := 0x0001A77F(=unknown+0x0)
[default.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079577/default.txt)

![mat3-loading](https://user-images.githubusercontent.com/28161000/27195427-5c61a5fe-51cc-11e7-8ca4-78b4a4c2344e.png)

Since this game has multiple executables, you can load those to boot directly into each game and each of them work to varying degrees.

Badlands (Badlands.xbe) crashes at a glitched loading screen.
Recieved Exception Code 0xC0000005 @ EIP := 0x0002A7EF(=XMountUtilityDrive+0x5c7a)
[Badlands.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079578/Badlands.txt)

![mat3-badlandsloading](https://user-images.githubusercontent.com/28161000/27195651-302b43a4-51cd-11e7-8fd1-14037d329c0a.png)

Hydro Thunder (Hydro_xbox.xbe) just crashes at a black screen.
Recieved Exception Code 0xC0000005 @ EIP := 0x00085CEB(=unknown+0x0)
[hydro_xbox.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079579/hydro_xbox.txt)

Super Off Road Track Pak (newOffroad.xbe) crashes at a glitched loading screen (see above).
Recieved Exception Code 0xC0000005 @ EIP := 0x0002A36F(=XMountUtilityDrive+0x7b26)
[newOffroad.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079580/newOffroad.txt)

Off Road Thunder (Offroad.xbe) displays menus but crashes once you select a track.
Recieved Exception Code 0xC0000005 @ EIP := 0x040384FB(=XInputSetState+0x3e03182)
[Offroad.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079584/Offroad.txt)

![mat3-offroadthundermenu](https://user-images.githubusercontent.com/28161000/27196121-e9cf9e94-51ce-11e7-8dee-4ede9214b7e5.png)

Super Off Road (oldOffroad.xbe) crashes at a glitched loading screen (see above).
Recieved Exception Code 0xC0000005 @ EIP := 0x0002A36F(=XMountUtilityDrive+0x7b26)
[oldOffroad.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079585/oldOffroad.txt)

Race Drivin' (Racedriv.xbe) crashes at a glitched loading screen (see above).
Recieved Exception Code 0xC0000005 @ EIP := 0x0003CECF(=XMountUtilityDrive+0x5c6e)
[Racedriv.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079586/Racedriv.txt)

Rush 2049 (rush.xbe) displays the title screen but crashes as soon as you press start.
Recieved Exception Code 0xC0000005 @ EIP := 0x040384FB(=XGetDeviceChanges+0x3e73a2c)
[rush.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079587/rush.txt)

![mat3-rush2049title](https://user-images.githubusercontent.com/28161000/27196586-a181da06-51d0-11e7-844f-9ab6042626d7.png)

Rush: The Rock (Rock.xbe) displays the first frame of the title screen then crashes.
Recieved Exception Code 0xC0000005 @ EIP := 0x63FA0F10(=XInputSetState+0x63e1d817)
[Rock.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079588/Rock.txt)

![mat3-rushrocktitle](https://user-images.githubusercontent.com/28161000/27196738-58fc6912-51d1-11e7-8fd2-dcff0af9435b.png)

Stun Runner (Stunrun.xbe) crashes at a glitched loading screen (see above).
[Stunrun.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1079589/Stunrun.txt)

Recieved Exception Code 0xC0000005 @ EIP := 0x000330AF(=XMountUtilityDrive+0x5b9e)

**Comment by literalmente-game** [comment]
If you can, provide the log of each test (just edit your issue to add the logs, you don't have to link them on a new comment).

**Comment by LukeUsher** [comment]
At a glance, it looks to me like the majority of this is caused by a missing HLE patch. I have access to the PAL version of this title, I'll investigate and see if that has the same issue

**Comment by LukeUsher** [comment]
Update: The PAL version behaves quite differently from this, and I don't have access to the NTSC version for testing.

I'll look into fixing the PAL version (which currently crashes with a black screen on ALL xbes) and hopefully, it will alllow the NTSC version to also progress further

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#91
