### ISSUE TITLE
Jet Set Radio Future is slow and glitchy 

### ISSUE THREAD

**Issue by chrisderwahre** [Cxbx-Reloaded/Cxbx-Reloaded#489]
If you run jet set radio future on cxbx reloaded it is slow and glitchy(glitchy = textures sometimes glitch away, sound sounds creepy) (slow = game is running 4 or 3 times slower than normal!)

**Comment by literalmente-game** [comment]
This is not a real issue, the emulation is far from complete or even playable state now and the info you've posted is known for months already. If you want to post useful information, test a game that was not tested before (search for the issues here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues before posting), create a new issue with this:
- What build you're using
- A screenshot (if it's a visual problem)
- The log of the test

**Comment by LukeUsher** [comment]
@literalmente-game is right, there is no information in this report and we already have an issue for JSRF #251 

Closing this

**Comment by bokhader** [comment]
Hi, I have the same issue in Yugioh the dawn of destiny the games turns very slow as soon as I start a game ( duel ) so is there a way to fix it ?

**Comment by PatrickvL** [comment]
@bokhader apart from using a faster computer, the only other way to make Cxbx-Reloaded faster, is by contributing improvements to the code
