### ISSUE TITLE
Project Velocity won't run.

### ISSUE THREAD

**Issue by autobotlongarm** [Cxbx-Reloaded/Cxbx-Reloaded#502]
So I downloaded some game called Project Velocity debug from theisozone and LoveROMS. Both of them didn't work.
The default.xbe needed a debug, and even calls it "Project Velocity Debug".
The F3_M.xbe didn't work and is called "Project Velocity"
The F3_R.xbe didn't work and is called "Project Velocity Optimized"
The unknown.xbe is the same as F3_M.xbe, but the size is 100kbs less.
Is there a way to fix this?

**Comment by PatrickvL** [comment]
Not for the foreseeable future, we're head deep into improvements of our kernel API's, logging, function detection, hooking, handling of threads, interrupts, deferred procedure calls, low level graphics emulation and all sorts of other stuff. If something doesn't work, it might improve after all those things are done, but no guarantees.

**Comment by LukeUsher** [comment]
This emulator is still in the early stages. Yes there 
ant many titles that boot, and even a small handful that are playable, however the vast majority of games still do nothing.

Additionally, we cannot and will not provide support for a downloaded copy of a game, that would be piracy and is illegal. Supporting piracy can put this entire project in danger.
