### ISSUE TITLE
Jet Set Radio Future / JSRF not booting

### ISSUE THREAD

**Issue by Drakonas** [Cxbx-Reloaded/Cxbx-Reloaded#504]
The game was booting fine before. I've tried builds from May and July, and neither boot it. I could have sworn it booted before with the May 28th 2017 build (389a8fd6). Now it just sits at black screen and the log fills with these lines and never loads the game:

        [0x5974] EmuWarn: EmuX86_Read32Aligned(0xFE820010) [Unknown address]

Latest build I tried was 78f4d067 (July 16th 2017).

Might be doing something wrong on my end, but I haven't touched my game files.... so nothing has changed. I also tried clearing the HLE cache and starting with a fresh Cxbx directory.

Log: https://pastebin.com/aE01ezRq

**Comment by literalmente-game** [comment]
The game is not even booting? I've used https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/78f4d067fbd2377987e25ae81b0ecd86d2d29055 and is booting.

**Comment by LukeUsher** [comment]
It looks like you have APU LLE enabled in the settings, make sure to disable all experimental LLE functionality, clear the HLE cache, then try again

**Comment by Drakonas** [comment]
Bingo! Thanks. Not sure how those options got turned on.
