### ISSUE TITLE
Final Fight Streetwise - included official CPS1 Final Fight incorrect colours.

### ISSUE THREAD

**Issue by dazchipsugar** [Cxbx-Reloaded/Cxbx-Reloaded#512]
![image](https://user-images.githubusercontent.com/30376716/28494214-962626d2-6f1f-11e7-95fb-fe8639352c98.png)

![image](https://user-images.githubusercontent.com/30376716/28494221-b9401290-6f1f-11e7-8407-21c35ba12f6e.png)

![image](https://user-images.githubusercontent.com/30376716/28494234-0dd2a76e-6f20-11e7-8584-35e167d27919.png)

![image](https://user-images.githubusercontent.com/30376716/28494237-2850a03c-6f20-11e7-9202-d5a8624df8df.png)

![image](https://user-images.githubusercontent.com/30376716/28494242-4492f236-6f20-11e7-9aa3-6012b090c9ec.png)

I think it is due to how the FinalF.xbe executable is doing the 2d 90s equivalent of of some fading effect as it seems to fade from or to the correct colours whenever a new scene is started.

However it seems completely playable. I don't have the patience to go further given the amount of other emulators that will play this game.

**Comment by LukeUsher** [comment]
It looks like an issue with P8 format textures. Thanks for the report, the fact that it's playable is very promising!

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#90
