### ISSUE TITLE
DOA XtremeBeachVolleyBall - Infinite black screen

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#517]
As the title says, the game shows a never ending black screen with no audio or graphics whatsoever. 
PAL version, 3ca1a354, win10

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173758/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185564/Xbe.txt)

![doa xtremebeachvolleyball](https://user-images.githubusercontent.com/30000751/28573034-b5554e00-7138-11e7-94dc-91dd73479e0c.PNG)

**Comment by CakeLancelot** [comment]
If you press F11 I believe there's at least something rendering, might be an error message.
![cxbx_2017-07-31_11-46-56](https://user-images.githubusercontent.com/5341136/28788386-0223465e-75e6-11e7-8172-a1f2add30430.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#88
