### ISSUE TITLE
Tenchu: return from darkness - Loading screen

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#518]
The game shows a loading screen but crashes immediately after. Also, you can hear a sound after the loading screen but just before the crash.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173810/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185619/Xbe.txt)
![tenchu](https://user-images.githubusercontent.com/30000751/28579060-04de572a-714b-11e7-81bd-31433ce84e04.PNG)
![tenchu2](https://user-images.githubusercontent.com/30000751/28579063-0869b4b6-714b-11e7-99ed-b02095cf0981.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#87
