### ISSUE TITLE
Broken Sword: The Sleeping Dragon - Crash on boot

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#519]
It crashes shortly after booting the game.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173841/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185556/Xbe.txt)

![the sleeping dragon](https://user-images.githubusercontent.com/30000751/28579421-322beb06-714c-11e7-9ef4-9bbec7a2c348.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#86
