### ISSUE TITLE
Project Zero - Infinite black screen

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#520]
A never ending black screen, and from the log the problem seems to be an unsupported texture format.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173855/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185615/Xbe.txt)

![project zero](https://user-images.githubusercontent.com/30000751/28579645-b9f573ea-714c-11e7-8466-6d39d8b402b5.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#85
