### ISSUE TITLE
Halo 2 (update.xbe) - Works

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#521]
I don't know if this is really useful and if you tell me it isn't I will close the issue. The update.xbe from Halo 2 works with corrupted graphics but crashes when it has finished. The game itself doesn't of course because it is an LTGC title. 
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173974/KrnlDebug.txt)
![halo2](https://user-images.githubusercontent.com/30000751/28581353-8408d312-7151-11e7-9d5a-ba1d5f9295c0.PNG)

**Comment by LukeUsher** [comment]
This crash issue is a known bug with HalReturnToFirmware() where it cannot resolve the symbolic link for the dashboard. This should be an easy to fix.

**Comment by ergo720** [comment]
Should I close this issue then?

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#84
