### ISSUE TITLE
Need for Speed Underground - Crash on boot

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#522]
It crashes shortly after booting. The original debug log had [0x10AC] EmuWarn: KeWaitForMultipleObjects failed! (STATUS_INVALID_HANDLE) repeated a huge number of times and the final size of the log was over 800 MB so I had to remove the repeated line to upload the log.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174072/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185608/Xbe.txt)

![nfs](https://user-images.githubusercontent.com/30000751/28582633-ad0fbc2c-7155-11e7-9145-51dc0c1f5c10.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#82
