### ISSUE TITLE
Need for Speed Underground 2 - Crash on boot

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#523]
Crash after booting just like NFS. The log file had the same problem as specified in #522. The line was again [0x23C4] EmuWarn: KeWaitForMultipleObjects failed! (STATUS_INVALID_HANDLE).
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174087/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185610/Xbe.txt)
![nfs2](https://user-images.githubusercontent.com/30000751/28582897-a9041186-7156-11e7-9911-3e2ab26b65fc.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#83
