### ISSUE TITLE
Fable - Instant crash

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#524]
It crashes as soon as you boot it with an error related to a texture function.
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174168/KrnlDebug.txt)
![fable](https://user-images.githubusercontent.com/30000751/28583809-01c7d0ca-715a-11e7-8aa9-ef43e46c07f1.PNG)

**Comment by LukeUsher** [comment]
This title used LTCG and cannot be supported until we implement low level NV2A emulation
