### ISSUE TITLE
Mortal Kombat: Deception Premium Pack: Mortal Kombat 1 playable

### ISSUE THREAD

**Issue by literalmente-game** [Cxbx-Reloaded/Cxbx-Reloaded#525]
And not only playable: I've finished the game using this build https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/3ca1a35479996f3c0f2e5c41fd250fd03313215f
Video: https://www.youtube.com/watch?v=fjiel73EKLs
Logs: [logs.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174529/logs.zip)

**Comment by LukeUsher** [comment]
This is great news!
How do the other Mortal Kombat titles fare?

**Comment by literalmente-game** [comment]
Mortal Kombat 1 came with Mortal Kombat 2 as a bonus from the Premium Pack version of Mortal Kombat: Deception, Mortal Kombat 2 didn't work and I haven't tested other games so far (but I'll).

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#81
