### ISSUE TITLE
The return of the King - Infinite black screen

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#526]
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174656/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185601/Xbe.txt)

![king](https://user-images.githubusercontent.com/30000751/28592075-71ce1e3e-7177-11e7-9547-8f4549c74636.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#80
