### ISSUE TITLE
The two Towers - Infinite black screen

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#527]
PAL, win10, 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174666/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185605/Xbe.txt)

![two](https://user-images.githubusercontent.com/30000751/28592176-ade3ac68-7177-11e7-8cf6-a1fd19eb52fb.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#79
