### ISSUE TITLE
ZSNES - Titles

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#528]
With 3ca1a354, I can only reach the title screen before it crashes. I remember that with previous versions I was able to reach the menus and selecting the options.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1176485/KrnlDebug.txt)
![zsnes](https://user-images.githubusercontent.com/30000751/28620169-588ea8a6-71fb-11e7-8a64-8180105746ab.PNG)

**Comment by LukeUsher** [comment]
No idea when this broke, thanks for the report!

Previously it worked to the point of being fully playable. (I tested playing Super Mario World)

**Comment by ergo720** [comment]
For over a month for sure, I have been having this issue for quite some time now

**Comment by PatrickvL** [comment]
We could try to bisect it

**Comment by literalmente-game** [comment]
Done: 
d5ce593f (15/05) can boot it and reach in-game (loading Super Mario World)
b83cc6f8 (18/05) crash with the error shown in this issue

**Comment by LukeUsher** [comment]
We don't have a commit # d5ce593f ?

**Comment by PatrickvL** [comment]
@literalmente-game Have you cleaned the HLE cache in between bisect runs?

**Comment by literalmente-game** [comment]
Yeap, still getting the same error @PatrickvL

**Comment by LukeUsher** [comment]
The key difference between these commits is that the following symbols are no longer detected after 4f019d9 is applied:

CDirectSoundBuffer_PlayEx=0
IDirectSoundBuffer_PlayEx=0

**Comment by LukeUsher** [comment]
Can you retest in the latest commit? Thanks!

**Comment by literalmente-game** [comment]
With the latest commit now it's working. Worth a note: games now run with 100% speed on ZSNES ! (timing is wrong like in Turok, but still 100% performance).

**Comment by LukeUsher** [comment]
Nice, problem solved

**Comment by ergo720** [comment]
Yes, I can also confirm the zsnes now works again but I would like to add that the input is partially broken. It's like the title is constantly receiving an UP button input and to actually select something I have to turn off the analog switch and use the directional buttons and even then it's still problematic to select something. The same behavior happens if I use the mouse or other controllers. I think this is the same problem that is causing me input issues with panzer dragoon orta.

**Comment by ergo720** [comment]
Ok, I have done more testing and the cause of the problem seems to be my USB hub. If I connect the controller through it, the issue happens but if I connect it directly to the pc, most of it is solved. The only problem remaining is that the directional buttons don't work and to make them working I have to switch off the analog button but at that point again panzer and zsnes start to select the options by themselves (constant UP input). I have tested this with commits 14e59d6e and 2d720a16 and the behavior is the same. (zsnes crashes with those versions though).

**Comment by LukeUsher** [comment]
This is a known issue with DirectInput, issue #156 exists to address this.
If you use an XInput controller, you should be fine.

**Comment by cybertronicgames** [comment]
ZsnexBox loads ROMs but, FPS is too fast to play.
![screenshot 21](https://user-images.githubusercontent.com/14711758/28992528-32a3654e-7964-11e7-9ce7-c29620102564.png)
![screenshot 22](https://user-images.githubusercontent.com/14711758/28992530-368286d6-7964-11e7-9fcf-32469c625219.png)
![screenshot 23](https://user-images.githubusercontent.com/14711758/28992531-3971638a-7964-11e7-9316-d2aee2569ae4.png)
![screenshot 24](https://user-images.githubusercontent.com/14711758/28992533-3bf36d92-7964-11e7-9d2c-226cd251350b.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202078/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202079/Xbe.txt)

**Comment by PatrickvL** [comment]
Turn V-sync on

**Comment by cybertronicgames** [comment]
V-sync is on when running the game. Also, in my Nvidia driver.

**Comment by LukeUsher** [comment]
Yeah it's a known issue: ZSNES now runs way too fast regardless of settings.
