### ISSUE TITLE
EA Sports F1 2001: Black screen and sound

### ISSUE THREAD

**Issue by TotalCaesar659** [Cxbx-Reloaded/Cxbx-Reloaded#530]
EA Sports F1 2001: Black screen only and sound from main menu.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178445/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178446/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#78
