### ISSUE TITLE
EA Sports F1 2002: Black screen only

### ISSUE THREAD

**Issue by TotalCaesar659** [Cxbx-Reloaded/Cxbx-Reloaded#531]
EA Sports F1 2002: Black screen only
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178447/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178450/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#77
