### ISSUE TITLE
Virtual Jaguar v0.981 - wrong colours + could not map error

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#532]
CXBX reloaded version 3ee227bf7461325adecd5bdd311f48be85db065c

The emulator has wrong colours when it's runs and also could not map error when I try to run some games with default.xbe. But when I run JagBox.xbe after this, it's runs correctly with game I selected before with Default.xbe. 
![selectscreen](https://user-images.githubusercontent.com/25540784/28654234-c9d11468-72cd-11e7-8c51-06d487bb3123.png)
![could_not_map](https://user-images.githubusercontent.com/25540784/28654239-d059d702-72cd-11e7-802b-d0c4297d7188.png)
![directory](https://user-images.githubusercontent.com/25540784/28654244-d5288fee-72cd-11e7-8e99-d8dd671ef18c.png)
![screenshot_2](https://user-images.githubusercontent.com/25540784/28654248-d952a3b6-72cd-11e7-97cc-325aafd8bae1.png)
![screenshot_3](https://user-images.githubusercontent.com/25540784/28654250-dc30eca0-72cd-11e7-931d-dfc5b50b752b.png)
______________________________________________________________________________________________________
dumps of Both Xbes
[XbeDefault.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178775/XbeDefault.txt)
[jagbox.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178782/jagbox.txt)
_____________________________________________________________________________________________
Debug Output Information from console
[default.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178794/default.txt)
[Jagbox.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1178796/Jagbox.txt)

Plus, if I try to run this emulator with output to file but not to the console I get this error . Unfortunately the log is too much weight to attach 
![image](https://user-images.githubusercontent.com/25540784/28654430-396179a2-72cf-11e7-906a-70fd60304e9a.png)

**Comment by LukeUsher** [comment]
The colour issue is a known issue with P8 format textures. It should hopefully be resolved when we get @PatrickvL's work merged into master.

The 'could not map' error is interesting, I'll investigate this.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#76
