### ISSUE TITLE
NestopiaX 1.3 - exception code

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#541]
Cxbx-Reloaded Version 3ee227bf
________________________________________________________________________________________________________
NestopiaX 1.3 has exception code XID_fCloseDevice+0x6e1bf5c2 
First screenshot with the  Hardware YUV Overlays enabled
![screenshot_3](https://user-images.githubusercontent.com/25540784/28722396-95577192-73ee-11e7-9552-b8998eb0a880.png)

And second with the Hardware YUV Overlays Disabled
![screenshot_2](https://user-images.githubusercontent.com/25540784/28722341-617c093c-73ee-11e7-80df-c8ad466254bf.png)
________________________________________________________________________________
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1183367/Xbe.txt)
[Nestopia_Log.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1183368/Nestopia_Log.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#73
