### ISSUE TITLE
FuzzyTeapot and Minnaert Regression [XDK 4627]

### ISSUE THREAD

**Issue by Voxel9** [Cxbx-Reloaded/Cxbx-Reloaded#545]
At some point, namely around April-May time, both these XDK samples used to boot and function completely fine, but now today they just encounter exceptions:

![image](https://user-images.githubusercontent.com/16278868/28745285-68c58da6-746d-11e7-9deb-cc7ac472514f.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1184982/KrnlDebug.txt)

![image](https://user-images.githubusercontent.com/16278868/28745305-babea318-746d-11e7-84d9-49ad3c23ddd2.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1184983/KrnlDebug.txt)

Most other 4627 XDK samples I tested boot as they normally should, but it just appears to be these ones that appear to have silently stopped working over the months. There might possibly be other samples that I didn't test that also regress in the same manner as these, in that case I'll update this issue with them.

**Comment by PatrickvL** [comment]
Thanks for this report, we should definitely keep these simple things running

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#72
