### ISSUE TITLE
Futurama Regression [NTSC]

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#546]
[HLE.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185121/HLE.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185191/KrnlDebug.txt)
![capture](https://user-images.githubusercontent.com/17304943/28747120-6260d658-744c-11e7-9154-9ecd806b723f.PNG)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185120/Xbe.txt)

**Comment by ergo720** [comment]
Please download the current version. A bug has been accidentally introduced in that version

**Comment by BenNottelling** [comment]
@ergo720 Same issue while using this build 
https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/d44c3930651a3e08864c2ba63d4ef109df00cf21/job/7h7967t3art588g4/artifacts

**Comment by ergo720** [comment]
I redownloaded it now and it works fine on my pc

**Comment by BenNottelling** [comment]
@ergo720 Hmm interesting, are you using NTSC or PAL?

**Comment by ergo720** [comment]
Well, I don't have this particular game, I was referring to the bug that causes cxbx to crash every time you try to save a debug log; that is the bug that was introduced in the past version. Are you talking about this or is it just the game that crashes?

**Comment by BenNottelling** [comment]
@ergo720 I thought you meant the game crashing was from the past version, I've got the debug file and uploaded it now

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#71
