### ISSUE TITLE
Info on 8 dashboard versions

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#547]
I've done some digging and found 8 dashboards, so here's some useful info:
- Dash 3944 Non LTCG, Will work in Cxbx
- Dash 4034 Non LTCG, Will work in Cxbx
- Dash 4817 Non LTCG, Will work in Cxbx
- Dash 4847 Non LTCG, Will work in Cxbx
- Dash 4920 Non LTCG, Will work in Cxbx

- Dash 5659 LTCG - Will not work in Cxbx
- Dash 5849 LTCG - Will not work in Cxbx
- Dash 5960 LTCG - Will not work in Cxbx

Chances are any dash 4920 and before will work as it is non LTCG and any dash 5659 will NOT work as it is LTCG

**Comment by PatrickvL** [comment]
5659 is listed twice, why?

**Comment by BenNottelling** [comment]
Not sure I guess I made a mistake, removed the duplicate

**Comment by PatrickvL** [comment]
Nine dashboards of Xbox in the title, nine dashboards of Xbox. One fell off aaaaand - eight dashboards of Xbox in the title, etc (variation on bottles of 🍺)

**Comment by BenNottelling** [comment]
@PatrickvL Haha! Yes it did lol I had 6 from the start, but then added a bit of info from what I've seen here on Github, then removed the duplicate :)

**Comment by CakeLancelot** [comment]
I've open a wiki page for dashboard compatibility which should be better suited than storing all info in this issue. Feel free to suggest/edit to add more accurate information (not sure how the permissions are set).

https://github.com/Cxbx-Reloaded/game-compatibility/wiki/Dashboard-Compatibility
