### ISSUE TITLE
[PAL] Alien Hominid crash

### ISSUE THREAD

**Issue by romaxy151** [Cxbx-Reloaded/Cxbx-Reloaded#549]
Alien Hominid crashes on start screen
![default](https://user-images.githubusercontent.com/30557931/28747939-8d079e7a-74b3-11e7-84af-0e286e4df069.PNG)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185210/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185211/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#70
