### ISSUE TITLE
Dead or Alive 3 - Crash on boot

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#550]
PAL, win10, d44c3930

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185245/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185557/Xbe.txt)

![doa3](https://user-images.githubusercontent.com/30000751/28748243-4df78684-74a2-11e7-873c-934783aa06cd.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#69
