### ISSUE TITLE
Conker Live & Reloaded Demo

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#553]
[defaultXBE.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185351/default.txt)
[DefaultXBEKrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185352/DefaultXBEKrnlDebug.txt)
[Conker Live & Reloaded Demo Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185354/Conker.Live.Reloaded.Demo.Xbe.txt)
[Conker Live & Reloaded Demo KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185355/Conker.Live.Reloaded.Demo.KrnlDebug.txt)
[ForzaXbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185356/ForzaXbe.txt)
[ForzaKrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185357/ForzaKrnlDebug.txt)

Audio is working and it does render the main menu, but it is only visible if you use wireframe mode. Audio also pops.
[audio.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185367/audio.zip)
![capture2](https://user-images.githubusercontent.com/17304943/28749427-d3ec247e-747b-11e7-89d3-7ac9c7ec4ace.PNG)
Videos seem to play (at least audio does and this line loads)
![capture3](https://user-images.githubusercontent.com/17304943/28749437-08523640-747c-11e7-8ddf-0fb5c619573d.PNG)
Starting any of the playable demos results in this crash(not launching the XBE directly)
![capture](https://user-images.githubusercontent.com/17304943/28749453-b744e936-747c-11e7-856c-e948a6472655.PNG)
If I launch the forza trial xbe file
![capture4](https://user-images.githubusercontent.com/17304943/28749460-f25923fc-747c-11e7-8daf-279e198db7c9.PNG)
Mech Assault demo uses D3D8LTCG, so that won't play.
If I run the Conker Live & Reloaded Demo xbe.
![capture5](https://user-images.githubusercontent.com/17304943/28749468-3a6e97d0-747d-11e7-9777-405394ce3214.PNG)
For just a fraction of a second after disabling wireframe mode it showed this:
![capture6](https://user-images.githubusercontent.com/17304943/28749548-d91104f2-747f-11e7-89b9-11d8ff3efb03.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#67
