### ISSUE TITLE
Godzilla Save the Earth - Screen turns grey then crashes

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#559]
When launching the game the screen will turn grey then crash with an error message. Tested on 413fbfcc

![firefox_2017-07-30_22-12-35](https://user-images.githubusercontent.com/5341136/28761598-4f26471a-7575-11e7-8d51-b721354be3d2.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186308/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186309/Xbe.txt)

**Comment by jackchentwkh** [comment]
the same issue as #311 ，the texture format is LIN_A8, shall we simply copy the handler from linear 16 bits for this linear 8 bit texture? I am not familiar with direct X texture formats, but from the code of handlers of both 16 bits and 32 bits linear texture, it should be the same for 8 bits linear texture.

**Comment by PatrickvL** [comment]
@jackchentwkh I've done a lot of work on texture-conversion a while ago (but can't merge it in yet), see https://github.com/PatrickvL/Cxbx-Reloaded/blob/WorkInProgress/src/CxbxKrnl/EmuD3D8.cpp#L6178

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#66
