### ISSUE TITLE
Metal Slug 3 - Audio with some visuals

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#560]
By starting emulation then switching to a different window and back to Cxbx you can hear the audio in Metal Slug 3. However, most of the time it's a black screen.Sometimes the screen will flash (1:23) or a colored box will appear (1:03, 1:30) - See this video and the aforementioned timestamps for details...
https://www.youtube.com/watch?v=FzKjdLD9eso&feature=youtu.be&t=24

I can't seem to get the game to reproduce this when Debug Output (Kernel) is on, it is only a black screen that does nothing. Perhaps related to #315 ? I will provide the output when it is enabled regardless.

Tested on 413fbfc
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186369/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186368/Xbe.txt)

**Comment by blueshogun96** [comment]
Oh, I thought I had reported this.  Looks like I forgot.  I took a look into it before.  I think it had something to do with render targets, I forgot.  It's been a while :/

Shogun

**Comment by furrya** [comment]
About the Debug Output (kernel) Issue.. It's like in the https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/532 issue, when the game instantly crashes when I try to run it without that Console output. But with Debug Output (kernel) to console output it's showes some loading and menues screens before the error appears

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#65
