### ISSUE TITLE
Cel Damage - Sound effect before crashing

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#561]
If you enable XADPCM in audio options you can hear a sound effect before the game crashes. There are no visuals, just a black screen. Tested on 413fbfc

Video: https://youtu.be/HIsk-42XryA

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186386/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1186387/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#64
