### ISSUE TITLE
[DEMO OXM 14] Panzer Dragoon Orta - FMV now working !

### ISSUE THREAD

**Issue by zaykho** [Cxbx-Reloaded/Cxbx-Reloaded#563]
Hello,

I wanted to add that the FMV are now working on Panzer Dragoon Orta demo OXM 14. (Still not working on the retail game though).

The audio and video are synchronized and the FMV framerate is really smooth, though, for some reasons, the video look scrambled : [see more here.](https://www.youtube.com/watch?v=zLDR_L8uxMQ)

Any idea why the FMV on the retail release still make the emulator crash and why the video is scrambled ?

Still, a good improvement, nice guys !

Version used:  Cxbx-Reloaded fc575e57 (Jul 30 2017), V-SYNC off and YUV enabled, PCM/XADPCM/Unknown Codec enabled.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#63
