### ISSUE TITLE
[TitleID: 55530008] [PAL] FarCry Instincts: Crash

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/Cxbx-Reloaded#565]
Hi guys.
i've tested Far Cry Instincts with the build a92a5d81
TitleID: 55530008
Region: 4
it crashes just after the "Ubisoft Montreal Studios" logo and playes the previous FMVs without any sound
It doesn't matter which sound options are enabled

![capture20170731224553709](https://user-images.githubusercontent.com/30478365/28798690-89b955fe-7645-11e7-96fd-21508e6d9b83.png)
![capture20170731224557883](https://user-images.githubusercontent.com/30478365/28798689-89b88016-7645-11e7-98f6-d16f9278089b.png)
![capture20170731224720398](https://user-images.githubusercontent.com/30478365/28798596-3fc92e38-7645-11e7-8651-8cea72a79b49.png)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188867/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188874/KrnlDebug.txt)

it also has a level editor ige.xbe
this one goes to the menu and if i start a map, it crashes during the loading screen:

![capture20170731225213466](https://user-images.githubusercontent.com/30478365/28798665-7dd884d0-7645-11e7-8458-408a005fa4f4.png)
![capture20170731225233697](https://user-images.githubusercontent.com/30478365/28798664-7dd6561a-7645-11e7-88c3-b1e25d255c87.png)
![capture20170731225254691](https://user-images.githubusercontent.com/30478365/28798666-7ddc4386-7645-11e7-9fa3-4553d0b859ca.png)

[ige_XBE.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188864/ige_XBE.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188876/KrnlDebug.txt)

====================================

but I've remembered, that this game went into the main menu a few month ago
so I digged around in older builds and found the last version where it plays all the intros and shows the main menu 7c266ad4
the sound in all FMVs is choppy and it ignores all controller inputs
![capture20170731223222273](https://user-images.githubusercontent.com/30478365/28799279-43e72ada-7648-11e7-9131-65e0df1f256f.png)
![capture20170731223250609](https://user-images.githubusercontent.com/30478365/28799280-43f12fb2-7648-11e7-8a1f-d0b6de6f2c7f.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188895/KrnlDebug.txt)

the next build 886229b1 crash after the "Montreal Studios" Logo
with: D3D::BlockOnTime not implemented (tell blueshogun)
![capture20170731223719156](https://user-images.githubusercontent.com/30478365/28799512-2c3d8d2e-7649-11e7-84ea-6b9c8bef9148.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188901/KrnlDebug.txt)

the next build where the behaviour to the previous bulds changed is e0daedb2
here it just crashs after the "Montreal Studios" Logo without any error message
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1188914/KrnlDebug.txt)

if it helps, I also have the hle-cache files

and of course my specs :)
i7 3820
Win10 x64
GTX 980Ti SLI

**Comment by hotzenplotz3000** [comment]
tested with build 77f28217
Intros are with Sound now
still crashes
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201533/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#62
