### ISSUE TITLE
WWE RAW 2 - Title and Intro (intro - earlier versions)

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#566]
In we clean cxbx profile folder (in appdata) - at first run you will get error (see pic RAW2_31072017_FirstRun_Error_CleanProfile, log RAW2 31072017_KRNLDEBUG_CLEAN):
![raw2_31072017_firstrun_error_cleanprofile](https://user-images.githubusercontent.com/24764335/28811682-7cc331a4-7699-11e7-8d9c-6b178e132251.PNG)
[RAW2 31072017_KRNLDEBUG_CLEAN.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1196280/RAW2.31072017_KRNLDEBUG_CLEAN.txt)

At second run - you willl get title but with crash on intro (see pics RAW2_31072017_SecondRun, RAW2_31072017_SecondRun_Error, log RAW2_31072017_KRNLDEBUG)
![raw2_31072017_secondrun](https://user-images.githubusercontent.com/24764335/28811684-8570387e-7699-11e7-972c-7c618678d68b.PNG)
![raw2_31072017_secondrun_error](https://user-images.githubusercontent.com/24764335/28811695-8d38776a-7699-11e7-9077-df282dca76a9.PNG)
[RAW2_31072017_KRNLDEBUG.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189639/RAW2_31072017_KRNLDEBUG.txt)

At ealier versions (at least from 21.04.2017 to 02.05.2017) - intro plays but flickering, see pic RAW2_21042017_IntroFlickering. 
![raw2_21042017_introflickering](https://user-images.githubusercontent.com/24764335/28811707-9bc54650-7699-11e7-83cf-033161848208.PNG)

After video - crash, see pic RAW2_21042017_IntroError, log RAW2_21042017_KRNLDEBUG.
![raw2_21042017_introerror](https://user-images.githubusercontent.com/24764335/28811713-a0fa9882-7699-11e7-9150-a05c519bde25.PNG)
[RAW2_21042017_KRNLDEBUG.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189641/RAW2_21042017_KRNLDEBUG.txt)

First version when intro does not play for all - 03,05,2017. See pic RAW2_03052017_StartCrashingBeforeIntro, log RAW2_03052017_StartCrashingBeforeIntroLOG
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189638/Xbe.txt)
![raw2_03052017_startcrashingbeforeintro](https://user-images.githubusercontent.com/24764335/28811720-ad4bc8a4-7699-11e7-9430-eb2358afed02.PNG)
[RAW2_03052017_StartCrashingBeforeIntroLOG.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189642/RAW2_03052017_StartCrashingBeforeIntroLOG.txt)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189644/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#61
