### ISSUE TITLE
WWE RAW - Title

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#567]
If you clean profile - you will get error on first run, see pic RAW31072017_FirstRunCleanProfile.
Version 31.07.2017 - shows only one screen, LOG file increasing size , see pic RAW31072017_SecondRun.
![raw31072017_firstruncleanprofile](https://user-images.githubusercontent.com/24764335/28811809-23890a0e-769a-11e7-9401-9ea1a49d387a.PNG)
![raw31072017_secondrun](https://user-images.githubusercontent.com/24764335/28811812-260a36a4-769a-11e7-9873-425c6d55ca3b.PNG)
[RAW_KRNLDEBUG.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189648/RAW_KRNLDEBUG.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1189649/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#60
