### ISSUE TITLE
Add "Drag and Drop" XBE-loading feature to GUI

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#568]
Fo this issue, extend the Cxbx GUI such, that an Xbe can be loaded using a Drag and Drop operatiun.
This should only be accepted when emulation is not running.
If no XBE is loaded yet, load the dropped XBE. If an XBE is already loaded, replace it with the dropped XBE.
Be carefull to use correct paths.

Some pointers that might contain valuable information on this subject:
* https://msdn.microsoft.com/en-us/library/windows/desktop/bb776406(v=vs.85).aspx
* https://msdn.microsoft.com/en-us/library/windows/desktop/bb774303(v=vs.85).aspx
* http://www.dreamincode.net/forums/topic/293568-drag-and-drop-files-demo-in-c/
* https://helgeklein.com/blog/2010/03/how-to-enable-drag-and-drop-for-an-elevated-mfc-application-on-vistawindows-7/

**Comment by ergo720** [comment]
I have implemented the feature as requested in my branch and tested with my games: they all work as before. I'll submit a new PR.

**Comment by PatrickvL** [comment]
That's great! I didn't expect a PR for this so quickly!

**Comment by PatrickvL** [comment]
Implemented in 4d30506
