### ISSUE TITLE
Lamborghini Demo

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#569]
Lamborghini was a racing video game developed by Rage Software... Only the demo ever saw the light of day though as they sold themselves before releasing the game. But the demo boots! I believe this is a video, but it's hard to tell I'm also thinking that there could be an issue with videos as I as a similar line with the Conker Live & Reloaded demo #553 
![capture](https://user-images.githubusercontent.com/17304943/28835587-bb2973f8-769a-11e7-9edc-7c95064861a1.PNG)
After this, the game gets to the menu but then crashes while playing the background music.  We actually get two errors here :) (no menu graphics are shown) 
![capture2](https://user-images.githubusercontent.com/17304943/28835718-33e3300e-769b-11e7-9fab-d0d7de6b1c6c.PNG)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191281/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191280/Xbe.txt)

**Comment by BenNottelling** [comment]
Now plays audio during the into

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#59
