### ISSUE TITLE
[TitleID: 454D001B] Mashed: Fully Loaded - Crash with sound

### ISSUE THREAD

**Issue by rozniak** [Cxbx-Reloaded/Cxbx-Reloaded#570]
Black screen stays for a bit, then crashed with some sort of engine noise in the background.
Tested on: aaafcb4f772f0785a491ef4c0757034a13c4c3ba

![mashed fully loaded](https://user-images.githubusercontent.com/13258281/28839915-21cdbcde-76ed-11e7-954e-dddf58636992.PNG)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191513/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191514/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#58
