### ISSUE TITLE
[TitleID: 56560008] The Hulk- Loads to title screen, working audio

### ISSUE THREAD

**Issue by rozniak** [Cxbx-Reloaded/Cxbx-Reloaded#573]
Tested on: aaafcb4f772f0785a491ef4c0757034a13c4c3ba

Interesting one, The Hulk loads with a lot of pulsing red flashing on the screen:
![loading](https://user-images.githubusercontent.com/13258281/28847334-beab55a2-7706-11e7-8f8a-a9b7d54b33fd.PNG)
It gets brighter than that screenshot but due to the hard timing this is what I could capture with Snipping Tool

It does get to the title screen as shown here, complete with the eerie ambience and heartbeart background sounds:
![title](https://user-images.githubusercontent.com/13258281/28847380-e3abdb4c-7706-11e7-97d3-02f1dddf43c3.PNG)

The game did not crash, but I could not get any futher as it would not respond to any input (neither the keyboard or XInput worked). Potentially could get some more out of it if it responds to the Start button being pressed

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191966/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1191967/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#57
