### ISSUE TITLE
wxWidgets or Qt?

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#578]
I was wondering about this, has anyone thought about using wxWidgets instead of win32 API for the GUI? I understand this is of very low priority now and would require a huge amount of work but I think it would make porting to other os easier in the distant future.

**Comment by PatrickvL** [comment]
Dolphin recently switched from wxWidgets to Qt, and given they've put considerable time in this, I this it's wise for us not to start on something that others have replaced already. Read more here : https://dolphin-emu.org/blog/2017/06/03/dolphin-progress-report-may-2017/#qt-ie-patootie

**Comment by ergo720** [comment]
Interesting article, I thought wxWidgets was better that Qt. Well, I was wrong then.

**Comment by LukeUsher** [comment]
A new GUI is planned for our first real release, v0.1.

The current Roadmap to v0.1 is very vague, has no estimated completion, but is **drafted** as the following:

1. HLE: Must be stable enough and compatible enough for most non-LTCG titles to at least boot
1. HLE: A significant percentage of titles should be playable 
1. HLE: At least 90% of titles are not regressing from best known compatibility status
1. HLE: Patches should be (mostly) transparent to the running software. No modification of Xbox resources, format conversions only at render time
1. LLE: least some functioning NV2A Emulation even if only enough to run a couple of XDK samples
1. UI:  A new, user friendly GUI, similar to Dolphin with a nice game browser and support for customising EEPROM settings
1. WEB: Next iteration of the website + compatibility list ready to go live same day as the release

This will be drafted up properly and made into a GitHub Milestone to track progress at a later date, after more planning

**Comment by Sarkie** [comment]
Rpcs3 also went to Qt. Their github has the issues they had.

**Comment by PatrickvL** [comment]
I believe we can safely say by now that a new GUI should using Qt.

Closing this.
