### ISSUE TITLE
[TitleID: 4D570032] Ed, Edd n Eddy: The MIS-EDventures - In-Game with Wrong Colors, no music, no videos

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#583]
![screenshot_2](https://user-images.githubusercontent.com/25540784/28903934-abc6dc62-7842-11e7-9441-5e33eb68e672.png)
![screenshot_3](https://user-images.githubusercontent.com/25540784/28903947-b98b8e1a-7842-11e7-82a1-207386f5714c.png)
![screenshot_5](https://user-images.githubusercontent.com/25540784/28903953-be6a92f0-7842-11e7-8263-246f15803ea0.png)
![screenshot_6](https://user-images.githubusercontent.com/25540784/28903958-c2efcbec-7842-11e7-8f11-17a711424fb0.png)
________________________________________________________________________________________
[Ed,Edd&Eddy_Kernel_debug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1195841/Ed.Edd.Eddy_Kernel_debug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1195842/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#55
