### ISSUE TITLE
[TitleID: 4D4A000B] Drake of the 99 Dragons - has sound but instantly crashes 

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#584]
Drake of the 99 Dragons has sound, but instantly crashes. And has no intro video
![screenshot_7](https://user-images.githubusercontent.com/25540784/28904095-922ad99c-7843-11e7-9a60-2d9f36f694bc.png)
______________________________________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1195851/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1195852/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#54
