### ISSUE TITLE
[TitleID=494d0002] NASCAR Thunder 2002 Demo

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#586]
NASCAR Thunder 2002 Demo gets to the menu, but it doesn't seem to respond to input and it can only be seen with wire frame (f11)
![capture](https://user-images.githubusercontent.com/17304943/28938517-29a50e4c-7843-11e7-80ec-d5b87953270a.PNG)
![capture2](https://user-images.githubusercontent.com/17304943/28938524-2cc4e2aa-7843-11e7-8a74-c26c05d4a246.PNG)
![capture3](https://user-images.githubusercontent.com/17304943/28938529-2f2a8d56-7843-11e7-875f-20c6030c0589.PNG)
The last frame seems to be the background from the main menu (seen here [https://youtu.be/nrXYpZXgFoM?t=18](url) )
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198302/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198304/KrnlDebug.txt)
[HLE.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198311/HLE.txt)

**Comment by BenNottelling** [comment]
Regression
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201512/KrnlDebug.txt)
![capture](https://user-images.githubusercontent.com/17304943/28985188-374105c8-7916-11e7-8772-19c57d071d37.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#53
