### ISSUE TITLE
[TitleID: 494D0045] MTV Music Generator 3 Demo - Playable SOMETIMES

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#587]
I have been able to get this fully playable ONCE all of the other times it showed this error directly after 100% on loading, I do not know what I did to have to boot correctly, just that I was clicked off using the snipping tool.
![capture](https://user-images.githubusercontent.com/17304943/28939563-9558d5a8-7846-11e7-9ad7-acd959517fd7.PNG)
![capture2](https://user-images.githubusercontent.com/17304943/28939580-9b82e70c-7846-11e7-806f-8636ab3c1274.PNG)
![capture10](https://user-images.githubusercontent.com/17304943/28939342-d1f040e2-7845-11e7-9f41-d94145039daf.PNG)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198343/Xbe.txt)
[KrnlDebug(crash).zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198353/KrnlDebug.crash.zip)
[381cf3f0.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198354/381cf3f0.txt)
Here's it working, would pass the first few pictures there and then run as normal(perfect audio too) ![capture3](https://user-images.githubusercontent.com/17304943/28939581-9b8c185e-7846-11e7-961e-f8bc22cc1901.PNG)
![capture4](https://user-images.githubusercontent.com/17304943/28939582-9b8d1664-7846-11e7-9ea3-cb70e45f3859.PNG)
![capture5](https://user-images.githubusercontent.com/17304943/28939583-9b911c8c-7846-11e7-818b-5f474ada792b.PNG)
![capture6](https://user-images.githubusercontent.com/17304943/28939584-9b92a566-7846-11e7-8ad6-86eff52ad9a5.PNG)
![capture7](https://user-images.githubusercontent.com/17304943/28939600-a8043242-7846-11e7-97f8-db81d75c2333.PNG)
![capture8](https://user-images.githubusercontent.com/17304943/28939601-a8081cb8-7846-11e7-93fe-7ba9052c46fa.PNG)
![capture9](https://user-images.githubusercontent.com/17304943/28939602-a80ad4da-7846-11e7-8955-c55a1cb9f927.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#52
