### ISSUE TITLE
[TitleID: 4B4E0008] International Superstar Soccer 2 - Loads to title, no input, glitchy sound

### ISSUE THREAD

**Issue by rozniak** [Cxbx-Reloaded/Cxbx-Reloaded#588]
Region: PAL/Elsewhere
Tested on: 9c74e12fb8be5db7dd2f2ae33604f955a28ebd07

Edit: Have retested using V-Sync as of BenNottelling's suggestion, updated results. Seems to allow perfect emulation of the 2D graphics mostly

Game loads through, Force Vsync allows the game to run at normal speed. No input is accepted (tried keyboard and XInput). Audio notes at end of this report.

Game save detection screen appears correctly:
![iss2hd](https://user-images.githubusercontent.com/13258281/28940435-a3c122e4-788c-11e7-87bf-652dea774f68.PNG)

An intro FMV is meant to play after this screen, but it seems to skip over it.

Title screen - displays correctly when using Force Vsync the first time it is displayed:
![iss2working](https://user-images.githubusercontent.com/13258281/28941547-450f800c-7890-11e7-9c74-6d80b30fdbd4.PNG)

After the demo plays, it will return to the title screen which now looks like:
![iss2](https://user-images.githubusercontent.com/13258281/28940508-d89e711a-788c-11e7-89c5-7107446d0fca.PNG)

The loading screen that appears before playing a demo works when using Force Vsync, it does not show up unless in wireframe mode without that setting:
![loadingscreen](https://user-images.githubusercontent.com/13258281/28941584-670aed54-7890-11e7-849e-47d32d445a41.PNG)

The game demo appears to play, although it only plays briefly, and is only a black screen (white screen when using VSync). You can see it in wireframe mode for a moment.
![wireframe](https://user-images.githubusercontent.com/13258281/28940692-78e72248-788d-11e7-9a39-d5d411ac98f5.PNG)

Also when using Force Vsync, very briefly audio of the crowd noise is played. The brief portion that is played sounds correct but it ends just after it starts playing. Probably because the demo seems to end just as fast.

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198421/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198458/KrnlDebug.txt)

**Comment by BenNottelling** [comment]
Maybe the 10x speed can be fixed with v-sync?

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#51
