### ISSUE TITLE
[TitleID: 4D57001C] Midway Arcade Treasures - Varying from perfect to unbootable

### ISSUE THREAD

**Issue by rozniak** [Cxbx-Reloaded/Cxbx-Reloaded#589]
Region: Elsewhere/US-Canada
Tested on: 9c74e12fb8be5db7dd2f2ae33604f955a28ebd07

XBE Dump: 
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198839/Xbe.txt)

This game has separate executables for certain individual arcade games in the collection. Not all are separated, ones that aren't are contained within Ziglar.xbe - here's a quick list of what's included before the report:

720: YES - 720.xbe
Blaster: NO
Bubbles: NO
Defender: NO
Defender 2: NO
Gauntlet: YES - Gauntlet.xbe
Joust: NO
Joust 2: NO
Klax: YES - Klax.xbe
Marble Madness: YES - MarbleMadness.xbe
Paperboy: YES - Paperboy.xbe
Rampage: NO
Rampart: YES - Rampart.xbe
RoadBlasters: YES - RoadBlasters.xbe
Robotron 2084: NO
Root Beer Tapper: NO
Satans Hollow: NO
Sinistar: NO
Smash TV: YES - SmashTV.xbe
Splat!: NO
Spyhunter: NO
Super Sprint: YES - SuperSprint.xbe
Toobin: YES - Toobin.xbe
Vindicators: YES - Vindicators.xbe

**Note on all games:**
All individual XBE arcade games (like rampart.xbe or toobin.xbe) have glitchy graphics on their controls screens as shown in these screenshots, the screen alternates between the two frames:
![controls1](https://user-images.githubusercontent.com/13258281/28945529-cd4a4444-789e-11e7-9d9f-259fe84c1f84.PNG)
![controls2](https://user-images.githubusercontent.com/13258281/28945534-d109c726-789e-11e7-836d-203ee92bf3eb.PNG)

**Tests on individual XBEs:**

720.xbe ¬
Crashes upon pressing A or Start on the controls screen.
![exceptionc05](https://user-images.githubusercontent.com/13258281/28945578-0458f566-789f-11e7-9c14-a12e368fc005.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198706/KrnlDebug.txt)

Default.xbe ¬
Crashes on black screen.
![defaultexception](https://user-images.githubusercontent.com/13258281/28945769-bbd261c8-789f-11e7-9f9b-fd591a7a4414.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198709/KrnlDebug.txt)

Gauntlet.xbe ¬
Perfect.
![gauntlet](https://user-images.githubusercontent.com/13258281/28945841-122f3de8-78a0-11e7-9359-91d65a7f5e2d.PNG)

Klax.xbe ¬
Perfect.
![klax](https://user-images.githubusercontent.com/13258281/28946060-07af3462-78a1-11e7-85bc-ebd7b4f43f84.PNG)

MarbleMadness.xbe ¬
Perfect.
![marble](https://user-images.githubusercontent.com/13258281/28946144-5dae3d04-78a1-11e7-9fd0-c92f4179d9d1.PNG)

Paperboy.xbe ¬
Crashes upon pressing A or Start on the controls screen.
![paperboy](https://user-images.githubusercontent.com/13258281/28946214-9df044a2-78a1-11e7-8a91-522c2720fb1c.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198737/KrnlDebug.txt)

Rampart.xbe ¬
Perfect.
![rampart](https://user-images.githubusercontent.com/13258281/28946310-15868350-78a2-11e7-8712-598f024d4db7.PNG)

RoadBlasters.xbe ¬
Perfect.
![roadblasters](https://user-images.githubusercontent.com/13258281/28946395-819a4400-78a2-11e7-867f-2e49dddae1c6.PNG)

SmashTV.xbe ¬
Perfect.
![smashtv](https://user-images.githubusercontent.com/13258281/28946453-c813f55c-78a2-11e7-9f80-59cf5755e41f.PNG)

SuperSprint.xbe ¬
Crashes upon pressing A or Start on the controls screen.
![supersprint](https://user-images.githubusercontent.com/13258281/28946485-e727278e-78a2-11e7-9ebc-9bebd59099da.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198747/KrnlDebug.txt)

Toobin.xbe ¬
Crashes upon pressing A or Start on the controls screen.
![toobin](https://user-images.githubusercontent.com/13258281/28946509-01d31868-78a3-11e7-998f-c52e591b06fc.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198757/KrnlDebug.txt)

Vindicators.xbe ¬
Almost perfect. Analog controls are broken - when moving the left analog stick, the Y axis is correctly interpreted, however the X axis is always interpreted as full-right. D-pad movement works fine as an alternative to play the game for now though.
![vindicators](https://user-images.githubusercontent.com/13258281/28946597-6f5f9ec4-78a3-11e7-99e9-596e1bc5772d.PNG)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198760/KrnlDebug.txt)

Ziglar.xbe ¬
This is the interesting one. This appears to be the main menu, but it also has all the games that don't have individual XBEs built into it as well, graphics appear to be broken, however the audio and gameplay seems to work fine.

![ziglar1](https://user-images.githubusercontent.com/13258281/28946671-b451de0c-78a3-11e7-9902-e503dd2bc081.PNG)
Main menu - navigatable with the D-pad. Background is not present, although the game preview and wobble effect on the preview seem to work fine. Also the controls text at the top is present.

![ziglar2](https://user-images.githubusercontent.com/13258281/28946717-ecc47506-78a3-11e7-9559-57d8c3a00c7d.PNG)
All games booted from this menu that do not have XBEs look like this, the game is running and can be played. Audio and controls work, the graphics seem to flicker a lot and are just shades of grey, but you can make out that I have selected Rampage for this screenshot.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198770/KrnlDebug.txt)

![ziglar3](https://user-images.githubusercontent.com/13258281/28946769-3161fa6c-78a4-11e7-8fca-27b1a7cc86b1.PNG)
Any game that does have an XBE that is booted from this menu hangs at a loading screen like this one, with repeating audio of the last 3 seconds played (a bit of the main menu BGM followed by the selection sound).

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1198773/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
Great report!

**Comment by LukeUsher** [comment]
Note that this title has both region flags set, both ELSEWHERE and US_CANADA

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#50

**Comment by crossonrose** [comment]
Another way to do it. If not you die.
