### ISSUE TITLE
Buffy The Vampire Slayer was working on CXBX-Reloaded 98b86c8 (Apr 14, 2017)

### ISSUE THREAD

**Issue by cybertronicgames** [Cxbx-Reloaded/Cxbx-Reloaded#591]
This game was working on build version CXBX-Reloaded 98b86c8a (Apr 14, 2017), The Xinput controller didn't work on any games so, I couldn't start the game. 
https://www.youtube.com/watch?v=uLW0qXI65Gc

**Comment by PatrickvL** [comment]
Perhaps it's better to add this to #241 instead of opening another issue for the same title

**Comment by LukeUsher** [comment]
Let's keep issues relating to the same title together.

**Comment by cybertronicgames** [comment]
I updated the comment with a screenshot & Xbe.txt.

**Comment by cybertronicgames** [comment]
I didn't see the open thread for this title in the compatibility list. Sorry.
