### ISSUE TITLE
[TitleID: 54540001] 4x4 EVO 2 - Crashes after selecting Start

### ISSUE THREAD

**Issue by romaxy151** [Cxbx-Reloaded/Cxbx-Reloaded#594]
The game runs, shows the Intro video but no sound, then on the start screen appears the sound but if you press START the game crashes.
![01](https://user-images.githubusercontent.com/30557931/28957941-e34583ea-78fc-11e7-9d7a-d11edfef232e.PNG)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199495/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199496/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
No audio for intro might be fixed, can you please try again with the latest build? Your version appear to be before the merge of audio fix for "Project Gotham Racing" which now has audio in intro video. It might fix the audio issue on your side.

**Comment by romaxy151** [comment]
Yes, the sound really works in latest build.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#49
