### ISSUE TITLE
[TitleID: 45410013] The Simpsons Road Rage - crashes at the loading screen after the menu

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#596]
Cxbx Reloaded 488db560 Version
 The Simpsons Road Rage - crashes at the loading screen after the menu. Also, the music is fully working at the intro video screen unfortunately without the video itself
![screenshot_2](https://user-images.githubusercontent.com/25540784/28963243-6948db68-7943-11e7-9423-aa704626f58c.png)
![screenshot_3](https://user-images.githubusercontent.com/25540784/28963244-694959e4-7943-11e7-876b-427e42e83e51.png)
![screenshot_4](https://user-images.githubusercontent.com/25540784/28963242-6947bd1e-7943-11e7-9d30-744b7307d39d.png)
![screenshot_8](https://user-images.githubusercontent.com/25540784/28963245-694bfc08-7943-11e7-92e4-4f3b585e7749.png)
![screenshot_9](https://user-images.githubusercontent.com/25540784/28963246-694ecb40-7943-11e7-9954-7f5a392813fd.png)
________________________________________________________________________________________
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199894/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1199933/KrnlDebug.txt)

Note: The game only boots  on Kernel Debug Output to Console

**Comment by PatrickvL** [comment]
@radwolfie This might be something up your alley...

**Comment by ObiKKa** [comment]
LOL. We need a video engineer!

**Comment by RadWolfie** [comment]
Confirmed 2 patches are missing which are...

- IDirectSoundBuffer_SetConeOrientation (4134 sig match, cause of crash)
- IDirectSoundBuffer_SetConeOutsideVolume (4134 sig match, didn't crash yet found in exception function with breakpoint trigger)

However XREF sigs from 4134 doesn't match at all, therefore require a new OOVPA sig for them since the internal functions are mostly different yet identical. (In other word, DSound 4134 and later introduced Enter/LeaveCriticalSection integration.

Finally it is confirmed missing couple patches for D3D section base on breakpoint in exception function. DirectX team, this is something up your alley. ;)

For now it's playable base on my side, yet needs more graphic fixes since I cannot see which direction I am supposed to go with an overlap of what it looks like a shape of a body.

**Comment by furrya** [comment]
Hmm. Very strange. The game now has some rendering problems. Version is 928ae41e
![screenshot_11](https://user-images.githubusercontent.com/25540784/29000435-712effb6-7aa5-11e7-8fc5-e8d304c137d0.png)
![screenshot_12](https://user-images.githubusercontent.com/25540784/29000436-71f46166-7aa5-11e7-8143-5370827fa4fd.png)
_______________________________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202848/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
I am aware of this, recent hot patch does not include OOVPA improvement to detect 2 patches and 2 xrefs. Hence the reason you're getting the same error. What it needs is a complete re-work for scanning title's version against HLE database version. It has been giving several false positives for certain titles. If you would like to try this title out in a playable state, please include these 4 lines below in your title's HLE cache file.

```
IDirectSoundBuffer_SetConeOrientation=17bf06
IDirectSoundBuffer_SetConeOutsideVolume=17bf3b
CDirectSoundBuffer_SetConeOrientation=17bc80
CDirectSoundBuffer_SetConeOutsideVolume=17b7ea
```

**Comment by furrya** [comment]
@RadWolfie Thank you for your explanation about the HLE cache. The game is loading now and shows some of  graphic. Cxbx-Reloaded Version 9d8ae41e.
![screenshot_1](https://user-images.githubusercontent.com/25540784/29003819-c8106ba0-7af8-11e7-934e-974195cdcbd3.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1203112/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
You're welcome, 2 textures on the top and top left side are what's blocking my visible on driving and a pointer where to go. On Nvidia GTX 1080, I can see the buildings, cars, scenery, etc just fine... Except for people are invisible, just like Lego Star Wars having issue with, and the car I'm driving is so dark inside...

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#48
