### ISSUE TITLE
Kung Fu Chaos

### ISSUE THREAD

**Issue by cybergear791** [Cxbx-Reloaded/Cxbx-Reloaded#597]
[0x2710] EmuMain: Recoeved Fatal Message:
* EmuD3DeferredTextureState was not found!
breaks at start up

**Comment by CakeLancelot** [comment]
Could you post the xbe info file? (Edit>Dump Xbe Info To...>File...)
Pretty sure this message is caused by titles that have LTCG. Probably won't be able to be emulated any time soon.

**Comment by cybergear791** [comment]
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1200994/Xbe.txt)

**Comment by CakeLancelot** [comment]
Eeyup

> Library Name                     : D3D8LTCG
Version                          : 1.0.5120
Flags                            : QFEVersion : 0x0001, Retail, Approved

**Comment by PatrickvL** [comment]
Thanks for reporting this nonetheless
