### ISSUE TITLE
[Title ID 49470013] Dungeon & Dragons Heroes boots to title screen, CXBX v. f5e9e777 (Aug 4, 2017). 

### ISSUE THREAD

**Issue by cybertronicgames** [Cxbx-Reloaded/Cxbx-Reloaded#599]
![screenshot 16](https://user-images.githubusercontent.com/14711758/28992239-8395f2bc-795c-11e7-9839-2584b9193670.png)
This game crashes at the first screen with an Exception code 0xC0000005 @ EIP := 0x6A98785F.
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202057/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202073/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202074/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
A screenshot and the Xbe dump attached would be nice

**Comment by cybertronicgames** [comment]
[https://discordapp.com/channels/227919799500406784/227919799500406784](url)

**Comment by cybertronicgames** [comment]
[https://discordapp.com/channels/227919799500406784/227919799500406784](url)

**Comment by cybertronicgames** [comment]
Thanks for the reply, I know your time is valuable. I edited the previous comment & attached the screenshot & Xbe.txt for you.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#47
