### ISSUE TITLE
[TitleID=494d80dc] Lego Star Wars Demo regression

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#600]
### Description

Lego StarWars demo used to be able to get past the main menu and almost ingame, but it now crashes before the menu

---

### Game info

[XBE Dump, KrnlDebug, HLE Cache, Ect]
[BeforeKrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201344/BeforeKrnlDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201348/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201349/Xbe.txt)
[b7400f0et.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202532/b7400f0et.txt)

---

### Status
**Previous behavior:** [Before regression]
Menu, intro video and ALMOST in-game (works with hack)

**Current behavior:** [On the latest build]
Crashes during logos before the menu

---

### Screenshots [Errors, Graphics, Glitches, ECT]

Current build:
![capture](https://user-images.githubusercontent.com/17304943/28982358-5f6374ca-790a-11e7-8de1-c50f9da309c2.PNG)
Before:
![capture2](https://user-images.githubusercontent.com/17304943/28982371-69574f56-790a-11e7-9690-8513ba2129cf.PNG)
![capture3](https://user-images.githubusercontent.com/17304943/28982372-6958e500-790a-11e7-9887-01c990757ce1.PNG)

And it could even go in-game if I stopped the error from showing
![capture4](https://user-images.githubusercontent.com/17304943/28982389-795b6054-790a-11e7-84c2-650d2408c611.PNG)

---

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#46
