### ISSUE TITLE
[TitleID: 424D0001][PAL] Chase: crashes after main menu

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/Cxbx-Reloaded#604]
Hi,
tested with dc9baf3f
titleID: 424D0001
Region: 4
Intros are playing with distorted sound.

It reaches the main menu and crash with "unknown+0x0" after pressing any button
The menu is also broken. It shows last rendered frame as background
![capture20170807223228619](https://user-images.githubusercontent.com/30478365/29044648-afd1bb16-7bc0-11e7-8aa2-b194bf907049.png)
![capture20170804222538057](https://user-images.githubusercontent.com/30478365/28986923-50ed5460-7969-11e7-824d-7934f98143b5.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201642/KrnlDebug.txt)
[KrnlDebug_dc9baf3f.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1206079/KrnlDebug_dc9baf3f.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1201644/Xbe.txt)

**Comment by hotzenplotz3000** [comment]
Error: "DirectSoundBuffer Lock Failed!" fixed with #618

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#45
