### ISSUE TITLE
187 ride or die

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#605]
<img width="479" alt="187 ride or die" src="https://user-images.githubusercontent.com/26704355/28986969-444b1f8a-7937-11e7-8c01-88b60d8e06e4.PNG">

**Comment by CakeLancelot** [comment]
Most likely a LTCG title, should be closed for now.

**Comment by PatrickvL** [comment]
First attach an Xbe dump, like described in the readme

**Comment by fatjohnny118** [comment]
yes i will add them soon sorry bout that
