### ISSUE TITLE
EmuNV2A: Incorrect mappings

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#61]
The switch statements in EmuNV2A_Read/Write functions are incorrect.

As an example, when hardware is attempting to access the 0x800044 (NV_USER_DMA_GET), the switch case statement interprets the access as an unknown PMC address (0x000044).

I ran into this while experimenting with disabling the CreateDevice patch

**Comment by LukeUsher** [comment]
Rather than fix the switch/case, it is probably better to look into implementing a mapping data structure similar to Qemu or Mame.

**Comment by LukeUsher** [comment]
Fix in pull request #62

**Comment by PatrickvL** [comment]
Other address ranges, for other devices, will benefit from a fast mapping mechanism too. Since we want out to be as fast as possible and since we don't have to create these dynamically, like in MAME, an optimized lookup can be constructed, that can cover all address ranges, not just the nv2a.
