### ISSUE TITLE
007 from russia with love

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#611]
<img width="479" alt="from russia with love" src="https://user-images.githubusercontent.com/26704355/28987242-720e1bec-7938-11e7-93a9-1d202f539568.PNG">

**Comment by BenNottelling** [comment]
@fatjohnny118 please only create an issue if game boots and shows graphics or plays audio

**Comment by PatrickvL** [comment]
Also, follow the procedure described in the readme

**Comment by fatjohnny118** [comment]
yes i will add them soon sorry bout that
