### ISSUE TITLE
timesplitters 2 pal

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#613]
<img width="477" alt="timesplitters2" src="https://user-images.githubusercontent.com/26704355/28987291-9d6faed6-7938-11e7-8367-75992c09f058.PNG">

**Comment by LukeUsher** [comment]
These bug reports are useless without the following information:
The TitleID and Region/Version of the title you are running
The XBE Dump text file generated by Cxbx-Reloaded (Edit Menu)
A kernel Debug log from Cxbx-Reloaded

**Comment by HyperScorpio** [comment]
Open the .xbe game, clean the cache first and try again. If the problem continues there is nothing you can do and better wait for a fix.

**Comment by fatjohnny118** [comment]
yes i will add them soon sorry bout that
