### ISSUE TITLE
SEGA GT 2002 (PAL Version)

### ISSUE THREAD

**Issue by HyperScorpio** [Cxbx-Reloaded/Cxbx-Reloaded#614]
![sega gt pal](https://user-images.githubusercontent.com/30736913/28988579-55850e60-7968-11e7-99a5-a07ceb8f29e9.png)

After opening the .xbe the emulator show this warning, it seems this game is not yet added to the emulator.
Before everyone report any error, please always clean your cache before starting a new game.
Thank you 👍

**Comment by PatrickvL** [comment]
Please follow the proper procedure for posting issues

**Comment by BenNottelling** [comment]
Titles with the error"EmuD3DDeferredRenderState" are often LTCG, meaning it is completely unsupported as of the moment. Also with issues we are looking for:
Screenshots
XBE dumps
Cxbx-Reloaded debug dumps
And HLE cache (title ID should be in this, but we want this as well)

**Comment by HyperScorpio** [comment]
Untill we have this errors is very hard to know how many bugs are in the game 👍

**Comment by LukeUsher** [comment]
I'm pretty certain this is an LTCG title and cannot be supported by Cxbx-Reloaded at this time. Emulating this title will require low-level emulation of the NV2A graphics hardware, which doesn't exist yet in Cxbx-Reloaded.

You may have better luck with XQEMU.

**Comment by HyperScorpio** [comment]
XQEMU is very slow for my computer.

**Comment by LukeUsher** [comment]
Currently if you want to play this game, your only options are XQEMU or a real xbox.
This game will not be supported in Cxbx-Reloaded until after we have full LLE of the NV2A graphics hardware, which is potentially long time away from now.
