### ISSUE TITLE
Jet Set Radio Future issues

### ISSUE THREAD

**Issue by HyperScorpio** [Cxbx-Reloaded/Cxbx-Reloaded#619]
Funny how we spray in the cops back and it doesn´t bug the map at all. The save game graffiti appears a annoying white X in the middle and it hide you from the screen.

The game just crash on all Spray edit options and in the secound tutorial from Roboy Charather. 

A error as well when we go to a new stage.
We press ok and we able to play it.

![1](https://user-images.githubusercontent.com/30736913/28988980-77b27eee-796a-11e7-9007-2ac8308dae3b.png)

I can confirm in a few graffiti's they are fixed in the first map, but in the wrong position, instead having the normal one's, it shows others. 
Example: The Fish instead that red boy with a microfone.
And those one's are locked by the graffiti souls yet. :)
Check and test the original game first. 

PS: I remove the message before and put it as new issue for @RadWolfie recieve my message. :)

NEW.

In the end of the 2nd level when i paint the last graffiti the game stops and say the disc is dirty or damage.

**Comment by JackaJacka123** [comment]
This sounds a lot like issues found in #251 and/or #466

**Comment by HyperScorpio** [comment]
It seems all game have this problem. I bypass the 2nd level and i finish. When i go play the streets of Rapid 99 the game crash.

**Comment by RadWolfie** [comment]
I already made a record about this pop up message in issue #485, which is...

> EmuPatch_IDirectSound_SetOrientation return 0x80070057 (DSERR_INVALIDPARAM)


P.S. What you did not include per pop up message requested are function name and return value code. If it is different from this, then put it in the issue I mentioned above. Don't create a new issue just for this. Thanks.

**Comment by Sarkie** [comment]
Regarding graffiti.

Are you saying instead of one texture being there an incorrect one is loaded instead?

**Comment by HyperScorpio** [comment]
@Sarkie Yes.

**Comment by Sarkie** [comment]
Can you verify on hardware if possible?

**Comment by CakeLancelot** [comment]
> Can you verify on hardware if possible?
I can confirm this issue (Second image is actual xbox):
![cxbx_2017-08-08_13-07-07](https://user-images.githubusercontent.com/5341136/29087166-a80c9e8a-7c3a-11e7-86ca-112b1dee72c8.png)
![graffiti](https://user-images.githubusercontent.com/5341136/29087180-adc70f86-7c3a-11e7-966d-2e9c78864814.png)

**Comment by ladsoftware** [comment]
Cant wait to see everything working.

**Comment by Sarkie** [comment]
@CakeLancelot Do you have another example please? 

I am guessing/hoping it is loading the wrong textures in a specific way, e.g. off-by-one error 
I'm hoping its a similar bug to one of my fave Dolphin bugs.
https://github.com/dolphin-emu/dolphin/commit/ed67d1ae2f9693ed42867a2e79b7cae4427574e3

**Comment by PatrickvL** [comment]
Wrong textures might be caused by an incorrect state after handling point sprite effects (as these move textures from stage 3 to 1). Or it might be mipmap related. We'll have to do some thorough investigation for this

**Comment by HyperScorpio** [comment]
Map Zone - 99th Street

![3](https://user-images.githubusercontent.com/30736913/29174484-61736bca-7dde-11e7-8469-fb01e892a069.png)

Graffiti
![2](https://user-images.githubusercontent.com/30736913/29174487-65b60314-7dde-11e7-9949-df0ee7488ce2.png)

The annoying white cross
![1](https://user-images.githubusercontent.com/30736913/29174491-67f5a18e-7dde-11e7-8e46-346cf615842a.png)

The annoying brown rectangle
![4](https://user-images.githubusercontent.com/30736913/29174495-6ae009f2-7dde-11e7-9dea-699c8afd5dad.png)

After beat the crazy cop.
![5](https://user-images.githubusercontent.com/30736913/29174498-6cd30368-7dde-11e7-9641-7e07a1997fe2.png)

Before entering on the Garage
![6](https://user-images.githubusercontent.com/30736913/29174501-6f04f614-7dde-11e7-929a-13cce6ca2f8c.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#44
