### ISSUE TITLE
[GUI] Set non-default Log files name then Log is not output.

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#620]
I set the log file which changed KrnlDebug.txt to another name (e.g. wip_log.txt), I then relunched Cxbx.exe
The log is not output to the specified log file.

The registry keys KrnlDebugFilename are initialized.

might be PR #548 related.

**Comment by ergo720** [comment]
You're right. Strangely enough, it happens only with the kernel log, not with the cxbx log. I will investigate this...
