### ISSUE TITLE
The Suffering: Ties That Bind

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/Cxbx-Reloaded#621]
Tested on 9d8ae41e

Region; PAL

The game hangs, right after booting with the following error.

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204873/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204874/KrnlDebug.txt)
![bandicam 2017-08-07 14-52-53-179](https://user-images.githubusercontent.com/29869781/29027634-c6f4d632-7b81-11e7-814d-fddba6a01e6b.png)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#43
