### ISSUE TITLE
BLiNX: the time sweeper

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/Cxbx-Reloaded#622]
Tested on 9d8ae41e
Region: PAl

The Game shows something for a fraction of second, then crashes.
![bandicam 2017-08-07 15-16-39-227](https://user-images.githubusercontent.com/29869781/29028070-6c157760-7b83-11e7-8254-27c34af0c396.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204916/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204917/KrnlDebug.txt)

**Comment by ObiKKa** [comment]
Can you refer to issue #235? Add your shots and comment there. Just use the search bar in the issue list to try to find a relevant game issue page.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#42

**Comment by nathan1234543** [comment]
Here's an update on the status of this game with the latest build currently available: https://youtu.be/j10Ro4lcTO8

fresh install of CXBX-R, with input options for an original 'duke' style controller being the only touched settings.
