### ISSUE TITLE
Splinter Cell 2 (online xbe) 55530019

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/Cxbx-Reloaded#623]
Tested on 9d8ae41e

Region PAL

The game shows the splash screen and the loading screen, once it has finished loading the game crashes.

![bandicam 2017-08-07 15-37-22-627](https://user-images.githubusercontent.com/29869781/29029128-e1847f02-7b86-11e7-8c8b-21e091e53300.png)
![bandicam 2017-08-07 00-56-35-864](https://user-images.githubusercontent.com/29869781/29029131-e46e0792-7b86-11e7-926b-2654a5f94f96.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204983/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1204982/Xbe.txt)

**Comment by ObiKKa** [comment]
As I said before it's wise to use the search bar in the issue list. Two issue pages already exist for this game, SC 2: Pandora Tomorrow - #401 & #455 (The latter has the same result screens as yours).

**Comment by LukeUsher** [comment]
Obikka is correct, closing as duplicate
