### ISSUE TITLE
Narc

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/Cxbx-Reloaded#624]
Tested on 9d8ae41
Region PAL

The game shows the splash screen, right after an error saying "could not create overly surface

![bandicam 2017-08-07 15-56-19-940](https://user-images.githubusercontent.com/29869781/29029866-6833d8b6-7b89-11e7-8d9e-0a34c33b9fc3.png)
![bandicam 2017-08-07 15-56-25-410](https://user-images.githubusercontent.com/29869781/29029869-694d748c-7b89-11e7-917b-ff98523b405e.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1205031/KrnlDebug.txt)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1205027/Xbe.txt)

**Comment by PatrickvL** [comment]
Try playing with the hardware overlay setting

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#41
