### ISSUE TITLE
Shenmue II

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/Cxbx-Reloaded#625]
Tested on 9d8ae41e
Region PAL

The game will progess less than the demo, it will hang on the first loading screen.

The console shows the following error.
EmuPatch_IDirectSound_DownloadEffectsImage unimplemented!

![bandicam 2017-08-07 20-36-38-299](https://user-images.githubusercontent.com/29869781/29040757-86c65dea-7bb0-11e7-9396-f7705bb4c5fa.png)

The loading screen looks like it is freezed, but if you turn on wireframe you can see how it is still moving.

![bandicam 2017-08-07 20-36-33-890](https://user-images.githubusercontent.com/29869781/29040802-b2d2a4c0-7bb0-11e7-971b-b68b1a527967.png)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1205780/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1205781/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#40
