### ISSUE TITLE
The Thing -- Crash on boot (LLE GPU)

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#627]
### Description

This title is LTGC, but if I enable LLE GPU I get an "unknown error".
PAL, win10, 0x56560003[title ID], dc9baf3f
---

### Game info
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1206406/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1206407/Xbe.txt)

---

### Status
**Previous behavior:** No info

**Current behavior:** Crashes shortly after booting

---

### Screenshots [Errors, Graphics, Glitches, ECT]
![capture](https://user-images.githubusercontent.com/30000751/29049270-81572736-7bc4-11e7-8862-d80c007bdfd8.PNG)

---

### Additional Information

I don't know if this is useful, I have also other LTGC games that crash like this.

**Comment by LukeUsher** [comment]
LLE GPU doesn't exist or work yet, this is normal/not an issue

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#39
