### ISSUE TITLE
25 To Life Boots

### ISSUE THREAD

**Issue by MarcoLoves360** [Cxbx-Reloaded/Cxbx-Reloaded#628]
### Description
game boots for a sec then crashes

---

![untitled](https://user-images.githubusercontent.com/30830822/29069154-9cd300c6-7c31-11e7-86f0-ae1567e74e42.jpg)

![2](https://user-images.githubusercontent.com/30830822/29069243-fd122c00-7c31-11e7-916f-dd10cb390cd6.jpg)

---

---

### Additional Information

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1207776/KrnlDebug.txt)

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1207785/CxbxDebug.txt)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1207794/Xbe.txt)

Any additional information such as configuration or other comments

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#38
