### ISSUE TITLE
4X4 EVOLUTION

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#629]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210074/CxbxDebug.txt)
<img width="601" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102172-486b8e32-7c85-11e7-9319-458bab7a791e.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210075/KrnlDebug.txt)
xbe dump below
[4x4 evolution.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213188/4x4.evolution.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#37
