### ISSUE TITLE
MK Deception crash

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#63]
Mortal Kombat crashing with exception in Cxbx-Reloaded b7f4b23(24 Dec 2016).
Part of log:
EmuMain (0x990): Recieved Exception (Code := 0xC0000005)
 EIP := 0x10047E56 EFL := 0x00010212
 EAX := 0x00000000 EBX := 0x00000000 ECX := 0x0000002E EDX := 0x0000002D
 ESI := 0x089DF250 EDI := 0x00000000 ESP := 0x089DDD10 EBP := 0x089DF23C
 CR2 := 0x00000000
EmuMain (0x990): Aborting Emulation

Why I think that is issue - at 791f885 (23 Dec 2016) MK boots until start menu (without graphics but with sound). Second run - error with trying dashboard loading. Cleaning of folder "AppData/Cxbx-Reloaded" will fix it, next try will also lead to start menu, next - boot dashboard,etc.

**Comment by PatrickvL** [comment]
Thanks for reporting this. Yet another title that has the potential to get further

**Comment by cybertronicgames** [comment]
[Title ID 4D570019] Mortal Kombat: Deception is getting sound but, no video.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202081/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202082/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202083/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#196
