### ISSUE TITLE
9 in 1

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#631]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210104/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102552-ef1e779c-7c87-11e7-96b1-dec0908a72c0.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210105/KrnlDebug.txt)
xbe dump below
[9 in 1.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213204/9.in.1.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#35
