### ISSUE TITLE
25 to life

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#632]
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102579-28ebc45c-7c88-11e7-942e-78a915860bc5.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210368/KrnlDebug.txt)

**Comment by literalmente-game** [comment]
Region: ?
Also, fix the "KrnDebug.txt" log link

**Comment by fatjohnny118** [comment]
regian is all and for some reason it doesnt want to play nice with the KrnDebug.txt i am using shaw open waiting for net at home apoligize for any inonvenence

**Comment by literalmente-game** [comment]
+ Duplicate from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/628, I guess

**Comment by fatjohnny118** [comment]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210370/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
Why all the Dxbx screenshots? Doesn't any of the recent titles you added generate gracious or sound?

**Comment by fatjohnny118** [comment]
they due sound but sound sometimes i garblled  i put the dxbx screenshots so the developers know what titles i have to eliminate confusion some say in discord region doesnt matter but i think it does and a few other devs have said certain games with diffrent regions work better besides that i like to be descriptive as best i can

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#34
