### ISSUE TITLE
187 ride or die

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#634]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210112/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102602-56cb2bd8-7c88-11e7-80f2-ad43f0d877ab.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210113/KrnlDebug.txt)

**Comment by fatjohnny118** [comment]
xbe dump below
[187 ride or die.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213222/187.ride.or.die.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#32
