### ISSUE TITLE
advent rising

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#635]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210115/CxbxDebug.txt)
<img width="959" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102611-68ce9752-7c88-11e7-863a-4fed4db77a6a.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210116/KrnlDebug.txt)
xbe dump below
[advent rising.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213223/advent.rising.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#31
