### ISSUE TITLE
afl live 2003

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#636]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210119/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102624-798fb1de-7c88-11e7-8011-3a65818b9c2a.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210121/KrnlDebug.txt)
xbe dump below
[afl live 2003.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213224/afl.live.2003.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#30
