### ISSUE TITLE
afl live 2004

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#637]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210123/CxbxDebug.txt)
<img width="958" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102634-8aca4d10-7c88-11e7-8dc5-7d202ab55f3b.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210124/KrnlDebug.txt)
xbe dump below
[afl live 2004.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213226/afl.live.2004.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#29
