### ISSUE TITLE
afl live premium ship edition

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#638]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210128/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102654-a763bb78-7c88-11e7-9ccd-a1d2fb365e56.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210129/KrnlDebug.txt)
xbe dump below
[afl live premium ship edition.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213227/afl.live.premium.ship.edition.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#28
