### ISSUE TITLE
afl premium ship

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#639]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210132/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102667-c18c4eac-7c88-11e7-94cd-3669c931f740.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210133/KrnlDebug.txt)
xbe dump below
[afl premiumship.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213228/afl.premiumship.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#27
