### ISSUE TITLE
after burner 2 arcade

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#640]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210135/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102682-d6468862-7c88-11e7-813c-12247d00c76b.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210136/KrnlDebug.txt)
xbe dump below
[after burner ll arcade.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213230/after.burner.ll.arcade.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#26
