### ISSUE TITLE
agressive inline

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#641]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210139/CxbxDebug.txt)
<img width="958" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102693-e6495f82-7c88-11e7-91bb-59de021635b9.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210140/KrnlDebug.txt)
xbe dump below
[agressive inline.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213231/agressive.inline.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#25
