### ISSUE TITLE
air force delta 2

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#642]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210141/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102700-f8bb5de6-7c88-11e7-9d25-cce1b465de86.PNG">
[krnldebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210162/krnldebug.txt)
xbe dump below
[AIRFORCE DELTA II.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213233/AIRFORCE.DELTA.II.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#24
