### ISSUE TITLE
air force delta storm

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#643]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210163/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102973-da9f1fda-7c8a-11e7-8cd5-d50f70169dd6.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210164/KrnlDebug.txt)
xbe dump below
[Airforce Delta Storm.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213243/Airforce.Delta.Storm.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#23
