### ISSUE TITLE
alias

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#644]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210167/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102992-0079351a-7c8b-11e7-9d7c-376e60f7dd9d.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210168/KrnlDebug.txt)
xbe dump below
[ALIAS.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213247/ALIAS.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#22
