### ISSUE TITLE
all star baseball 2004

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#645]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210171/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103003-1110b1a0-7c8b-11e7-9874-7740bcc770f6.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210172/KrnlDebug.txt)
xbe dump below
[All-Star Baseball '04.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213248/All-Star.Baseball.04.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#21
