### ISSUE TITLE
american chopper 2

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#646]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210174/CxbxDebug.txt)
<img width="957" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103018-2dec923a-7c8b-11e7-96b9-5af3259269f5.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210175/KrnlDebug.txt)
xbe dump below
[American Chopper 2 Full Throttle.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213250/American.Chopper.2.Full.Throttle.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#20
