### ISSUE TITLE
americas army rise of a soldier

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#647]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210177/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103027-4aaedd9c-7c8b-11e7-8891-58994b8ba3cf.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210178/KrnlDebug.txt)
xbe dump below
[America’s Army RoaS.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213252/America.s.Army.RoaS.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#19
