### ISSUE TITLE
amf bowling 2004

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#648]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210179/CxbxDebug.txt)
<img width="959" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103046-60943724-7c8b-11e7-846f-f4d62853d506.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210180/KrnlDebug.txt)
xbe dump below
[AMF Bowling 2004.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213253/AMF.Bowling.2004.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#18
