### ISSUE TITLE
amf extreme bowling

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#649]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210182/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103062-71c9bfb4-7c8b-11e7-91be-8f545aecbef8.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210183/KrnlDebug.txt)
xbe dump below
[AMF Xtreme Bowling 2006.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213254/AMF.Xtreme.Bowling.2006.txt)

**Comment by literalmente-game** [comment]
Duplicate from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/298

**Comment by fatjohnny118** [comment]
sorry i apoligize just trying to help but thank for taking the time to look

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#17
