### ISSUE TITLE
amped

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#650]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210184/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103077-82efd4ae-7c8b-11e7-9fe9-3798886c8945.PNG">
<img width="322" alt="capture" src="https://user-images.githubusercontent.com/26704355/29103080-852089c6-7c8b-11e7-9f21-62ce75dd7d28.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210185/KrnlDebug.txt)
xbe dump below
[Amped.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213255/Amped.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#16
