### ISSUE TITLE
and 1 street ball 

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#651]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210186/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103088-941131e2-7c8b-11e7-9597-9b6890902d52.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210187/KrnlDebug.txt)
xbe dump below
[And 1 StreetBall.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213257/And.1.StreetBall.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#15
