### ISSUE TITLE
area 51

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#652]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210189/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103104-a4115e14-7c8b-11e7-82f1-602508af75c8.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210191/KrnlDebug.txt)
xbe dump below
[Area51.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213259/Area51.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#14
