### ISSUE TITLE
avp 

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#653]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210192/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103115-b2d79cba-7c8b-11e7-9a0b-7ecdbd08a557.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210194/KrnlDebug.txt)
xbe dump below
[AvP Extinction.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213260/AvP.Extinction.txt)

**Comment by HyperScorpio** [comment]
That is DXBX Emulator not CXBX. Grab throw here: https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/job/0x2ptrtguykrj7lv/artifacts Thank you.

**Comment by fatjohnny118** [comment]
im using dxbx to show what version of the game i am using with cxbx reloaded

**Comment by HyperScorpio** [comment]
It doesn´t make any sence! Test CXBX not DXBX. They are different emulators and secound please use the search bar before you make a new filter. Thank you.

**Comment by Sarkie** [comment]
He's using as a reference for versioning only

**Comment by fatjohnny118** [comment]
yes sarkie thats right

**Comment by HyperScorpio** [comment]
Ah okay thanks.

**Comment by fatjohnny118** [comment]
yeh i wanted to show the librarys the game uses and region some say usa pal and others say all so no region i would assume is a patch

**Comment by LukeUsher** [comment]
All this information is present in an Xbe dump, no need to screenshot Dxbx.
What we need are XBE Dumps (COMPLETE!) and Kernel logs.

To get an XBE Dump: In Cxbx-Reloaded, to to Edit->Dump XBE Info To => File.

**Comment by fatjohnny118** [comment]
ok i will due that ill be back with that info and add xbe dump

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#13
