### ISSUE TITLE
dino crisis 3

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#655]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210198/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103181-0f1a1e8a-7c8c-11e7-8fef-d88ca4cc7ccb.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210199/KrnlDebug.txt)
xbe dump below
[DINO CRISIS 3.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213262/DINO.CRISIS.3.txt)

**Comment by literalmente-game** [comment]
Duplicate from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/416

**Comment by fatjohnny118** [comment]
sorry i apoligize im just trying to make sure the version im using is getting worked on as well as others

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#11
