### ISSUE TITLE
007 from russia with love

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#656]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210200/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103194-2556b9b0-7c8c-11e7-8817-960baeee6f4b.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210201/KrnlDebug.txt)
xbe dump below
[FROM RUSSIA WITH LOVE.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213263/FROM.RUSSIA.WITH.LOVE.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#10
