### ISSUE TITLE
quantum redshift

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#657]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210203/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103209-38a3de6c-7c8c-11e7-8fe2-d40fe5e9556e.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210204/KrnlDebug.txt)
xbe dump below
[Quantum Redshift.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213264/Quantum.Redshift.txt)

**Comment by literalmente-game** [comment]
Duplicate from https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/30

**Comment by fatjohnny118** [comment]
sorry i apoligize just trying to help but thank for taking the time to look

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#9
