### ISSUE TITLE
timesplitters 2

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/Cxbx-Reloaded#658]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210205/CxbxDebug.txt)
<img width="958" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29103216-494575fa-7c8c-11e7-9222-60d10061684b.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210207/KrnlDebug.txt)
xbe dump below
[TimeSplitters 2.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213265/TimeSplitters.2.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#8
