### ISSUE TITLE
The King Of Fighters '94 Rebout (NTSC-U)

### ISSUE THREAD

**Issue by HyperScorpio** [Cxbx-Reloaded/Cxbx-Reloaded#659]
![sem titulo](https://user-images.githubusercontent.com/30736913/29148137-88de9958-7d63-11e7-9d19-51c3673b443a.png)

**Comment by BenNottelling** [comment]
As I already said here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/614#issuecomment-320423571
This title is probably LTCG so we can't support it in Cxbx-Reloaded, this report is also missing a XBE dump, kernal debug, ect making it useless to us

**Comment by HyperScorpio** [comment]
Now i get it. This errors are the same for the games are not yet added, sorry next time i will search for bugs ingame. Thanks!

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#7
