### ISSUE TITLE
House of the dead 3

### ISSUE THREAD

**Issue by luffytam** [Cxbx-Reloaded/Cxbx-Reloaded#660]
### Description

Black screen and high CPU usage and system slowdown
---

### Game info
[HOTD3 KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1215134/HOTD3.KrnlDebug.txt)
[HOTD3 Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1215138/HOTD3.Xbe.txt)

---

### Status
**Previous behavior:** [Before regression]
blackscreen
**Current behavior:** [On the latest build]
blackscreen
---

### Screenshots [Errors, Graphics, Glitches, ECT]
![hotd3](https://user-images.githubusercontent.com/8058504/29174063-c6f77e9e-7e17-11e7-9e64-1d678f29b16a.jpg)

---

### Additional Information
No LLE

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#6
