### ISSUE TITLE
House of the dead 2

### ISSUE THREAD

**Issue by luffytam** [Cxbx-Reloaded/Cxbx-Reloaded#661]
### Description

First time show me a unhandled exception and in the next few times booting with black screen

---

### Game info
[XBE Dump, KrnlDebug, HLE Cache, Ect]
[HOTD2 KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1215182/HOTD2.KrnlDebug.txt)
[HOTD2 Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1215183/HOTD2.Xbe.txt)

---

### Status
**Previous behavior:** [Before regression]

**Current behavior:** [On the latest build]
blackscreen or unhandled exception
---

### Screenshots [Errors, Graphics, Glitches, ECT]
![hotd2](https://user-images.githubusercontent.com/8058504/29174466-016a882c-7e19-11e7-930a-67a42a8e0bbc.jpg)

---

### Additional Information
No LLE

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#5
