### ISSUE TITLE
crash wrath of cortex black screen

### ISSUE THREAD

**Issue by saq123** [Cxbx-Reloaded/Cxbx-Reloaded#662]
Every time I run the .XBE file or the logo does not appear! Only one black screen

**Comment by literalmente-game** [comment]
As Cxbx-Reloaded is in early stages of development right now, most games will either crash or do nothing. Please do not submit issues for these games.

Please report games that actually do something. If a game outputs graphics or audio before crashing, please submit a bug report at GitHub containing the build tested with, error message displayed (if any), screenshots, an Xbe dump (created via [Edit -> Dump Xbe Info To -> File]), and a Kernel Debug file (created when running a game when [View -> Debug Output (Kernel) -> File]) is selected.

**Comment by saq123** [comment]
oh,sorry.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#4

**Comment by lowdickieshighsocks** [comment]
I’m not too used to this platform so I don’t know where to report this or who to contact about this, but I tried playing crash bandicoot TWOC yesterday and the game kept crashing at the loading screens where crash is falling through a green wormhole looking thing, I get an error saying the xbe received an unexpected load or something along the lines of that
