### ISSUE TITLE
[NTSC] Alien vs Predator Extinction

### ISSUE THREAD

**Issue by romaxy151** [Cxbx-Reloaded/Cxbx-Reloaded#663]
### Description
The game crashes immediately after splash screen

---

### Game info
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1217835/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1217836/Xbe.txt)

---

### Screenshots [Errors, Graphics, Glitches, ECT]
![default](https://user-images.githubusercontent.com/30557931/29213392-c58878a8-7eab-11e7-9c9a-5ddca2cb07d1.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#3
