### ISSUE TITLE
Sneakers - Broken logo screens (grey triangles), Black screen, eventually crashes

### ISSUE THREAD

**Issue by Voxel9** [Cxbx-Reloaded/Cxbx-Reloaded#665]
Basically what it says on the title. Nothing but 2 grey triangles on bootup, which I assume are the logo screens, then nothing but a black screen, and crashes a few seconds later.
You can hear the title music, and using the analog stick and A button seems to play navigation sound effects, so it's at least a _tiny_ bit interactive...

![image](https://user-images.githubusercontent.com/16278868/29251066-a0c76b90-8046-11e7-85ec-1a94d23b1bd2.png)

![image](https://user-images.githubusercontent.com/16278868/29251100-43936bf8-8047-11e7-92ac-7b14052d99b8.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1220552/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1220553/Xbe.txt)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#2
