### ISSUE TITLE
[NTSC] American Chopper

### ISSUE THREAD

**Issue by romaxy151** [Cxbx-Reloaded/Cxbx-Reloaded#667]
I just don't know how to explain it all.
Here's the video: https://youtu.be/n1ncUqwBceQ
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1222867/Xbe.txt)
[KrnlDebug.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1223015/KrnlDebug.zip)

**Comment by literalmente-game** [comment]
Compact the file with 7zip (in the .zip format) and upload it

**Comment by BenNottelling** [comment]
Also turn on v-sycn so it's closer to real time speed.. maybe we will be able to see something

**Comment by romaxy151** [comment]
Enabled V-sync the FPS count decreased but still not what is not seen.

**Comment by BenNottelling** [comment]
Darn, I was hoping it was just playing too fast 😀 oh well

**Comment by romaxy151** [comment]
And the font is all squares.

**Comment by LukeUsher** [comment]
It has been brought to our attention that the linked YouTube video contains evidence of using illegally downloaded content on Cxbx-Reloaded. (Path references to a known piracy website in the recent history menu). 

We cannot and will not provide any support for illegally downloaded software. Emulation is not illegal, but running games that you do not own, and did not dump yourself is, so this is a necessary stance to protect the project from possible legal action. There is also the possibility that the reference to said piracy site could be seen as advertisement or endorsement for the website on our behalf, which is not the case.



Additionally, there are technical reasons why we should not support pirates content: the software could be modified in ways that could interfere with normal execution.
