### ISSUE TITLE
Add 'self-referencing' XREF feature to our OOVPA's

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#669]
I've got an idea on XREF's that point inside a function itself;

Currently, the (offset+value)-tuples are used for two purposes;
1. Actual byte values at specified offsets - this is the primary usage
2. XREF ID's at specified offsets - this is a secondary usage

(Note : A while ago, I swapped the members of XREF entries, so that the uint08 is used as Offset, while the uint16 is used as XREF ID. I did this, so that we can have up to 2^16=65536 XREF ID's instead of only 2^8=256, without sacrificing storage space.)

Anyway, we could add an additional usage to the (offset+value)-tuples:
3. uint08 Delta, uint16 Offset - a third usage of the same tuple definition.

We would need to add a counter to the OOVPA to indicate the amount of these entries.

I'm not yet sure if these tuples should come before or after the normal XREF entries,
but they should surely come before the normal (offset+value)-tuples / OV-pairs.

Then, we would need to add the neccesary code that checks for each of the Offset's,
if the function references itself with the given Delta or not.

I suspect most (if not all) internal references will be relatively addressed
(see https://en.wikipedia.org/wiki/Addressing_mode#PC-relative ).

(We could allow absolute addressed references too, but log if this ever happens,
but I don't expect it will ever show up.)

If any of the internal 'self'-references fails, the checking on this address failed,
so should stop and return to the caller, who will probably try another address.

For this issue:
* discuss this idea
* reach consensus
* formulate follow-up steps

**Comment by PatrickvL** [comment]
Thinking about this some more, maybe this didn't really necessary, since the same offsets could just as well be checked with regular offset+value pairs.

**Comment by RadWolfie** [comment]
Moved to XbSymbolDatabase
