### ISSUE TITLE
Spongebob - Battle for Bikini Bottom crashes on initial screen

### ISSUE THREAD

**Issue by notkaleb56** [Cxbx-Reloaded/Cxbx-Reloaded#670]
### Description

Displays garbled copyright screen and crashes

---

### Game info
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1226178/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1226179/KrnlDebug.txt)

---

### Screenshot
![image](https://user-images.githubusercontent.com/19540035/29333071-492b9fba-81b7-11e7-9d89-832bb24a4db3.png)

**Comment by LukeUsher** [comment]
We have a separate issue tracker for game compatibility issues, this issue tracker is for issues relating directly to emulation only.

Please create a new issue in https://github.com/Cxbx-Reloaded/game-compatibility, make sure to read the readme there first!
