### ISSUE TITLE
Show loaded XBE logo in user interface

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#674]
Many Xbe files contain a logo image. (Dxbx showed these on its user interface.) Do the same in Cxbx-Reloaded. Do it such that it's easily portable to Qt, might we switch over to that later on.

Note, there's three types of images:

1. a 100x17 pixel 4-bit gray-scale banner, often showing the "Microsoft" company logo
2. a 128x128 (or 64x64), full color game-specific logo
3. a 128x128 (or 64x64), full color game-specific save icon

[The banner is already shown in the lower-right corner of our GUI once an XBE is loaded.](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/c8c4f81e73041568da09be9958446168ed93a85b/src/Cxbx/WndMain.cpp#L1279)

For this issue, load and show the game-specific logo. If that's absent, show the save icon instead.
For now, if there's no logo present at all, show nothing (or a ["No icon available" image](http://dxbx-emu.com/wp-content/gallery/screenshots/XMarbles.JPG)).

Some pointers :
* [Dxbx mentions two images](https://github.com/PatrickvL/Dxbx/blob/master/Source/Delphi/src/uConsts.pas#L129) : 
````
  // XPR constants
  XBE_SECTIONNAME_GAMEICON = '$$XTIMAGE';
  XBE_SECTIONNAME_SAVEICON = '$$XSIMAGE';
````
* [Dxbx contains code that loads the Logo](https://github.com/PatrickvL/Dxbx/blob/bcafc5b5e022c8a884241731607f99731ef3e7ee/Source/Delphi/src/uXbe.pas#L1184)
* [Dxbx contains code that shows the Logo](https://github.com/PatrickvL/Dxbx/blob/master/Source/Delphi/src/ufrm_Main.pas#L1860) (it rounds the corners somewhat too)
* [Dxbx screenshot gallery, showing the logo](http://dxbx-emu.com/media/screenshots/)

**Comment by LukeUsher** [comment]
I believe the Microsoft logo is already shown, at least I remember seeing code relating to this within Cxbx-Reloaded. It should appear somewhere at the bottom of the window when a Microsoft XBE is loaded. (If it even works, that is)

**Comment by PatrickvL** [comment]
Turns out you're right : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/Cxbx/WndMain.cpp#L1269

**Comment by PatrickvL** [comment]
Dxbx loads the Logo with the following code : https://github.com/PatrickvL/Dxbx/blob/bcafc5b5e022c8a884241731607f99731ef3e7ee/Source/Delphi/src/uXbe.pas#L1184
And it shows the Logo with the following code : https://github.com/PatrickvL/Dxbx/blob/master/Source/Delphi/src/ufrm_Main.pas#L1860 (it rounds the corners somewhat too).

**Comment by PatrickvL** [comment]
https://github.com/PatrickvL/Dxbx/blob/master/Source/Delphi/src/uConsts.pas#L129 mentions two images : 
````
  // XPR constants
  XBE_SECTIONNAME_GAMEICON = '$$XTIMAGE';
  XBE_SECTIONNAME_SAVEICON = '$$XSIMAGE';
````

**Comment by PatrickvL** [comment]
@Luca1991 has done this in PR #708, so closing this issue.
