### ISSUE TITLE
Remove remnant visual elements after emulation stops/crashes

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#678]
Once emulation stops, all visual emulation output (like FPS counter and LED states) should not be drawn anymore.
(See https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/574#issuecomment-324013493 for more details).

If this is already working correctly when emulation is terminated manually, then check if emualtion crashes are handled correctly too. If not, fix those by somehow detecting the crash.

**Comment by LukeUsher** [comment]
One possibility would be storing the process ID of the child emulation process we create, then checking it's status in a polling loop (based around some kind of timer so it doesn't waste resources). If the process no longer exists, we can assume it has either crashed, or emulation has been stopped through other means.

Note that this may cause problems for titles with multiple xbe's.. When the emulator needs to load a new Xbe, it kills the current process and starts a new one. This situation would need to be handled, perhaps by using something in EmuShared to enable/disable the process monitoring.

**Comment by PatrickvL** [comment]
Good idea. To support XBE's launching others, we could put the ProcessID of the most recently launched XBE in EmuShared. That way the GUI executable can keep monitoring all of them.

**Comment by PatrickvL** [comment]
To check if a process is still running, call [GetExitCodeProcess](https://msdn.microsoft.com/en-us/library/ms683189(VS.85).aspx), it'll return `STILL_RUNNING`

**Comment by PatrickvL** [comment]
Fixed by @ergo720 in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/763
