### ISSUE TITLE
Controller Vibration Support [low priority]

### ISSUE THREAD

**Issue by Voxel9** [Cxbx-Reloaded/Cxbx-Reloaded#680]
I just mentioned on Discord that it would be nice to add in some gamepad vibration support for games that make use of it.
Patrick recommended that I make a small issue here so it's not forgotten, so yeah... here it is. 😃

**Comment by LukeUsher** [comment]
Now that we have XINPUT support it should be possible through that, not sure how much work it will be to implement this into our controller emulation currently, but it is definitely possible.

I'll be looking into LLE emulating USB and GamePad hardware after I'm done with my current experimental branch, so I'll pick it up as part of that.

**Comment by CakeLancelot** [comment]
Fixed in #1003
