### ISSUE TITLE
Crash on emulation start due to logging code.

### ISSUE THREAD

**Issue by darrena092** [Cxbx-Reloaded/Cxbx-Reloaded#682]
### Description

Code added in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/48f6c1107acfad6bdd08fc0e23a100466dbceff3 is causing a memory access violation which means that emulation fails to start.

It seems that the access violation is when memcpy is called in the various accessors in EmuShared. 

I've tested this with two different games, both resulting in the same behaviour.

---

### Game info
Tested with both "Kingdom Under Fire: The Crusaders" and "Crash Twinsanity".

---

### Status
**Previous behavior:** Emulation starts successfully.

**Current behavior:** Emulation fails to start due to memory access violation.

---

**Comment by darrena092** [comment]
Submitted a PR which solves this issue https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/683

**Comment by PatrickvL** [comment]
> seems that the access violation is when memcpy is called in the various accessors in EmuShared

If that's the case (seemingly a bounds overflow), then it's only avoided by using a separately allocated structure (not actually fixed). It'd be good to know which memcpy call(s) is/are the actual culprit (s).

**Comment by darrena092** [comment]
It turned out to be simpler than that - the XBVideo and XBAudio classes weren't being instanced, so the functions from EmuShared were just writing to unallocated memory.

**Comment by darrena092** [comment]
Also, I'm an idiot. It's to do with the objects being deleted at the end of their scope. The only issue I solved in my PR was accidentally avoiding their deletion, so things continued along happily.

Will look into it further and see if I can come up with a solution - it would be helpful to see if anyone else can reproduce this issue.

**Comment by PatrickvL** [comment]
So the fix should be calling their constructors?

**Comment by darrena092** [comment]
Submitted a second PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/684

This solves the issue by using copy constructors. The reason that it hadn't become a problem before was that it seems there was nowhere that actually used the accessor methods in EmuShared and subsequently deleted the copied object until now.
