### ISSUE TITLE
Remarks by JayFoxRox on the game-compatibility template

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#685]
JayFoxRox made a few remarks on the current game-compatibility template; Here they are, for us to discuss, reach consensus over and apply:
The template is a good attempt, and it's probably good that you use one. But the implementation is very lacking still:

* Be more strict strict if users don't follow rules
* The comment box is so small, that it only shows the comment on top. which is probably the least important part of it.
* There should be a text as part of the template, stating that the template should be used / filled out.
* It should also include stuff like `WRITE YOUR ANSWER HERE` / `REPLACE THIS WITH A TEXT ABOUT ...`
* It should be readable and easy to understand, even for people not familar with markdown. There should be clear seperation of markup and parts to fill out:
  * Example: The use of `---` and `-->` seems rather confusing at the moment
  * someone might accidentally remove `-->`, thinking it's useless padding. It should be on the same line as the comment
  * Same about `---`. it might signal a blank line (_______) to write into, as users don't understand markdown; so some users would accidentally remove it
  * These `---` lines don't help the readability either: you are already using headlines (`###`)
* There is no text which says how to add screenshots and the comment in brackets is rather confusing.
  * What's ECT?
  * How do you screenshot an error? also, do you really want screenshots of error messages? wouldn't it be more helpful to type them out / have them as part of a log, so you can find them using the github search?
* Why is there a description text in the additional information section, but nowhere else?

From experience I can tell you: users are bad at using templates:
Either they are too stupid [don't care / know / understand the template], or too smart [they'll come up with own templates].
Therefore, moderation is far more important than having a good template. You should still have a template. However, assume that in >> 50% of all cases, you'll still have to moderate.

Additionally, there is at least one minor formatting issue in the README:

* "Unique reports" is clearly a bulletin list. If it was formatted as one, it would appear to be shorter / more read-worthy

**Comment by RadWolfie** [comment]
To me, issue template for game-compatibility is very KISS, aka Keep It Simple Stupid, design. Which is correct way to do it. The only changes we need is...

- Change ect to "etc" for proper English.
- Add new line for screenshot.
- Commented line of official url link to proper issue created as demonstrate.

Other than that, for better details how to get certain files or things into issue creation. We need to make a wiki page with instruction then have url link in issue template as commented section.

**Comment by ergo720** [comment]
One question: the template is mandatory for the first post of course but what about the other posts after the first one, would be acceptable to submit just standard reports with kernel debugs, issue description and screenshots? I personally think it should be acceptable because it would become boring to repeat it over and over in all posts

**Comment by BenNottelling** [comment]
I did a little work on it: https://github.com/BenNottelling/game-compatibility/edit/template-update/.github/ISSUE_TEMPLATE.md are my proposed changes and it links to https://github.com/BenNottelling/game-compatibility/issues/1 as an example issue
