### ISSUE TITLE
Log XBE flags as readable string

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#686]
It would be good to log region flags by name within an xbe dump. We currently log region flags by the hex value, however this is not clear to a user unless they understand the region flag encoding. 

I propose outputting the textual name of these flags in brackets next to the region flag in the xbe dump.

Note that any combination of the above flags is possible, so a region code of 0x00000005 would mean a title that runs on US/CANADA hardware, and the rest of the world except for JAPAN, while 0x00000007 is region free. 

It would also be good if at the same time, logging of the media type flag could be implemented, as above, we currently only log the hex values, but not the text representation.

For a list of supported flags that need to be logged, see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/223e20d1528ac7bf9a2d8013f7352af6c9f39bae/src/Common/Xbe.h#L277

**Comment by PatrickvL** [comment]
In addition to this, all other flags in the XBE header could be dumped as string too. But perhaps it's best to create one issue per case for this.

**Comment by PatrickvL** [comment]
Part of this is done in PR #715 (it logs TitleID, TitleName and Region as string)

**Comment by PatrickvL** [comment]
Taking inspiration from Dxbx's XbeExplorer, here some more fields that could be rendered as string :
- [ ] Xbe::Header.dwTimeDate
- [ ] Xbe::Header.dwInitFlags
- [ ] Xbe::Header.dwPeTimeDate
- [ ] Xbe::Header.dwDebugPathnameAddr
- [ ] Xbe::Header.dwDebugFilenameAddr
- [ ] Xbe::Header.dwDebugUnicodeFilenameAddr
- [ ] Xbe::Certificate.dwTimeDate
- [ ] Xbe::Certificate.dwAllowedMedia
- [X] Xbe::Certificate.dwGameRegion - done by #715
- [ ] Xbe::Certificate.dwGameRatings
- [ ] Xbe::SectionHeader.dwFlags
- [ ] Xbe::LibraryVersion.dwFlags
- [ ] Xbe::TLS.dwCharacteristics

**Comment by PatrickvL** [comment]
Also, see https://github.com/PatrickvL/Dxbx/blob/master/Source/Delphi/src/uXbe.pas#L243

**Comment by Fisherman166** [comment]
For the GameRatings field, I assume this is referring to the games ESRB rating. Searching the internet, I was not able to find documentation of defined values for this field. Using my small game collection as a test, it appears that 0x2 = "M", 0x3 = "T", and 0x4 = 'E'. If I am on the right track here, I can write a string interpreter for GameRatings.

**Comment by PatrickvL** [comment]
@Fisherman166 Game rating needs some more reverse engineering, as does Characteristics. Did you look through the openxdk and nxdk headers?

**Comment by LukeUsher** [comment]
The GameRatings field is directly related to the Parental Control settings in the Xbox Dashboard.(stored as XC_PARENTAL_CONTROL_GAMES in EEPROM

When an XBE is launched, the XAPI library linked into the title aborts execution if the XBE GameRating field is less than the parental control setting specified in the dashboard.

**Comment by Fisherman166** [comment]
@PatrickvL I found a table describing the rating values in EEPROM today while searching through the XboxDevWiki. From my quick testing on games I own, the rating field matches up to what is displayed in the table.

**Comment by PatrickvL** [comment]
Then it's safe to assume the Xbe field and the EEPROM field are using the same type. Meaning both could be rendered as string with the same function. (Look at how LOG_FUNC_ARG_TYPE uses stream traits, the new function could be hooked into that too..)

**Comment by PatrickvL** [comment]
There's a new issue, directly related to this one, here : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/850

**Comment by PatrickvL** [comment]
Except `Xbe::TLS.dwCharacteristics`, all flags are now printable. I'll close this issue, as that last one doesn't warrant keeping this issue open for...
