### ISSUE TITLE
Debug Assertion Failed! on #ea279e1

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#70]
```
Debug Assertion Failed!

Program:
...\Cxbx.exe
File: minkernel\crts\ucrt\src\appcrt\lowio\isatty.cpp
Line: 17

Expression: (fh >= 0 && (unsigned)fh < (unsigned)_nhandle)

For more information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to to debug the application)

```
No Workaround

**Comment by PatrickvL** [comment]
I have no idea where this comes from. Is it reproducible? With which software? Doing what?

**Comment by BiatuAutMiahn** [comment]
Tried a number of things, event log showed an error with MSVC2010 libs, had to reset the install of win10. Working fine now. So id consider closed.

**Comment by LukeUsher** [comment]
Sounds like it could have been a Windows installation/runtime library issue
