### ISSUE TITLE
Missing/Incomplete XACT HLE Database

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#705]
The HLE database is missing symbols for all XACT libraries except 4627

This causes problems in execution due to XACT hitting hardware registers directly, so it needs to be patched.

This affects quite a few titles, notably the Kingdom Under Fire Series, Forza Motorsport, Nightmare Before Christmas, Lord Of The Rings: The Two Towers, Links 2004, Headhunter: Redemption and possibly many more titles, so it is quite important to fix.

**Comment by jarupxx** [comment]
I created this HLE Database PR #722.
There is a worrisome thing. IXACTSoundBank_Play function does not be registered in the library. Does this mean to use the PlayEx function?

**Comment by PatrickvL** [comment]
PlayEx is probably an extended version of Play, with more arguments. Often, in libraries, a define forwards the lesser too the extended function. If no patch is applied, they can be treated as one and the same

**Comment by blueshogun96** [comment]
I initially wrote the HLE database for Unreal Championship (XDK 4928).  Since I never actually did much to get the HLE functions working, someone will have to implement the loading of xsb and/or xwb files IIRC.  It's been a long time since I've touched it but someone did manage to document the file formats.

Shogun

**Comment by RadWolfie** [comment]
Actually... IXACTSoundBank_Play is just a wrapper to IXACTSoundBank_PlayEx interface somewhere after revision 4627 and before, or at, 5344.

**Comment by PatrickvL** [comment]
@blueshogun96 Do you mean this : https://github.com/hcs64/vgm_ripping/blob/master/soundbank/otoxwb/unxwb.c ?

**Comment by jarupxx** [comment]
Thanks for the information on PlayEx. I will prepare IXACTSoundBank_PlayEx OOVPA so can be called directly.

**Comment by jarupxx** [comment]
Strangely, failed initialization of XACT then use DSound instead.
I noticed disable all XACT patches a few titles improved compatibility. This affects titles the Burnout 2, Karaoke Revolution.

**Comment by RadWolfie** [comment]
Moving the issue to XbSymbolDatabase repo.
