### ISSUE TITLE
DSOUND OOVPA for 5233

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#709]
DSOUND OOVPA for 5233 are rather poor, some of which are definitely not specific enough.

At least REGISTER_OOVPA(IDirectSoundBuffer_SetVolume, 4134, PATCH) is incorrect.

For the Xbox Online Dashboard (5233 XDK) I have noticed the following:
In the Cxbx Debug console this function is detected at 0x00081407, when disassembling the XBE with Dxbx symbols confirms that this location is actually CDirectSoundBuffer::SetMixBins.

The correct location for IDirectSoundBuffer_SetVolume is 0x00081423

Note that the patterns for these symbols are VERY alike, they differ only because of an XRef. It's very possible that the XREF is incorrect too, so the whole of DSOUND for this XDK, and perhaps others too likely need verification.

![image](https://user-images.githubusercontent.com/740003/30006070-1ecf474a-90e8-11e7-9e8c-be4ed7652739.png)

**Comment by LukeUsher** [comment]
@RadWolfie as you implemented so many DSOUND improvements, would you mind taking a look at this?

**Comment by LukeUsher** [comment]
Actually, I just tested with this branch and the issue is solved: 
https://github.com/jarupxx/Cxbx-Reloaded/tree/WIP_HLEDB_v2

So it looks like we just need to wait for this to be completed, I'll close this then!

**Comment by RadWolfie** [comment]
That's great to hear! I believe it will cause merge conflict for WIP_HLEDB_v2. Since it is just one file, I can manage it. For now, I'll assign myself to be sure I did not make a mess during rebase merge base on #710 pull request.

**Comment by RadWolfie** [comment]
Resolved
