### ISSUE TITLE
Documenting the shorcut keys and hidden features of cxbx-r

### ISSUE THREAD

**Issue by zaykho** [Cxbx-Reloaded/Cxbx-Reloaded#716]
It will be interesting to have a wiki page or some info in the readme file about the shortcut keys and some hidden features that cxbx-reloaded use.

Like the F11 shortcut that actually switch the rendering type:  ( wireframe / points ) and F12 that : (pause the emulation ?)

**Comment by RadWolfie** [comment]
It's better to implement the string for these shortcut keys as well. Lots of software are doing this.

Here's an example from Microsoft Visual Studio IDE.
![image](https://user-images.githubusercontent.com/3938312/30066498-b7501e78-921d-11e7-8e45-04a00cd26631.png)

**Comment by LukeUsher** [comment]
We already do that for some, the issue here is that we have shortcut keys that have no corresponding menu item, so people don't even know what functionality exists

**Comment by RadWolfie** [comment]
I just saw what you're saying. Perhaps in About window with a shortcut tab to include the overall shortcut keys. I'm working on a wiki page.

**Comment by zaykho** [comment]
> Perhaps in About window with a shortcut tab to include the overall shortcut keys.

That would be a good idea. (in complement of the wiki page)

**Comment by RadWolfie** [comment]
[Shortcut-Keys Wiki page](/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Shortcut-Keys), here you go. There might be more or need to make it more clearly explanation.

**Comment by zaykho** [comment]
Nice, for some reasons though, F10 doesn't seems to do anything (Alt + ENTER work though).

**Comment by RadWolfie** [comment]
Either it's not listening to our input correctly, not responding thread, or something went wrong behind this. I'm just giving complete info I have discovered with VK_ keyword within this project. Plus what they are expected to do base on description it has.

**Comment by Margen67** [comment]
If all the hotkeys have been found the TODO at the bottom of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Shortcut-Keys should be removed.

**Comment by PatrickvL** [comment]
Yeah, you're right. Any future change in keyboard shortcuts will need an update in documentation anyway.
