### ISSUE TITLE
xboxdash.xbe could not be found i get this everytime i try load gun valkryie

### ISSUE THREAD

**Issue by libs1233** [Cxbx-Reloaded/Cxbx-Reloaded#717]
### Description

[Description of the issue]

---when I click on the xbe it trys to load then says xboxdash.xbe could not be found

### Game info
[XBE Dump, KrnlDebug, HLE Cache, Ect]

---

### Status
**Previous behavior:** [Before regression]

**Current behavior:** [On the latest build]

---

### Screenshots [Errors, Graphics, Glitches, ECT]

---

### Additional Information

Any additional information such as configuration or other comments

**Comment by LukeUsher** [comment]
Please upload an Xbe dump and KrnlDebug log, but it sounds like the game is trying to reboot the xbox (likely due to an error) and you don't have a dashboard installed.

**Comment by libs1233** [comment]
how do I install a dashboard?

**Comment by LukeUsher** [comment]
Copy the dashboard files to the emulated hard drive located, at "%AppData%\Cxbx-Reloaded\EmuDisk\Partition2". 

Note that only early dashboard versions work on Cxbx-Reloaded, Any dashboard version older than 1.00.4920.01 should work, but any newer versions won't.

**Comment by libs1233** [comment]
what did I do wrong this time?

**Comment by LukeUsher** [comment]
We don't know: This game probably doesn't work well yet.
Please upload an Xbe dump txt file and a Kernel Debug log, so we can identify what the issue is, and what version of the game you are using.. We can't help without this information.

Please submit this in https://github.com/Cxbx-Reloaded/game-compatibility, following the readme there.

**Comment by libs1233** [comment]
sorry I don't no how to upload the log I just copy paste

**Comment by LukeUsher** [comment]
That's the wrong log, we want a Kernel debug log, not a GUI debug log, check the settings in the edit menu.

**Comment by libs1233** [comment]
[0x3230] EmuMain: Cxbx-Reloaded Version bf5719e1 (Aug 14 2017)
[0x3230] EmuMain: Log started at 2017-09-06 02:15:40
[0x3230] EmuMain: Debug Trace Disabled.
EmuMain : Using XInput
[0x3230] EmuWarn: Failed to load Keys.bin. Cxbx-Reloaded will be unable to read Save Data from a real Xbox
CxbxDbg> 
*******************************************************************************
* Cxbx-Reloaded High Level Emulation database last modified Fri Apr 21 20:06:20 2017
*******************************************************************************

Found HLE Cache File: 5C1388C0.ini
HLE Cache file is outdated and will be regenerated
HLE: Detected Microsoft XDK application...
HLE: Starting pass #1...
HLE: * Searching HLE database for XAPILIB version 1.0.4134... Found
HLE: 0x001ad82c -> XInitDevices 3911	*PATCHED*
HLE: 0x0013db00 -> SetThreadPriority 3911	*PATCHED*
HLE: 0x0013dcb3 -> GetExitCodeThread 3911	*PATCHED*
HLE: 0x001ae23d -> XGetDevices 3911	*PATCHED*
HLE: 0x001b47df -> XInputOpen 4134	*PATCHED*
HLE: 0x001b4a52 -> XInputGetState 4134	*PATCHED*
HLE: 0x001b4ac3 -> XInputSetState 3911	*PATCHED*
HLE: 0x0013b702 -> XMountUtilityDrive 4134	*PATCHED*
HLE: 0x00139aa5 -> GetTimeZoneInformation 3911	*DISABLED*
HLE: 0x0013dd11 -> XRegisterThreadNotifyRoutine 3911	*PATCHED*
HLE: 0x001ae25f -> XGetDeviceChanges 3911	*PATCHED*
HLE: 0x001ae8cd -> XID_fCloseDevice 3911	(XREF)
HLE: 0x001b4854 -> XInputClose 3911	*PATCHED*
HLE: 0x001b4860 -> XInputGetCapabilities 3911	*PATCHED*
HLE: 0x0013db52 -> GetThreadPriority 3911	*PATCHED*
HLE: 0x001b4afb -> XInputPoll 4134	*PATCHED*
HLE: 0x0013dba6 -> SetThreadPriorityBoost 3911	*PATCHED*
HLE: 0x0013adec -> XLaunchNewImageA 3911	*PATCHED*
HLE: 0x0013b1c3 -> OutputDebugStringA 3911	*PATCHED*
HLE: * Searching HLE database for D3DX8 version 1.0.4134... Skipped
HLE: * Searching HLE database for XBOXKRNL version 1.0.4134... Skipped
HLE: * Searching HLE database for LIBCMT version 1.0.4134... Skipped
HLE: * Searching HLE database for LIBCPMT version 1.0.4134... Skipped
HLE: Starting pass #2...
HLE: * Searching HLE database for XAPILIB version 1.0.4134... Found
HLE: * Searching HLE database for D3DX8 version 1.0.4134... Skipped
HLE: * Searching HLE database for XBOXKRNL version 1.0.4134... Skipped
HLE: * Searching HLE database for LIBCMT version 1.0.4134... Skipped
HLE: * Searching HLE database for LIBCPMT version 1.0.4134... Skipped
HLE: Resolved 1 cross reference(s)

[0x1EBC] EmuMain: Received Exception (Code := 0xC0000005)

 EIP := 0x0406F04F(=XInputPoll+0x3eba554)
 EFL := 0x00010206
 EAX := 0x00000000 EBX := 0x040B5740 ECX := 0x74AC5D43 EDX := 0x000000C0
 ESI := 0x80011008 EDI := 0x80012000 ESP := 0x0F98DF18 EBP := 0x0F98F124
 CR2 := 0x00000000

[0x1EBC] EmuMain: Aborting Emulation

**Comment by libs1233** [comment]
what am I missing cause I read it goes in game

**Comment by LukeUsher** [comment]
You could be using a different version of the game, or it could be a new bug/regression.
According to the compatibility report https://github.com/Cxbx-Reloaded/game-compatibility/issues/180, this title has not been tested by anybody since March/April time.

**Comment by libs1233** [comment]
to bad I would of liked to try it out
