### ISSUE TITLE
Prefix symbol names with section

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#725]
When showing symbol names (for example in error dialogs), when the effective address lies inside one of the Xbe's section address ranges, the name of the section should also be shown before the symbol name.

For this issue, implement a function that returns the section name of an address, or NULL if it can't be determined. Then use this function in the display of symbol names.

**Comment by PatrickvL** [comment]
(This is related to issue #206 too, by the way.)

**Comment by RadWolfie** [comment]
Isn't it relative to issue #697 as a feature?

**Comment by PatrickvL** [comment]
Hm. That issue is indeed similar. But, yours talks about crashs messages, while this one is a bit more generic, requesting an extension to the display of any symbol name.

We can merge these two issues, if you want. Or just leave them both open, and close them together once this feature is implemented. I'll let you decide.

**Comment by RadWolfie** [comment]
Crash and error are pretty much handled by "exception" handler. We'll close this issue. As for issue #206, it's completely not relative as issue state of ability to use pdb file generator usage.

P.S. Any time it generate a 0xC000000E (access violation) without exception handler, it will perform a crash.
