### ISSUE TITLE
Fix wrong window size in DEBUG builds

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#728]
When Cxbx-Reloaded is build with the DEBUG (as opposed to the default RELEASE) configuration, the main window size is smaller. (That, or the window size is larger under RELEASE builds.)

In any case, for this issue:
* find out what causes the difference
* fix it such that both builds show the same window size
* as a bonus, prepare the code such, that :
* * GUI-mode (when not emulating) can be resized
* * Emulation-mode sizes according to active screen resolution

**Comment by CakeLancelot** [comment]
I haven't been able to reproduce this, I built two binaries: one in release configuration and the other in debug, but they appear to be the same size.
![2018-02-12_13-18-07](https://user-images.githubusercontent.com/5341136/36114976-3a1b2210-0ff7-11e8-92d9-581cfcf4cff5.gif)

**Comment by RadWolfie** [comment]
This is an old issue, is the issue still exist?

**Comment by PatrickvL** [comment]
I believe this has been fixes months ago when resize-window functionality was added
