### ISSUE TITLE
Multi-XBE Titles don't want to stop

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/Cxbx-Reloaded#730]
I found a bug, where multi-xbe titles won't stop emulation when using Emulation->Stop or F6
After a game launches another xbe, Stop/F6 do nothing
In this case it's also posible to start a second child thread, while the first is still running 
for example Controller Test default.xbe
It also happens, when a game crashes to dashboard

I tracked it back to PR #712 
it didn't happen before this
only way to stop it, is to close the kernel debug console or cxbx-r

![capture20170913224047439](https://user-images.githubusercontent.com/30478365/30400128-3340b7b8-98d6-11e7-80fc-d3fc7263e065.png)

**Comment by PatrickvL** [comment]
Thanks for reporting this regression. All help is welcome.

I suspect this issue is because restarts of the emulator don't communicate the new ProcessID back to the host (GUI) process.

**Comment by PatrickvL** [comment]
Look for writes to, and reads from, m_hwndChild. My guess is, cascaded launches send their process ID to the parent processes, but aren't detected
