### ISSUE TITLE
JSRF: Controller crash, application freeze and unable to open games in HDD larger than 2 GB

### ISSUE THREAD

**Issue by petran79** [Cxbx-Reloaded/Cxbx-Reloaded#747]
Using the latest version. Whenever I configure controlls, either keyboard or gamepad, I get this error. Happens right after the 3D graphics appear. after the logos. If I disable controls Jet Set Radio boots fine but I cant do anything.

Also application freezes while game is running. I cant pick any menus. It freezes even during the error message sometimes.

https://abload.de/img/jetsethakbw.jpg

Also Jet Set Radio refuses to run if I have the files on a HDD larger than 2 TB. I get a black screen. Had to transfer game to a smaller drive.

**Comment by CakeLancelot** [comment]
Could you confirm the hard drive issue on other games if possible?

**Comment by CakeLancelot** [comment]
I have tested and confirmed that the game does work when I disable xinput and don't have a directinput controller connected. However as said in the comment above this would be a game specific issue, so we might want to move this to game-compatibility.

**Comment by LukeUsher** [comment]
For the HDD issue: It's possible the game queries drive size/space available via the Windows NT Api. 
If this is the case, the game will see the information about your host hard drive (size, free space, serial number)

It's possible that the hard drive size being > 2TB causes some kind of integer overflow.
Perhaps we need to enforce upper limits to return values in Filesystem APIs.

**Comment by jarupxx** [comment]
I noticed that Fuzion Frenzy is output a debugLog.txt.
Free hard drive size, CPU frequency, memory size, etc. are included.

Perhaps we may need to enforce those return values.
[debugLog.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1336637/debugLog.txt)

**Comment by PatrickvL** [comment]
What would be hugely valuable, is a copy of the same file from a real machine. That way, we can tune our emulator on various fronts to return similar values. That will surely fix all sorts of corner cases.

**Comment by LukeUsher** [comment]
A key area would be to not return more disc space or RAM than is possible on the Xbox, so the totals should be no higher than 128MB for RAM and a sensible number for HDD (A modded BIOS can support 1TB, but the stock Xbox HDD is 8-10GB)

**Comment by Sarkie** [comment]
A few early games I've tested with have similar debug logs, they complain about memory and time date overflowing

**Comment by PatrickvL** [comment]
@Sarkie please elaborate, attaching all available information

**Comment by LukeUsher** [comment]
We just need to limit the return values to prevent overflows in free memory calculations. I'd say 8GB for HDD size and 128MB for Memory Size as maximum values, basis that real xbox's ship with 8GB storage and debug units have 128MB RAM.

**Comment by PatrickvL** [comment]
If we could go down that road, then it's be wise to return correct results right from the start; For memory that would mean each mapped page must be counted, and for disc space each occupied sector

**Comment by Sarkie** [comment]
@PatrickvL  currently away, I'll add more to the ticket next week
