### ISSUE TITLE
Fix ExQueryNonVolatileSetting

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#75]
This function implementation contains a lot of hard coded offsets and values, we really should implement a data structure to represent the emulated EEPROM and read/save values from there.

This also opens up the possibility of persisting these settings when they are changed.

**Comment by PatrickvL** [comment]
Done!

**Comment by LukeUsher** [comment]
Fixed in Pull Request #76
