### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#762]
I had some spare time and designed a new logo, here is the main logo as well as two different icons:
![logo](https://user-images.githubusercontent.com/5341136/31321504-b8671f98-ac4c-11e7-8d12-a9aa27827e5b.png)
[SVG File](
https://mega.nz/#!TIhQjaxK!mV4ePLGIVchMZAh4d2r473M7NCTaIWiVn8hyaW_MVN0)

![icona](https://user-images.githubusercontent.com/5341136/31321526-25784f1c-ac4d-11e7-9c09-75d7b6d698b3.png)
![iconb](https://user-images.githubusercontent.com/5341136/31321525-2574c32e-ac4d-11e7-9c62-ca30bcfc6dea.png)

I'm licensing under Creative Commons Attribution 4.0 International (CC BY 4.0) - Free free to use these logos as you wish! (Credit to [BatmanForever](https://fonts2u.com/batmanforeveralternate.font) Font, author not listed)

You can also propose any changes that you might want and I'll do my best to recreate them.

**Comment by ObiKKa** [comment]
I think the green 'R' letter might need some shininess over it, maybe in two diagonally intersecting ways?
I think the vertical orientation of 'CXBX' before the 'R' letter is cute. That's for a small thumbnail icon, I'm sure.

**Comment by PatrickvL** [comment]
Very creative. Thanks for the effort. Don't know yet what to do with it though.

**Comment by RadWolfie** [comment]
@PatrickvL, are we programming a Cxbx or Cxbx Reloaded here? Hence the reason of this new logo proposal. I'm sure it will be replacing the icon logo and background image of Cxbx Reloaded's window.

I think it's better to have a Cxbx on top of the letter R for readable name. (I can confirm it by shrink it down to 32x32 pixels.) However, cxbx might need to be little bit bigger font size to see letter B more clearly.

I had tried to think of way to keep Reloaded in the main image. I just don't think it will look good anyway.

**Comment by CakeLancelot** [comment]
> However, cxbx might need to be little bit bigger font size to see letter B more clearly.

Here's an adjusted image:
![image](https://user-images.githubusercontent.com/5341136/31357526-b6eca50a-ad07-11e7-88f1-ab388337ed11.png)
and I mainly made these because as @RadWolfie we're still using the Cxbx logos, and for the program icon just it seems to be a generic xbox symbol.

**Comment by RadWolfie** [comment]
I'll take this assignment to update old logo of Cxbx to new Cxbx-R brand. Currently waiting on @CakeLancelot to provide latest svg file format in order to make a PR.

**Comment by PatrickvL** [comment]
Thanks!

**Comment by CakeLancelot** [comment]
![transparent](https://user-images.githubusercontent.com/5341136/38530480-5a8ccf98-3c30-11e8-8cc7-69e1d362ff92.png)
Dropping a transparent version of RadWolfie's logo here so I can use it on the wiki.. don't mind me
