### ISSUE TITLE
Emulation overlay GUI

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#767]
At some point in time, it might become useful to add a GUI on top of the emulated screen output.
It could show a debugging command line, performance counters, memory statistics, memory watches, and whatever else we might come up with.

https://github.com/ocornut/imgui seems like The library to use for adding a GUI on top of the Xbox output.

**Comment by RadWolfie** [comment]
Since Xenia is using this third-party overlay GUI. I'm giving this a thumb up to be use in Cxbx-R.
