### ISSUE TITLE
EmuCreateDeviceProxy logic misses common texture formats

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/Cxbx-Reloaded#783]
Hello!

When using the latest build I notice `EmuCreateDeviceProxy` has some incorrect warnings:

```
EmuD3D8: FourCC[4] = UYVY
EmuWarn: EmuD3D8: FourCC format UYVY not previously detected via CheckDeviceFormat()! Enabling it.
EmuD3D8: FourCC[5] = YUY2
EmuWarn: EmuD3D8: FourCC format YUY2 not previously detected via CheckDeviceFormat()! Enabling it.
```

The loop on [this line](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/EmuD3D8.cpp#L1745-L1758) assumes the texture enum is a linear range, but MSDN lists the enum values using their FourCC format - see https://msdn.microsoft.com/en-us/library/windows/desktop/bb172558(v=vs.85).aspx

A very minor fix (good for contributors?) would help remove this warning from the console log!

**Comment by PatrickvL** [comment]
The loop uses the Xbox enum, which doesn't contain fourcc values. I believe it's correct like this, but please explain if it's really not okay

**Comment by RadWolfie** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/66502da40f4c92ef96ab89625d1224dab0c237e1/src/CxbxKrnl/EmuD3D8Types.h#L136-L137
should be the same as
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/e3a19a2a3d74ad85ee28b3b8f8fdb17a14017840/import/DirectX8/include/d3d8types.h#L1296-L1297
?

**Comment by PatrickvL** [comment]
Xbox uses is own declaration of those values, so no.

**Comment by RadWolfie** [comment]
Right, what I'm saying is it's XB to PC format function might be missing this fourCC check?

**Comment by RadWolfie** [comment]
Also EmuXBFormatRequiresConversionToARGB function seem to be unnecessary? We can just directly map xbox to pc format check. If they're not compatible, then it should be "skipped"?

**Comment by PatrickvL** [comment]
Xbox textures expressed in a format not supported on host need a conversion, because otherwise they wouldn't show, resulting in broken rendering.

**Comment by PatrickvL** [comment]
I'll look into it, although to be honest, most of this is reworked in my WIP Less Vertex Patching branch, so I'm trying to focus on that foremost

**Comment by RadWolfie** [comment]
Okay... I'll make it clear. EmuXB2PC_D3DFormat should be called then check with graphic's CheckDeviceFormat function, if it is supported. Then we just need to apply "is supported" to g_bSupportsTextureFormat.

I believe EmuXBFormatRequiresConversionToARGB is not necessary because CheckDeviceFormat from graphic card will tell us the true compatible support texture. Does that make sense?

**Comment by x1nixmzeng** [comment]
Thanks for the explaination - I now understand why this is not an issue!
