### ISSUE TITLE
Implement actual memory page management

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#788]
Currently our memory management is flawed; Our memory manager processes contiguous memory separately from other memory, allocates other memory via heap malloc, and doesn't offer any kind of statistics for the kernel Mm API's.

For these issues, the above problems must be fixed by implementing memory page management.

This should include page table entries (PTE's) and page directory entries (PDE's), alongside the separate read/write/execute watches, described in issue https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/748.

Page table entries should reside at 0xC0000000, one DWORD per page, containing the upper 20 bits of the virtual address a page is mapped to, protection flags, end-of-allocation-range marker, and possibly other flags.

Page directory entries should reside at 0xC030000. TODO : Add more detail

As issue https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/769 describes, all required memory ranges should already be reserved. Allocating memory will retrieve free page numbers from the directory/table. The memory behind these pages numbers can be taken from a page 'pool' representation, in the form of a memory mapped file.

Memory mapped files under Windows, can be mapped partially (per page for example) to specific virtual addresses. Thus, each page from this 'pool' can be seen as a 'physical' page, which can be mapped into the appropriate virtual memory range (which were reserved at launch - see the other issue describing that in more detail).
Mapping will be done using MapViewOfFileEx.

A (part of a) memory mapped file can be mapped to multiple virtual addresses, so even mirror pages can be implemented.

Feasibility of the above should first be investigated in a small test application.

If the above can indeed be made to work, the kernel Mm API's should be updated to make use of the new page manager code, so that these API's will work much more like the real thing too.

**Comment by PatrickvL** [comment]
Please let me explain what I was thinking (maybe you already know everything I'm going to write here, if so, please forgive me)

The great thing about MapViewOfFileEx is that it allows to do two very special things:

It can map any page from a memory mapped file to a virtual memory address that can be specified freely (the address range has to be unoccupied of course)

PatrickvL

23:48

It can map any page from a memory mapped file multiple timesto a virtual memory address (each time to another unoccupied virtual memory address range of course).

PatrickvL

23:55

Those two aspects make it an ideal API for emulating both physical and virtual memory at the same time, as the entire 64 mb range can initially be mapped to where the Xbox has it's physical memory (0x80000000), and on top of that each of these pages can be mapped to another address, which is in essence what virtual memory management boils down to : the act of allowing the CPU to access memory from a physical backing store (normally actual RAM chips) at addresses controlled by the kernel running a process.

PatrickvL

00:01

Perhaps you knew this already too, but : the way Windows implements memory mapped files actually results in the use of host physical memory, since the file itself is treated 'just' as a backing store for the data. Most of the time, when data from a memory mapped file is accessed, this data is read into physical host memory, and accessed from there by the CPU. Only when physical memory is fully occupied, Windows starts freeing up physical memory by discarding memory mapped pages that haven't been modified, and by flushing dirty pages back to disc. (This is what's famously known as "swapping".)

PatrickvL

00:08

So, when using a memory mapped file for the emulation of both physical andvirtual memory, you're actually using behavioural features from Windows that are nearly identical to what the original Xbox did. The only difference is, that the original Xbox didn't have a file behind it's physical memory, to which "overflow" data may be swapped on the host. (In practise, this flushing of data back into a file doesn't happen until either : physical memory is full, process limits are reached, or a range is unmapped.)

Furthermore, one can direct Windows away from flushing your data, by marking the entire memory mapped file as temporary storage, using the "delete on close" flag during the opening of the file. Windows avoids flushing physical pages from those type of files, since the data won't persist anyway after the file is closed. (Instead, Windows flushes other, more urgent, persisting pages first.)

**Comment by haxar** [comment]
AFAIK, the Xbox kernel only allows memory allocation and usage below 0x08000000 (128MiB). If a memory access is over that, then it would be bitmasked to 0x07FFFFFF by the XBE, essentially dropping the 27th and higher bits.

If you were to allocate host virtual memory after 0x08000000 and then pass it back to the XBE, like 0x08BEEEEF, the XBE would bitmask and see the address 0x00BEEEEF, potentially causing a page fault within the XBE. I've seen this true for NV2A DMA accesses.

Implementing a memory manager countering these cases would prove valuable. A simple call to `malloc` should not return an address higher than or equal to 0x08000000 (128MiB), the total Xbox memory.

Physical Xbox memory at 0x00000000 and 0x80000000 are the same. The 31st bit is simply dropped.

After reading your proposal, I'm left confused on the usage of the memory mapped file. Would it map all of the 128MiB of usable memory? Writing to disk would be a bottleneck, unless you wanted to save the state of the game.

**Comment by PatrickvL** [comment]
You're right about the NV2A having just 26 bits of address lines, but that's not virtual memory, the NV2A is accessing physical memory without going through an MMU. (The kernel calls this "contiguous memory" btw.)

The CPU can access physical memory at 0x80000000 and up, but through a MMU also at virtual addresses. These addresses don't get bitmasked, and the Xbe code doesn't insert masking opcodes either. Instead, the entire 32 bit address space is possible, but the kernel doesn't seem to grow higher than the 128 MiB mark in practise. (But in theory, nothing is stopping it from putting virtual memory at whatever high address it likes.)

As for using a memory mapped file being potentially slow : no. Windows only writes to the file when the need arises - and like I explained, this only happens when absolutely required. Windows actively tries to avoid swapping data back to disc, so don't worry about this on modern day machines with plenty of memory to spare

**Comment by PatrickvL** [comment]
Oh, and one final argument in favour of memory mapped files: we're already using that for contiguous memory (in which the NV2A resources are put), and speed is not an issue at all (if anything, we often run much too fast)

**Comment by PatrickvL** [comment]
To answer you question: yes, as emulation of physical memory, we're mapping the entire file as Xbox ram to 0x80000000. This issue merely extends this to implement virtual memory too.

**Comment by PatrickvL** [comment]
I've noticed that if we don't reserve a placeholder section of 128 MiB in the loader executable, then a guard page and the stack of the main thread gets placed right behind the executable memory - as far as I know this can't be influenced and thus would block our control over this memory range.
So therefore to avoid this we must reserve a 128 MiB range of memory using a placeholder variable.
If this has the side-effect that we might not be able to virtual-free individual pages of the reserved low memory range, then I would suggest to use low memory solely for loading xbe's, and put all virtual memory ranges further down in memory

**Comment by ergo720** [comment]
I believe this can be closed now. Future enhancements of the virtual manager (real NtAllocateVirtualMemory, real page tables instead of the array container) can have a new issue on their own.
