### ISSUE TITLE
Implement functionality for resetting to default settings

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#791]
In some cases, the Cxbx-Reloaded registry becomes corrupted, this can manifest in various ways, ranging from input issues, errors, to outright crashes.

I propose we should add a menu option to reset all settings to defaults, to cover this situation.

Obviously, It would be better if this corruption didn't happen at all, so if that can be solved, great. 

That said, a reset to default is still a nice option to have.

**Comment by RadWolfie** [comment]
I'm not having this issue anymore since one of the contributor fixed it by using function initialization instead of memory copy.

However we do need a reset option in order to bisect properly.
