### ISSUE TITLE
TASK: Restore ALL FUNC_EXPORTS Patches

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#792]
Since HLE v2 database is merge into master. We need to restore all FUNC_EXPORTS and transfer all of disabled functions marked as `UNPATCHED` ONLY.

Why?
So we can troubleshoot what we need to restore a patch or disable in later future. There is absolutely no longer necessary to comment out the whole function when we might need to re-use again. See image below for true purpose for HLE v2 database management to control patch and unpatch.

![my database v2 method](https://user-images.githubusercontent.com/3938312/32670045-1df0ff08-c608-11e7-936d-6a56cb38b379.png)

If we must comment out the "body" of the function, then please use `#if 0 ... #endif` inside _do not include_ `FUNC_EXPORTS` inside `#if 0... #endif`. Then include `LOG_UNIMPLEMENTED();` inside the patch function's body.

**Comment by PatrickvL** [comment]
I'm not convinced this is the wisest thing to do.

I'll grant you, that having all patches available, and their exports restored, would open the possibility to enable a patch just by updating it's entry in the HLE cache.

But what I don't see, is how that's going to help us in the long run. Our goal is to get as much software as possible to run. Either a patch is needed, or it isn't. (Plus, the more we move towards LLE, the less patches will be needed.)

I just don't think offering users the possibility to fool around with the HLE cache would be beneficial. Instead, it could bring cause for confusion, and lots of wasted time investigating what will be essentially non-issues.

Now, for development research I can understand your point of view, but does it really matter if we disable or enable a patch via either the export marker, or via OOVPA registration flag?
Both methods reach the same goal, but the export marker has the benefit of being right inside the actual code, while the OOVPA registration could be (and in my opinion should be) an independent piece of functionality (that in my opinion shouldn't be used for enabling or disabling patches - it's a symbol detection method after all, not a patch placement instrument).

Anyway, that's just how I view this, you and others are free to reason differently about this.

**Comment by LukeUsher** [comment]
I agree with Patrick, OOVPA are strictly for symbol detection, not patches. Also doesn't UNPATCHED work internally by adding _Unpatched to the function name? If this is the case, what would happen if we want an OOVPA that is unpatched, but that we still need to detect the location of, for example, if one of our patches needs to call a different native (unpatched) xbox function.
