### ISSUE TITLE
DirectSoundCreate8 Failed

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#793]
---------------------------
Cxbx-Reloaded
---------------------------
[0x1EC] EmuMain: Received Fatal Message:

* DirectSoundCreate8 Failed!

---------------------------
OK   
---------------------------

![dx 8 sound fail](https://user-images.githubusercontent.com/3212225/32691237-deab0204-c6c9-11e7-9186-129af18eba0d.PNG)

When trying to launch my games for testing I now get the mentioned error. This happens on previous versions of cxbx reloaded that I know work with my computer and their output on various games.  I've recently updated windows 10 to fall creators update, only thing that has changed since I last booted cxbx reloaded. I do know Microsoft did some fixes for dx9, most notably the memory allocation bug. A newer version of dx12 was included in the update as well. I'm curious if they removed something, and if anyone else is seeing this issue with the latest windows 10 update. Running dxdiag lists feature level down to 9_1 only.

**Comment by x1nixmzeng** [comment]
I've had this happen after disconnecting speakers - Windows can't find any playback devices and handles this badly

**Comment by NNX3x** [comment]
After further investigation, windows 10 fall update was to blame. Rollback to previous fixed the issue. I tracked it down to the audio inputs and outputs. The "speakers" under device manager when right clicked has an events tab, with the latest update the device fails to migrate and start up. Latest drivers were used as well.
