### ISSUE TITLE
Obsolete OOVPA maintenance

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#798]
Recently, all OOVPA have been revised.
As a result, we now have OOVPA in our code that are disabled, because these OOVPA where either:
* moved to another version,
* replaced by a better declaration,
* declared entirely wrong,
* describing an unknown symbol,
* duplicate to another declaration,
* too generic,
* or disabled for another reason.

For this issue:

* review all disabled OOVPA
* remove all OOVPA that we can safely do without
* add notes to the ones that need more attention
* create an issue with a remaining task list, gained from the previous step
* report, test and deliver the above results and then close this issue

**Comment by RadWolfie** [comment]
Moved the issue to XbSymbolDatabase repo.
