### ISSUE TITLE
Switch instruction decoding in EmuX86 to use Distorm

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#8]
Just a suggestion / question :
How about switching to distorm3 (https://github.com/gdabah/distorm) instead of zyan disassembler (zydis)?

distorm lib is only 45kb, as opposed to 350+ kb for zydis.
For cxbx purposes, disassembling to a string is not necessary.
All distorm does is instruction decoding, which seems a better fit.
Furthermore, distorm is probably faster (although that might not be all that important as long as illegal instructions and/or memory access are trapped via an exception handler, which causes huge overhead).

**Comment by LukeUsher** [comment]
Finally got around to looking at distorm, and I must say it seems like a better alternative to Zydiss, it may even make our instruction decoding logic easier to follow.

**Comment by PatrickvL** [comment]
I look forward to what you can do with it

**Comment by LukeUsher** [comment]
We have done this now, so I think we can close this?
