### ISSUE TITLE
My bugs databse

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#81]
Here is a link to my server with a simple file browser with a text viewer for viewing various information about tests I've run. I will include Crash notes, Kernel Logs, XBE infos and the XBE itself.

Link: [https://tinyurl.com/InfinityCxbxBugs](https://tinyurl.com/InfinityCxbxBugs)

Note:
At the moment, there is only one entry as I'm having an issue preventing me from emulating on my dev box, but will resolve later today. Then I will go through all the game/homebrews, and populate them there.

I hope it is useful!

Update:
Fixed issues with dev machine, I've added quite a few entries so far.
Should I include full game data instead of just xbe? (Except retails of course)

**Comment by PatrickvL** [comment]
You did exactly the same as I did back when I was working on Dxbx. Every now and then something started to work, which I moved from wherever it was to the most suitable folder.
For now this is more than enough data. The notes you kept are good to have.

Do realise however that we are probably going to be looking at this sporadically at most, as most of our time goes into figuring out small bits and pieces, inching along towards getting something small working.

**Comment by BiatuAutMiahn** [comment]
Understood, I just figured that this would help. I plan to update these every build there is a decent amount of progress. I'm thinking of writing a script that will do all of this for me. Except the notes part, that I will need to write myself.

**Comment by BiatuAutMiahn** [comment]
Just made a rather big update, check out "2017.01.30- Update.txt" for more information.
Link is still: [https://tinyurl.com/InfintiyCxbxBugs](https://tinyurl.com/InfintiyCxbxBugs)

**Comment by PatrickvL** [comment]
You mention log filtering - to what extend would that need to be implemented to be useful?

**Comment by BiatuAutMiahn** [comment]
I think having only errors and warnings in the log would reduce alot of overhead in the logs. In a previously closed issue, I suggested the feature of log verbosity.

**Comment by LukeUsher** [comment]
I had suggested waiting until we have a new GUI implementation before adding this functionality, given that this would be useful to have now, and that a new GUi is a long way off, we could probably hack this functionality into the current interface.

**Comment by BiatuAutMiahn** [comment]
right. I am by no means rushing the log verbosity. However the point of my post was an update to my Bugs database

**Comment by PatrickvL** [comment]
Off topic: in Dxbx I used flags for different categories of logging, each one could be disabled at runtime, this proved to be a flexible way to reduce logging when running Simone tests, while it still offered to ability to log extensively

**Comment by PatrickvL** [comment]
On topic: to what extend did you automate populating this database?

**Comment by BiatuAutMiahn** [comment]
I made a wrapper forCxbx. You can either open an Xbe within it, or associate all Xbe's. When an Xbe is loaded, you can select a Cxbx build from a drop down list. This list is populated via the "Update" function that will automatically clone the repo, then get ALL commits, and building each one. This update function is manual, and you only need to do so every other build, and additionally, builds are not rebuilt. When running, the wrapper will set the KrnlLog path to a temp file, then Cxbx will be launched. The tester/user can select from a range of options including any notes/comments that can accurately describe how Cxbx performed. After the emulation has crashed, or exits the wrapper will automatically compress the log in a subfolder in the Xbe's dir.  A .CxbxReport will be generated on click of Save Button, and Upload button will send it to my server.

**Comment by BiatuAutMiahn** [comment]
So basically, each time you run an Xbe/Title, you have the ability to add to the database

**Comment by BiatuAutMiahn** [comment]
Just Released CxbxWrapper, check it out, and let me know if u run into issues.

**Comment by PatrickvL** [comment]
Thanks for your contribution, could you please host the source code for it on github?

**Comment by BiatuAutMiahn** [comment]
https://github.com/BiatuAutMiahn/CxbxWrapper

**Comment by PatrickvL** [comment]
Question, could you do a test-run with the latest commit, in which I re-enabled XGIsSwizzledFormat?

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/a8e9ca4aa174bc805e3017752c99f361d294497d
