### ISSUE TITLE
Can't Terminate Dashboard process!

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#813]
Let's say you have a game that boots back to the dashboard and successfully launches it.  You lose the ability to close the process emulating the dashboard.  You can't click Stop (F6) because Cxbx only accounts for that game you were trying to run earlier.  If you simply exit Cxbx, then the process will still be running and you will have to close it using the task manager.  If the user attempts to ignore it, then eventually games will always hang before emulation begins.  Even funnier, if you attempt to just load another game, not only will the dashboard emulation process still run in the background, but you will see the screen flicker back and forth between the new game emulation session and the dashboard.

Not sure if this is a known issue but it's definitely one that can get quite tedious to deal with when testing alot of titles.  

Shogun

**Comment by PatrickvL** [comment]
It's been reported before, but it doesn't seem to happen when Cxbx runs from within the visual studio debugger. (At least not to me, using vs2015 under Windows 7, nor using vs2017 under Windows 10)

**Comment by RadWolfie** [comment]
I believe this issue has been resolved since merged pull request #1279. Since it contain a method to prevent launching another title until it either crash or stopped.
