### ISSUE TITLE
AppVeyor debug/release artifacts are identical

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/Cxbx-Reloaded#815]
Hello

I noticed the AppVeyor artifact files `Debug.zip` and `Release.zip` contain identical `Cxbx.exe` binaries,

The **Debug** configuration seems to fail to produce artifacts:

```
Collecting artifacts...
No artifacts found matching 'export\Release.zip' path
No artifacts found matching 'export\Debug.zip' path
Build success
```

See https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/job/cteotbmg62b0i06v

Then **Release** manages to find and publish both:

```
Collecting artifacts...
Found artifact 'export\Debug.zip' matching 'export\Debug.zip' path
Found artifact 'export\Release.zip' matching 'export\Release.zip' path
Uploading artifacts...
[1/2] export\Debug.zip (735,806 bytes)...100%
[2/2] export\Release.zip (735,806 bytes)...100%
Build success
```

See https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/job/xb3eauxw3m6rcakm

In both cases, the SHA-1 is `1A13B6C777BB81984CB99E998A55B394D4AFBC4A`.

Could be an issue with `Export.bat` although I've not checked 🎉

**Comment by jarupxx** [comment]
Please check the AppVeyor, I fixed this issue.

**Comment by PatrickvL** [comment]
@x1nixmzeng Can you please confirm this issue is fixed now (thanks to jarpuxx work)?

**Comment by x1nixmzeng** [comment]
Brilliant, good work @jarupxx this is now fixed!

FYI a download link to the latest master `Release.zip` artifact is here:

https://ci.appveyor.com/api/projects/SoullessSentinel/cxbx-reloaded/artifacts/export/Release.zip?branch=master&job=Configuration:%20Release

It might be worth asking if @LukeUsher wants to add a direct link to the readme?
