### ISSUE TITLE
Can't open Official Xbox Magazine Disc 18

### ISSUE THREAD

**Issue by NNX3x** [Cxbx-Reloaded/Cxbx-Reloaded#817]
I can load this game on previous versions just fine, but I get an exception before any emulation starts.

**Steps**
1.) Select game
2.) Start Emulation
3.) Error pops up after hitting start.

![fail on open](https://user-images.githubusercontent.com/3212225/33517500-f57860da-d74a-11e7-8c25-8d6d8b584744.PNG)

**Comment by PatrickvL** [comment]
Please add more details, like build hashes that still worked, what exact software this is, what you mean by "load just fine" and from which build hash it stopped working.

**Comment by NNX3x** [comment]
I currently only have build version eb818bd8 available at the moment to confirm it was still working. Version 274bccd0  is what I logged the issue with. 

[KrnlDebug_eb818bd8.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1524152/KrnlDebug_eb818bd8.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1524153/KrnlDebug.txt)



**I'm attempting to get VS2017 up and running to help further, but it seems to be having trouble with opening source files such as string.h, pm me if anyone wants to help.

**Comment by ergo720** [comment]
This is probably caused by some missing files in the game dump because I encountered the same issue in another test xbe and after copying the missing files the problem was solved. If so, this is an invalid issue

**Comment by PatrickvL** [comment]
@NNX3x Could you please review ergo720's comment, and report back if this is indeed an installation issue?

**Comment by NNX3x** [comment]
@ergo720 I can look into seeing if its missing anything. I can check and see if my files are missing anything by comparing it to my backups on a external HDD. Sadly I cannot find the game disc anymore, so ripping it might not be possible. I will keep looking for it when I can.

Per my previous comments, why would an older version of cxbx reloaded play it just fine, but a new version will not? I tried 07e274ed, but it still has the same issue.

**Comment by ergo720** [comment]
Because I have 6 demo disks like this one and after you reported this I tried them all and they worked. I don't have specifically this one but it sounds strange that it would be any different than the others since they are all of the same series (Official Xbox Magazine Disc)

**Comment by NNX3x** [comment]
Finally got my backup, they are identical files in each after I did a binary compare on them. So for now I cannot do anything more other than hope to find that disc. I'm fine with closing this issue, as it can be reopened if any further findings come to light.

**Comment by NNX3x** [comment]
As an update, I got this game working again! I was having issues with JSRF and looked at its current status and stumbled on a solution posted by LukeUsher about clearing the cache. This seems to have done the trick.

> Also you could try cleaning your cache partitions: this is different from clearing the HLECache. There is an EmuDisk sub folder under %AppData%\Cxbx-Reloaded. Please delete all contents of EmuDisk, except for Partition1 and Partition2: these ones should stay, and try again.

**Comment by PatrickvL** [comment]
Thanks for the update. I'll close this issue then.
