### ISSUE TITLE
There is no .exe for my cxbx reloaded

### ISSUE THREAD

**Issue by PikaButt** [Cxbx-Reloaded/Cxbx-Reloaded#818]
![ded](https://user-images.githubusercontent.com/34245552/33564288-2790a404-d955-11e7-8827-e3c39c62a29c.png)

**Comment by CakeLancelot** [comment]
This is the source code, check the Appveyor for precompiled builds.
[Here's a link to the latest build](https://ci.appveyor.com/project/SoullessSentinel/cxbx-reloaded/build/job/9tgx7cpkq604ofj9/artifacts). Click export\Release.zip and extract and you should be good to go.
