### ISSUE TITLE
Unused HLE signatures

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/Cxbx-Reloaded#82]
The repo contains a RAR file with a few more HLE signatures:

`/src/CxbxKrnl/HLEDataBase/HLE_3911.rar`

Is there any reason this isn't unpacked and in-use?

**Comment by PatrickvL** [comment]
I don't know who put that there. But recently I've deleted a few OOVPA's because we don't really need them. Perhaps someone did the same in the past, but also put them in this archive so they wouldn't be lost completely.

**Comment by LukeUsher** [comment]
We can probably remove that archive, as well as the many 'Copy of' files that are scattered across the code base.

My guess is they are left-overs from previous contributors to Cxbx who were not all using version control at the time.

Everything is in version control now, so we can restore the files if we ever need to refer to them.

**Comment by PatrickvL** [comment]
Agreed

**Comment by LukeUsher** [comment]
Pull Request #83
