### ISSUE TITLE
Remove _CXBXKRNL_INTERNAL define

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#820]
The define `_CXBXKRNL_INTERNAL` that appears everywhere appears to be a legacy inheritance.

For this issue :
* Verify it doesn't alter any behavior in our current code base
* If the above succeeds, remove this define from our entire source tree

**Comment by x1nixmzeng** [comment]
This is never `#ifdef` checked anywhere - only ever defined. Removing it will have no effect so this is safe to delete.

Another define is `_XBOXKRNL_DEFEXTRN_` which has the same issue.

**Comment by PatrickvL** [comment]
That other one is used in openxdk, so that's not the same issue (it might need another approach)

**Comment by PatrickvL** [comment]
Fixed by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/840
