### ISSUE TITLE
Differentiating game versions/regions in the game-compatibility repository

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#855]
In the game-compatibility issue page, there hasn't been a set rule on how duplicates are marked. Generally I've used my best judgement: closing issues that appear to be the exact same game, allowing regional variations to have their own issue, etc, etc. However we should decide an official stance that can be put in the README and followed by testers/maintainers. 

## Things to consider
- Different regional versions of game may have different titles (see Cxbx-Reloaded/game-compatibility#533)
- Should Platinum Hits or other game re-releases get their own issues? Perhaps get put into the same issue as the base game unless they emulate differently?
- Does the template need updating? Maybe a 'game editions' section describing different releases of the game?
- Titles could use the exact same Xbe but have different media (for example a German version of a game just uses different files/media, while having the same executable (Xbe) as the PAL version.
- Due to the above, the 'Digital Signature' field of Xbe dumps could help find different Xbe's, but currently we can't detect changes in the media/files the game uses.

## Additional considerations
- Homebrews often use a zero-ed out title ID, hence why we currently don't include them in issue title, however this was never stated in the README and probably should be added for clarification.

## Quotes for thought

**From @PatrickvL in a discord direct message:**

> There are at least three approaches: merge every report on the same title into one (meaning all differences between versions of a game are ignored), or keep all reports open (meaning we never even check if they are about the same game or not) or we specify what makes a game unique (and compare reports on that base, closing duplicates according to this definition).
I think the last approach is what should be done
Hence, we need to come up with a definition of what makes a game unique
Title ID is probably the main key differentiator
Although that mainly applies to games, as various homebrew and XDK samples often specify the same Title ID.
That would make the type (game, demo, homebrew, sample, etc) the leading differentiator
So, first two keys are Type+TitleID
But after that it becomes fuzzy
Title names might differ between reports, but it could still be the same game (just using differently localised media, but otherwise the same executables). How do we check that? And do we consider them a duplicate or not?

## In closing
I welcome any feedback from both the developers and other issue maintainers on how to tackle this issue. Please let me know your thoughts, thanks! 👍

**Comment by LukeUsher** [comment]
Ideally, we would use the disc product numbers/pressing dates numbers as a method of uniquely identifying games, but as Cxbx-Reloaded doesn't read from real media, we can't really capture information within XBE Dumps.

The Title ID is not sufficient alone because different regions can have the same title ID, but different disc contents or a different Xbe.

I wouldn't be surprised if different revisions of a game exist with the exact same Xbe but different data files, so perhaps we need to hash the entire contents and use that as a unique identifier, but that could get nasty/take some time for larger games.

**Comment by CakeLancelot** [comment]
I'll go ahead and mention @Cxbx-Reloaded/issue-maintainers since this should be relevant to them as well.

**Comment by LukeUsher** [comment]
Closing as solved: The combination of Serial No (Title ID) and Version String (v1.XX) is enough to uniquely identify titles.
