### ISSUE TITLE
PsCreateSystemThreadEx regression

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#857]
Since https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/853 went in yesterday, some titles hang instead of continuing;

Confirmed cases:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/542#issuecomment-357476308
https://github.com/Cxbx-Reloaded/game-compatibility/issues/62#issuecomment-357476876

Possibly:
https://github.com/Cxbx-Reloaded/game-compatibility/issues/118#issuecomment-357470829

Instead of reverting the entire commit (and losing the safeguards that got added) the solution is probably to move this line `SetEvent(hStartedEvent);` down to where it was before, under the `callComplete:` label.

It's strange though. Restoring that previous behaviour will make the thread calling `PsCreateSystemThreadEx` wait until the new thread is done executing. You would expect it to return once the new thread is created (especially so if the new thread is initially created to be in suspended state!).

Thus, I suspect there's something else wrong instead of this. But that will have to be researched later. First get this regression out if the way. Then, create an issue to look into this strange behaviour. (It might even be that the caller *has* to wait, but then we should verify and document that.)

**Comment by LukeUsher** [comment]
PR #858 solves this issue in Call of Duty, but I'm not entirely sure why.

Thread creation is in a poor state at the moment, so much so that all Debug executables assert immediately due to incorrect memory layout (mostly regarding TLS), this is just another issue that furthers the need for revisiting these kernel APIs and creating a better implementation,

**Comment by ergo720** [comment]
All three games reported above are now confirmed as booting and no longer hang. Thus, it's very likely this was fixed during the past years and can probably be closed now.

**Comment by PatrickvL** [comment]
See #1998
