### ISSUE TITLE
restore LaunchDataPage Bug

### ISSUE THREAD

**Issue by hotzenplotz3000** [Cxbx-Reloaded/Cxbx-Reloaded#861]
I've just found a bug while testing some games with current build.
This issue appears only with multi xbe titles.
In this case CxbxRestoreLaunchDataPage() restors the wrong address from the previous run.

the code looks like this:
```
xboxkrnl::LaunchDataPage = (xboxkrnl::LAUNCH_DATA_PAGE*)CONTIGUOUS_MEMORY_BASE + LaunchDataPAddr;
```

I think CONTIGUOUS_MEMORY_BASE and LaunchDataPAddr should be casted to get the proper address:
```
xboxkrnl::LaunchDataPage = (xboxkrnl::LAUNCH_DATA_PAGE*)(CONTIGUOUS_MEMORY_BASE + LaunchDataPAddr);
```
Please correct me if I'm wrong.

I've tested this with these games, which regressed since the MemoryManager update
 - Prisoner of War
 - Unreal 2
 - TopSpin

Prisoner of War and Unreal 2 also pass some arguments through LauchDate to another xbe that otherwise got lost

**Comment by PatrickvL** [comment]
It looks like you're right

**Comment by LukeUsher** [comment]
I noticed another potential issue where the launchdatapage is restored before the memory manager sets up and registers memory, I was going to work on this but I don't have any multi xbe titles on hand right now

**Comment by PatrickvL** [comment]
Note : I've checked our entire codebase on the regular expression `=.*\*\)[^(].*\+` (an assignment with a pointer typecast without further brackets that does addition) and found no more cases that go wrong.

**Comment by PatrickvL** [comment]
This issue is fixed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/862 , closing.

**Comment by hotzenplotz3000** [comment]
@PatrickvL thanks for commiting my suggestion 👍 

PS: I'm glad that this didn't break anything 🤣
