### ISSUE TITLE
Call `SetWindowText` from just one place

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#863]
Currently, Cxbx-Reloaded calls `SetWindowText` from multiple locations. These will conflict with eachother.
For this issue:
* build a list of places which currently call `SetWindowText`
* determine which state influences the `lpString` argument
* create a set of  strings that can be part of all text send to `SetWindowText`
* concatenate all these together in one central place
* make sure all states that are needed for this, are communicated from their current locations (possible via `EmuShared`)
* remove all but the central `SetWindowText` call
* test, issue a pull request and close this issue ;)

**Comment by CakeLancelot** [comment]
I've found these 3 instances of SetWindowText for the main window:
- CxbxKrnlSuspend()
- CxbxKrnlResume()
- WndMain::UpdateCaption()

There were other calls for SetWindowText but they were either commented out or for a different window/control (ex. controller setup dialog). I'll try to centralize this to just  WndMain::UpdateCaption() and submit a PR.

**Comment by bryce13950** [comment]
Also, is there are specific reason why `UpdateCaption` is private? If I could make that function public, then I could take care of this in 10 minutes without worry.
