### ISSUE TITLE
Bug in SMC device?

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#871]
I think I've found a bug. I finished to wrote the LED implementation with the SMC device and tested it with Avalauch dashboard (which now is fully functional by the way, except for the network support). However, when I try to change the color of LED with the option inside the dashboard, it never happens. While debugging, I discovered it's because ExecuteTransaction cannot find the SMC device (the iterator is end) and so my code to changing the LED is never called. I don't think this is normal, it should actually find the SMC device, right?
![bug](https://user-images.githubusercontent.com/30000751/35189142-cb356338-fe44-11e7-97a4-32916c8cc60d.PNG)

**Comment by PatrickvL** [comment]
You're completely right, and there's a fix already pending in my PR.

This is the fix on itself : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/1f7e8c9877672ee90e1eafd54b8b95ee4b8a63ca

**Comment by LukeUsher** [comment]
This should be resolved in master now, please retest and confirm and we'll close this issue.

**Comment by PatrickvL** [comment]
Note, even with the fix in, not all SMBUS connected devices are currently emulated, so we'll keep hitting that log message until then

**Comment by ergo720** [comment]
Yes, the issue is solved so this can be closed. Thanks to PatrickvL
