### ISSUE TITLE
Cxbx Crashes when Clicking Audio Settings

### ISSUE THREAD

**Issue by JackaJacka123** [Cxbx-Reloaded/Cxbx-Reloaded#894]
Here is a link to a YouTube Video to see the crash in Real Time to see the exact steps that I take to recreate the bug. This happens every time. I'm also trying to isolate why Jet Set Radio Future will not start. If needed, I can add what I am experiencing to game compatibility or make another issue.

Link: https://youtu.be/dhrSwv6kY54

Thanks!

**Comment by CakeLancelot** [comment]
Have you tried https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/793#issuecomment-343699793 or https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/793#issuecomment-343699793 ?

**Comment by RadWolfie** [comment]
In summary, attempt to access audio setting from GUI making the crash is cause of registry corruption for getting invalid audio adapter device. This also includes attempt to start xbe as well for "DirectSoundCreate8 Failed!" message too.

The issue is relative to #827 anyway.

**Comment by JackaJacka123** [comment]
@CakeLancelot deleting that section of the registry for the audio did fix my problem. I can close this issue if needed.
