### ISSUE TITLE
Input on controllers other than P1

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#902]
Currently, there are no options for additional controllers beyond the first in Directinput. When attempting to use a second Xinput controller, the actions do not appear to be reflected in-game. This would be a nice addition once more multiplayer-based games are working.

**Comment by RadWolfie** [comment]
XInput controllers with up to 4 controllers are currently supported from pull request #1196. Plus one DirectInput is also support from the pull request too.

Is there any further concern about this issue? Or it is safe to close the issue?

**Comment by CakeLancelot** [comment]
Probably safe to close
