### ISSUE TITLE
Port back all HLE D3D8 improvements from Dxbx

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#91]
Dxbx started out as a translation of Cxbx to the Delphi language. Once the translation was finished, Dxbx began to improve it's D3D8 HLE code.

For this issue, compare all D3D8 code in Dxbx to the corresponding Cxbx code. (The most recent Dxbx codebase can be found here on github.)

Either create a report of improvements, or immediately port them back to Cxbx.

Make sure every change is an actual improvement, otherwise keep it commented out. 
Verify against software known to run in Cxbx, and software known to run in Dxbx.

(Dxbx runs almost all xdk samples, lots of homebrew and a few games like Turok, Smashing Drive, Petit Copter, Gauntlet Dark Legacy and Battlestar Galactica)

Also compare the results of the symbol detection of both emulators;
(Dxbx finds many more symbols because of its pattern trie approach). For each symbol that is lacking in Cxbx, create or improve it's OOVPA. Afterwards, verify that Cxbx can find the function, applies the associated patch and runs software equal or better afterwards. 

"Better" in this context means: equal or less graphical glitches, more supported on-screen effects, no missing effects, not crashing (earlier), running as fast or faster than before the change, equal or less error logging.

Because this is a big task, keep notes of progress in this issue.

**Comment by LukeUsher** [comment]
Tagged as help-wanted to hopefully attract more contributors to work on this

**Comment by x1nixmzeng** [comment]
Some of my old Github project were written in Pascal! I should be able to help with porting, although as you say the first step is breaking down the differences.

**Comment by LukeUsher** [comment]
Just an additional note, that Dxbx was updated to work with DirectX9, but as far as I know, this mode doesn't work with shaders yet.  I'm sure Patrick will correct me if I'm wrong, but I think we should port over both code paths, rather than only the DirectX9 implementation.

It would be nice to be able to leave DirectX8 behind, however I feel there are more important things to work on right now than a DirectX9 shader implementation.

**Comment by PatrickvL** [comment]
Well, DirectX9 never really worked at all in Dxbx. It was a port that I never finished, otherwise I would have dropped DirectX8 support immediately. It compiled, but that's about it, really. So yeah, we can backport that, but it won't be usable in its current state.

**Comment by x1nixmzeng** [comment]
A quick skim-read of Dxbx source seems to suggest there is another branch of Cxbx with a lot more implemented - `shogun  Revision:0.8.1-Pre2`. Which Cxbx fork did this branch come from?

**Comment by PatrickvL** [comment]
Hmmm, that could be interesting. I'll look it up tomorrow and will get back to you on that. But for now let's assume Luke merged all available cxbx forks into one, and the new stuff you're seeing are actual Dxbx improvements that just weren't marked as such.

**Comment by LukeUsher** [comment]
To clarify this a little but, I created Cxbx-Reloaded by forking Echelon9's branch, implementing a new EmuFS implementation to fix 64-bit, and then I merged all the changes from shogun's latest branch here on Github, however, shogun's branch didn't come with any change history, so the changes were merged by doing a file compare and manually going through all the changes. 

I may have missed some things, but anything marked Echelon9 or Shogun is already present. XAPI functions that exist in other branches but not in Cxbx-Reloaded were intentionally removed as part of the effort to improve the kernel HLE, so it should be safe to ignore those.

**Comment by PatrickvL** [comment]
This is duplicated by issue #173 - these should be merged together.

**Comment by LukeUsher** [comment]
Closing as we've done as much of this as we are likely to ever do: Cxbx-R's D3D implementation is now rather different than Dxbx's in many places, and has many improvements, porting is no longer worth the time/effort over new-developments.
