### ISSUE TITLE
Underflow in physical memory usage counter

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/Cxbx-Reloaded#913]
After running latest, the function `PhysicalMemory::AllocatePhysicalMemoryRange` is asserting at:

> assert(m_MaxContiguousAddress >= m_PhysicalMemoryInUse);

Where it looks like the physical memory in use track has underflowed:

`m_MaxContiguousAddress == 0x07fd0000`
`m_PhysicalMemoryInUse == 0xffff3000`

Note the protection flags are 0x404 which means PAGE_WRITECOMBINE is requested (and there is already a comment that this isn't implemented) but this shouldn't be an issue.

Tested with WormsX (WormS_beta2.rar) from http://www.xbdev.net/tuts/tuts.php

**Comment by x1nixmzeng** [comment]
Turns out removing the asserts will run the XBE without noticable issue (with Worms anyway).

Maybe the asserts could be moved to a macro and enabled in certain builds?

**Comment by PatrickvL** [comment]
@Ergo720 is currently reworking page tables, let's wait if that works (in)directly fixes this. Otherwise, sure

**Comment by ergo720** [comment]
I'm not sure but could this be a duplicate of #831?

**Comment by PatrickvL** [comment]
This out of memory issue is the fallout from leaks in various places, but one thing is special about this issue : Underflow in the memory counters. That shouldn't ever happen, and is worth this separate issue. (I'll rename it to make this more clear)

**Comment by ergo720** [comment]
This one is fixed by #1002 on my end, so it should probably be fine to close this now

**Comment by x1nixmzeng** [comment]
Good call!, thanks @ergo720 :+1:
