### ISSUE TITLE
AppVeyor issue

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#916]
After merging the debugger commit, AppVeyor is no longer creating the exported artifacts, both debug and release builds contain the error "No artifacts found matching 'export\*.zip' path"

**Comment by x1nixmzeng** [comment]
Good spot.

For some reason the CI is trying to build the debugger - although it shouldn't be part of the normal configurations

> warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\projects\cxbx-reloaded\import\cs_x86\Debug\cs_x86.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\projects\cxbx-reloaded\src\CxbxDebugger\CxbxDebugger.csproj]

I will investigate

**Comment by x1nixmzeng** [comment]
AppVeyor was building the first solution it could find, which was the C# project. The PR will help, but it's incomplete!
