### ISSUE TITLE
A readme.md for setting up the development environment and building the projects is needed.

### ISSUE THREAD

**Issue by jackchentwkh** [Cxbx-Reloaded/Cxbx-Reloaded#92]
I git this repo and open the VC solution file with Visual Studio Community 2015, try to build the projects but fail. two error msg showed me that the bat file was not executed corrently. So I managed to remove the execution of the batch file and replace it with manual operation, 1st I created the version.h, 2nd I copied the necessary dll file to debug directory. After that I could build those projects. But the output cxbx can't be executed in my Windows 10 64 bit. I don't know why. I check the build configuration, and it's win32. So I modified the platform to X64, and this time the building process introduced many error messages. 

I would suggest that we could have a text file describing the setup of develop environment, and the building process. that's would be great.

**Comment by PatrickvL** [comment]
I'm using the same IDE, except on Windows 7 64 bit, don't know what's going on here

**Comment by jackchentwkh** [comment]
I figured out the problem. The directory name contents the cloned repo shouldn't have a space in it, other wise the execution of .bat file will fail. after modifying the directory name, I successfully build the projects and the output execution file is not executable. Sorry for bothering you.

**Comment by x1nixmzeng** [comment]
Which batch file has the error? It sounds like a bug :smile:

**Comment by ergo720** [comment]
I don't know if this is relevant but when I tried to build cxbx with Visual Studio Community 2017 I got a single error post-build saying that it was unable to copy the file glew32.dll to the release directory. I simply copied the dll manually and cxbx worked fine afterwards. To actually get rid of the error, I had to put the source in a path that doesn't contain any spaces.
