### ISSUE TITLE
Jet Set Radio Future Crashes on Load

### ISSUE THREAD

**Issue by chrisderwahre** [Cxbx-Reloaded/Cxbx-Reloaded#937]
JSRF Isnt Running it cant be started.

Issue:

![screenshot_9](https://user-images.githubusercontent.com/23343464/36561927-92722c76-1815-11e8-997a-c1c371e7cf68.png)

Settings:

![screenshot_1](https://user-images.githubusercontent.com/23343464/36561941-9bcee2f0-1815-11e8-8fc2-d3ce7aac11dd.png)

The Screen is black for around 10 secounds befor the Issue pop up. in earier version it runs with texture bugs or the music plays on a black screen (no screenshot)

Version: JSRF NTSC-U

**Comment by CakeLancelot** [comment]
Don't use the software mode, it generally has much worse results. If you computer was made in the last 10 years then it will support DirectX 8.1.

**Comment by chrisderwahre** [comment]
@CakeLancelot Same result

**Comment by CakeLancelot** [comment]
Please provide a log (View>Debug Output (Kernel)>File...) and for future reference post any compatibility issues in https://github.com/Cxbx-Reloaded/game-compatibility. I have the NTSC version here and it works fine for me - so it's down to either software or hardware configuration here.

**Comment by LukeUsher** [comment]
This is quite normal with JSRF: It's very timing sensitive and rather crashy, weather it boots or not on a particular attempt is mostly just luck.

**Comment by HyperScorpio** [comment]
Works fine for me.

**Comment by chrisderwahre** [comment]
Here's the log, ive tried to start it with like any settings over 10 Times, still the same.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1751763/KrnlDebug.txt)

**Comment by chrisderwahre** [comment]
@CakeLancelot Could you give me your Settings please? If it works for you, i should try them out.

**Comment by CakeLancelot** [comment]
According to the log you posted you're still using software mode (Direct3D REF). Make sure to select the hardware accelerated mode in video settings and hit apply (closing out with the X will discard your changes).

**Comment by chrisderwahre** [comment]
Ok; Ive Tried out Compling the newest version (ive used the version from http://www.emucr.com/search/label/XBox?&max-results=16) and now all versions of the programm crash (even the downloaded, lol)

**Comment by PatrickvL** [comment]
Others don't have this problem. Please test again with a clean environment and report back your findings
