### ISSUE TITLE
"Could not map" Error

### ISSUE THREAD

**Issue by imivz** [Cxbx-Reloaded/Cxbx-Reloaded#942]
I get an error saying "Could not map ...\Cxbx-Reloaded\EmuDisk\Partition5" when launching a game.

![udklip](https://user-images.githubusercontent.com/15425986/36624954-c70a4282-1916-11e8-86b4-3eb27ffdd3bf.PNG)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1753957/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1753959/KrnlDebug.txt)
Cxbx Build: 3329a9d0 (Feb 23 2018)

**Comment by PatrickvL** [comment]
Sometimes the Cxbx executable doesn't terminate. Check using a task manager / process explorer, and kill every running instance of Cxbx.exe. That might release file locks

**Comment by x1nixmzeng** [comment]
I had this exact issue - and added the try/catch to stop it from just crashing.

I think the file handle is still in use (or wasn't closed properly) if Cxbx crashes. Restarting my PC fixed the issue, but it does happen quite frequently...

**Comment by imivz** [comment]
I've tried rebooting, deleting partition5, changed read-only, changed folder permission, running Cxbx as admin and killed the only Cxbx.exe there was but nothing works.
