### ISSUE TITLE
Controller Config Error

### ISSUE THREAD

**Issue by mohsinous** [Cxbx-Reloaded/Cxbx-Reloaded#946]
When i try to config controller, after B button, it crashed and nothing has been saved!!!!
have this problem since 2 weeks ago.

**Comment by PatrickvL** [comment]
Try deleting your Cxbx-Reloaded registry tree (use regedit, backup first)

**Comment by LukeUsher** [comment]
Alternatively, you could try the "Reset to Defaults" option at the bottom of the Settings menu

**Comment by PatrickvL** [comment]
Closing this due to lack of feedback. We can always reopen this report if needed.
