### ISSUE TITLE
Newest progression for Iron Phoenix

### ISSUE THREAD

**Issue by fuhuan416** [Cxbx-Reloaded/Cxbx-Reloaded#948]
I used d57aa2be to test the game Iron Phoenix. Whatever, you guys are great work!
Currently it can through LOGO and going to loading interface, in loading interface, FPS just very low, a few seconds popup a dialog, write words on it:

Received Exception Code 0xC0000005 @ EIP :=0x00000000(=unknown+0x0)

**Comment by fuhuan416** [comment]
Debug GUI all the items are OK
Here the Kernel.txt
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1758262/KrnlDebug.txt)

**Comment by NNX3x** [comment]
Game compatibility issues have their own section now.  Update the existing Iron Phoenix game compatibility issue here:  https://github.com/Cxbx-Reloaded/game-compatibility/issues/117.

**Comment by PatrickvL** [comment]
Assuming the above request will be done regardless, I'll close this already.
