### ISSUE TITLE
ExAllocatePool(WithTag) and friends should actually be pooling

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#953]
Our kernel currently doesn't pool memory allocations made by `ExAllocatePool` and `ExAllocatePoolWithTag`, instead these calls are directly forwarded to the virtual memory manager, which deals with whole pages at a time.

Especially when many of these calls are made, these memory pages aren't used up to their full capacity.

Verify this is true (or debunk it);
Add pooling capabilities to our kernel.

**Comment by ergo720** [comment]
Yes, it's true. At the moment, it uses the standard Allocate function of the virtual manager which has a minimum allocation size of a page so this needs correction
