### ISSUE TITLE
Linux (wine) : uncaught_exceptions

### ISSUE THREAD

**Issue by 7oxicshadow** [Cxbx-Reloaded/Cxbx-Reloaded#955]
I am not even sure this belongs here as it is more than likely an issue with Wine but its best to let you know just incase anything can be done. (This issue can be deleted if it is not relevant)

I have tried the Feb 27 2018 build of CXBX-Reloaded and unfortunately games no longer boot within Wine. When selecting "Start" a momentary black screen appears as if the game is loading and then it instantly returns back to the GUI.

The following error is shown in the Wine log:

```
wine: Unimplemented function msvcp140.dll.?uncaught_exceptions@std@@YAHXZ called at address 0x7b4421d2 (thread 0059), starting debugger...
005f:fixme:dbghelp:i386_stack_walk new PC=7db0d39c different from Eip=7da97699
```

Tested using Wine 3.2 (64bit)

**Comment by LukeUsher** [comment]
The Wine implementation of msvcp140.dll lacks support for exception handling. You need to install the MIcrosoft Visual Studio runtimes (2015 and 2017) either via Winetricks or some other method.

**Comment by PatrickvL** [comment]
@7oxicshadow Did Luke's hint help?

**Comment by 7oxicshadow** [comment]
I can confirm that installing vcrun2015 using winetricks allows the emulator to run as expected.

Thanks for the tip
