### ISSUE TITLE
Frame limiter 

### ISSUE THREAD

**Issue by xana43** [Cxbx-Reloaded/Cxbx-Reloaded#959]
so, i've been trying out various games on this emulator, and all of them work, besides the framrate, I know that Vsync is a thing but seeing as most monitors now a-days are 60Hz (and sometimes even more than that) and Vsync locks the game to screen refresh rate (I.E. 60fps) it messes up all of the game mechanics, and plus being just a very difficult thing to play with, so I suggest a framerate limiter that can be changed in the UI, I know this might be a bit hard to do seeing as framerate might be hard to do this because of how programming works, especially in the regard of video games where the rendered frames have mostly unknown states and data in them, but someone on here can do it. I just think it'd be a nice addition instead of having to manually change my screen's refresh rate and then forget to change it back after i'm done playing then wondering why my other games are locked to 30fps

**Comment by LukeUsher** [comment]
Since we implemented support for QueryPerformanceCounter & also fixed the D3DDevice_Swap function to wait until the frame duration has ended, this is no longer an issue.
