### ISSUE TITLE
Mouse lock/Force full screen

### ISSUE THREAD

**Issue by xana43** [Cxbx-Reloaded/Cxbx-Reloaded#962]
Testing out this emulator some more i've managed to test a lot of games using the keyboard and mouth (still had that issue though) what I suggest is some kind of mouse lock so when i'm playing a game with any controller it doesn't select other things on my computer (and i've tried other resolutions, most of the games don't work with anything above 480p) which leads me to another thing, it'd also be nice if there was a fullscreen mode, though someone might already be working on this, just incase someone isn't i've made this post just to spur some kind of thought to some QoL features that would be nice if they were added. As always, keep up the good work all of you who are working on this emulator

**Comment by BenNottelling** [comment]
Pressing `ALT` + `ENTER `will toggle between full screen and windowed mode. Under the video config checking `Use Hardware Video Mode` should have the same effect too, but I found it to be unreliable when I originally tried using it and I believe that it affects emulation as well, but I'm not sure

**Comment by xana43** [comment]
I've tried that as well, and there's still no mouse lock so I can be playing my games and accidentally open the windows app store, or like, steam or something

**Comment by BenNottelling** [comment]
Oh, apparently there is also a registry flag to enable full-screen as mentioned in issue #901. As to the problem of clicking on apps and such in Windows shouldn't running the emulator in full screen fix this? Then you would be clicking on the emulator and only the emulator, maybe I don't understand though, but I still understand why you want mouse lock

**Comment by xana43** [comment]
Running the emulator at full screen doesn't solve this because in order for the mouse to be locked to the screen, there has to be a region marked out by the API where the mouse is able to go, now I'll continue to see if I can get something to stay in the emulator window, but as far as I can tell, the mouse during emulation is just free to click on anything (even when using an actual xbox controller plugged in via USB)

**Comment by CakeLancelot** [comment]
Mouse movement can no longer be mapped in DirectInput, so this issue doesn't really apply currently.

**Comment by PatrickvL** [comment]
"keyboard and mouth" ...
