### ISSUE TITLE
Add 'boot to dashboard' option

### ISSUE THREAD

**Issue by CakeLancelot** [Cxbx-Reloaded/Cxbx-Reloaded#974]
Add an option to the menu bar that will allow the user to boot an installed dashboard without having to navigate to the Appdata folder and open it from there.

**Comment by fancymelonub** [comment]
How do you install a dashboard?

**Comment by x1nixmzeng** [comment]
The dashboard is itself an XBE that would need to be run through the emulator. Cxbx would need to be pretty stable to support booting straight into anything.

At the moment can you use the F5 key to run the last XBE you started - from the "most recently used" list?

**Comment by CakeLancelot** [comment]
> The dashboard is itself an XBE that would need to be run through the emulator. Cxbx would need to be pretty stable to support booting straight into anything.
> 
> At the moment can you use the F5 key to run the last XBE you started - from the "most recently used" list?

This is effectively a menu option that does just that - launches the dashboard XBE if one is found in the Emudisk.

**Comment by PatrickvL** [comment]
This is implemented by @ergo720 via pull request #1017
