### ISSUE TITLE
DDR Ultramix 3 loading problems

### ISSUE THREAD

**Issue by OFFLINEX** [Cxbx-Reloaded/Cxbx-Reloaded#982]
I was trying to run Dance dance revolution ultramix 3 for xbox. when it loads up all that happens is I can see a small square that takes up about 1/4 of the upper left screen, and what I see is wire mesh models going through the intro at like x2 speed, cant do anything with the controller either.

**Comment by Voxel9** [comment]
@OFFLINEX Use the official game compatibility list for any game-specific issues.
https://github.com/Cxbx-Reloaded/game-compatibility/issues

This issue section is for general emulator-related issues and not game-related/compatibility issues.
