### ISSUE TITLE
Upon Start of emulation - 0xC000005 @ EIP := 0x0005f500(unknown+0x0)

### ISSUE THREAD

**Issue by M0DULU5** [Cxbx-Reloaded/Cxbx-Reloaded#985]
Currently I have only really tried one XBOX game since it is the only game I have, but currently when starting Emulation, the screen goes black, I hear a error sound and I get this error here.
https://gyazo.com/c509518c00c0a46e83745eaf5088b429
I haven't seen any other post on here of this specific error, so would like to know if it's something on my end.

Specs: 
Intel(R) Core(TM) i5-6600K CPU @ 3.50 GHz
16GB RAM
Windows 7 Home Premium 64x
NVIDIA GTX 960

**Comment by CakeLancelot** [comment]
Unless this is an issue present across multiple games, please find or make an issue in [game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) and report your findings there.
