### ISSUE TITLE
Several games throws exception at EmuD3D8.cpp#L2240 (pHostTexture)

### ISSUE THREAD

**Issue by JohnGodgames** [Cxbx-Reloaded/Cxbx-Reloaded#988]
Tested by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/93cf2ab789aaa422ef8f3a194b45f22e6f990731

## Issued games:

**Backyard Wrestling: Don't Try This at Home
Batman: Rise of Sin Tzu
Burnout
Burnout 2: Point of Impact
Disney's Extreme Skate Adventure
Lemony Snicket's A Series of Unfortunate Events
Max Payne 2: The Fall of Max Payne
Melbourne Cup Challenge
SpongeBob SquarePants: Battle for Bikini Bottom
Spy Hunter 2**

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/EmuD3D8.cpp#L2240

```
// Derived from EmuUnswizzleActiveTexture
static void EmuUnswizzleTextureStages()
{
	LOG_INIT; // Allows use of DEBUG_D3DRESULT

	for( int i = 0; i < TEXTURE_STAGES; i++ )
	{
		XTL::X_D3DBaseTexture *pBaseTexture = XTL::EmuD3DActiveTexture[i];
		if (pBaseTexture == NULL)
			continue;

		HRESULT hRet;
		XTL::IDirect3DTexture8 *pHostTexture = GetHostTexture(pBaseTexture);
		if (pHostTexture != nullptr)
		{
			if (pHostTexture->GetType() == XTL::D3DRTYPE_CUBETEXTURE) continue; // Prevent exceptions - skip cubes for now
			►►►hRet = pHostTexture->UnlockRect(0); // remove old lock
			DEBUG_D3DRESULT(hRet, "pHostTexture->UnlockRect");
		}

		if(!IsXboxResourceLocked(pBaseTexture))
			continue;

		XTL::X_D3DFORMAT XBFormat = GetXboxPixelContainerFormat(pBaseTexture);
		if(!XTL::EmuXBFormatIsSwizzled(XBFormat))
			continue;

		DWORD dwBPP = XTL::EmuXBFormatBytesPerPixel(XBFormat);
		pBaseTexture->Common &= ~X_D3DCOMMON_ISLOCKED;

		// TODO: potentially XXHash32::hash() to see if this surface was actually modified..

		if (pHostTexture == nullptr)
			continue;

		//
		// unswizzle texture
		//

		{
```

**Comment by PatrickvL** [comment]
pHostTexture might be a surface instead of a texture

**Comment by PatrickvL** [comment]
I've removed EmuUnswizzleActiveTexture, so this issue should no longer show. Can someone verify?

**Comment by PatrickvL** [comment]
Oh wait, no need for that, I've already seen reports on some of the above game. Closing
